select sap.NU_CARTEIRA_VERSION , 
CASE WHEN (SELECT COUNT(1) 
            FROM VND.ELO_CARTEIRA_SAP_IMPORT TEMPARCIAL 
            WHERE TEMPARCIAL.NU_CARTEIRA_VERSION = sap.NU_CARTEIRA_VERSION) >= 1 THEN 1
ELSE 0 END TEMPARCIAL ,
--count(1), min(sap.dh_carteira)
sap.CD_BLOQUEIO_CREDITO, impor.CD_BLOQUEIO_CREDITO,
sap.CD_BLOQUEIO_ENTREGA, impor.CD_BLOQUEIO_ENTREGA,
sap.CD_BLOQUEIO_FATURAMENTO, impor.CD_BLOQUEIO_FATURAMENTO,
sap.CD_BLOQUEIO_FATURAMENTO_ITEM, impor.CD_BLOQUEIO_FATURAMENTO_ITEM,
sap.CD_BLOQUEIO_REMESSA, impor.CD_BLOQUEIO_REMESSA,
sap.CD_BLOQUEIO_REMESSA_ITEM, impor.CD_BLOQUEIO_REMESSA_ITEM,
sap.CD_CENTRO_EXPEDIDOR, impor.CD_CENTRO_EXPEDIDOR,
sap.CD_CULTURA_SAP, impor.CD_CULTURA_SAP,
sap.CD_ELO_CARTEIRA_SAP, impor.CD_ELO_CARTEIRA_SAP,
sap.CD_GRUPO_EMBALAGEM, impor.CD_GRUPO_EMBALAGEM,
sap.CD_ITEM_CONTRATO, impor.CD_ITEM_CONTRATO,
sap.CD_ITEM_PEDIDO, impor.CD_ITEM_PEDIDO,
sap.CD_MOEDA, impor.CD_MOEDA,
sap.CD_MOTIVO_RECUSA, impor.CD_MOTIVO_RECUSA,
sap.CD_PRODUTO_SAP, impor.CD_PRODUTO_SAP,
sap.CD_SACARIA, impor.CD_SACARIA,
sap.CD_SALES_DISTRICT, impor.CD_SALES_DISTRICT,
sap.CD_SALES_GROUP, impor.CD_SALES_GROUP,
sap.CD_SALES_OFFICE, impor.CD_SALES_OFFICE,
sap.CD_SALES_ORG, impor.CD_SALES_ORG,
sap.CD_SEGMENTACAO_CLIENTE, impor.CD_SEGMENTACAO_CLIENTE,
sap.CD_SUPPLY_GROUP, impor.CD_SUPPLY_GROUP,
sap.DH_CARTEIRA, impor.DH_CARTEIRA,
sap.DH_ENTREGA, impor.DH_ENTREGA,
sap.DH_INCLUSAO, impor.DH_INCLUSAO,
sap.DS_CENTRO_EXPEDIDOR, impor.DS_CENTRO_EXPEDIDOR,
sap.DS_CREDIT_BLOCK_REASON, impor.DS_CREDIT_BLOCK_REASON,
sap.DS_CULTURA_SAP, impor.DS_CULTURA_SAP,
sap.DS_ROTEIRO_ENTREGA, impor.DS_ROTEIRO_ENTREGA,
sap.DS_SACARIA, impor.DS_SACARIA,
sap.DS_SEGMENTACAO_CLIENTE, impor.DS_SEGMENTACAO_CLIENTE,
sap.DT_CREDITO, impor.DT_CREDITO,
sap.DT_FIM, impor.DT_FIM,
sap.DT_INICIO, impor.DT_INICIO,
sap.DT_PAGO, impor.DT_PAGO,
sap.NO_PRODUTO_SAP, impor.NO_PRODUTO_SAP,
sap.NO_SALES_DISTRICT, impor.NO_SALES_DISTRICT,
sap.NO_SALES_GROUP, impor.NO_SALES_GROUP,
sap.NO_SALES_OFFICE, impor.NO_SALES_OFFICE,
sap.NU_CARTEIRA_VERSION, impor.NU_CARTEIRA_VERSION,
sap.NU_CONTRATO_SAP, impor.NU_CONTRATO_SAP,
sap.NU_ORDEM_VENDA, impor.NU_ORDEM_VENDA,
sap.QT_SALDO, impor.QT_SALDO,
sap.VL_BRL, impor.VL_BRL,
sap.VL_FRETE_DISTRIBUICAO, impor.VL_FRETE_DISTRIBUICAO,
sap.VL_TAXA_DOLAR, impor.VL_TAXA_DOLAR,
sap.VL_USD, impor.VL_USD


from vnd.elo_carteira_sap sap
left join vnd.elo_carteira_sap_import impor
on sap.nu_carteira_version = impor.nu_carteira_version 
and sap.nu_contrato_sap = impor.nu_contrato_sap
and sap.cd_item_contrato = impor.cd_item_contrato
and sap.cd_produto_sap = impor.cd_produto_sap 
and NVL(sap.NU_ORDEM_VENDA, '0') = NVL(impor.NU_ORDEM_VENDA,'0')

WHERE 1=1
--AND NU_CARTEIRA_VERSION = '20180405060009'
and sap.dh_carteira > current_date - 2  
--and impor.nu_carteira_version is null 
--GROUP BY sap.nu_carteira_version