
CREATE INDEX VND.IDX_CARTSAP_IMPORT  ON VND.ELO_CARTEIRA_SAP
(DH_CARTEIRA, NU_CARTEIRA_VERSION, NU_CONTRATO_SAP, CD_ITEM_CONTRATO, CD_PRODUTO_SAP, NU_ORDEM_VENDA)
LOGGING
TABLESPACE WEB_DATA
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );
           
CREATE INDEX VND.IDX_CART_IMPORT_IMPORT  ON VND.ELO_CARTEIRA_SAP_IMPORT
(NU_CARTEIRA_VERSION, NU_CONTRATO_SAP, CD_ITEM_CONTRATO, CD_PRODUTO_SAP, NU_ORDEM_VENDA)
LOGGING
TABLESPACE WEB_DATA
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );           