SELECT NU_CARTEIRA_VERSION, NU_CONTRATO_SAP, CD_ITEM_CONTRATO, NU_ORDEM_VENDA , COUNT(1) 
FROM VND.VW_ELO_CARTEIRA_SAP 
GROUP BY NU_CARTEIRA_VERSION, NU_CONTRATO_SAP, CD_ITEM_CONTRATO, NU_ORDEM_VENDA
HAVING COUNT(1) > 1;


SELECT * FROM VND.ELO_CARTEIRA_SAP 
WHERE NU_CARTEIRA_VERSION = '20180506233001' AND NU_CONTRATO_SAP = '0040368063' AND CD_ITEM_CONTRATO = 10;


SELECT * FROM VND.ELO_CARTEIRA 
WHERE 
NU_CONTRATO_SAP = '0040368063' AND CD_ITEM_CONTRATO = 10
AND CD_ELO_AGENDAMENTO IN (

SELECT CD_ELO_AGENDAMENTO FROM VND.ELO_AGENDAMENTO WHERE NU_CARTEIRA_VERSION = '20180506233001'
) AND CD_STATUS_CEL_FINAL IS NOT NULL; 


