DROP VIEW VND.VW_ELO_CARTEIRA_SAP_BY_OV_TMP;

/* Formatted on 06/06/2018 17:59:27 (QP5 v5.318) */
CREATE OR REPLACE FORCE VIEW VND.VW_ELO_CARTEIRA_SAP_BY_OV_TMP
(
    SESSION_ID,
    CD_ELO_CARTEIRA_SAP,
    NU_CARTEIRA_VERSION,
    CD_CENTRO_EXPEDIDOR,
    DS_CENTRO_EXPEDIDOR,
    DH_CARTEIRA,
    CD_SALES_ORG,
    NU_CONTRATO_SAP,
    CD_TIPO_CONTRATO,
    NU_CONTRATO_SUBSTITUI,
    DT_PAGO,
    NU_CONTRATO,
    NU_ORDEM_VENDA,
    DS_STATUS_CONTRATO_SAP,
    CD_CLIENTE,
    NO_CLIENTE,
    CD_INCOTERMS,
    CD_SALES_DISTRICT,
    NO_SALES_DISTRICT,
    CD_SALES_OFFICE,
    NO_SALES_OFFICE,
    CD_SALES_GROUP,
    NO_SALES_GROUP,
    CD_AGENTE_VENDA,
    NO_AGENTE,
    DH_VENCIMENTO_PEDIDO,
    DT_CREDITO,
    DT_INICIO,
    DT_FIM,
    DH_INCLUSAO,
    DH_ENTREGA,
    SG_ESTADO,
    NO_MUNICIPIO,
    DS_BAIRRO,
    CD_PRODUTO_SAP,
    NO_PRODUTO_SAP,
    QT_PROGRAMADA,
    QT_ENTREGUE,
    QT_SALDO,
    VL_UNITARIO,
    VL_BRL,
    VL_TAXA_DOLAR,
    VL_USD,
    PC_COMISSAO,
    CD_SACARIA,
    DS_SACARIA,
    CD_CULTURA_SAP,
    DS_CULTURA_SAP,
    CD_BLOQUEIO_REMESSA,
    CD_BLOQUEIO_FATURAMENTO,
    CD_BLOQUEIO_CREDITO,
    CD_BLOQUEIO_REMESSA_ITEM,
    CD_BLOQUEIO_FATURAMENTO_ITEM,
    CD_MOTIVO_RECUSA,
    CD_LOGIN,
    CD_SEGMENTACAO_CLIENTE,
    DS_SEGMENTACAO_CLIENTE,
    DS_SEGMENTO_CLIENTE_SAP,
    CD_FORMA_PAGAMENTO,
    CD_TIPO_PAGAMENTO,
    DS_TIPO_PAGAMENTO,
    CD_AGRUPAMENTO,
    CD_BLOQUEIO_ENTREGA,
    NU_CNPJ,
    NU_CPF,
    NU_INSCRICAO_ESTADUAL,
    NU_INSCRICAO_MUNICIPAL,
    NU_CEP,
    DS_ENDERECO_RECEBEDOR,
    CD_CLIENTE_RECEBEDOR,
    NO_CLIENTE_RECEBEDOR,
    CD_MOEDA,
    CD_SUPPLY_GROUP,
    DS_VENDA_COMPARTILHADA,
    CD_STATUS_LIBERACAO,
    CD_ITEM_PEDIDO,
    CD_CLIENTE_PAGADOR,
    NO_CLIENTE_PAGADOR,
    VL_FRETE_DISTRIBUICAO,
    CD_GRUPO_EMBALAGEM,
    DS_CREDIT_BLOCK_REASON,
    DH_CREDIT_BLOCK,
    CD_ITEM_CONTRATO,
    DS_ROTEIRO_ENTREGA,
    DS_ENDERECO_PAGADOR
)
AS
    WITH
        CTE_SALES_GROUP
        AS
            (SELECT DISTINCT PB.NU_CARTEIRA_VERSION,
                             PB.CD_SALES_DISTRICT,
                             PB.NO_SALES_DISTRICT,
                             PB.CD_SALES_OFFICE,
                             PB.NO_SALES_OFFICE,
                             PB.CD_SALES_GROUP,
                             PB.NO_SALES_GROUP
               FROM VND.VW_ELO_CARTEIRA_SAP_SALESGROUP PB
              WHERE     PB.NO_SALES_GROUP IS NOT NULL
                    AND PB.NO_SALES_GROUP <> ' '
                    AND LENGTH (PB.NO_SALES_GROUP) > 3
             UNION
             SELECT DISTINCT PB.NU_CARTEIRA_VERSION,
                             PB.CD_SALES_DISTRICT,
                             PB.NO_SALES_DISTRICT,
                             PB.CD_SALES_OFFICE,
                             PB.NO_SALES_OFFICE,
                             PB.CD_SALES_GROUP,
                             PB.NO_SALES_GROUP
               FROM VND.ELO_CARTEIRA_SAP_BY_OV_TMP PB
              WHERE PB.DH_CARTEIRA > (SYSDATE - 30))
    SELECT 
    CTSAP.SESSION_ID,
    CTSAP.CD_ELO_CARTEIRA_SAP,
           CTSAP.NU_CARTEIRA_VERSION,
           CTSAP.CD_CENTRO_EXPEDIDOR,
           (SELECT CC.DS_CENTRO_EXPEDIDOR
              FROM CTF.CENTRO_EXPEDIDOR CC
             WHERE CTSAP.CD_CENTRO_EXPEDIDOR = CC.CD_CENTRO_EXPEDIDOR)
               DS_CENTRO_EXPEDIDOR,
           --CTSAP.DS_CENTRO_EXPEDIDOR,
           CTSAP.DH_CARTEIRA,
           CTSAP.CD_SALES_ORG,
           CTSAP.NU_CONTRATO_SAP,
           CTSAP.CD_TIPO_CONTRATO,
           CTSAP.NU_CONTRATO_SUBSTITUI,
           CTSAP.DT_PAGO,
           CTSAP.NU_CONTRATO,
           CTSAP.NU_ORDEM_VENDA,
           CTSAP.DS_STATUS_CONTRATO_SAP,
           CTSAP.CD_CLIENTE,
           CTSAP.NO_CLIENTE,
           CTSAP.CD_INCOTERMS,
           NVL (
               CTSAP.CD_SALES_DISTRICT,
               (SELECT PB.CD_SALES_DISTRICT
                  FROM VND.CTE_SALES_GROUP PB
                 WHERE     PB.CD_SALES_GROUP = CTSAP.CD_SALES_GROUP
                       AND PB.NU_CARTEIRA_VERSION = CTSAP.NU_CARTEIRA_VERSION
                       AND ROWNUM = 1))
               CD_SALES_DISTRICT,
           NVL (
               CTSAP.NO_SALES_DISTRICT,
               (SELECT PB.NO_SALES_DISTRICT
                  FROM CTE_SALES_GROUP PB
                 WHERE     PB.CD_SALES_GROUP = CTSAP.CD_SALES_GROUP
                       AND PB.NU_CARTEIRA_VERSION = CTSAP.NU_CARTEIRA_VERSION
                       AND ROWNUM = 1))
               NO_SALES_DISTRICT,
           NVL (
               CTSAP.CD_SALES_OFFICE,
               (SELECT PB.CD_SALES_OFFICE
                  FROM CTE_SALES_GROUP PB
                 WHERE     PB.CD_SALES_GROUP = CTSAP.CD_SALES_GROUP
                       AND PB.NU_CARTEIRA_VERSION = CTSAP.NU_CARTEIRA_VERSION
                       AND ROWNUM = 1))
               CD_SALES_OFFICE,
           NVL (
               CTSAP.NO_SALES_OFFICE,
               (SELECT PB.NO_SALES_OFFICE
                  FROM CTE_SALES_GROUP PB
                 WHERE     PB.CD_SALES_GROUP = CTSAP.CD_SALES_GROUP
                       AND PB.NU_CARTEIRA_VERSION = CTSAP.NU_CARTEIRA_VERSION
                       AND ROWNUM = 1))
               NO_SALES_OFFICE,
           CTSAP.CD_SALES_GROUP,
           CASE
               WHEN NVL (CTSAP.NO_SALES_GROUP, ' ') = ' '
               THEN
                   (SELECT PB.NO_SALES_GROUP
                      FROM CTE_SALES_GROUP PB
                     WHERE     PB.CD_SALES_GROUP = CTSAP.CD_SALES_GROUP
                           AND PB.NU_CARTEIRA_VERSION =
                               CTSAP.NU_CARTEIRA_VERSION
                           AND ROWNUM = 1)
               ELSE
                   CTSAP.NO_SALES_GROUP
           END
               NO_SALES_GROUP,
           CTSAP.CD_AGENTE_VENDA,
           CTSAP.NO_AGENTE,
           CTSAP.DH_VENCIMENTO_PEDIDO,
           CTSAP.DT_CREDITO,
           CTSAP.DT_INICIO,
           CTSAP.DT_FIM,
           CTSAP.DH_INCLUSAO,
           CTSAP.DH_ENTREGA,
           CTSAP.SG_ESTADO,
           CTSAP.NO_MUNICIPIO,
           CTSAP.DS_BAIRRO,
           CTSAP.CD_PRODUTO_SAP,
           CTSAP.NO_PRODUTO_SAP,
           CTSAP.QT_PROGRAMADA,
           CTSAP.QT_ENTREGUE,
           CTSAP.QT_SALDO,
           CTSAP.VL_UNITARIO,
           CTSAP.VL_BRL,
           CTSAP.VL_TAXA_DOLAR,
           CTSAP.VL_USD,
           CTSAP.PC_COMISSAO,
           CTSAP.CD_SACARIA,
           CTSAP.DS_SACARIA,
           CTSAP.CD_CULTURA_SAP,
           CTSAP.DS_CULTURA_SAP,
           CTSAP.CD_BLOQUEIO_REMESSA,
           CTSAP.CD_BLOQUEIO_FATURAMENTO,
           CTSAP.CD_BLOQUEIO_CREDITO,
           CTSAP.CD_BLOQUEIO_REMESSA_ITEM,
           CTSAP.CD_BLOQUEIO_FATURAMENTO_ITEM,
           CTSAP.CD_MOTIVO_RECUSA,
           CTSAP.CD_LOGIN,
           CTSAP.CD_SEGMENTACAO_CLIENTE,
           CTSAP.DS_SEGMENTACAO_CLIENTE,
           CTSAP.DS_SEGMENTO_CLIENTE_SAP,
           CTSAP.CD_FORMA_PAGAMENTO,
           CTSAP.CD_TIPO_PAGAMENTO,
           CTSAP.DS_TIPO_PAGAMENTO,
           CTSAP.CD_AGRUPAMENTO,
           CTSAP.CD_BLOQUEIO_ENTREGA,
           CTSAP.NU_CNPJ,
           CTSAP.NU_CPF,
           CTSAP.NU_INSCRICAO_ESTADUAL,
           CTSAP.NU_INSCRICAO_MUNICIPAL,
           CTSAP.NU_CEP,
           CTSAP.DS_ENDERECO_RECEBEDOR,
           CTSAP.CD_CLIENTE_RECEBEDOR,
           CTSAP.NO_CLIENTE_RECEBEDOR,
           CTSAP.CD_MOEDA,
           CTSAP.CD_SUPPLY_GROUP,
           CTSAP.DS_VENDA_COMPARTILHADA,
           CTSAP.CD_STATUS_LIBERACAO,
           CTSAP.CD_ITEM_PEDIDO,
           CTSAP.CD_CLIENTE_PAGADOR,
           CTSAP.NO_CLIENTE_PAGADOR,
           CTSAP.VL_FRETE_DISTRIBUICAO,
           CTSAP.CD_GRUPO_EMBALAGEM,
           CTSAP.DS_CREDIT_BLOCK_REASON,
           CTSAP.DH_CREDIT_BLOCK,
           CTSAP.CD_ITEM_CONTRATO,
           CTSAP.DS_ROTEIRO_ENTREGA,
           CTSAP.DS_ENDERECO_PAGADOR
      FROM VND.ELO_CARTEIRA_SAP_BY_OV_TMP CTSAP
 
WITH READ ONLY;


GRANT SELECT ON VND.VW_ELO_CARTEIRA_SAP_BY_OV_TMP TO CTF WITH GRANT OPTION;

GRANT SELECT ON VND.VW_ELO_CARTEIRA_SAP_BY_OV_TMP TO VND_SEC WITH GRANT OPTION;


SELECT * FROM VND.VW_ELO_CARTEIRA_SAP_BY_OV_TMP;