CREATE OR REPLACE PACKAGE VND."GX_ELO_DELIVERED_QUANTITY" AS

TYPE T_CURSOR IS REF CURSOR;
  /* TODO enter package declarations (types, exceptions, methods etc) here */ 
  PROCEDURE PX_DELIVERED_QUANTITY(P_RETORNO OUT T_CURSOR);

END GX_ELO_DELIVERED_QUANTITY;


/