CREATE OR REPLACE PACKAGE VND."GX_ELO_CAPACITY_REPORT" AS 
TYPE T_CURSOR IS REF CURSOR;

PROCEDURE PX_GET_POLO
    (
    P_RETORNO     OUT T_CURSOR
    );
PROCEDURE PX_GET_CENTRO
    (
    P_RETORNO OUT T_CURSOR
    );

END GX_ELO_CAPACITY_REPORT;


/