CREATE OR REPLACE PACKAGE BODY VND."GX_ELO_PLANNING_VS_ACTUAL" AS

  PROCEDURE PX_GET_CENTRO(
        P_CD_POLO        in ELO_AGENDAMENTO_CENTRO.CD_POLO%type,
        P_DT_WEEK_START   in ELO_AGENDAMENTO_CENTRO.DT_WEEK_START%type,
        P_RETORNO         out T_CURSOR
 )
 IS

  BEGIN
    -- TODO: Implementation required for PROCEDURE GX_ELO_PLANNING_VS_ACTUAL.PX_GET_CENTRO
   OPEN P_RETORNO FOR
            SELECT CD_AGENDAMENTO_CENTRO,CD_CENTRO_EXPEDIDOR
            FROM ELO_AGENDAMENTO_CENTRO
            WHERE
                    trim(CD_POLO) = NVL(
                        trim(P_CD_POLO),
                        null
                    )
                AND
                    trunc(DT_WEEK_START) = NVL(trunc(P_DT_WEEK_START),DT_WEEK_START);
                    null;


  END PX_GET_CENTRO;

PROCEDURE PX_GET_AGENDAMENTO(
        P_CD_POLO         in ELO_AGENDAMENTO.CD_POLO%type,

       P_DT_WEEK_START   in ELO_AGENDAMENTO.CD_WEEK%type,
        P_RETORNO         out T_CURSOR
 )
  IS
  BEGIN
   OPEN P_RETORNO FOR
           SELECT * FROM ELO_AGENDAMENTO 
           WHERE
           (CD_POLO=P_CD_POLO OR CD_CENTRO_EXPEDIDOR IN ( SELECT CD_CENTRO_EXPEDIDOR
            FROM ELO_AGENDAMENTO_CENTRO))

         --AND DT_WEEK_START = NVL(trunc(P_DT_WEEK_START),DT_WEEK_START)
         and CD_WEEK=trunc(P_DT_WEEK_START)
         AND IC_ATIVO='S';
         null;

 END PX_GET_AGENDAMENTO ; 



 /********************************************************************* 
 PROCEDURE PX_GET_MARCACAO(
        P_CD_POLO         in ELO_AGENDAMENTO_CENTRO.CD_POLO%type,
         P_CD_CENTRO_EXPEDIDOR          in ELO_AGENDAMENTO_CENTRO.CD_CENTRO_EXPEDIDOR %type,
          P_DT_WEEK_START   in ELO_AGENDAMENTO.DT_WEEK_START%type,
        P_RETORNO         out T_CURSOR
)
 IS
  BEGIN
   OPEN P_RETORNO FOR
   SELECT * FROM ELO_MARCACAO
           WHERE
           P_CD_POLO IN(SELECT 

           AND SG_CLASSIFICACAO ='SEMPLAN'
           AND IC_ATIVO ='S';
           null;
  END  PX_GET_MARCACAO;         

  PROCEDURE PX_GET_MARCACAO(
        P_CD_POLO         in ELO_AGENDAMENTO_CENTRO.CD_POLO%type,
        P_DT_WEEK_START   in ELO_AGENDAMENTO_CENTRO.DT_WEEK_START%type,
        P_RETORNO         out T_CURSOR
)
 IS
  BEGIN
   OPEN P_RETORNO FOR
           SELECT * FROM ELO_MARCACAO
           WHERE
           (CD_POLO=P_CD_POLO OR CD_CENTRO IN ( select CD_CENTRO_EXPEDIDOR 
           FROM ELO_CARTEIRA
            WHERE CD_ELO_CARTEIRA IN ( SELECT CD_ELO_CARTEIRA  from ELO_MARCACA0))
                    AND SG_CLASSIFICACAO ='SEMPLAN'
         and IC_ATIVO='S';
         null;
   END PX_GET_MARCACAO ; 
   **************************************************************************/

   PROCEDURE PX_GET_ALL_AGENDAMENTO(
       P_CD_POLO         in ELO_AGENDAMENTO.CD_POLO%type,
        P_CD_CENTRO_EXPEDIDOR    in ELO_AGENDAMENTO.CD_CENTRO_EXPEDIDOR%type,
        P_CD_MACHINE      in ELO_AGENDAMENTO.CD_MACHINE%type,
        P_DT_WEEK_START   in ELO_AGENDAMENTO.DT_WEEK_START%type,
        P_RETORNO         out T_CURSOR
 )
  IS
  BEGIN
   OPEN P_RETORNO FOR
           SELECT * FROM ELO_AGENDAMENTO 
           WHERE
           CD_POLO=P_CD_POLO
           AND
           CD_CENTRO_EXPEDIDOR =P_CD_CENTRO_EXPEDIDOR
           AND
           CD_MACHINE =P_CD_MACHINE
           AND
           DT_WEEK_START=P_DT_WEEK_START
           AND
           IC_ATIVO ='S';
           null;

END PX_GET_ALL_AGENDAMENTO ;
 PROCEDURE PX_GET_AGENDAMENTO_SUPERVISOR(
      --  P_ELO_AGENDAMENTO in ELO_AGENDAMENTO_SUPERVISOR.CD_ELO_AGENDAMENTO%type,
        P_CD_POLO         in ELO_AGENDAMENTO.CD_POLO%type,
        P_DT_WEEK_START   in ELO_AGENDAMENTO.DT_WEEK_START%type,
        P_RETORNO         out T_CURSOR
)
  IS
  BEGIN
   OPEN P_RETORNO FOR

   SELECT * FROM ELO_AGENDAMENTO_SUPERVISOR
   WHERE
   CD_ELO_AGENDAMENTO IN(SELECT CD_ELO_AGENDAMENTO FROM ELO_AGENDAMENTO 
           WHERE
           (CD_POLO=P_CD_POLO OR CD_CENTRO_EXPEDIDOR IN ( SELECT CD_CENTRO_EXPEDIDOR
            FROM ELO_AGENDAMENTO_CENTRO
            WHERE
                    trim(CD_POLO) = NVL(trim(P_CD_POLO),null)

                AND
                    trunc(DT_WEEK_START) = NVL(trunc(P_DT_WEEK_START),DT_WEEK_START)))
                    and DT_WEEK_START = NVL(trunc(P_DT_WEEK_START),DT_WEEK_START)
         and IC_ATIVO='S');


   NULL;
   END PX_GET_AGENDAMENTO_SUPERVISOR;


   PROCEDURE PX_GET_AGENDAMENTO_ITEM(
       -- P_ELO_AGENDAMENTO in ELO_AGENDAMENTO_SUPERVISOR.CD_ELO_AGENDAMENTO%type,
        P_CD_POLO         in ELO_AGENDAMENTO.CD_POLO%type,
        P_DT_WEEK_START   in ELO_AGENDAMENTO.DT_WEEK_START%type,
        P_RETORNO         out T_CURSOR
)
IS
  BEGIN
   OPEN P_RETORNO FOR

   SELECT * FROM ELO_AGENDAMENTO_ITEM
   WHERE 
   CD_ELO_AGENDAMENTO_SUPERVISOR IN(SELECT CD_ELO_AGENDAMENTO_SUPERVISOR FROM ELO_AGENDAMENTO_SUPERVISOR
   WHERE
   CD_ELO_AGENDAMENTO IN(SELECT CD_ELO_AGENDAMENTO FROM ELO_AGENDAMENTO 
           WHERE
           (CD_POLO=P_CD_POLO OR CD_CENTRO_EXPEDIDOR IN ( SELECT CD_CENTRO_EXPEDIDOR
            FROM ELO_AGENDAMENTO_CENTRO
            WHERE
                    trim(CD_POLO) = NVL(trim(P_CD_POLO),null)

                AND
                    trunc(DT_WEEK_START) = NVL(trunc(P_DT_WEEK_START),DT_WEEK_START)))
                    and DT_WEEK_START = NVL(trunc(P_DT_WEEK_START),DT_WEEK_START)
         and IC_ATIVO='S'))
         AND IC_ATIVO='S';

    NULL;
   END PX_GET_AGENDAMENTO_ITEM;

PROCEDURE PX_GET_CARTEIRA(

     --  P_ELO_AGENDAMENTO in ELO_AGENDAMENTO_SUPERVISOR.CD_ELO_AGENDAMENTO%type,
        P_CD_POLO         in ELO_AGENDAMENTO.CD_POLO%type,
        P_DT_WEEK_START   in ELO_AGENDAMENTO.DT_WEEK_START%type,
        P_RETORNO         out T_CURSOR

)
IS
  BEGIN
   OPEN P_RETORNO FOR

  SELECT * FROM ELO_CARTEIRA
   WHERE
   CD_ELO_AGENDAMENTO_ITEM IN(SELECT CD_ELO_AGENDAMENTO_ITEM FROM ELO_AGENDAMENTO_ITEM
   WHERE 
   CD_ELO_AGENDAMENTO_SUPERVISOR IN(SELECT CD_ELO_AGENDAMENTO_SUPERVISOR FROM ELO_AGENDAMENTO_SUPERVISOR
   WHERE
   CD_ELO_AGENDAMENTO IN(SELECT CD_ELO_AGENDAMENTO FROM ELO_AGENDAMENTO 
           WHERE
           (CD_POLO=P_CD_POLO OR CD_CENTRO_EXPEDIDOR IN ( SELECT CD_CENTRO_EXPEDIDOR
            FROM ELO_AGENDAMENTO_CENTRO
            WHERE
                    trim(CD_POLO) = NVL(trim(P_CD_POLO),null)

                AND
                    trunc(DT_WEEK_START) = NVL(trunc(P_DT_WEEK_START),DT_WEEK_START)))
                    and DT_WEEK_START = NVL(trunc(P_DT_WEEK_START),DT_WEEK_START)
         and IC_ATIVO='S'))
         AND IC_ATIVO='S')
         and IC_ATIVO ='S'
           and QT_AGENDADA_CONFIRMADA > 0;



    NULL;
   END PX_GET_CARTEIRA;

   PROCEDURE PX_GET_CARTEIRA_DAY(
      --  P_ELO_AGENDAMENTO in ELO_AGENDAMENTO_SUPERVISOR.CD_ELO_AGENDAMENTO%type,
        P_CD_POLO         in ELO_AGENDAMENTO.CD_POLO%type,
        P_DT_WEEK_START   in ELO_AGENDAMENTO.DT_WEEK_START%type,
        P_RETORNO         out T_CURSOR


)
IS
  BEGIN
   OPEN P_RETORNO FOR
   SELECT * FROM ELO_CARTEIRA_DAY
   WHERE CD_ELO_CARTEIRA IN( SELECT CD_ELO_CARTEIRA FROM ELO_CARTEIRA
   WHERE
   CD_ELO_AGENDAMENTO_ITEM IN(SELECT CD_ELO_AGENDAMENTO_ITEM FROM ELO_AGENDAMENTO_ITEM
   WHERE 
   CD_ELO_AGENDAMENTO_SUPERVISOR IN(SELECT CD_ELO_AGENDAMENTO_SUPERVISOR FROM ELO_AGENDAMENTO_SUPERVISOR
   WHERE
   CD_ELO_AGENDAMENTO IN(SELECT CD_ELO_AGENDAMENTO FROM ELO_AGENDAMENTO 
           WHERE
           (CD_POLO=P_CD_POLO OR CD_CENTRO_EXPEDIDOR IN ( SELECT CD_CENTRO_EXPEDIDOR
            FROM ELO_AGENDAMENTO_CENTRO
            WHERE
                    trim(CD_POLO) = NVL(trim(P_CD_POLO),null)

                AND
                    trunc(DT_WEEK_START) = NVL(trunc(P_DT_WEEK_START),DT_WEEK_START)))
                    and DT_WEEK_START = NVL(trunc(P_DT_WEEK_START),DT_WEEK_START)
         and IC_ATIVO='S'))
         AND IC_ATIVO='S')
         and IC_ATIVO ='S'
           and QT_AGENDADA_CONFIRMADA > 0);

   NULL;
   END PX_GET_CARTEIRA_DAY;

   PROCEDURE PX_GET_CLIENTE(
       -- P_ELO_AGENDAMENTO in ELO_AGENDAMENTO_SUPERVISOR.CD_ELO_AGENDAMENTO%type,
        P_CD_POLO         in ELO_AGENDAMENTO.CD_POLO%type,
        P_DT_WEEK_START   in ELO_AGENDAMENTO.DT_WEEK_START%type,
        P_RETORNO         out T_CURSOR


)
IS
  BEGIN
   OPEN P_RETORNO FOR
   SELECT * FROM CTF.CLIENTE
WHERE   CD_CLIENTE_PAGADOR  IN( SELECT CD_CLIENTE_PAGADOR   FROM ELO_CARTEIRA
   WHERE
   CD_ELO_AGENDAMENTO_ITEM IN(SELECT CD_ELO_AGENDAMENTO_ITEM FROM ELO_AGENDAMENTO_ITEM
   WHERE 
   CD_ELO_AGENDAMENTO_SUPERVISOR IN(SELECT CD_ELO_AGENDAMENTO_SUPERVISOR FROM ELO_AGENDAMENTO_SUPERVISOR
   WHERE
   CD_ELO_AGENDAMENTO IN(SELECT CD_ELO_AGENDAMENTO FROM ELO_AGENDAMENTO 
           WHERE
           (CD_POLO=P_CD_POLO OR CD_CENTRO_EXPEDIDOR IN ( SELECT CD_CENTRO_EXPEDIDOR
            FROM ELO_AGENDAMENTO_CENTRO
            WHERE
                    trim(CD_POLO) = NVL(trim(P_CD_POLO),null)

                AND
                    trunc(DT_WEEK_START) = NVL(trunc(P_DT_WEEK_START),DT_WEEK_START)))
                    and DT_WEEK_START = NVL(trunc(P_DT_WEEK_START),DT_WEEK_START)
         and IC_ATIVO='S'))
         AND IC_ATIVO='S')
         and IC_ATIVO ='S'
           and QT_AGENDADA_CONFIRMADA > 0)
OR
CD_CLIENTE_RECEBEDOR  IN( SELECT CD_CLIENTE_RECEBEDOR   FROM ELO_CARTEIRA
   WHERE
   CD_ELO_AGENDAMENTO_ITEM IN(SELECT CD_ELO_AGENDAMENTO_ITEM FROM ELO_AGENDAMENTO_ITEM
   WHERE 
   CD_ELO_AGENDAMENTO_SUPERVISOR IN(SELECT CD_ELO_AGENDAMENTO_SUPERVISOR FROM ELO_AGENDAMENTO_SUPERVISOR
   WHERE
   CD_ELO_AGENDAMENTO IN(SELECT CD_ELO_AGENDAMENTO FROM ELO_AGENDAMENTO 
           WHERE
           (CD_POLO=P_CD_POLO OR CD_CENTRO_EXPEDIDOR IN ( SELECT CD_CENTRO_EXPEDIDOR
            FROM ELO_AGENDAMENTO_CENTRO
            WHERE
                    trim(CD_POLO) = NVL(trim(P_CD_POLO),null)

                AND
                    trunc(DT_WEEK_START) = NVL(trunc(P_DT_WEEK_START),DT_WEEK_START)))
                    and DT_WEEK_START = NVL(trunc(P_DT_WEEK_START),DT_WEEK_START)
         and IC_ATIVO='S'))
         AND IC_ATIVO='S')
         and IC_ATIVO ='S'
           and QT_AGENDADA_CONFIRMADA > 0);
           NULL;
           END PX_GET_CLIENTE;


PROCEDURE PX_GET_MARCACAO(
       --P_ELO_AGENDAMENTO in ELO_AGENDAMENTO_SUPERVISOR.CD_ELO_AGENDAMENTO%type,
        P_CD_POLO         in ELO_AGENDAMENTO.CD_POLO%type,
        P_DT_WEEK_START   in ELO_AGENDAMENTO.DT_WEEK_START%type,
        P_RETORNO         out T_CURSOR


)
IS
  BEGIN
   OPEN P_RETORNO FOR
SELECT * FROM ELO_MARCACAO
WHERE CD_ELO_CARTEIRA IN(SELECT CD_ELO_CARTEIRA FROM ELO_CARTEIRA
   WHERE
   CD_ELO_AGENDAMENTO_ITEM IN(SELECT CD_ELO_AGENDAMENTO_ITEM FROM ELO_AGENDAMENTO_ITEM
   WHERE 
   CD_ELO_AGENDAMENTO_SUPERVISOR IN(SELECT CD_ELO_AGENDAMENTO_SUPERVISOR FROM ELO_AGENDAMENTO_SUPERVISOR
   WHERE
   CD_ELO_AGENDAMENTO IN(SELECT CD_ELO_AGENDAMENTO FROM ELO_AGENDAMENTO 
           WHERE
           (CD_POLO=P_CD_POLO OR CD_CENTRO_EXPEDIDOR IN ( SELECT CD_CENTRO_EXPEDIDOR
            FROM ELO_AGENDAMENTO_CENTRO
            WHERE
                    trim(CD_POLO) = NVL(trim(P_CD_POLO),null)

                AND
                    trunc(DT_WEEK_START) = NVL(trunc(P_DT_WEEK_START),DT_WEEK_START)))
                    and DT_WEEK_START = NVL(trunc(P_DT_WEEK_START),DT_WEEK_START)
         and IC_ATIVO='S'))
         AND IC_ATIVO='S')
         and IC_ATIVO ='S'
           and QT_AGENDADA_CONFIRMADA > 0)
           and IC_ATIVO ='S';
           null;
END PX_GET_MARCACAO;



PROCEDURE PX_GET_CLINTE_MARCACAO(
        -- P_ELO_AGENDAMENTO in ELO_AGENDAMENTO_SUPERVISOR.CD_ELO_AGENDAMENTO%type,
        P_CD_POLO         in ELO_AGENDAMENTO.CD_POLO%type,
        P_DT_WEEK_START   in ELO_AGENDAMENTO.DT_WEEK_START%type,
        P_RETORNO         out T_CURSOR

)
IS
  BEGIN
   OPEN P_RETORNO FOR
   SELECT * FROM CTF.CLIENTE
   WHERE CD_CLIENTE IN(SELECT CD_CLIENTE FROM ELO_MARCACAO
WHERE CD_ELO_CARTEIRA IN(SELECT CD_ELO_CARTEIRA FROM ELO_CARTEIRA
   WHERE
   CD_ELO_AGENDAMENTO_ITEM IN(SELECT CD_ELO_AGENDAMENTO_ITEM FROM ELO_AGENDAMENTO_ITEM
   WHERE 
   CD_ELO_AGENDAMENTO_SUPERVISOR IN(SELECT CD_ELO_AGENDAMENTO_SUPERVISOR FROM ELO_AGENDAMENTO_SUPERVISOR
   WHERE
   CD_ELO_AGENDAMENTO IN(SELECT CD_ELO_AGENDAMENTO FROM ELO_AGENDAMENTO 
           WHERE
           (CD_POLO=P_CD_POLO OR CD_CENTRO_EXPEDIDOR IN ( SELECT CD_CENTRO_EXPEDIDOR
            FROM ELO_AGENDAMENTO_CENTRO
            WHERE
                    trim(CD_POLO) = NVL(trim(P_CD_POLO),null)

                AND
                    trunc(DT_WEEK_START) = NVL(trunc(P_DT_WEEK_START),DT_WEEK_START)))
                    and DT_WEEK_START = NVL(trunc(P_DT_WEEK_START),DT_WEEK_START)
         and IC_ATIVO='S'))
         AND IC_ATIVO='S')
         and IC_ATIVO ='S'
           and QT_AGENDADA_CONFIRMADA > 0)
           and IC_ATIVO ='S');



   NULL;
END PX_GET_CLINTE_MARCACAO;


PROCEDURE PX_SUM_ELO_CARTEIRA_DAY (
  --P_ELO_AGENDAMENTO in ELO_AGENDAMENTO_SUPERVISOR.CD_ELO_AGENDAMENTO%type,
        P_CD_POLO         in ELO_AGENDAMENTO.CD_POLO%type,
        P_CD_WEEK   in ELO_AGENDAMENTO.CD_WEEK%type,
        P_RETORNO         out T_CURSOR
)
IS
  BEGIN
   OPEN P_RETORNO FOR
SELECT SUM(NU_QUANTIDADE) FROM ELO_CARTEIRA_DAY ED
INNER JOIN ELO_CARTEIRA EC
ON ED.CD_ELO_CARTEIRA=EC.CD_ELO_CARTEIRA
 WHERE
   CD_ELO_AGENDAMENTO_ITEM IN(SELECT CD_ELO_AGENDAMENTO_ITEM FROM ELO_AGENDAMENTO_ITEM
   WHERE 
   CD_ELO_AGENDAMENTO_SUPERVISOR IN(SELECT CD_ELO_AGENDAMENTO_SUPERVISOR FROM ELO_AGENDAMENTO_SUPERVISOR
   WHERE
   CD_ELO_AGENDAMENTO IN(SELECT CD_ELO_AGENDAMENTO FROM ELO_AGENDAMENTO 
           WHERE
           (CD_POLO=P_CD_POLO OR CD_CENTRO_EXPEDIDOR IN ( SELECT CD_CENTRO_EXPEDIDOR
            FROM ELO_AGENDAMENTO_CENTRO
            WHERE
                    trim(CD_POLO) = NVL(trim(P_CD_POLO),null)

                AND
                    trim(CD_WEEK) = NVL(trim(P_CD_WEEK),null)))

                    and  trim(CD_WEEK) = NVL(trim(P_CD_WEEK),null)
         and IC_ATIVO='S'))
         AND IC_ATIVO='S')
         and IC_ATIVO ='S'
           and QT_AGENDADA_CONFIRMADA > 0
GROUP BY CD_TIPO_AGENDAMENTO, CD_CLIENTE,EC.CD_INCOTERMS,ED.NU_DIA_SEMANA ;
NULL;
END PX_SUM_ELO_CARTEIRA_DAY;



PROCEDURE PX_SUM_ELO_MARCACAO (
      --  P_ELO_AGENDAMENTO in ELO_AGENDAMENTO_SUPERVISOR.CD_ELO_AGENDAMENTO%type,
        P_CD_POLO         in ELO_AGENDAMENTO.CD_POLO%type,
        P_CD_WEEK   in ELO_AGENDAMENTO.CD_WEEK%type,
        P_RETORNO         out T_CURSOR
)
IS
  BEGIN
   OPEN P_RETORNO FOR

SELECT SUM(ED.NU_QUANTIDADE),SG_CLASSIFICACAO,EC.CD_CLIENTE,EC.CD_INCOTERMS,NU_DIA_SEMANA,IC_PRIORIDADE,ed.NU_QUANTIDADE FROM ELO_MARCACAO EM
INNER JOIN ELO_CARTEIRA EC
ON EM.CD_ELO_CARTEIRA=EC.CD_ELO_CARTEIRA
INNER JOIN ELO_CARTEIRA_DAY ED
ON ED.CD_ELO_CARTEIRA=EC.CD_ELO_CARTEIRA
WHERE
   CD_ELO_AGENDAMENTO_ITEM IN(SELECT CD_ELO_AGENDAMENTO_ITEM FROM ELO_AGENDAMENTO_ITEM
   WHERE 
   CD_ELO_AGENDAMENTO_SUPERVISOR IN(SELECT CD_ELO_AGENDAMENTO_SUPERVISOR FROM ELO_AGENDAMENTO_SUPERVISOR
   WHERE
   CD_ELO_AGENDAMENTO IN(SELECT CD_ELO_AGENDAMENTO FROM ELO_AGENDAMENTO 
           WHERE
           (CD_POLO=P_CD_POLO OR CD_CENTRO_EXPEDIDOR IN ( SELECT CD_CENTRO_EXPEDIDOR
            FROM ELO_AGENDAMENTO_CENTRO
             WHERE
                    trim(CD_POLO) = NVL(trim(P_CD_POLO),null)
                      
          ))
                   
                    and  trim(CD_WEEK) = NVL(trim(P_CD_WEEK),null)
         and IC_ATIVO='S'))
         AND IC_ATIVO='S')
         and EC.IC_ATIVO ='S'
           and QT_AGENDADA_CONFIRMADA > 0
            AND SG_CLASSIFICACAO IN('PLAN','REPLAN')
GROUP BY SG_CLASSIFICACAO,EC.CD_CLIENTE,EC.CD_INCOTERMS,NU_DIA_SEMANA,ed.NU_QUANTIDADE,IC_PRIORIDADE ;
NULL;
END PX_SUM_ELO_MARCACAO;

PROCEDURE PX_SUM_ALL_ELO_MARCACAO (
       P_CD_POLO         in ELO_AGENDAMENTO.CD_POLO%type,
        P_CD_CENTRO_EXPEDIDOR    in ELO_AGENDAMENTO.CD_CENTRO_EXPEDIDOR%type,
        P_CD_MACHINE      in ELO_AGENDAMENTO.CD_MACHINE%type,
        P_CD_WEEK   in ELO_AGENDAMENTO.CD_WEEK%type,
        P_RETORNO         out T_CURSOR
)
IS
  BEGIN
   OPEN P_RETORNO FOR

SELECT SUM(ED.NU_QUANTIDADE),SG_CLASSIFICACAO,EC.CD_CLIENTE,EC.CD_INCOTERMS,NU_DIA_SEMANA,IC_PRIORIDADE,ed.NU_QUANTIDADE FROM ELO_MARCACAO EM
INNER JOIN ELO_CARTEIRA EC
ON EM.CD_ELO_CARTEIRA=EC.CD_ELO_CARTEIRA
INNER JOIN ELO_CARTEIRA_DAY ED
ON ED.CD_ELO_CARTEIRA=EC.CD_ELO_CARTEIRA
WHERE
   CD_ELO_AGENDAMENTO_ITEM IN(SELECT CD_ELO_AGENDAMENTO_ITEM FROM ELO_AGENDAMENTO_ITEM
   WHERE 
   CD_ELO_AGENDAMENTO_SUPERVISOR IN(SELECT CD_ELO_AGENDAMENTO_SUPERVISOR FROM ELO_AGENDAMENTO_SUPERVISOR
   WHERE
   CD_ELO_AGENDAMENTO IN(SELECT CD_ELO_AGENDAMENTO FROM ELO_AGENDAMENTO EA
           WHERE
           CD_POLO=P_CD_POLO
           AND
           CD_CENTRO_EXPEDIDOR =P_CD_CENTRO_EXPEDIDOR
           AND
           CD_MACHINE =P_CD_MACHINE
           AND
           EA.CD_WEEK=P_CD_WEEK
           AND
           IC_ATIVO ='S'
          
         and IC_ATIVO='S'))
         AND IC_ATIVO='S')
         and EC.IC_ATIVO ='S'
           and QT_AGENDADA_CONFIRMADA > 0
          AND SG_CLASSIFICACAO IN('PLAN','REPLAN')
GROUP BY SG_CLASSIFICACAO,EC.CD_CLIENTE,EC.CD_INCOTERMS,NU_DIA_SEMANA,ed.NU_QUANTIDADE,IC_PRIORIDADE ;
NULL;
END PX_SUM_ALL_ELO_MARCACAO;
/**************************older version******************************************* 
PROCEDURE PX_SUM_GET_CARTEIRA(

       P_CD_POLO         in ELO_AGENDAMENTO.CD_POLO%type,
        P_DT_WEEK_START   in ELO_AGENDAMENTO.DT_WEEK_START%type,

      -- P_CD_INCOTERMS    in ELO_CARTEIRA.CD_INCOTERMS %TYPE,
        P_RETORNO         out T_CURSOR



)
IS
  BEGIN
 -- IF P_CD_INCOTERMS = 'FOB'
--THEN
  OPEN P_RETORNO FOR

SELECT sum(ed.NU_QUANTIDADE)NU_QUANTIDADE,ec.QT_PROGRAMADA,ec.CD_TIPO_AGENDAMENTO,ec.NO_CLIENTE,ec.CD_CLIENTE,ec.CD_INCOTERMS,ed.NU_DIA_SEMANA,CD_CLIENTE_PAGADOR,ec.CD_CLIENTE_RECEBEDOR
fROM ELO_CARTEIRA_DAY ed
INNER JOIN ELO_CARTEIRA ec
on ed.CD_ELO_CARTEIRA=ec.CD_ELO_CARTEIRA
WHERE
   CD_ELO_AGENDAMENTO_ITEM IN(SELECT CD_ELO_AGENDAMENTO_ITEM FROM ELO_AGENDAMENTO_ITEM
   WHERE 
   CD_ELO_AGENDAMENTO_SUPERVISOR IN(SELECT CD_ELO_AGENDAMENTO_SUPERVISOR FROM ELO_AGENDAMENTO_SUPERVISOR
   WHERE
   CD_ELO_AGENDAMENTO IN(SELECT CD_ELO_AGENDAMENTO FROM ELO_AGENDAMENTO 
           WHERE
           (CD_POLO=P_CD_POLO OR CD_CENTRO_EXPEDIDOR IN ( SELECT CD_CENTRO_EXPEDIDOR
            FROM ELO_AGENDAMENTO_CENTRO
            WHERE
                    trim(CD_POLO) = NVL(trim(P_CD_POLO),null)

                AND
                    trunc(DT_WEEK_START) = NVL(trunc(P_DT_WEEK_START),DT_WEEK_START)))
                    and DT_WEEK_START = NVL(trunc(P_DT_WEEK_START),DT_WEEK_START)
        and IC_ATIVO='S'
         ))
        AND IC_ATIVO='S'
        )
       and IC_ATIVO ='S'
           and QT_AGENDADA_CONFIRMADA > 0

GROUP BY ec.CD_TIPO_AGENDAMENTO,ec.NO_CLIENTE,ec.CD_CLIENTE,ec.QT_PROGRAMADA, ec.CD_INCOTERMS ,ed.NU_DIA_SEMANA,ec.CD_CLIENTE_PAGADOR,ec.CD_CLIENTE_RECEBEDOR;









--ELSE IF P_CD_INCOTERMS = 'CIF'
--THEN
--OPEN P_RETORNO  FOR
--SELECT sum(ed.NU_QUANTIDADE),ec.CD_TIPO_AGENDAMENTO,ec.CD_CLIENTE,ec.CD_INCOTERMS,ec.CD_CLIENTE_RECEBEDOR
--fROM ELO_CARTEIRA_DAY ed
--INNER JOIN ELO_CARTEIRA ec
--on ed.CD_ELO_CARTEIRA=ec.CD_ELO_CARTEIRA
--GROUP BY ec.CD_TIPO_AGENDAMENTO, ec.CD_CLIENTE, ec.CD_INCOTERMS ,ed.NU_DIA_SEMANA,ec.CD_CLIENTE_RECEBEDOR;
--END IF;
--END IF;
END PX_SUM_GET_CARTEIRA;




PROCEDURE PX_SUM_ALL_GET_CARTEIRA(

      P_CD_POLO         in ELO_AGENDAMENTO.CD_POLO%type,
        P_CD_CENTRO_EXPEDIDOR    in ELO_AGENDAMENTO.CD_CENTRO_EXPEDIDOR%type,
        P_CD_MACHINE      in ELO_AGENDAMENTO.CD_MACHINE%type,
        P_DT_WEEK_START   in ELO_AGENDAMENTO.DT_WEEK_START%type,
        P_RETORNO         out T_CURSOR



)
IS
  BEGIN
 -- IF P_CD_INCOTERMS = 'FOB'
--THEN
  OPEN P_RETORNO FOR

SELECT sum(ed.NU_QUANTIDADE)NU_QUANTIDADE,ec.QT_PROGRAMADA,ec.CD_TIPO_AGENDAMENTO,ec.NO_CLIENTE,ec.CD_CLIENTE,ec.CD_INCOTERMS,ed.NU_DIA_SEMANA,CD_CLIENTE_PAGADOR,ec.CD_CLIENTE_RECEBEDOR
fROM ELO_CARTEIRA_DAY ed
INNER JOIN ELO_CARTEIRA ec
on ed.CD_ELO_CARTEIRA=ec.CD_ELO_CARTEIRA
WHERE
   CD_ELO_AGENDAMENTO_ITEM IN(SELECT CD_ELO_AGENDAMENTO_ITEM FROM ELO_AGENDAMENTO_ITEM
   WHERE 
   CD_ELO_AGENDAMENTO_SUPERVISOR IN(SELECT CD_ELO_AGENDAMENTO_SUPERVISOR FROM ELO_AGENDAMENTO_SUPERVISOR
   WHERE
   CD_ELO_AGENDAMENTO IN(SELECT CD_ELO_AGENDAMENTO FROM ELO_AGENDAMENTO 

           WHERE
           CD_POLO=P_CD_POLO
           AND
           CD_CENTRO_EXPEDIDOR =P_CD_CENTRO_EXPEDIDOR
           AND
           CD_MACHINE =P_CD_MACHINE
           AND
           DT_WEEK_START=P_DT_WEEK_START
           AND
           IC_ATIVO ='S'
         ))
        AND IC_ATIVO='S'
        )
       and IC_ATIVO ='S'
           and QT_AGENDADA_CONFIRMADA > 0

GROUP BY ec.CD_TIPO_AGENDAMENTO,ec.NO_CLIENTE,ec.CD_CLIENTE,ec.QT_PROGRAMADA, ec.CD_INCOTERMS ,ed.NU_DIA_SEMANA,ec.CD_CLIENTE_PAGADOR,ec.CD_CLIENTE_RECEBEDOR;


END PX_SUM_ALL_GET_CARTEIRA;



***************************************************************************/

PROCEDURE PX_SUM_GET_CARTEIRA_AAA(
        P_CD_POLO           in VND.ELO_AGENDAMENTO.CD_POLO%type,
        P_CENTRO            IN VND.ELO_AGENDAMENTO.CD_CENTRO_EXPEDIDOR%TYPE,
        P_MAQUINA           IN VND.ELO_AGENDAMENTO.CD_MACHINE%TYPE,
        P_CD_WEEK           in VND.ELO_AGENDAMENTO.CD_WEEK%type,
        P_RETORNO           out T_CURSOR
        )

    IS
    BEGIN

    OPEN P_RETORNO FOR
    WITH CTE_RESULT AS (
    SELECT 
        CASE
            WHEN EC.CD_TIPO_AGENDAMENTO = 24 THEN 'Plan'
            WHEN EC.CD_TIPO_AGENDAMENTO = 25 THEN 'Replan'
            ELSE 'Sem Cota'
            END "TIPO_AGENDAMENTO",
        EC.CD_ELO_AGENDAMENTO,
        EC.CD_INCOTERMS,
        CLI.NO_CLIENTE "CLIENTE",
        CASE
            WHEN TRIM(EC.CD_INCOTERMS) = 'FOB' THEN EC.CD_CLIENTE_PAGADOR
            WHEN TRIM(EC.CD_INCOTERMS) = 'CIF' THEN EC.CD_CLIENTE_RECEBEDOR
        END "COD_CLIENTE",
        SUMOFAG.SEG, 
        SUMOFAG.TER, 
        SUMOFAG.QUA,  
        SUMOFAG.QUI, 
        SUMOFAG.SEX,  
        SUMOFAG.SAB,  
        SUMOFAG.DOM, 
        TOT_QT.NU_QUANTIDADE "NU_QUANTIDADE",
        SUMOFMAR.SEG "MAR_SEG",
        SUMOFMAR.TER "MAR_TER", 
        SUMOFMAR.QUA "MAR_QUA",  
        SUMOFMAR.QUI "MAR_QUI", 
        SUMOFMAR.SEX "MAR_SEX",  
        SUMOFMAR.SAB "MAR_SAB",  
        SUMOFMAR.DOM "MAR_DOM", 
        MAR_QT.MARCACAO_TOTAL "MARCACAO_TOTAL"
    FROM VND.ELO_CARTEIRA EC
    INNER JOIN VND.ELO_AGENDAMENTO EA ON EC.CD_ELO_AGENDAMENTO = EA.CD_ELO_AGENDAMENTO
    INNER JOIN VND.ELO_STATUS STS ON STS.CD_ELO_STATUS = EA.CD_ELO_STATUS
    INNER JOIN CTF.CLIENTE CLI ON CLI.CD_CLIENTE = EC.CD_CLIENTE_PAGADOR
    INNER JOIN (SELECT  
                EA.CD_ELO_AGENDAMENTO,
                EAI.CD_ELO_AGENDAMENTO_ITEM,
                ECX.CD_ELO_CARTEIRA,
                SUM(CASE EAD.NU_DIA_SEMANA WHEN 1 THEN EAD.NU_QUANTIDADE ELSE 0 END) AS SEG,
                SUM(CASE EAD.NU_DIA_SEMANA WHEN 2 THEN EAD.NU_QUANTIDADE ELSE 0 END) AS TER,
                SUM(CASE EAD.NU_DIA_SEMANA WHEN 3 THEN EAD.NU_QUANTIDADE ELSE 0 END) AS QUA,
                SUM(CASE EAD.NU_DIA_SEMANA WHEN 4 THEN EAD.NU_QUANTIDADE ELSE 0 END) AS QUI,
                SUM(CASE EAD.NU_DIA_SEMANA WHEN 5 THEN EAD.NU_QUANTIDADE ELSE 0 END) AS SEX,
                SUM(CASE EAD.NU_DIA_SEMANA WHEN 6 THEN EAD.NU_QUANTIDADE ELSE 0 END) AS SAB,
                SUM(CASE EAD.NU_DIA_SEMANA WHEN 7 THEN EAD.NU_QUANTIDADE ELSE 0 END) AS DOM
                FROM VND.ELO_AGENDAMENTO EA
                INNER JOIN VND.ELO_CARTEIRA ECX ON EA.CD_ELO_AGENDAMENTO = ECX.CD_ELO_AGENDAMENTO
                INNER JOIN VND.ELO_AGENDAMENTO_SUPERVISOR EAS ON EA.CD_ELO_AGENDAMENTO = EAS.CD_ELO_AGENDAMENTO
                INNER JOIN VND.ELO_AGENDAMENTO_ITEM EAI ON (EAS.CD_ELO_AGENDAMENTO_SUPERVISOR =  EAI.CD_ELO_AGENDAMENTO_SUPERVISOR
                                                        AND (ECX.CD_CLIENTE_PAGADOR = EAI.CD_CLIENTE OR ECX.CD_CLIENTE_RECEBEDOR = EAI.CD_CLIENTE))
                INNER JOIN VND.ELO_AGENDAMENTO_WEEK EAW ON EAI.CD_ELO_AGENDAMENTO_ITEM = EAW.CD_ELO_AGENDAMENTO_ITEM
                INNER JOIN VND.ELO_AGENDAMENTO_DAY EAD ON EAW.CD_ELO_AGENDAMENTO_WEEK = EAD.CD_ELO_AGENDAMENTO_WEEK
                /*INNER JOIN VND.ELO_AGENDAMENTO_SUPERVISOR EAS ON EA.CD_ELO_AGENDAMENTO = EAS.CD_ELO_AGENDAMENTO
                INNER JOIN VND.ELO_AGENDAMENTO_ITEM EAI ON EAS.CD_ELO_AGENDAMENTO_SUPERVISOR = EAI.CD_ELO_AGENDAMENTO_SUPERVISOR
                INNER JOIN VND.ELO_CARTEIRA EC ON EA.CD_ELO_AGENDAMENTO = EC.CD_ELO_AGENDAMENTO
                LEFT JOIN VND.ELO_CARTEIRA_DAY ECD ON EC.CD_ELO_CARTEIRA = ECD.CD_ELO_CARTEIRA*/
                WHERE EA.IC_ATIVO ='S'
                GROUP BY EA.CD_ELO_AGENDAMENTO,  ECX.CD_ELO_CARTEIRA, EAI.CD_ELO_AGENDAMENTO_ITEM) SUMOFAG 
        ON SUMOFAG.CD_ELO_AGENDAMENTO = EC.CD_ELO_AGENDAMENTO AND SUMOFAG.CD_ELO_CARTEIRA = EC.CD_ELO_CARTEIRA 
    LEFT JOIN(
                SELECT   
                EA.CD_ELO_AGENDAMENTO,
                EC.NU_CONTRATO,
                EC.NU_ORDEM_VENDA,
                EC.CD_ELO_CARTEIRA,
                SUM(NVL(EC.QT_AGENDADA_CONFIRMADA,0)) AS NU_QUANTIDADE
                FROM VND.ELO_CARTEIRA EC
                INNER JOIN VND.ELO_AGENDAMENTO EA ON EA.CD_ELO_AGENDAMENTO = EC.CD_ELO_AGENDAMENTO
                INNER JOIN VND.ELO_AGENDAMENTO_SUPERVISOR EAS ON EA.CD_ELO_AGENDAMENTO = EAS.CD_ELO_AGENDAMENTO
                INNER JOIN VND.ELO_AGENDAMENTO_ITEM EAI ON (EAS.CD_ELO_AGENDAMENTO_SUPERVISOR =  EAI.CD_ELO_AGENDAMENTO_SUPERVISOR
                                                        AND (EC.CD_CLIENTE_PAGADOR = EAI.CD_CLIENTE OR EC.CD_CLIENTE_RECEBEDOR = EAI.CD_CLIENTE))
                GROUP BY EA.CD_ELO_AGENDAMENTO, EC.NU_CONTRATO, EC.NU_ORDEM_VENDA, EC.CD_ELO_CARTEIRA) TOT_QT
        ON (TOT_QT.CD_ELO_AGENDAMENTO = EC.CD_ELO_AGENDAMENTO AND TOT_QT.NU_CONTRATO = EC.NU_CONTRATO )
        
    LEFT JOIN (SELECT  
                EA.CD_ELO_AGENDAMENTO,
                EC.CD_ELO_CARTEIRA, 
                SUM(CASE ECD.NU_DIA_SEMANA WHEN 1 THEN MAR.NU_QUANTIDADE ELSE 0 END) AS SEG,
                SUM(CASE ECD.NU_DIA_SEMANA WHEN 2 THEN MAR.NU_QUANTIDADE ELSE 0 END) AS TER,
                SUM(CASE ECD.NU_DIA_SEMANA WHEN 3 THEN MAR.NU_QUANTIDADE ELSE 0 END) AS QUA,
                SUM(CASE ECD.NU_DIA_SEMANA WHEN 4 THEN MAR.NU_QUANTIDADE ELSE 0 END) AS QUI,
                SUM(CASE ECD.NU_DIA_SEMANA WHEN 5 THEN MAR.NU_QUANTIDADE ELSE 0 END) AS SEX,
                SUM(CASE ECD.NU_DIA_SEMANA WHEN 6 THEN MAR.NU_QUANTIDADE ELSE 0 END) AS SAB,
                SUM(CASE ECD.NU_DIA_SEMANA WHEN 7 THEN MAR.NU_QUANTIDADE ELSE 0 END) AS DOM
                FROM VND.ELO_AGENDAMENTO EA 
                INNER JOIN VND.ELO_AGENDAMENTO_SUPERVISOR EAS ON EA.CD_ELO_AGENDAMENTO = EAS.CD_ELO_AGENDAMENTO
                INNER JOIN VND.ELO_CARTEIRA EC ON EA.CD_ELO_AGENDAMENTO = EC.CD_ELO_AGENDAMENTO
                LEFT JOIN VND.ELO_CARTEIRA_DAY ECD ON EC.CD_ELO_CARTEIRA = ECD.CD_ELO_CARTEIRA
                LEFT JOIN VND.ELO_MARCACAO MAR ON EC.CD_ELO_CARTEIRA = MAR.CD_ELO_CARTEIRA
                WHERE EA.IC_ATIVO ='S'
                GROUP BY EA.CD_ELO_AGENDAMENTO,EC.CD_ELO_CARTEIRA ) SUMOFMAR
        ON SUMOFMAR.CD_ELO_AGENDAMENTO = EC.CD_ELO_AGENDAMENTO  AND SUMOFMAR.CD_ELO_CARTEIRA = EC.CD_ELO_CARTEIRA
        
    LEFT JOIN(
                SELECT  MAR.CD_ELO_CARTEIRA, MAR.SG_CLASSIFICACAO, SUM(MAR.NU_QUANTIDADE) "MARCACAO_TOTAL"
                FROM    VND.ELO_MARCACAO MAR
                WHERE   MAR.DH_ENTRADA IS NOT NULL
                GROUP BY MAR.CD_ELO_CARTEIRA, MAR.SG_CLASSIFICACAO
            ) MAR_QT
                
        ON (EC.CD_ELO_CARTEIRA = MAR_QT.CD_ELO_CARTEIRA)
        
    WHERE ( EA.IC_ATIVO ='S' )
    AND (EC.IC_ATIVO = 'S')
    AND (EC.QT_AGENDADA_CONFIRMADA > 0 OR EC.QT_AGENDADA_CONFIRMADA IS NOT NULL)
    AND (EA.CD_WEEK = P_CD_WEEK) 
    AND (P_CENTRO IS NULL OR EA.CD_CENTRO_EXPEDIDOR = P_CENTRO)
    AND (P_CD_POLO IS NULL OR EA.CD_POLO = P_CD_POLO)
    AND (P_MAQUINA IS NULL OR EA.CD_MACHINE = P_MAQUINA)
    )
 
    SELECT 
        "Classe", "NomeCliente", "NumCliente", "Modalidade", SEG, TER, QUA, QUI, SEX, SAB, DOM, SUM("TotalPlan") "TotalPlan",
        "MAR_SEG", "MAR_TER", "MAR_QUA", "MAR_QUI", "MAR_SEX", "MAR_SAB", "MAR_DOM", NVL("TotalExec", 0) "TotalExec", 
        SUM(ROUND((("TotalPlan") / ("TotalExec")*100), 2)) "%"
        FROM(   
            SELECT 
                    TIPO_AGENDAMENTO "Classe"
                  , CLIENTE "NomeCliente"
                  , COD_CLIENTE "NumCliente"
                  , CD_INCOTERMS "Modalidade"
                  , SUM(ROUND(SEG, 2)) SEG
                  , SUM(ROUND(TER, 2)) TER
                  , SUM(ROUND(QUA, 2)) QUA
                  , SUM(ROUND(QUI, 2)) "QUI"
                  , SUM(ROUND(SEX, 2)) "SEX"
                  , SUM(ROUND(SAB, 2)) "SAB"
                  , SUM(ROUND(DOM, 2)) "DOM"
                  , ROUND(NU_QUANTIDADE, 2) "TotalPlan"
                  , SUM(NVL(ROUND("MAR_SEG", 2),0)) "MAR_SEG"
                  , SUM(NVL(ROUND("MAR_TER", 2),0)) "MAR_TER"
                  , SUM(NVL(ROUND("MAR_QUA", 2),0)) "MAR_QUA"
                  , SUM(NVL(ROUND("MAR_QUI", 2),0)) "MAR_QUI"
                  , SUM(NVL(ROUND("MAR_SEX", 2),0)) "MAR_SEX"
                  , SUM(NVL(ROUND("MAR_SAB", 2),0)) "MAR_SAB"
                  , SUM(NVL(ROUND("MAR_DOM", 2),0)) "MAR_DOM"
                  , SUM(ROUND(MARCACAO_TOTAL, 2)) "TotalExec"
                 
            FROM CTE_RESULT 
            GROUP BY TIPO_AGENDAMENTO, CLIENTE, COD_CLIENTE, CD_INCOTERMS, NU_QUANTIDADE
        )
        GROUP BY "Classe", "NomeCliente", "NumCliente", "Modalidade", SEG, TER, QUA, QUI, SEX, SAB, DOM, "MAR_SEG", "MAR_TER", "MAR_QUA", 
            "MAR_QUI", "MAR_SEX", "MAR_SAB", "MAR_DOM", "TotalExec"
        ORDER BY 1, 2, 3, 4; 

END PX_SUM_GET_CARTEIRA_AAA;


PROCEDURE PX_SUM_GET_CARTEIRA(
        P_CD_POLO           in VND.ELO_AGENDAMENTO.CD_POLO%type,
        P_CENTRO            IN VND.ELO_AGENDAMENTO.CD_CENTRO_EXPEDIDOR%TYPE,
        P_MAQUINA           IN VND.ELO_AGENDAMENTO.CD_MACHINE%TYPE,
        P_CD_WEEK           in VND.ELO_AGENDAMENTO.CD_WEEK%type,
        P_RETORNO           out T_CURSOR
        )

    IS
    P_SUPERVISOR            VND.ELO_AGENDAMENTO_SUPERVISOR.CD_SALES_GROUP%TYPE;
    BEGIN

    
    P_SUPERVISOR:=null;

    PX_SUM_GET_CARTEIRA(P_CD_POLO, P_CENTRO, P_MAQUINA, P_CD_WEEK, P_SUPERVISOR,  P_RETORNO);
    

END PX_SUM_GET_CARTEIRA;



PROCEDURE PX_SUM_GET_CARTEIRA(
        P_CD_POLO           in VND.ELO_AGENDAMENTO.CD_POLO%type,
        P_CENTRO            IN VND.ELO_AGENDAMENTO.CD_CENTRO_EXPEDIDOR%TYPE,
        P_MAQUINA           IN VND.ELO_AGENDAMENTO.CD_MACHINE%TYPE,
        P_CD_WEEK           in VND.ELO_AGENDAMENTO.CD_WEEK%type,
        P_SUPERVISOR        IN VND.ELO_AGENDAMENTO_SUPERVISOR.CD_SALES_GROUP%TYPE,
        P_RETORNO           out T_CURSOR
        )

    IS
    BEGIN

    OPEN P_RETORNO FOR
        WITH CTE_AGENDAMENTO AS 
        (
        SELECT AGE.CD_ELO_AGENDAMENTO, AGE.CD_CENTRO_EXPEDIDOR, 
        AGE.CD_MACHINE, ma.DS_MACHINE, AGE.CD_WEEK ,
        es.DS_STATUS, AGE.CD_ELO_STATUS
        FROM VND.ELO_AGENDAMENTO AGE 
        LEFT JOIN CTF.MACHINE ma
        on AGE.CD_MACHINE = ma.CD_MACHINE
        inner join VND.ELO_STATUS es
        on es.CD_ELO_STATUS = AGE.CD_ELO_STATUS
        
        WHERE AGE.IC_ATIVO = 'S'
        AND (es.SG_STATUS IN ('PLAN','AGCTR','AGENC'))
        AND (P_CD_WEEK is null OR AGE.CD_WEEK = P_CD_WEEK)
        --AND ('W182018' is null OR AGE.CD_WEEK = 'W182018')
        and (P_MAQUINA is null OR AGE.CD_MACHINE IN (P_MAQUINA))
        and (P_CD_POLO is null OR AGE.CD_POLO IN (P_CD_POLO))
        
        ),
        --SELECT * FROM CTE_AGENDAMENTO
        
    CTE_CARTEIRA AS 
        (
        
        SELECT DISTINCT 
        CTAF.CD_ELO_CARTEIRA , 
        CTAF.CD_ELO_AGENDAMENTO, 
        CTAF.CD_TIPO_AGENDAMENTO, 
        STS.DS_STATUS DS_TIPO_AGENDAMENTO,
        CTAF.CD_TIPO_REPLAN, 
        CTAF.QT_AGENDADA_CONFIRMADA,
        CTAF.CD_ELO_AGENDAMENTO_ITEM,
        CTAF.CD_INCOTERMS,
        CTAF.CD_CLIENTE ,
        CTAF.NO_CLIENTE ,
        CTAF.CD_CLIENTE_PAGADOR,
        CTAF.NO_CLIENTE_PAGADOR,
        CTAF.CD_CLIENTE_RECEBEDOR,
        CTAF.NO_CLIENTE_RECEBEDOR,
        CASE
            WHEN TRIM(CTAF.CD_INCOTERMS) = 'FOB' THEN CTAF.CD_CLIENTE_PAGADOR
            WHEN TRIM(CTAF.CD_INCOTERMS) = 'CIF' THEN CTAF.CD_CLIENTE_RECEBEDOR
        END COD_CLIENTE, 
        
        CASE
            WHEN TRIM(CTAF.CD_INCOTERMS) = 'FOB' THEN CTAF.NO_CLIENTE_PAGADOR
            WHEN TRIM(CTAF.CD_INCOTERMS) = 'CIF' THEN CTAF.NO_CLIENTE_RECEBEDOR
        END CLIENTE,         
        
        CTAF.DH_BACKLOG_CIF,
        CTAF.DS_CENTRO_EXPEDIDOR,
        CTAF.CD_CENTRO_EXPEDIDOR,
        CTAF.CD_SALES_GROUP,
        CTAF.CD_GRUPO_EMBALAGEM,
        CTAF.IC_ATIVO,
        CTAF.QT_SALDO
        FROM VND.ELO_CARTEIRA CTAF
        INNER JOIN CTE_AGENDAMENTO AGEF
        ON CTAF.CD_ELO_AGENDAMENTO = AGEF.CD_ELO_AGENDAMENTO
        LEFT JOIN VND.ELO_STATUS STS 
        ON STS.CD_ELO_STATUS = CTAF.CD_TIPO_AGENDAMENTO
        WHERE
        CTAF.IC_ATIVO = 'S'
        and (P_CENTRO is null or CTAF.CD_CENTRO_EXPEDIDOR = P_CENTRO)
        --and ('6060' is null or CTAF.CD_CENTRO_EXPEDIDOR = '6060')
        AND ((CTAF.CD_TIPO_AGENDAMENTO IN (22, 23, 24) AND 
                NVL(CTAF.QT_AGENDADA_CONFIRMADA,0) <> 0 AND 
                (CTAF.IC_CORTADO_FABRICA <> 1 OR CTAF.IC_CORTADO_FABRICA IS NULL))
                OR (CTAF.QT_AGENDADA_CONFIRMADA > 0 AND CTAF.CD_TIPO_AGENDAMENTO = 25 AND CTAF.CD_STATUS_REPLAN = 32) 
        )
        and exists (select 1 from vnd.elo_agendamento_supervisor sup
        INNER JOIN vnd.elo_agendamento_item item 
        on sup.CD_ELO_AGENDAMENTO_SUPERVISOR = item.CD_ELO_AGENDAMENTO_SUPERVISOR
        where AGEF.CD_ELO_AGENDAMENTO = sup.CD_ELO_AGENDAMENTO
        AND CTAF.CD_ELO_AGENDAMENTO_ITEM = item.CD_ELO_AGENDAMENTO_ITEM
        AND (P_SUPERVISOR IS NULL OR SUP.CD_SALES_GROUP = P_SUPERVISOR ))
        
        ),
        --SELECT * FROM CTE_CARTEIRA
        
        CTE_AGENDAMENTO_FILTER AS 
        (
        SELECT ag.CD_ELO_AGENDAMENTO, ag.CD_CENTRO_EXPEDIDOR, ag.CD_MACHINE, ag.DS_MACHINE, ag.CD_WEEK , ag.DS_STATUS, ag.CD_ELO_STATUS
        FROM CTE_AGENDAMENTO ag
        WHERE 
            EXISTS (
                    SELECT 1 FROM CTE_CARTEIRA CTA 
                    WHERE 
                    CTA.CD_ELO_AGENDAMENTO = ag.CD_ELO_AGENDAMENTO
                    )
        ),
        --SELECT * FROM CTE_AGENDAMENTO_FILTER
        
        ELO_AG_DAY_BY_INCOTERMS_ITEM  AS (
        SELECT  EA_SUP_I.CD_ELO_AGENDAMENTO, EA_SUP_I.CD_SALES_GROUP , EAG_ITEM_I.CD_ELO_AGENDAMENTO_ITEM, EAG_ITEM_I.CD_INCOTERMS, 
        DAYY.CD_GRUPO_EMBALAGEM, DAYY.NU_DIA_SEMANA, SUM(DAYY.NU_QUANTIDADE) NU_QUANTIDADE, 
        MAX(CD_COTA_COMPARTILHADA) CD_COTA_COMPARTILHADA, EAG_ITEM_I.CD_CLIENTE
        FROM CTE_AGENDAMENTO_FILTER FILT
        INNER JOIN VND.ELO_AGENDAMENTO_SUPERVISOR EA_SUP_I  
        ON FILT.CD_ELO_AGENDAMENTO = EA_SUP_I.CD_ELO_AGENDAMENTO
        INNER JOIN VND.VW_ELO_AGENDAMENTO_ITEM_R EAG_ITEM_I
        ON 
        EAG_ITEM_I.CD_ELO_AGENDAMENTO_SUPERVISOR = EA_SUP_I.CD_ELO_AGENDAMENTO_SUPERVISOR
        AND EAG_ITEM_I.IC_ATIVO = 'S'	
        
        INNER JOIN VND.VW_ELO_AGENDAMENTO_WEEK_PLAN EAG_WE_I
        ON EAG_ITEM_I.CD_ELO_AGENDAMENTO_ITEM = EAG_WE_I.CD_ELO_AGENDAMENTO_ITEM
        
        --LEFT JOIN VND.ELO_AGENDAMENTO_GROUPING EAG_GRO_I
        --ON EAG_GRO_I.CD_ELO_AGENDAMENTO_WEEK = EAG_WE_I.CD_ELO_AGENDAMENTO_WEEK
        INNER JOIN VND.VW_ELO_AGENDAMENTO_DAY_PLAN DAYY
        ON 
        DAYY.CD_ELO_AGENDAMENTO_WEEK = EAG_WE_I.CD_ELO_AGENDAMENTO_WEEK
        
        WHERE 
        EA_SUP_I.IC_ATIVO = 'S'
           
        AND             EXISTS (
                    SELECT 1 FROM CTE_CARTEIRA CTA 
                    WHERE 
                    CTA.CD_ELO_AGENDAMENTO_ITEM = EAG_ITEM_I.CD_ELO_AGENDAMENTO_ITEM
                    )
                                        
        GROUP BY  EA_SUP_I.CD_ELO_AGENDAMENTO, EA_SUP_I.CD_SALES_GROUP , EAG_ITEM_I.CD_ELO_AGENDAMENTO_ITEM, 
        EAG_ITEM_I.CD_INCOTERMS, DAYY.CD_GRUPO_EMBALAGEM, DAYY.NU_DIA_SEMANA , EAG_ITEM_I.CD_CLIENTE                                   
        )   ,
        --SELECT * FROM ELO_AG_DAY_BY_INCOTERMS_ITEM

        
       
CTE_CENARIO_CIF_FOB AS 
(
    select  
    ag.CD_ELO_AGENDAMENTO ,
    
    (select d.CD_ELO_CARTEIRA 
    FROM CTE_CARTEIRA D 
    where d.CD_ELO_AGENDAMENTO_ITEM = AGDAY.CD_ELO_AGENDAMENTO_ITEM 
    AND ROWNUM =1 ) CD_ELO_CARTEIRA ,
    ag.CD_WEEK ,
    ag.CD_ELO_STATUS ,
    ag.DS_STATUS  ,
    --TO_CHAR(ec.CD_TIPO_REPLAN) || '-' || estrp.DS_STATUS                 as TIPO_REPLAN,
    (select CASE WHEN UPPER(estrp.DS_STATUS) = 'REPLAN' THEN 'Replan' ELSE 'Plan' END
    FROM CTE_CARTEIRA D 
    INNER JOIN VND.ELO_STATUS estrp
    ON d.CD_TIPO_AGENDAMENTO = estrp.CD_ELO_STATUS
    where d.CD_ELO_AGENDAMENTO_ITEM = AGDAY.CD_ELO_AGENDAMENTO_ITEM 
    AND ROWNUM =1 ) TIPO_REPLAN,
    --to_char(ec.DH_BACKLOG_CIF)  DH_BACKLOG_CIF,
    (select d.DH_BACKLOG_CIF 
    FROM CTE_CARTEIRA D 
    where d.CD_ELO_AGENDAMENTO_ITEM = AGDAY.CD_ELO_AGENDAMENTO_ITEM 
    AND ROWNUM =1 ) DH_BACKLOG_CIF,
    (select d.DS_CENTRO_EXPEDIDOR 
    FROM CTE_CARTEIRA D 
    where d.CD_ELO_AGENDAMENTO_ITEM = AGDAY.CD_ELO_AGENDAMENTO_ITEM 
    AND d.DS_CENTRO_EXPEDIDOR is not null
    AND ROWNUM =1 ) DS_CENTRO_EXPEDIDOR ,
    NVL(ag.CD_CENTRO_EXPEDIDOR, ( select d.CD_CENTRO_EXPEDIDOR 
    FROM CTE_CARTEIRA D 
    where d.CD_ELO_AGENDAMENTO_ITEM = AGDAY.CD_ELO_AGENDAMENTO_ITEM 
    AND d.CD_CENTRO_EXPEDIDOR is not null
    AND ROWNUM =1  )) CD_CENTRO_EXPEDIDOR,
    ma.DS_MACHINE ,
    ma.CD_MACHINE,
    AGDAY.CD_INCOTERMS ,
    AGDAY.CD_CLIENTE ,
    NVL(CLI.NO_CLIENTE, (select d.NO_CLIENTE 
    FROM CTE_CARTEIRA D 
    where d.CD_ELO_AGENDAMENTO_ITEM = AGDAY.CD_ELO_AGENDAMENTO_ITEM 
    AND ROWNUM =1 )) NO_CLIENTE  ,
    --eai.CD_COTA_COMPARTILHADA                                            as COTA,
    '' AS COTA,
    (SELECT u.CD_USUARIO || '-' || u.NO_USUARIO 
    FROM CTE_CARTEIRA d 
    INNER JOIN CTF.USUARIO u
    on D.CD_SALES_GROUP = u.CD_USUARIO_ORIGINAL
    where d.CD_ELO_AGENDAMENTO_ITEM = AGDAY.CD_ELO_AGENDAMENTO_ITEM 
    AND ROWNUM =1) as SUPERVISOR,
    (SELECT GEI.DS_GRUPO_EMBALAGEM FROM VND.GRUPO_EMBALAGEM GEI WHERE AGDAY.CD_GRUPO_EMBALAGEM = GEI.CD_GRUPO_EMBALAGEM ) as DS_GRUPO_EMBALAGEM,
    AGDAY.CD_GRUPO_EMBALAGEM,
    
    CASE 
    WHEN AGDAY.CD_INCOTERMS IN ('CIF', 'FOB') AND AGDAY.NU_QUANTIDADE > 
                            (SELECT ROUND(SUM(ITS.QT_AGENDADA_CONFIRMADA),0) QT 
                                FROM CTE_CARTEIRA ITS 
                                WHERE AGDAY.CD_ELO_AGENDAMENTO_ITEM = ITS.CD_ELO_AGENDAMENTO_ITEM)    THEN 
    AGDAY.NU_QUANTIDADE / (SELECT  COUNT(IT.CD_ELO_AGENDAMENTO_ITEM) QT 
                                FROM CTE_CARTEIRA IT  
                                WHERE IT.CD_ELO_AGENDAMENTO_ITEM = AGDAY.CD_ELO_AGENDAMENTO_ITEM)
    ELSE AGDAY.NU_QUANTIDADE END  NU_QUANTIDADE,
    AGDAY.CD_ELO_AGENDAMENTO_ITEM,
    AGDAY.CD_COTA_COMPARTILHADA,
    AGDAY.NU_DIA_SEMANA, 
    AGDAY.CD_SALES_GROUP,
    AGDAY.CD_SALES_GROUP || ' - ' || USU.NO_USUARIO NO_SUPERVISOR
    

    
    FROM ELO_AG_DAY_BY_INCOTERMS_ITEM AGDAY
    INNER JOIN CTE_AGENDAMENTO_FILTER ag
    ON 
    ag.CD_ELO_AGENDAMENTO = AGDAY.CD_ELO_AGENDAMENTO
    left join CTF.MACHINE ma
    on ag.CD_MACHINE = ma.CD_MACHINE
    
    left JOIN  CTF.CLIENTE CLI
    ON AGDAY.CD_CLIENTE = CLI.CD_CLIENTE
    
    left join CTF.USUARIO USU
    on
    USU.CD_USUARIO_ORIGINAL = AGDAY.CD_SALES_GROUP
    
    WHERE 
    AGDAY.CD_INCOTERMS IN( 'CIF', 'FOB')
  
  
),
--SELECT * FROM CTE_CENARIO_CIF_FOB  
--SELECT * FROM VND.ELO_MARCACAO
CTE_MARCACAO AS (

SELECT 
(SELECT AG_FIL.CD_ELO_AGENDAMENTO 
FROM CTE_AGENDAMENTO_FILTER AG_FIL 
WHERE ROWNUM=1) CD_ELO_AGENDAMENTO,
E_MAR.CD_ELO_CARTEIRA, E_MAR.CD_ELO_MARCACAO, E_MAR.NU_QUANTIDADE ,
E_MAR.SG_CLASSIFICACAO, E_MAR.DH_MARCACAO, E_MAR.CD_CENTRO_EXPEDIDOR, E_MAR.CD_CLIENTE, E_MAR.NO_CLIENTE,
E_MAR.CD_GRUPO_EMBALAGEM, E_MAR.CD_INCOTERMS, E_MAR.CD_WEEK, 
(1 + TRUNC (E_MAR.DH_MARCACAO) - TRUNC (E_MAR.DH_MARCACAO, 'IW')) NU_DIA_SEMANA,
(
SELECT USS.CD_USUARIO_ORIGINAL  || ' - ' || USS.NO_USUARIO FROM CTF.USUARIO USS WHERE USS.CD_USUARIO_ORIGINAL =
NVL(E_MAR.CD_SALES_GROUP, (SELECT CTX.CD_SALES_GROUP FROM CTE_CARTEIRA CTX WHERE E_MAR.CD_ELO_CARTEIRA = CTX.CD_ELO_CARTEIRA )) 
)  NO_SUPERVISOR

FROM VND.ELO_MARCACAO E_MAR
WHERE 
E_MAR.IC_DESISTENCIA = 'N' 
AND E_MAR.IC_DISPENSADO = 'N'
AND E_MAR.IC_ATIVO = 'S'
AND EXISTS (SELECT 1 
FROM CTE_AGENDAMENTO_FILTER AGF 
INNER JOIN CTE_CARTEIRA ec
ON AGF.CD_ELO_AGENDAMENTO = ec.CD_ELO_AGENDAMENTO
WHERE 
E_MAR.CD_WEEK = AGF.CD_WEEK
AND E_MAR.CD_CENTRO_EXPEDIDOR = ec.CD_CENTRO_EXPEDIDOR
))
--SELECT * FROM CTE_MARCACAO
, CTE_GRAND_FINALI AS (
SELECT 
PLORRE.CD_ELO_AGENDAMENTO,
PLORRE.CD_WEEK, 
PLORRE.TIPO_REPLAN,
PLORRE.CD_CENTRO_EXPEDIDOR,
PLORRE.CD_INCOTERMS,
PLORRE.CD_CLIENTE,
PLORRE.NO_CLIENTE,
PLORRE.NO_SUPERVISOR,
SUM(PLORRE.NU_QUANTIDADE) NU_QUANTIDADE,
SUM(PLORRE.SEG) SEG,
SUM(PLORRE.TER) TER,
SUM(PLORRE.QUA) QUA,
SUM(PLORRE.QUI) QUI,
SUM(PLORRE.SEX) SEX,
SUM(PLORRE.SAB) SAB,
SUM(PLORRE.DOM) DOM, 
(PLORRE.MAR_SEG) MAR_SEG,
(PLORRE.MAR_TER) MAR_TER,
(PLORRE.MAR_QUA) MAR_QUA,
(PLORRE.MAR_QUI) MAR_QUI,
(PLORRE.MAR_SEX) MAR_SEX,
(PLORRE.MAR_SAB) MAR_SAB,
(PLORRE.MAR_DOM) MAR_DOM,
(PLORRE.MAR_SEG + PLORRE.MAR_TER + PLORRE.MAR_QUA + PLORRE.MAR_QUI+ PLORRE.MAR_SEX+ PLORRE.MAR_SAB+PLORRE.MAR_DOM ) MAR_TOTAL

FROM (

SELECT 
CIF_FOB.CD_ELO_AGENDAMENTO,
CIF_FOB.CD_WEEK,
CIF_FOB.TIPO_REPLAN,
CIF_FOB.CD_CENTRO_EXPEDIDOR,
CIF_FOB.CD_INCOTERMS, 
CIF_FOB.CD_CLIENTE,
CIF_FOB.NO_CLIENTE,
CIF_FOB.NU_QUANTIDADE,
CIF_FOB.NU_DIA_SEMANA,
CIF_FOB.NO_SUPERVISOR,

NVL((SELECT SUM(FORDAY.NU_QUANTIDADE) NU_QUANTIDADE  
FROM CTE_CENARIO_CIF_FOB FORDAY 
WHERE  
FORDAY.NU_DIA_SEMANA = 1 
AND FORDAY.CD_CLIENTE = CIF_FOB.CD_CLIENTE
AND FORDAY.NU_DIA_SEMANA = CIF_FOB.NU_DIA_SEMANA
AND FORDAY.CD_GRUPO_EMBALAGEM = CIF_FOB.CD_GRUPO_EMBALAGEM
AND FORDAY.CD_INCOTERMS = CIF_FOB.CD_INCOTERMS
AND FORDAY.CD_ELO_AGENDAMENTO_ITEM = CIF_FOB.CD_ELO_AGENDAMENTO_ITEM
AND FORDAY.CD_ELO_AGENDAMENTO = CIF_FOB.CD_ELO_AGENDAMENTO),0) as SEG, 

NVL((SELECT SUM(FORDAY.NU_QUANTIDADE) NU_QUANTIDADE  
FROM CTE_CENARIO_CIF_FOB FORDAY 
WHERE  
FORDAY.NU_DIA_SEMANA = 2 
AND FORDAY.CD_CLIENTE = CIF_FOB.CD_CLIENTE
AND FORDAY.NU_DIA_SEMANA = CIF_FOB.NU_DIA_SEMANA
AND FORDAY.CD_GRUPO_EMBALAGEM = CIF_FOB.CD_GRUPO_EMBALAGEM
AND FORDAY.CD_INCOTERMS = CIF_FOB.CD_INCOTERMS
AND FORDAY.CD_ELO_AGENDAMENTO_ITEM = CIF_FOB.CD_ELO_AGENDAMENTO_ITEM
AND FORDAY.CD_ELO_AGENDAMENTO = CIF_FOB.CD_ELO_AGENDAMENTO),0) as TER,

NVL((SELECT SUM(FORDAY.NU_QUANTIDADE) NU_QUANTIDADE  
FROM CTE_CENARIO_CIF_FOB FORDAY 
WHERE  
FORDAY.NU_DIA_SEMANA = 3 
AND FORDAY.CD_CLIENTE = CIF_FOB.CD_CLIENTE
AND FORDAY.NU_DIA_SEMANA = CIF_FOB.NU_DIA_SEMANA
AND FORDAY.CD_GRUPO_EMBALAGEM = CIF_FOB.CD_GRUPO_EMBALAGEM
AND FORDAY.CD_INCOTERMS = CIF_FOB.CD_INCOTERMS
AND FORDAY.CD_ELO_AGENDAMENTO_ITEM = CIF_FOB.CD_ELO_AGENDAMENTO_ITEM
AND FORDAY.CD_ELO_AGENDAMENTO = CIF_FOB.CD_ELO_AGENDAMENTO),0) as QUA,

NVL((SELECT SUM(FORDAY.NU_QUANTIDADE) NU_QUANTIDADE  
FROM CTE_CENARIO_CIF_FOB FORDAY 
WHERE  
FORDAY.NU_DIA_SEMANA = 4 
AND FORDAY.CD_CLIENTE = CIF_FOB.CD_CLIENTE
AND FORDAY.NU_DIA_SEMANA = CIF_FOB.NU_DIA_SEMANA
AND FORDAY.CD_GRUPO_EMBALAGEM = CIF_FOB.CD_GRUPO_EMBALAGEM
AND FORDAY.CD_INCOTERMS = CIF_FOB.CD_INCOTERMS
AND FORDAY.CD_ELO_AGENDAMENTO_ITEM = CIF_FOB.CD_ELO_AGENDAMENTO_ITEM
AND FORDAY.CD_ELO_AGENDAMENTO = CIF_FOB.CD_ELO_AGENDAMENTO),0) as QUI,

NVL((SELECT SUM(FORDAY.NU_QUANTIDADE) NU_QUANTIDADE  
FROM CTE_CENARIO_CIF_FOB FORDAY 
WHERE  
FORDAY.NU_DIA_SEMANA = 5 
AND FORDAY.CD_CLIENTE = CIF_FOB.CD_CLIENTE
AND FORDAY.NU_DIA_SEMANA = CIF_FOB.NU_DIA_SEMANA
AND FORDAY.CD_GRUPO_EMBALAGEM = CIF_FOB.CD_GRUPO_EMBALAGEM
AND FORDAY.CD_INCOTERMS = CIF_FOB.CD_INCOTERMS
AND FORDAY.CD_ELO_AGENDAMENTO_ITEM = CIF_FOB.CD_ELO_AGENDAMENTO_ITEM
AND FORDAY.CD_ELO_AGENDAMENTO = CIF_FOB.CD_ELO_AGENDAMENTO),0) as SEX,

NVL((SELECT SUM(FORDAY.NU_QUANTIDADE) NU_QUANTIDADE  
FROM CTE_CENARIO_CIF_FOB FORDAY 
WHERE  
FORDAY.NU_DIA_SEMANA = 6 
AND FORDAY.CD_CLIENTE = CIF_FOB.CD_CLIENTE
AND FORDAY.NU_DIA_SEMANA = CIF_FOB.NU_DIA_SEMANA
AND FORDAY.CD_GRUPO_EMBALAGEM = CIF_FOB.CD_GRUPO_EMBALAGEM
AND FORDAY.CD_INCOTERMS = CIF_FOB.CD_INCOTERMS
AND FORDAY.CD_ELO_AGENDAMENTO_ITEM = CIF_FOB.CD_ELO_AGENDAMENTO_ITEM
AND FORDAY.CD_ELO_AGENDAMENTO = CIF_FOB.CD_ELO_AGENDAMENTO),0) as SAB,

NVL((SELECT SUM(FORDAY.NU_QUANTIDADE) NU_QUANTIDADE  
FROM CTE_CENARIO_CIF_FOB FORDAY 
WHERE  
FORDAY.NU_DIA_SEMANA = 7 
AND FORDAY.CD_CLIENTE = CIF_FOB.CD_CLIENTE
AND FORDAY.NU_DIA_SEMANA = CIF_FOB.NU_DIA_SEMANA
AND FORDAY.CD_GRUPO_EMBALAGEM = CIF_FOB.CD_GRUPO_EMBALAGEM
AND FORDAY.CD_INCOTERMS = CIF_FOB.CD_INCOTERMS
AND FORDAY.CD_ELO_AGENDAMENTO_ITEM = CIF_FOB.CD_ELO_AGENDAMENTO_ITEM
AND FORDAY.CD_ELO_AGENDAMENTO = CIF_FOB.CD_ELO_AGENDAMENTO),0) as DOM, 

NVL((SELECT SUM(FORDAY.NU_QUANTIDADE) NU_QUANTIDADE  
FROM CTE_MARCACAO FORDAY 
WHERE  
FORDAY.NU_DIA_SEMANA = 1 
AND FORDAY.CD_CLIENTE = CIF_FOB.CD_CLIENTE
--AND FORDAY.NU_DIA_SEMANA = CIF_FOB.NU_DIA_SEMANA
AND FORDAY.CD_GRUPO_EMBALAGEM = CIF_FOB.CD_GRUPO_EMBALAGEM
AND FORDAY.CD_INCOTERMS = CIF_FOB.CD_INCOTERMS
AND FORDAY.SG_CLASSIFICACAO = 'Plan'
--AND FORDAY.CD_ELO_AGENDAMENTO_ITEM = CIF_FOB.CD_ELO_AGENDAMENTO_ITEM
AND FORDAY.CD_ELO_AGENDAMENTO = CIF_FOB.CD_ELO_AGENDAMENTO),0) as MAR_SEG,

NVL((SELECT SUM(FORDAY.NU_QUANTIDADE) NU_QUANTIDADE  
FROM CTE_MARCACAO FORDAY 
WHERE  
FORDAY.NU_DIA_SEMANA = 2 
AND FORDAY.CD_CLIENTE = CIF_FOB.CD_CLIENTE
--AND FORDAY.NU_DIA_SEMANA = CIF_FOB.NU_DIA_SEMANA
AND FORDAY.CD_GRUPO_EMBALAGEM = CIF_FOB.CD_GRUPO_EMBALAGEM
AND FORDAY.CD_INCOTERMS = CIF_FOB.CD_INCOTERMS
AND FORDAY.SG_CLASSIFICACAO = 'Plan'
--AND FORDAY.CD_ELO_AGENDAMENTO_ITEM = CIF_FOB.CD_ELO_AGENDAMENTO_ITEM
AND FORDAY.CD_ELO_AGENDAMENTO = CIF_FOB.CD_ELO_AGENDAMENTO),0) as MAR_TER,
NVL((SELECT SUM(FORDAY.NU_QUANTIDADE) NU_QUANTIDADE  
FROM CTE_MARCACAO FORDAY 
WHERE  
FORDAY.NU_DIA_SEMANA = 3 
AND FORDAY.CD_CLIENTE = CIF_FOB.CD_CLIENTE
--AND FORDAY.NU_DIA_SEMANA = CIF_FOB.NU_DIA_SEMANA
AND FORDAY.CD_GRUPO_EMBALAGEM = CIF_FOB.CD_GRUPO_EMBALAGEM
AND FORDAY.CD_INCOTERMS = CIF_FOB.CD_INCOTERMS
AND FORDAY.SG_CLASSIFICACAO = 'Plan'
--AND FORDAY.CD_ELO_AGENDAMENTO_ITEM = CIF_FOB.CD_ELO_AGENDAMENTO_ITEM
AND FORDAY.CD_ELO_AGENDAMENTO = CIF_FOB.CD_ELO_AGENDAMENTO),0) as MAR_QUA,
NVL((SELECT SUM(FORDAY.NU_QUANTIDADE) NU_QUANTIDADE  
FROM CTE_MARCACAO FORDAY 
WHERE  
FORDAY.NU_DIA_SEMANA = 4 
AND FORDAY.CD_CLIENTE = CIF_FOB.CD_CLIENTE
--AND FORDAY.NU_DIA_SEMANA = CIF_FOB.NU_DIA_SEMANA
AND FORDAY.CD_GRUPO_EMBALAGEM = CIF_FOB.CD_GRUPO_EMBALAGEM
AND FORDAY.CD_INCOTERMS = CIF_FOB.CD_INCOTERMS
AND FORDAY.SG_CLASSIFICACAO = 'Plan'
--AND FORDAY.CD_ELO_AGENDAMENTO_ITEM = CIF_FOB.CD_ELO_AGENDAMENTO_ITEM
AND FORDAY.CD_ELO_AGENDAMENTO = CIF_FOB.CD_ELO_AGENDAMENTO),0) as MAR_QUI,
NVL((SELECT SUM(FORDAY.NU_QUANTIDADE) NU_QUANTIDADE  
FROM CTE_MARCACAO FORDAY 
WHERE  
FORDAY.NU_DIA_SEMANA = 5 
AND FORDAY.CD_CLIENTE = CIF_FOB.CD_CLIENTE
--AND FORDAY.NU_DIA_SEMANA = CIF_FOB.NU_DIA_SEMANA
AND FORDAY.CD_GRUPO_EMBALAGEM = CIF_FOB.CD_GRUPO_EMBALAGEM
AND FORDAY.CD_INCOTERMS = CIF_FOB.CD_INCOTERMS
AND FORDAY.SG_CLASSIFICACAO = 'Plan'
--AND FORDAY.CD_ELO_AGENDAMENTO_ITEM = CIF_FOB.CD_ELO_AGENDAMENTO_ITEM
AND FORDAY.CD_ELO_AGENDAMENTO = CIF_FOB.CD_ELO_AGENDAMENTO),0) as MAR_SEX,
NVL((SELECT SUM(FORDAY.NU_QUANTIDADE) NU_QUANTIDADE  
FROM CTE_MARCACAO FORDAY 
WHERE  
FORDAY.NU_DIA_SEMANA = 6 
AND FORDAY.CD_CLIENTE = CIF_FOB.CD_CLIENTE
--AND FORDAY.NU_DIA_SEMANA = CIF_FOB.NU_DIA_SEMANA
AND FORDAY.CD_GRUPO_EMBALAGEM = CIF_FOB.CD_GRUPO_EMBALAGEM
AND FORDAY.CD_INCOTERMS = CIF_FOB.CD_INCOTERMS
AND FORDAY.SG_CLASSIFICACAO = 'Plan'
--AND FORDAY.CD_ELO_AGENDAMENTO_ITEM = CIF_FOB.CD_ELO_AGENDAMENTO_ITEM
AND FORDAY.CD_ELO_AGENDAMENTO = CIF_FOB.CD_ELO_AGENDAMENTO),0) as MAR_SAB,
NVL((SELECT SUM(FORDAY.NU_QUANTIDADE) NU_QUANTIDADE  
FROM CTE_MARCACAO FORDAY 
WHERE  
FORDAY.NU_DIA_SEMANA = 7 
AND FORDAY.CD_CLIENTE = CIF_FOB.CD_CLIENTE
--AND FORDAY.NU_DIA_SEMANA = CIF_FOB.NU_DIA_SEMANA
AND FORDAY.CD_GRUPO_EMBALAGEM = CIF_FOB.CD_GRUPO_EMBALAGEM
AND FORDAY.CD_INCOTERMS = CIF_FOB.CD_INCOTERMS
AND FORDAY.SG_CLASSIFICACAO = 'Plan'
--AND FORDAY.CD_ELO_AGENDAMENTO_ITEM = CIF_FOB.CD_ELO_AGENDAMENTO_ITEM
AND FORDAY.CD_ELO_AGENDAMENTO = CIF_FOB.CD_ELO_AGENDAMENTO),0) as MAR_DOM

FROM CTE_CENARIO_CIF_FOB CIF_FOB
) PLORRE
GROUP BY 
PLORRE.CD_ELO_AGENDAMENTO,
PLORRE.CD_WEEK, 
PLORRE.TIPO_REPLAN,
PLORRE.CD_CENTRO_EXPEDIDOR,
PLORRE.CD_INCOTERMS,
PLORRE.CD_CLIENTE,
PLORRE.NO_CLIENTE, 
PLORRE.NO_SUPERVISOR,
(PLORRE.MAR_SEG) ,
(PLORRE.MAR_TER) ,
(PLORRE.MAR_QUA) ,
(PLORRE.MAR_QUI) ,
(PLORRE.MAR_SEX) ,
(PLORRE.MAR_SAB) ,
(PLORRE.MAR_DOM) 
) 

SELECT 
CGF.CD_ELO_AGENDAMENTO,
CGF.CD_WEEK,
CGF.TIPO_REPLAN Classe,
CGF.CD_CENTRO_EXPEDIDOR,
CGF.CD_INCOTERMS Modalidade,
CGF.CD_CLIENTE NumCliente,
CGF.NO_CLIENTE NomeCliente,
CGF.NO_SUPERVISOR,
ROUND(SUM(CGF.NU_QUANTIDADE),0) TotalPlan,
ROUND(SUM(CGF.SEG),0) SEG,
ROUND(SUM(CGF.TER),0) TER,
ROUND(SUM(CGF.QUA),0) QUA,
ROUND(SUM(CGF.QUI),0) QUI,
ROUND(SUM(CGF.SEX),0) SEX,
ROUND(SUM(CGF.SAB),0) SAB,
ROUND(SUM(CGF.DOM),0) DOM,
ROUND(SUM(CGF.MAR_SEG),0) MAR_SEG,
ROUND(SUM(CGF.MAR_TER),0) MAR_TER,
ROUND(SUM(CGF.MAR_QUA),0) MAR_QUA,
ROUND(SUM(CGF.MAR_QUI),0) MAR_QUI,
ROUND(SUM(CGF.MAR_SEX),0) MAR_SEX,
ROUND(SUM(CGF.MAR_SAB),0) MAR_SAB,
ROUND(SUM(CGF.MAR_DOM),0) MAR_DOM,
ROUND(SUM(CGF.MAR_TOTAL),0) TotalExec,
ROUND((ROUND(SUM(CGF.MAR_TOTAL),3) / ROUND(SUM( CGF.NU_QUANTIDADE ),0))* 100,1) /*PARTICIPANTE_PERC */ "%"

FROM CTE_GRAND_FINALI CGF
HAVING  ROUND(SUM( CGF.NU_QUANTIDADE ),0) >  0 
GROUP BY 
CGF.CD_ELO_AGENDAMENTO,
CGF.CD_WEEK,
CGF.TIPO_REPLAN,
CGF.CD_CENTRO_EXPEDIDOR,
CGF.CD_INCOTERMS,
CGF.CD_CLIENTE,
CGF.NO_CLIENTE,
CGF.NO_SUPERVISOR
--CGF.NU_QUANTIDADE,
--CGF.MAR_TOTAL

UNION 
SELECT 

MAR_SOM.CD_ELO_AGENDAMENTO, MAR_SOM.CD_WEEK, MAR_SOM.TIPO_RELAN, MAR_SOM.CD_CENTRO_EXPEDIDOR, MAR_SOM.CD_INCOTERMS,
MAR_SOM.CD_CLIENTE, MAR_SOM.NO_CLIENTE, MAR_SOM.NO_SUPERVISOR,  MAR_SOM.NU_QUANTIDADE, 
MAR_SOM.SEG, MAR_SOM.TER, MAR_SOM.QUA, MAR_SOM.QUI, MAR_SOM.SEX, MAR_SOM.SAB, MAR_SOM.DOM,
SUM(MAR_SOM.MAR_SEG) MAR_SEG, 
SUM(MAR_SOM.MAR_TER) MAR_TER, 
SUM(MAR_SOM.MAR_QUA) MAR_QUA, 
SUM(MAR_SOM.MAR_QUI) MAR_QUI, 
SUM(MAR_SOM.MAR_SEX) MAR_SEX, 
SUM(MAR_SOM.MAR_SAB) MAR_SAB, 
SUM(MAR_SOM.MAR_DOM) MAR_DOM,
SUM(MAR_SOM.MAR_TOTAL) MAR_TOTAL,
0 PARTICIPANTE_PERC

FROM (

SELECT FORMAR.CD_ELO_AGENDAMENTO, FORMAR.CD_WEEK, 'Sem Cota' TIPO_RELAN, FORMAR.CD_CENTRO_EXPEDIDOR, FORMAR.CD_INCOTERMS,
FORMAR.CD_CLIENTE, FORMAR.NO_CLIENTE, FORMAR.NO_SUPERVISOR, 0 NU_QUANTIDADE, 0 SEG, 0 TER, 0 QUA, 0 QUI, 0 SEX, 0 SAB, 0 DOM,
CASE WHEN NU_DIA_SEMANA = 1 THEN NU_QUANTIDADE ELSE 0 END MAR_SEG, 
CASE WHEN NU_DIA_SEMANA = 2 THEN NU_QUANTIDADE ELSE 0 END MAR_TER, 
CASE WHEN NU_DIA_SEMANA = 3 THEN NU_QUANTIDADE ELSE 0 END MAR_QUA, 
CASE WHEN NU_DIA_SEMANA = 4 THEN NU_QUANTIDADE ELSE 0 END MAR_QUI, 
CASE WHEN NU_DIA_SEMANA = 5 THEN NU_QUANTIDADE ELSE 0 END MAR_SEX, 
CASE WHEN NU_DIA_SEMANA = 6 THEN NU_QUANTIDADE ELSE 0 END MAR_SAB, 
CASE WHEN NU_DIA_SEMANA = 7 THEN NU_QUANTIDADE ELSE 0 END MAR_DOM,
NU_QUANTIDADE MAR_TOTAL 
FROM CTE_MARCACAO FORMAR
WHERE 
SG_CLASSIFICACAO = 'Sem cota'
) MAR_SOM
GROUP BY 
MAR_SOM.CD_ELO_AGENDAMENTO, MAR_SOM.CD_WEEK, MAR_SOM.TIPO_RELAN, MAR_SOM.CD_CENTRO_EXPEDIDOR, MAR_SOM.CD_INCOTERMS,
MAR_SOM.CD_CLIENTE, MAR_SOM.NO_SUPERVISOR, MAR_SOM.NO_CLIENTE,
MAR_SOM.SEG, MAR_SOM.TER, MAR_SOM.QUA, MAR_SOM.QUI, MAR_SOM.SEX, MAR_SOM.SAB, MAR_SOM.DOM
;

/*
SELECT * FROM VND.ELO_MARCACAO WHERE CD_WEEK = 'W182018' AND CD_CENTRO_EXPEDIDOR = '6060'
AND DH_MARCACAO IS NOT NULL AND NU_QUANTIDADE > 0  AND SG_CLASSIFICACAO = 'Sem cota'
*/    
    
    

END PX_SUM_GET_CARTEIRA;





PROCEDURE PX_SUM_ALL_GET_CARTEIRA(

    P_CD_POLO               IN ELO_AGENDAMENTO.CD_POLO%type,
    P_CD_CENTRO_EXPEDIDOR   IN ELO_AGENDAMENTO.CD_CENTRO_EXPEDIDOR%type,
    P_CD_MACHINE            IN ELO_AGENDAMENTO.CD_MACHINE%type,
    P_CD_WEEK               IN ELO_AGENDAMENTO.CD_WEEK%type,
    P_RETORNO               OUT T_CURSOR
)

IS

  BEGIN

  OPEN P_RETORNO FOR

    SELECT 
        SUM(ed.NU_QUANTIDADE)NU_QUANTIDADE
        , ec.QT_PROGRAMADA
        , ec.CD_TIPO_AGENDAMENTO
        , ec.NO_CLIENTE
        , ES.CD_ELO_STATUS
        , ec.CD_CLIENTE
        , ec.CD_INCOTERMS
        , ed.NU_DIA_SEMANA
        , CD_CLIENTE_PAGADOR
        , ec.CD_CLIENTE_RECEBEDOR
    FROM ELO_CARTEIRA_DAY ed INNER JOIN ELO_CARTEIRA ec ON ed.CD_ELO_CARTEIRA=ec.CD_ELO_CARTEIRA
    INNER JOIN ELO_STATUS ES ON ec.CD_TIPO_AGENDAMENTO=ES.CD_ELO_STATUS
    WHERE CD_ELO_AGENDAMENTO_ITEM IN(
                                    SELECT CD_ELO_AGENDAMENTO_ITEM 
                                    FROM ELO_AGENDAMENTO_ITEM
                                    WHERE CD_ELO_AGENDAMENTO_SUPERVISOR IN(
                                                                SELECT CD_ELO_AGENDAMENTO_SUPERVISOR 
                                                                FROM ELO_AGENDAMENTO_SUPERVISOR
                                                                WHERE CD_ELO_AGENDAMENTO IN(
                                                                        SELECT CD_ELO_AGENDAMENTO 
                                                                        FROM ELO_AGENDAMENTO 
                                                                        WHERE CD_WEEK = P_CD_WEEK
                                                                        AND (P_CD_POLO IS NULL OR CD_POLO = P_CD_POLO)
                                                                        AND (P_CD_CENTRO_EXPEDIDOR IS NULL OR CD_CENTRO_EXPEDIDOR = P_CD_CENTRO_EXPEDIDOR)
                                                                        AND (P_CD_MACHINE IS NULL OR CD_MACHINE = P_CD_MACHINE)
                                                                        AND IC_ATIVO ='S')
                                                                        )
                                    AND IC_ATIVO='S')
    AND IC_ATIVO ='S' 
    AND QT_AGENDADA_CONFIRMADA > 0
    GROUP BY ec.CD_TIPO_AGENDAMENTO,ec.NO_CLIENTE,ec.CD_CLIENTE,ec.QT_PROGRAMADA, ec.CD_INCOTERMS,ES.CD_ELO_STATUS,ed.NU_DIA_SEMANA,ec.CD_CLIENTE_PAGADOR,ec.CD_CLIENTE_RECEBEDOR;


END PX_SUM_ALL_GET_CARTEIRA;


PROCEDURE PX_SUM_GET_SEMPLANMARCACO(
       P_CD_POLO         in ELO_AGENDAMENTO.CD_POLO%type,
      P_CD_WEEK   in ELO_AGENDAMENTO.CD_WEEK%type,
     
      -- P_CD_INCOTERMS    in ELO_CARTEIRA.CD_INCOTERMS %TYPE,
        P_RETORNO         out T_CURSOR
    


)
IS
  BEGIN
   OPEN P_RETORNO FOR
   SELECT SUM(ED.NU_QUANTIDADE),SG_CLASSIFICACAO,EC.CD_CLIENTE,EC.CD_INCOTERMS,NU_DIA_SEMANA,IC_PRIORIDADE,ed.NU_QUANTIDADE,EC.NO_CLIENTE FROM ELO_MARCACAO EM
INNER JOIN ELO_CARTEIRA EC
ON EM.CD_ELO_CARTEIRA=EC.CD_ELO_CARTEIRA
INNER JOIN ELO_CARTEIRA_DAY ED
ON ED.CD_ELO_CARTEIRA=EC.CD_ELO_CARTEIRA
WHERE
   CD_ELO_AGENDAMENTO_ITEM IN(SELECT CD_ELO_AGENDAMENTO_ITEM FROM ELO_AGENDAMENTO_ITEM
   WHERE 
   CD_ELO_AGENDAMENTO_SUPERVISOR IN(SELECT CD_ELO_AGENDAMENTO_SUPERVISOR FROM ELO_AGENDAMENTO_SUPERVISOR
   WHERE
   CD_ELO_AGENDAMENTO IN(SELECT CD_ELO_AGENDAMENTO FROM ELO_AGENDAMENTO 
           WHERE
           (CD_POLO=P_CD_POLO OR CD_CENTRO_EXPEDIDOR IN ( SELECT CD_CENTRO_EXPEDIDOR
            FROM ELO_AGENDAMENTO_CENTRO
             WHERE
                    trim(CD_POLO) = NVL(trim(P_CD_POLO),null)
                      
                ))
                   
                    and  trim(CD_WEEK) = NVL(trim(P_CD_WEEK),null)
         and IC_ATIVO='S'))
         AND IC_ATIVO='S')
         and EC.IC_ATIVO ='S'
          and QT_AGENDADA_CONFIRMADA > 0
      AND SG_CLASSIFICACAO='SEMPLAN'
GROUP BY SG_CLASSIFICACAO,EC.CD_CLIENTE,EC.CD_INCOTERMS,NU_DIA_SEMANA,ed.NU_QUANTIDADE,EC.NO_CLIENTE,IC_PRIORIDADE ;

END PX_SUM_GET_SEMPLANMARCACO;

PROCEDURE PX_SUM_GET_ALL_SEMPLANMARCACO(
         P_CD_POLO         in ELO_AGENDAMENTO.CD_POLO%type,
        P_CD_CENTRO_EXPEDIDOR    in ELO_AGENDAMENTO.CD_CENTRO_EXPEDIDOR%type,
        P_CD_MACHINE      in ELO_AGENDAMENTO.CD_MACHINE%type,
        P_CD_WEEK   in ELO_AGENDAMENTO.CD_WEEK%type,
        P_RETORNO         out T_CURSOR
 )
    



IS
  BEGIN
   OPEN P_RETORNO FOR
   SELECT SUM(ED.NU_QUANTIDADE),SG_CLASSIFICACAO,EC.CD_CLIENTE,EC.CD_INCOTERMS,NU_DIA_SEMANA,IC_PRIORIDADE,ed.NU_QUANTIDADE,EC.NO_CLIENTE FROM ELO_MARCACAO EM
INNER JOIN ELO_CARTEIRA EC
ON EM.CD_ELO_CARTEIRA=EC.CD_ELO_CARTEIRA
INNER JOIN ELO_CARTEIRA_DAY ED
ON ED.CD_ELO_CARTEIRA=EC.CD_ELO_CARTEIRA
WHERE
   CD_ELO_AGENDAMENTO_ITEM IN(SELECT CD_ELO_AGENDAMENTO_ITEM FROM ELO_AGENDAMENTO_ITEM
   WHERE 
   CD_ELO_AGENDAMENTO_SUPERVISOR IN(SELECT CD_ELO_AGENDAMENTO_SUPERVISOR FROM ELO_AGENDAMENTO_SUPERVISOR
   WHERE
   CD_ELO_AGENDAMENTO IN(SELECT CD_ELO_AGENDAMENTO FROM ELO_AGENDAMENTO
          
           WHERE
           CD_POLO=P_CD_POLO
           AND
           CD_CENTRO_EXPEDIDOR =P_CD_CENTRO_EXPEDIDOR
           AND
           CD_MACHINE =P_CD_MACHINE
           AND
           CD_WEEK=P_CD_WEEK
           AND
           IC_ATIVO ='S'))
         AND IC_ATIVO='S')
         and EC.IC_ATIVO ='S'
           and QT_AGENDADA_CONFIRMADA > 0
           AND SG_CLASSIFICACAO='SEMPLAN'
GROUP BY SG_CLASSIFICACAO,EC.CD_CLIENTE,EC.CD_INCOTERMS,NU_DIA_SEMANA,ed.NU_QUANTIDADE,IC_PRIORIDADE,EC.NO_CLIENTE ;

END PX_SUM_GET_ALL_SEMPLANMARCACO;


PROCEDURE PX_GET_Num_Cliente(
 P_RETORNO         out T_CURSOR
)
IS
  BEGIN
   OPEN P_RETORNO FOR

   SELECT CD_INCOTERMS FROM ELO_CARTEIRA;

NULL;
END PX_GET_Num_Cliente;

PROCEDURE PX_GET_NumCliente(
P_CD_CLIENTE   in ELO_CARTEIRA.CD_CLIENTE_PAGADOR%TYPE,
 P_RETORNO         out T_CURSOR
)
IS
  BEGIN

 IF P_CD_CLIENTE = 'FOB'
THEN
OPEN P_RETORNO  FOR
      SELECT CD_CLIENTE_PAGADOR FROM ELO_CARTEIRA;


ELSE IF P_CD_CLIENTE = 'CIF'
THEN
OPEN P_RETORNO  FOR
      SELECT CD_CLIENTE_RECEBEDOR
      FROM ELO_CARTEIRA;

END IF;
END IF;
 end PX_GET_NumCliente; 



 /*************************PROCEDURES RELATED TO 403 ***************************/
 PROCEDURE PX_GET_ALL_REPORTDETAILS(
 P_CD_POLO         in ELO_AGENDAMENTO.CD_POLO%type,
 P_CD_WEEK          in ELO_AGENDAMENTO.CD_WEEK%type,
 P_RETORNO         out T_CURSOR
 )
 IS
 BEGIN

OPEN P_RETORNO  FOR

SELECT * FROM ELO_AGENDAMENTO 
           WHERE
           (CD_POLO=P_CD_POLO OR CD_CENTRO_EXPEDIDOR IN ( SELECT CD_CENTRO_EXPEDIDOR
            FROM ELO_AGENDAMENTO_CENTRO))
         and CD_WEEK=P_CD_WEEK
         AND IC_ATIVO='S';


         --   Get data from table ELO_AGENDAMENTO_SUPERVISOR Where CD_ELO_AGENDAMENTO JOIN ELO_AGENDAMENTO-CD_ELO_AGENDAMENTO
OPEN P_RETORNO  FOR
SELECT * FROM ELO_AGENDAMENTO_SUPERVISOR WHERE CD_ELO_AGENDAMENTO IN(SELECT CD_ELO_AGENDAMENTO FROM ELO_AGENDAMENTO 
           WHERE
           (CD_POLO=P_CD_POLO OR CD_CENTRO_EXPEDIDOR IN ( SELECT CD_CENTRO_EXPEDIDOR
            FROM ELO_AGENDAMENTO_CENTRO))
         and CD_WEEK=P_CD_WEEK
         AND IC_ATIVO='S');

       --  Get data from table ELO_AGENDAMENTO_ITEM Where CD_ELO_AGENDAMENTO_SUPERVISOR JOIN ELO_AGENDAMENTO_SUPERVISOR-CD_ELO_AGENDAMENTO_SUPERVISOR and IC_ATIVO = ‘S’

OPEN P_RETORNO  FOR
SELECT * FROM ELO_AGENDAMENTO_ITEM WHERE CD_ELO_AGENDAMENTO_SUPERVISOR IN(SELECT CD_ELO_AGENDAMENTO_SUPERVISOR FROM ELO_AGENDAMENTO_SUPERVISOR
WHERE CD_ELO_AGENDAMENTO IN(SELECT CD_ELO_AGENDAMENTO FROM ELO_AGENDAMENTO 
           WHERE
           (CD_POLO=P_CD_POLO OR CD_CENTRO_EXPEDIDOR IN ( SELECT CD_CENTRO_EXPEDIDOR
            FROM ELO_AGENDAMENTO_CENTRO))
         and CD_WEEK=P_CD_WEEK
         AND IC_ATIVO='S'));




--Get data from table CD_ELO_CARTEIRA where CD_ELO_AGENDAMENTO_ITEM JOIN 
--ELO_AGENDAMENTO_ITEM-CD_ELO_AGENDAMENTO_ITEM
 -- and IC_ATIVO = ‘S’
 -- and QT_AGENDADA_CONFIRMADA > 0

OPEN P_RETORNO  FOR
SELECT * FROM ELO_CARTEIRA WHERE CD_ELO_AGENDAMENTO_ITEM IN(SELECT CD_ELO_AGENDAMENTO_ITEM FROM ELO_AGENDAMENTO_ITEM WHERE
CD_ELO_AGENDAMENTO_SUPERVISOR IN(SELECT CD_ELO_AGENDAMENTO_SUPERVISOR FROM ELO_AGENDAMENTO_SUPERVISOR
WHERE CD_ELO_AGENDAMENTO IN(SELECT CD_ELO_AGENDAMENTO FROM ELO_AGENDAMENTO 
           WHERE
           (CD_POLO=P_CD_POLO OR CD_CENTRO_EXPEDIDOR IN ( SELECT CD_CENTRO_EXPEDIDOR
            FROM ELO_AGENDAMENTO_CENTRO))
         and CD_WEEK=P_CD_WEEK
         AND IC_ATIVO='S')))
         and IC_ATIVO ='S'
         and QT_AGENDADA_CONFIRMADA > 0 ;


         --Get data from table CD_ELO_CARTEIRA_DAY
  --where CD_ELO_CARTEIRA JOIN CD_ELO_CARTEIRA-CD_ELO_CARTEIRA 
 -- and IC_ATIVO = ‘S’
 OPEN P_RETORNO  FOR
SELECT * FROM ELO_CARTEIRA_DAY ED
INNER JOIN ELO_CARTEIRA EC
ON ED.CD_ELO_CARTEIRA=EC.CD_ELO_CARTEIRA
WHERE CD_ELO_AGENDAMENTO_ITEM IN(SELECT CD_ELO_AGENDAMENTO_ITEM FROM ELO_AGENDAMENTO_ITEM WHERE
CD_ELO_AGENDAMENTO_SUPERVISOR IN(SELECT CD_ELO_AGENDAMENTO_SUPERVISOR FROM ELO_AGENDAMENTO_SUPERVISOR
WHERE CD_ELO_AGENDAMENTO IN(SELECT CD_ELO_AGENDAMENTO FROM ELO_AGENDAMENTO 
           WHERE
           (CD_POLO=P_CD_POLO OR CD_CENTRO_EXPEDIDOR IN ( SELECT CD_CENTRO_EXPEDIDOR
            FROM ELO_AGENDAMENTO_CENTRO))
         and CD_WEEK=P_CD_WEEK
         AND IC_ATIVO='S')))
         and IC_ATIVO ='S'
         and QT_AGENDADA_CONFIRMADA > 0 
         AND EC.IC_ATIVO='S';

         --Get data from CD_ELO_MARCACAO
  --where CD_ELO_CARTEIRA JOIN CD_ELO_CARTEIRA where
  --CD_ELO_CARTEIRA = CD_ELO_CARTEIRA-CD_ELO_CARTEIRA
  --and CD_MOTIVO_STATUS is not null
  --and IC_ATIVO = ‘S’
  OPEN P_RETORNO  FOR
  SELECT * FROM ELO_MARCACAO EM
  INNER JOIN ELO_CARTEIRA EC ON EM.CD_ELO_CARTEIRA=EC.CD_ELO_CARTEIRA 
  WHERE CD_ELO_AGENDAMENTO_ITEM IN(SELECT CD_ELO_AGENDAMENTO_ITEM FROM ELO_AGENDAMENTO_ITEM WHERE
CD_ELO_AGENDAMENTO_SUPERVISOR IN(SELECT CD_ELO_AGENDAMENTO_SUPERVISOR FROM ELO_AGENDAMENTO_SUPERVISOR
WHERE CD_ELO_AGENDAMENTO IN(SELECT CD_ELO_AGENDAMENTO FROM ELO_AGENDAMENTO 
           WHERE
           (CD_POLO=P_CD_POLO OR CD_CENTRO_EXPEDIDOR IN ( SELECT CD_CENTRO_EXPEDIDOR
            FROM ELO_AGENDAMENTO_CENTRO))
         and CD_WEEK=P_CD_WEEK
         AND IC_ATIVO='S')))
         and EC.IC_ATIVO ='S'
         and QT_AGENDADA_CONFIRMADA > 0 
         AND EC.IC_ATIVO='S'
         AND EM.CD_MOTIVO_STATUS IS NOT NULL
         AND EM.IC_ATIVO='S';
         END PX_GET_ALL_REPORTDETAILS;

        -- Get data from CD_ELO_CONTROLLERSHIP_REASON
	  --where CD_ELO_CONTROLLERSHIP_REASON JOIN CD_ELO_MARCACAO-CD_MOTIVO_STATUS
PROCEDURE PX_GET_CONTROLLERSHIP_MARCACAO(
 P_CD_POLO         in ELO_AGENDAMENTO.CD_POLO%type,
 P_CD_WEEK          in ELO_AGENDAMENTO.CD_WEEK%type,
 P_RETORNO         out T_CURSOR
 )
 IS
 BEGIN
     OPEN P_RETORNO  FOR
    SELECT SUM(CD_MOTIVO_STATUS) FROM ELO_CONTROLLERSHIP_REASON ECR
    INNER JOIN ELO_MARCACAO EM
    ON ECR.CD_ELO_CONTROLLERSHIP_REASON=EM.CD_MOTIVO_STATUS
  INNER JOIN ELO_CARTEIRA EC ON EM.CD_ELO_CARTEIRA=EC.CD_ELO_CARTEIRA 
  WHERE CD_ELO_AGENDAMENTO_ITEM IN(SELECT CD_ELO_AGENDAMENTO_ITEM FROM ELO_AGENDAMENTO_ITEM WHERE
CD_ELO_AGENDAMENTO_SUPERVISOR IN(SELECT CD_ELO_AGENDAMENTO_SUPERVISOR FROM ELO_AGENDAMENTO_SUPERVISOR
WHERE CD_ELO_AGENDAMENTO IN(SELECT CD_ELO_AGENDAMENTO FROM ELO_AGENDAMENTO 
           WHERE
           (CD_POLO=P_CD_POLO OR CD_CENTRO_EXPEDIDOR IN ( SELECT CD_CENTRO_EXPEDIDOR
            FROM ELO_AGENDAMENTO_CENTRO))
         and CD_WEEK=P_CD_WEEK
         AND IC_ATIVO='S')))
         and EC.IC_ATIVO ='S'
         and QT_AGENDADA_CONFIRMADA > 0 
         AND EC.IC_ATIVO='S'
         AND EM.CD_MOTIVO_STATUS IS NOT NULL
         AND EM.IC_ATIVO='S';
       --  GROUP BY DS_CONTROLLERSHIP_REASON;


END PX_GET_CONTROLLERSHIP_MARCACAO;

PROCEDURE PX_GET_REASONPANELREPORT(
 P_CD_POLO         in ELO_AGENDAMENTO.CD_POLO%type,
 P_CD_WEEK          in ELO_AGENDAMENTO.CD_WEEK%type,

 P_RETORNO         out T_CURSOR

)
 IS
 BEGIN
     OPEN P_RETORNO  FOR

     /***********************************/
      SELECT DH_SAIDA,DH_ENTRADA,CD_MOTIVO_STATUS,NU_QUANTIDADE FROM ELO_MARCACAO EM
  INNER JOIN ELO_CARTEIRA EC ON EM.CD_ELO_CARTEIRA=EC.CD_ELO_CARTEIRA 
  WHERE CD_ELO_AGENDAMENTO_ITEM IN(SELECT CD_ELO_AGENDAMENTO_ITEM FROM ELO_AGENDAMENTO_ITEM WHERE
CD_ELO_AGENDAMENTO_SUPERVISOR IN(SELECT CD_ELO_AGENDAMENTO_SUPERVISOR FROM ELO_AGENDAMENTO_SUPERVISOR
WHERE CD_ELO_AGENDAMENTO IN(SELECT CD_ELO_AGENDAMENTO FROM ELO_AGENDAMENTO 
           WHERE
                     (CD_POLO=P_CD_POLO OR CD_CENTRO_EXPEDIDOR IN ( SELECT CD_CENTRO_EXPEDIDOR
            FROM ELO_AGENDAMENTO_CENTRO))

         --  ((P_CD_POLO IS NULL OR CD_POLO=P_CD_POLO) OR CD_CENTRO_EXPEDIDOR IN ( SELECT CD_CENTRO_EXPEDIDOR
           --FROM ELO_AGENDAMENTO_CENTRO))
         and CD_WEEK=P_CD_WEEK
         AND IC_ATIVO='S')))
         and EC.IC_ATIVO ='S'
         and QT_AGENDADA_CONFIRMADA > 0 
         AND EC.IC_ATIVO='S'
         AND EM.CD_MOTIVO_STATUS IS NOT NULL
         AND EM.IC_ATIVO='S';
         /*****************************************/
         /********
           SELECT DH_SAIDA,DH_ENTRADA,CD_MOTIVO_STATUS,NU_QUANTIDADE FROM ELO_MARCACAO EM
  INNER JOIN ELO_CARTEIRA EC ON EM.CD_ELO_CARTEIRA=EC.CD_ELO_CARTEIRA 
  WHERE 


        EC.IC_ATIVO ='S'
         and QT_AGENDADA_CONFIRMADA > 0 
         AND EM.CD_MOTIVO_STATUS IS NOT NULL
         AND EM.IC_ATIVO='S';
         ****************/

END PX_GET_REASONPANELREPORT;


PROCEDURE PX_GET_ALLREASONPANELREPORT(
        P_CD_POLO         in ELO_AGENDAMENTO.CD_POLO%type,
        P_CD_CENTRO_EXPEDIDOR    in ELO_AGENDAMENTO.CD_CENTRO_EXPEDIDOR%type,
        P_CD_MACHINE      in ELO_AGENDAMENTO.CD_MACHINE%type,
        P_CD_WEEK   in ELO_AGENDAMENTO.CD_WEEK%type,
        P_RETORNO         out T_CURSOR

)
IS
 BEGIN
     OPEN P_RETORNO  FOR
      SELECT DH_SAIDA,DH_ENTRADA,CD_MOTIVO_STATUS,NU_QUANTIDADE FROM ELO_MARCACAO EM
  INNER JOIN ELO_CARTEIRA EC ON EM.CD_ELO_CARTEIRA=EC.CD_ELO_CARTEIRA 
  WHERE CD_ELO_AGENDAMENTO_ITEM IN(SELECT CD_ELO_AGENDAMENTO_ITEM FROM ELO_AGENDAMENTO_ITEM WHERE
CD_ELO_AGENDAMENTO_SUPERVISOR IN(SELECT CD_ELO_AGENDAMENTO_SUPERVISOR FROM ELO_AGENDAMENTO_SUPERVISOR
WHERE CD_ELO_AGENDAMENTO IN(SELECT CD_ELO_AGENDAMENTO FROM ELO_AGENDAMENTO 

           WHERE
           CD_POLO=P_CD_POLO
           AND
           CD_CENTRO_EXPEDIDOR =P_CD_CENTRO_EXPEDIDOR
           AND
           CD_MACHINE =P_CD_MACHINE
           AND
           CD_WEEK=P_CD_WEEK
           AND
           IC_ATIVO ='S')))
         and EC.IC_ATIVO ='S'
         and QT_AGENDADA_CONFIRMADA > 0 
         AND EC.IC_ATIVO='S'
         AND EM.CD_MOTIVO_STATUS IS NOT NULL
         AND EM.IC_ATIVO='S';
END PX_GET_ALLREASONPANELREPORT;


PROCEDURE PX_GET_CONTROLLERSHIP_REASON(

 P_RETORNO         out T_CURSOR
 )
 IS
 BEGIN
     OPEN P_RETORNO  FOR
    SELECT DS_CONTROLLERSHIP_REASON,CD_ELO_CONTROLLERSHIP_REASON FROM ELO_CONTROLLERSHIP_REASON ;



END PX_GET_CONTROLLERSHIP_REASON;







 END GX_ELO_PLANNING_VS_ACTUAL;
/