CREATE OR REPLACE PACKAGE VND."GX_ELO_REPLAN_EMAIL" AS 
TYPE T_CURSOR IS REF CURSOR;
  /* TODO enter package declarations (types, exceptions, methods etc) here */ 
PROCEDURE PX_GET_LOGISTICA_MAIL(
P_RETURN OUT T_CURSOR
); 
PROCEDURE PX_GET_TORRE_DE_FRESTES_MAIL(
P_RETURN OUT T_CURSOR
);
PROCEDURE PX_GET_CONTROLADORIA_MAIL(
P_RETURN OUT T_CURSOR
);

END GX_ELO_REPLAN_EMAIL;


/