ALTER TABLE VND.INTERFACE
 ADD (CD_USUARIO  NUMBER(9));

ALTER TABLE VND.INTERFACE
 ADD (DT_INCLUSAO  DATE);
 
CREATE SEQUENCE VND.SEQ_INTERFACE
  START WITH 1
  MAXVALUE 9999999999999999999999999999
  MINVALUE 1
  NOCYCLE
  CACHE 20
  NOORDER;
  
CREATE OR REPLACE TRIGGER VND.TI_INTERFACE 
BEFORE INSERT ON VND.INTERFACE 
REFERENCING NEW AS new FOR EACH ROW
DECLARE



BEGIN

    IF :new.CD_INTERFACE IS NULL   THEN 
        :new.CD_INTERFACE:= VND.SEQ_INTERFACE.NEXTVAL;
    END IF;

END;  

GRANT EXECUTE ON VND.GX_ELO_INTERFACE TO VND, VND_SEC;

  
  