WITH AGENDAMENTO AS 
(

SELECT AGE.CD_ELO_AGENDAMENTO, AGE.CD_WEEK, AGE.CD_POLO, PO.DS_POLO, AGE.CD_MACHINE, AGE.CD_CENTRO_EXPEDIDOR, 
AGE.CD_ELO_STATUS, AGE.DT_WEEK_START 
FROM VND.ELO_AGENDAMENTO AGE
LEFT JOIN CTF.POLO PO ON AGE.CD_POLO = PO.CD_POLO
WHERE 
AGE.IC_ATIVO = 'S'
AND AGE.DT_WEEK_START < CURRENT_DATE - 20
--AND AGE.CD_ELO_STATUS IN (3,4,5,6,7)
--AND AGE.CD_ELO_STATUS IN (3,4,5,6)
--AND AGE.CD_ELO_STATUS IN (4,6)  --1 PASSO SEM ERRO STATUS 59
AND AGE.CD_ELO_STATUS IN (6, 7)  --2 PASSO SEM ERRO STATUS 59 
)
--select * from AGENDAMENTO

SELECT DISTINCT
ag.cd_elo_agendamento, AG.CD_WEEK, AG.CD_POLO, AG.DS_POLO, AG.CD_CENTRO_EXPEDIDOR, ag.CD_MACHINE, AG.CD_ELO_STATUS STAGEND, AG.DT_WEEK_START, 
CT.*,
 
(SELECT SUM(NVL(SS.QT_SEMANA,0)) FROM VND.ELO_AGENDAMENTO_WEEK SS 
WHERE CT.CD_ELO_AGENDAMENTO_ITEM = SS.CD_ELO_AGENDAMENTO_ITEM) QT_SEMANA,

(SELECT SUM(NVL(DDAY.NU_QUANTIDADE,0)) FROM VND.ELO_AGENDAMENTO_WEEK SS
INNER JOIN VND.ELO_AGENDAMENTO_DAY DDAY ON SS.CD_ELO_AGENDAMENTO_WEEK = DDAY.CD_ELO_AGENDAMENTO_WEEK 
WHERE CT.CD_ELO_AGENDAMENTO_ITEM = SS.CD_ELO_AGENDAMENTO_ITEM) QT_DAY,

(SELECT SUM(NVL(ss.qt_agendada_confirmada,0)) FROM VND.ELO_carteira SS
WHERE CT.CD_ELO_AGENDAMENTO_item = SS.CD_ELO_AGENDAMENTO_item
and ss.cd_status_cel_final = 59
AND (ss.CD_TIPO_AGENDAMENTO IN (22,23,24) 
        OR (ss.CD_TIPO_AGENDAMENTO = 25 AND ss.CD_STATUS_REPLAN = 32) 
        OR (ss.CD_TIPO_AGENDAMENTO IS NULL 
        AND EXISTS (SELECT 1 FROM VND.VW_ELO_AGENDAMENTO_ITEM_ADICAO IIS WHERE IIS.CD_ELO_AGENDAMENTO_ITEM = ss.CD_ELO_AGENDAMENTO_ITEM)) )

) QT_carteira


FROM AGENDAMENTO AG 
left join VND.ELO_CARTEIRA CT
ON 
AG.CD_ELO_AGENDAMENTO = CT.CD_ELO_AGENDAMENTO
WHERE
1=1 
and CT.IC_ATIVO = 'S'

AND NVL(CT.QT_AGENDADA_CONFIRMADA,0) > 0
--AND CT.QT_AGENDADA > 0
--AND (CT.DH_CORTADO_FABRICA IS NULL AND NVL(CT.QT_AGENDADA_CELULA, 1) > 0)  
--AND NVL(CT.CD_STATUS_CEL_FINAL, 40) NOT IN (66, 41, 59, 57, 58 )
AND NVL(CT.CD_STATUS_CEL_FINAL, 40)  IN (59 )
--AND CT.CD_MOTIVO_RECUSA IS NULL
--AND NOT(NVL(CT.NU_ORDEM_VENDA, '0') IN ('          ', '0', '0         ' )) 

AND (CT.CD_TIPO_AGENDAMENTO IN (22,23,24) 
        OR (CT.CD_TIPO_AGENDAMENTO = 25 AND CT.CD_STATUS_REPLAN = 32) 
        OR (CT.CD_TIPO_AGENDAMENTO IS NULL 
        AND EXISTS (SELECT 1 FROM VND.VW_ELO_AGENDAMENTO_ITEM_ADICAO IIS WHERE IIS.CD_ELO_AGENDAMENTO_ITEM = CT.CD_ELO_AGENDAMENTO_ITEM)) )


;
