ALTER TABLE VND.CONTRATO
 ADD (CD_BLOQUEIO_REMESSA  CHAR(2));

ALTER TABLE VND.CONTRATO
 ADD (CD_BLOQUEIO_FATURAMENTO  CHAR(2));

ALTER TABLE VND.CONTRATO
 ADD (CD_BLOQUEIO_CREDITO  CHAR(1));

ALTER TABLE VND.CONTRATO
 ADD (CD_BLOQUEIO_ENTREGA  CHAR(2));

ALTER TABLE VND.CONTRATO
 ADD (DS_ROTEIRO_ENTREGA  VARCHAR2(4000));

ALTER TABLE VND.CONTRATO
 ADD (DS_CREDIT_BLOCK_REASON  VARCHAR2(50));


ALTER TABLE VND.PEDIDO
 DROP CONSTRAINT SYS_C0012744;

ALTER TABLE VND.PEDIDO
 MODIFY(CD_BLOQUEIO_CREDITO CHAR(1));

ALTER TABLE VND.PEDIDO
 ADD (CD_BLOQUEIO_ENTREGA  CHAR(2));

ALTER TABLE VND.PEDIDO
 ADD (DS_CREDIT_BLOCK_REASON  VARCHAR2(50));

ALTER TABLE VND.PEDIDO
 ADD (CD_BLOQUEIO_FATURAMENTO_ITEM  CHAR(2));

ALTER TABLE VND.PEDIDO
 ADD (CD_BLOQUEIO_REMESSA_ITEM  CHAR(2));


ALTER TABLE VND.ITEM_CONTRATO
 ADD (CD_BLOQUEIO_FATURAMENTO_ITEM  CHAR(2));



COMMENT ON COLUMN VND.PEDIDO.DS_ROTEIRO_ENTREGA IS 'Text ID = Z009';

COMMENT ON COLUMN VND.PEDIDO.CD_BLOQUEIO_REMESSA IS 'VBAK-LIFSK';

COMMENT ON COLUMN VND.PEDIDO.CD_BLOQUEIO_FATURAMENTO IS 'VBAK-FAKSK';

COMMENT ON COLUMN VND.PEDIDO.CD_BLOQUEIO_CREDITO IS 'VBUK-CMGST';

COMMENT ON COLUMN VND.PEDIDO.DS_CREDIT_BLOCK_REASON IS 'VBAK-ZZCRE_BLK';

COMMENT ON COLUMN VND.PEDIDO.CD_BLOQUEIO_FATURAMENTO_ITEM IS 'VBAP-FAKSP';

COMMENT ON COLUMN VND.PEDIDO.CD_BLOQUEIO_REMESSA_ITEM IS 'VBEP-LIFSP';



COMMENT ON COLUMN VND.CONTRATO.CD_BLOQUEIO_REMESSA IS 'VBAK-LIFSK';

COMMENT ON COLUMN VND.CONTRATO.CD_BLOQUEIO_FATURAMENTO IS 'VBAK-FAKSK';

COMMENT ON COLUMN VND.CONTRATO.CD_BLOQUEIO_CREDITO IS 'VBUK-CMGST';

COMMENT ON COLUMN VND.CONTRATO.DS_ROTEIRO_ENTREGA IS 'Text ID = Z009';

COMMENT ON COLUMN VND.CONTRATO.DS_CREDIT_BLOCK_REASON IS 'VBAK-ZZCRE_BLK';



COMMENT ON COLUMN VND.ITEM_CONTRATO.CD_BLOQUEIO_FATURAMENTO_ITEM IS 'VBAP-FAKSP';