CREATE TABLE VND.ELO_AGENDAMENTO_BACKLOG
(
  CD_ELO_AGENDAMENTO_BACKLOG        NUMBER(9),
  CD_WEEK                           VARCHAR2(10)             NOT NULL,
  DT_WEEK_START                     DATE                     NOT NULL,
  SG_TIPO_DOCUMENTO                 CHAR(1)                  NOT NULL,
  NU_DOCUMENTO                      VARCHAR2(30)             NOT NULL,
  NU_ITEM_DOCUMENTO                 NUMBER(6),
  QT_FORNECIDA                      NUMBER(10,3)             DEFAULT 0                     NOT NULL,
  QT_BACKLOG                        NUMBER(10,3)             DEFAULT 0                     NOT NULL,
  QT_BACKLOG_CONFIRMADA             NUMBER(10,3)             DEFAULT 0,
  QT_CONTRATADA                     NUMBER(10,3)             DEFAULT 0,
  QT_AGENDADA_SEMANA_2              NUMBER(10,3)             DEFAULT 0,
  QT_REJEITADA_SEMANA_2             NUMBER(10,3)             DEFAULT 0,
  DH_BACKLOG                        DATE                     NOT NULL,
  DT_WEEK_START_REF                 DATE
);

COMMENT ON COLUMN VND.ELO_AGENDAMENTO_BACKLOG.SG_TIPO_DOCUMENTO IS 'P = Protocolo; C = Contrato Não Desdobramento e Não Venda Ordem; D = Contrato Desdobramento';

CREATE UNIQUE INDEX VND.ELO_AGENDAMENTO_BACKLOG_PK ON VND.ELO_AGENDAMENTO_BACKLOG
(CD_ELO_AGENDAMENTO_BACKLOG);

ALTER TABLE VND.ELO_AGENDAMENTO_BACKLOG ADD (
  CONSTRAINT ELO_AGENDAMENTO_BACKLOG_PK
  PRIMARY KEY
  (CD_ELO_AGENDAMENTO_BACKLOG)
  USING INDEX VND.ELO_AGENDAMENTO_BACKLOG_PK
  ENABLE VALIDATE);

ALTER TABLE VND.ELO_AGENDAMENTO_BACKLOG
 ADD CONSTRAINT ELO_AGENDAMENTO_BACKLOG_U01
  UNIQUE (DT_WEEK_START, NU_DOCUMENTO, NU_ITEM_DOCUMENTO)
  ENABLE VALIDATE;

CREATE INDEX VND.IDX_ELO_AGENDAMENTO_BAKCLOG_1 ON VND.ELO_AGENDAMENTO_BACKLOG
(CD_WEEK);
