CREATE TABLE VND.ELO_AGENDAMENTO_BACKLOG_LOG
(
  CD_ELO_AGENDAMENTO_BACKLOG_LOG  NUMBER(9)     NOT NULL,
  DH_LOG                          DATE          NOT NULL,
  CD_USUARIO                      NUMBER(9)     NOT NULL,
  QT_BACKLOG_CONFIRMADA_OLD       NUMBER(10,3),
  QT_BACKLOG_CONFIRMADA_NEW       NUMBER(10,3)
)
STORAGE    (
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOCOMPRESS 
NOCACHE
RESULT_CACHE (MODE DEFAULT)
NOPARALLEL
NOMONITORING;


ALTER TABLE VND.ELO_AGENDAMENTO_BACKLOG_LOG ADD (
  CONSTRAINT ELO_AGENDAMENTO_BACKLOG_LOG_PK
  PRIMARY KEY
  (CD_ELO_AGENDAMENTO_BACKLOG_LOG)
  ENABLE VALIDATE);