ALTER TABLE VND.ELO_CARTEIRA
 ADD (QT_REJEITADA  NUMBER(15,3)                    DEFAULT 0)
/

ALTER TABLE VND.ELO_CARTEIRA
 ADD (QT_AGENDADA_ORIGINAL  NUMBER(15,3))
/

ALTER TABLE VND.ELO_CARTEIRA
 ADD (DS_VERSAO  VARCHAR2(4000))
/