WITH AGENDAMENTO AS 
(
--SELECT * FROM CTF.POLO
SELECT AGE.CD_ELO_AGENDAMENTO, AGE.CD_WEEK, AGE.CD_POLO, AGE.CD_MACHINE, AGE.CD_CENTRO_EXPEDIDOR, 
AGE.CD_ELO_STATUS
FROM VND.ELO_AGENDAMENTO AGE
WHERE 
AGE.IC_ATIVO = 'S'
--AND ('P002' IS NULL OR AGE.CD_CENTRO_EXPEDIDOR = '6100')
AND ('P002' IS NULL OR AGE.CD_POLO = 'P002')
AND AGE.CD_WEEK = 'W172018'
)

SELECT proto.* FROM VND.ELO_CARTEIRA CAT
INNER JOIN AGENDAMENTO AGE
ON AGE.CD_ELO_AGENDAMENTO = CAT.CD_ELO_AGENDAMENTO 
INNER JOIN VND.ELO_VBAK_PROTOCOLO PROTO
ON CAT.CD_ELO_CARTEIRA = PROTO.CD_ELO_CARTEIRA

WHERE 
1=1
--CAT.NU_CONTRATO_SAP = '0040381286'
--AND CAT.NU_ORDEM_VENDA = '0002329331'
AND PROTO.NU_PROTOCOLO in( 'R121342CL1', 'R121354UB1')


UPDATE VND.ELO_VBAK_PROTOCOLO 
SET QT_AGENDADA_PROTOCOLO = 0 
WHERE 
CD_ELO_CARTEIRA = 27631
AND NU_PROTOCOLO in( 'R121342CL1', 'R121354UB1')
AND CD_ELO_VBAK_PROTOCOLO in ( 292, 298);
commit;

