WITH AGENDAMENTO AS 
(
--SELECT * FROM CTF.POLO
SELECT AGE.CD_ELO_AGENDAMENTO, AGE.CD_WEEK, AGE.CD_POLO, AGE.CD_MACHINE, AGE.CD_CENTRO_EXPEDIDOR, 
AGE.CD_ELO_STATUS
FROM VND.ELO_AGENDAMENTO AGE
WHERE 
AGE.IC_ATIVO = 'S'
AND AGE.CD_ELO_STATUS IN (4,5, 6,7) 
--AND ('6100' IS NULL OR AGE.CD_CENTRO_EXPEDIDOR = '6100')
--AND ('P002' IS NULL OR AGE.CD_POLO = 'P002')
--AND AGE.CD_WEEK = 'W172018'
),
--select * from AGENDAMENTO

CTE_SHOW_BY_TYPE AS 
(
SELECT 'CARTEIRA', 'S' IC_ATIVO FROM  DUAL
UNION
SELECT 'CONTRATO', 'N' IC_ATIVO FROM  DUAL
UNION
SELECT 'ITEM_CONTRATO', 'N' IC_ATIVO FROM  DUAL
UNION
SELECT 'PEDIDO', 'S' IC_ATIVO FROM  DUAL
UNION
SELECT 'PROTOCOLO', 'N' IC_ATIVO FROM  DUAL
UNION
SELECT 'ENTREGA', 'N' IC_ATIVO FROM  DUAL
UNION
SELECT 'AGENDAMENTO_ITEM', 'N' IC_ATIVO FROM  DUAL
UNION
SELECT 'AGENDAMENTO_DAY', 'N' IC_ATIVO FROM  DUAL

),


--SELECT * FROM CTE_SHOW_BY_TYPE

CTE_CONTRATO_PEDIDOS AS 
(
SELECT 
'' NU_CONTRATO_SAP, 
0 CD_ITEM_CONTRATO, 
'' NU_ORDEM_VENDA, 
'' CD_PRODUTO_SAP, 
0 NU_CONTRATO ,
'' NU_PROTOCOLO
FROM DUAL
UNION
SELECT 
'' NU_CONTRATO_SAP, 
0 CD_ITEM_CONTRATO, 
'' NU_ORDEM_VENDA, 
'' CD_PRODUTO_SAP , 
0 NU_CONTRATO ,
'' NU_PROTOCOLO
FROM DUAL
UNION 
SELECT DISTINCT 
CT.NU_CONTRATO_SAP, 
CT.CD_ITEM_CONTRATO, 
CT.NU_ORDEM_VENDA, 
CT.CD_PRODUTO_SAP, 
CT.NU_CONTRATO ,
'' NU_PROTOCOLO
FROM VND.ELO_CARTEIRA CT
INNER JOIN AGENDAMENTO AG
ON 
AG.CD_ELO_AGENDAMENTO = CT.CD_ELO_AGENDAMENTO
WHERE 
CT.IC_ATIVO = 'S'
AND CT.QT_AGENDADA_CONFIRMADA >0
AND CT.CD_STATUS_CEL_FINAL <> 59

),
--SELECT * FROM CTE_CONTRATO_PEDIDOS

CTE_CONTRATO AS
(
SELECT  
CONT.CD_CONTRATO,CONT.NU_CONTRATO,CONT.CD_STATUS_CONTRATO,CONT.CD_CLIENTE_CONTRATO,
CONT.CD_CLIENTE_EMISSOR,CONT.CD_TIPO_ORDEM, CONT.CD_CENTRO_EXPEDIDOR,CONT.CD_USUARIO_VENDA,
CONT.CD_AGENTE_VENDA,CONT.CD_USUARIO_INCLUSAO,CONT.DH_INCLUSAO,
CONT.DH_GERACAO,CONT.DH_IMPRESSAO,CONT.DH_ASSINATURA,CONT.DH_ENVIO_ADVEN,CONT.DH_ENVIO_SAP,
CONT.DH_PROCESSAMENTO,CONT.DT_PAGAMENTO,CONT.DS_FORMA_PAGAMENTO,CONT.DS_COND_ESP_PAGTO,CONT.DT_INICIO,
CONT.DT_FIM,CONT.VL_FRETE_DISTRIBUICAO,CONT.DS_PROTOCOLO,CONT.IC_ATIVO,CONT.DS_JUSTIFICATIVA,
CONT.CD_MOTIVO_ORDEM,CONT.DS_COMPOSICAO_CARGA,CONT.DS_OBSERVACAO,CONT.IC_ALTERA_SUBSTITUI,
CONT.CD_INCOTERMS,CONT.DH_LISTA_PRECO,CONT.DS_GARANTIAS,CONT.DH_PRAZO_GARANTIA,CONT.VL_FACIL,
CONT.DS_CREDENCIAMENTO_FOB,CONT.CD_SALES_ORG,CONT.CD_DISTRIBUTION_CHANNEL,CONT.CD_SALES_DIVISION,
CONT.IC_NEW_PRODUCT,CONT.IC_NEW_CUSTOMER,CONT.IC_SIGNED,CONT.IC_SAP_READY,CONT.DH_NEW_PRODUCT,
CONT.DH_NEW_CUSTOMER,CONT.DH_SAP_READY,CONT.DH_EMAIL_MASTERDATA,CONT.DH_EMAIL_ADVEN,CONT.NU_CONTRATO_SAP,
CONT.CD_TIPO_CONTRATO,CONT.DH_CANCELAMENTO,CONT.CD_USUARIO_CANCELAMENTO,CONT.DH_ULT_INTERFACE,
CONT.CD_BLOCKING_REASON,CONT.CD_SITUACAO_CONTRATO,CONT.CD_FORMA_PAGAMENTO,CONT.IC_SAP,
CONT.CD_STATUS_CONTRATO_SAP,CONT.CD_USUARIO_RECEBIMENTO,CONT.DH_RECEBIMENTO,
CONT.IC_RECEBIDO,CONT.DH_ULT_ALTERACAO,CONT.IC_ORIGEM_CONTRATO,CONT.CD_TIPO_PAGAMENTO,
CONT.CD_CLIENTE_PO_NUMERO,CONT.DH_ENVIO_ASSINATURA,CONT.DH_REENVIO_ASSINATURA,
CONT.CD_USUARIO_APROVACAO_CLIENTE,CONT.CD_USUARIO_REJEICAO_CLIENTE,CONT.CD_USUARIO_REJEICAO_SUPERVISOR,
CONT.DH_APROVACAO_CLIENTE,CONT.DH_REJEICAO_CLIENTE,CONT.DH_REJEICAO_SUPERVISOR,CONT.DS_MOTIVO_REJEICAO_CLIENTE,
CONT.DS_MOTIVO_REJEICAO_SUPERVISOR,CONT.IC_ASSINATURA_ELETRONICA,
CONT.CD_USUARIO_APROVACAO_SUPERV,CONT.DH_APROVACAO_SUPERVISOR,CONT.CD_BLOQUEIO_CREDITO,CONT.CD_BLOQUEIO_ENTREGA,
CONT.CD_BLOQUEIO_FATURAMENTO,CONT.CD_BLOQUEIO_REMESSA,CONT.DS_CREDIT_BLOCK_REASON,CONT.DS_ROTEIRO_ENTREGA

FROM vnd.contrato CONT
WHERE 
EXISTS (SELECT 1 FROM  CTE_CONTRATO_PEDIDOS CP 
WHERE CP.NU_CONTRATO_SAP = CONT.NU_CONTRATO_SAP AND NVL(CP.CD_ITEM_CONTRATO, '') = ''  )
UNION
SELECT DISTINCT 
CONT.CD_CONTRATO,CONT.NU_CONTRATO,CONT.CD_STATUS_CONTRATO,CONT.CD_CLIENTE_CONTRATO,
CONT.CD_CLIENTE_EMISSOR,CONT.CD_TIPO_ORDEM, CONT.CD_CENTRO_EXPEDIDOR,CONT.CD_USUARIO_VENDA,
CONT.CD_AGENTE_VENDA,CONT.CD_USUARIO_INCLUSAO,CONT.DH_INCLUSAO,
CONT.DH_GERACAO,CONT.DH_IMPRESSAO,CONT.DH_ASSINATURA,CONT.DH_ENVIO_ADVEN,CONT.DH_ENVIO_SAP,
CONT.DH_PROCESSAMENTO,CONT.DT_PAGAMENTO,CONT.DS_FORMA_PAGAMENTO,CONT.DS_COND_ESP_PAGTO,CONT.DT_INICIO,
CONT.DT_FIM,CONT.VL_FRETE_DISTRIBUICAO,CONT.DS_PROTOCOLO,CONT.IC_ATIVO,CONT.DS_JUSTIFICATIVA,
CONT.CD_MOTIVO_ORDEM,CONT.DS_COMPOSICAO_CARGA,CONT.DS_OBSERVACAO,CONT.IC_ALTERA_SUBSTITUI,
CONT.CD_INCOTERMS,CONT.DH_LISTA_PRECO,CONT.DS_GARANTIAS,CONT.DH_PRAZO_GARANTIA,CONT.VL_FACIL,
CONT.DS_CREDENCIAMENTO_FOB,CONT.CD_SALES_ORG,CONT.CD_DISTRIBUTION_CHANNEL,CONT.CD_SALES_DIVISION,
CONT.IC_NEW_PRODUCT,CONT.IC_NEW_CUSTOMER,CONT.IC_SIGNED,CONT.IC_SAP_READY,CONT.DH_NEW_PRODUCT,
CONT.DH_NEW_CUSTOMER,CONT.DH_SAP_READY,CONT.DH_EMAIL_MASTERDATA,CONT.DH_EMAIL_ADVEN,CONT.NU_CONTRATO_SAP,
CONT.CD_TIPO_CONTRATO,CONT.DH_CANCELAMENTO,CONT.CD_USUARIO_CANCELAMENTO,CONT.DH_ULT_INTERFACE,
CONT.CD_BLOCKING_REASON,CONT.CD_SITUACAO_CONTRATO,CONT.CD_FORMA_PAGAMENTO,CONT.IC_SAP,
CONT.CD_STATUS_CONTRATO_SAP,CONT.CD_USUARIO_RECEBIMENTO,CONT.DH_RECEBIMENTO,
CONT.IC_RECEBIDO,CONT.DH_ULT_ALTERACAO,CONT.IC_ORIGEM_CONTRATO,CONT.CD_TIPO_PAGAMENTO,
CONT.CD_CLIENTE_PO_NUMERO,CONT.DH_ENVIO_ASSINATURA,CONT.DH_REENVIO_ASSINATURA,
CONT.CD_USUARIO_APROVACAO_CLIENTE,CONT.CD_USUARIO_REJEICAO_CLIENTE,CONT.CD_USUARIO_REJEICAO_SUPERVISOR,
CONT.DH_APROVACAO_CLIENTE,CONT.DH_REJEICAO_CLIENTE,CONT.DH_REJEICAO_SUPERVISOR,CONT.DS_MOTIVO_REJEICAO_CLIENTE,
CONT.DS_MOTIVO_REJEICAO_SUPERVISOR,CONT.IC_ASSINATURA_ELETRONICA,
CONT.CD_USUARIO_APROVACAO_SUPERV,CONT.DH_APROVACAO_SUPERVISOR,CONT.CD_BLOQUEIO_CREDITO,CONT.CD_BLOQUEIO_ENTREGA,
CONT.CD_BLOQUEIO_FATURAMENTO,CONT.CD_BLOQUEIO_REMESSA,CONT.DS_CREDIT_BLOCK_REASON,CONT.DS_ROTEIRO_ENTREGA
FROM vnd.contrato CONT
INNER JOIN VND.ITEM_CONTRATO ICTR
ON CONT.CD_CONTRATO = ICTR.CD_CONTRATO
WHERE 
EXISTS (
SELECT 1 FROM  CTE_CONTRATO_PEDIDOS CP 
WHERE 
CP.NU_CONTRATO_SAP = CONT.NU_CONTRATO_SAP 
AND CP.CD_ITEM_CONTRATO = ICTR.CD_ITEM_CONTRATO )
),
--SELECT * FROM CTE_CONTRATO

CTE_ITEM_CONTRATO AS 
(
SELECT ICTR.* FROM VND.ITEM_CONTRATO ICTR
WHERE EXISTS (SELECT 1 FROM CTE_CONTRATO CCTR WHERE CCTR.CD_CONTRATO = ICTR.CD_CONTRATO)
),
--SELECT * FROM CTE_ITEM_CONTRATO
CTE_WHOISPEDIDO AS 
(
SELECT PED.CD_PEDIDO, PED.CD_ITEM_PEDIDO FROM VND.PEDIDO PED
WHERE
EXISTS (SELECT 1 FROM CTE_CONTRATO_PEDIDOS CCP 
WHERE CCP.NU_CONTRATO = PED.NU_CONTRATO)
UNION 
SELECT PED.CD_PEDIDO, PED.CD_ITEM_PEDIDO FROM VND.PEDIDO PED
WHERE 
EXISTS (SELECT 1 FROM CTE_CONTRATO_PEDIDOS CCP 
WHERE CCP.NU_ORDEM_VENDA = PED.NU_ORDEM_VENDA)
),

CTE_PEDIDO AS 
(
SELECT  
PED.CD_PEDIDO,PED.CD_ITEM_PEDIDO,PED.CD_CONTRATO,PED.CD_SITUACAO_PEDIDO,PED.CD_PRODUTO_SAP,
PED.DS_PRODUTO_SAP,PED.CD_CENTRO_EXPEDIDOR,PED.NU_ORDEM_VENDA,PED.DH_PEDIDO,
PED.DH_ULT_EXPEDICAO,PED.NU_QUANTIDADE,PED.NU_QUANTIDADE_SALDO,PED.NU_ORDEM_VENDA_ORIGINAL,
PED.IC_CANCELAMENTO,PED.DH_CANCELAMENTO,PED.DS_ROTEIRO_ENTREGA,PED.CD_BLOQUEIO_REMESSA,
PED.CD_BLOQUEIO_FATURAMENTO,PED.CD_BLOQUEIO_CREDITO,PED.CD_MOTIVO_RECUSA,PED.CD_SACARIA,
PED.DH_ULT_ALTERACAO,PED.DH_EMISSAO,PED.IC_FATURADO,PED.DH_INCLUSAO,
PED.CD_MOTIVO_BLOQUEIO_CREDITO,PED.DH_ULT_INTERFACE,PED.IC_BLOQUEIO_DIVISAO_REMESSA,
PED.NU_CONTRATO,PED.NU_CONTRATO_SAP,PED.NU_QUANTIDADE_ENTREGUE,PED.DH_ENTREGA,
PED.CD_ITEM_CONTRATO,PED.CD_BLOQUEIO_ENTREGA,PED.CD_BLOQUEIO_FATURAMENTO_ITEM,
PED.CD_BLOQUEIO_REMESSA_ITEM,PED.DS_CREDIT_BLOCK_REASON
FROM VND.PEDIDO PED
WHERE 
EXISTS 
(SELECT 1 FROM CTE_WHOISPEDIDO WHP
WHERE WHP.CD_PEDIDO = PED.CD_PEDIDO AND WHP.CD_ITEM_PEDIDO = PED.CD_ITEM_PEDIDO)
)--,
SELECT * FROM CTE_PEDIDO

CTE_DISPONIBILIDADE_PROT AS
(
SELECT VPR.CD_ELO_CARTEIRA, VPR.NU_PROTOCOLO, 
VB.NU_CONTRATO_SAP, VB.CD_ITEM_CONTRATO, 
VPR.QT_AGENDADA_PROTOCOLO, VPR.CD_ELO_VBAK, VPR.CD_ELO_VBAK_PROTOCOLO
FROM VND.ELO_VBAK_PROTOCOLO VPR
INNER JOIN VND.ELO_VBAK VB
ON VPR.CD_ELO_VBAK = VB.CD_ELO_VBAK
WHERE 

EXISTS (SELECT 1 FROM VND.ELO_CARTEIRA CTA 
INNER JOIN AGENDAMENTO AGEN ON CTA.CD_ELO_AGENDAMENTO = AGEN.CD_ELO_AGENDAMENTO
INNER JOIN CTE_CONTRATO_PEDIDOS CCPP 
ON CCPP.NU_CONTRATO_SAP = CTA.NU_CONTRATO_SAP
AND CCPP.CD_ITEM_CONTRATO = CTA.CD_ITEM_CONTRATO
WHERE  VPR.CD_ELO_CARTEIRA = CTA.CD_ELO_CARTEIRA
AND CTA.IC_ATIVO = 'S')

AND VPR.IC_ATIVO = 'S'
AND VB.IC_ATIVO = 'S'
UNION
SELECT VPR.CD_ELO_CARTEIRA, VPR.NU_PROTOCOLO, 
VB.NU_CONTRATO_SAP, VB.CD_ITEM_CONTRATO, 
VPR.QT_AGENDADA_PROTOCOLO, VPR.CD_ELO_VBAK, VPR.CD_ELO_VBAK_PROTOCOLO
FROM VND.ELO_VBAK_PROTOCOLO VPR
INNER JOIN VND.ELO_VBAK VB
ON VPR.CD_ELO_VBAK = VB.CD_ELO_VBAK
WHERE 

EXISTS (SELECT 1 FROM CTE_CONTRATO_PEDIDOS CCPP 
WHERE  CCPP.NU_PROTOCOLO = VPR.NU_PROTOCOLO)
AND VPR.IC_ATIVO = 'S'
AND VB.IC_ATIVO = 'S'


),
--SELECT * FROM CTE_DISPONIBILIDADE_PROT
CTE_ENTREGA AS (
SELECT CPT_ENT.CD_ENTREGA, CPT_ENT.DT_SUGESTAO_ENTREGA, CPT_ENT.QT_QUANTIDADE, 
CPT_ENT.DS_ROTEIRO,CPT_ENT.SG_STATUS, CPT_ENT.QT_FORNECIDO, CPT_ENT.NU_PROTOCOLO_ENTREGA,
CPT_ENT.IC_ENTREGA_OUTRA_FILIAL, CPT_AUT.CD_COOPERADO, CPT_AUT.NU_NOTA_FISCAL, 
CPT_AUT.NU_ITEM_NOTA_FISCAL, CPT_AUT.QT_QUANTIDADE QT_QUANTIDADE_AUTORIZADA,
CPT_AUT.CD_PROPRIEDADE, CPT_AUT.CD_COOPERATIVA_FILIAL, CPT_AUT.CD_SACARIA,
CPT_AUT.CD_PRODUTO_SAP, CPT_AUT.NU_CONTRATO, CPT_AUT.NU_ORDEM_VENDA, 
CPT_AUT.NU_CONTRATO_SAP, CPT_AUT.CD_ITEM_CONTRATO
FROM CPT.ENTREGA CPT_ENT 
INNER JOIN CPT.AUTORIZACAO_ENTREGA CPT_AUT 
ON CPT_ENT.CD_AUTORIZACAO_ENTREGA = CPT_AUT.CD_AUTORIZACAO_ENTREGA 
WHERE
CPT_ENT.SG_STATUS NOT IN ( 'C')
AND EXISTS (SELECT 1 
        FROM CTE_DISPONIBILIDADE_PROT PRPT 
        WHERE CPT_ENT.NU_PROTOCOLO_ENTREGA = PRPT.NU_PROTOCOLO)
UNION
SELECT CPT_ENT.CD_ENTREGA, CPT_ENT.DT_SUGESTAO_ENTREGA, CPT_ENT.QT_QUANTIDADE, 
CPT_ENT.DS_ROTEIRO,CPT_ENT.SG_STATUS, CPT_ENT.QT_FORNECIDO, CPT_ENT.NU_PROTOCOLO_ENTREGA,
CPT_ENT.IC_ENTREGA_OUTRA_FILIAL, CPT_AUT.CD_COOPERADO, CPT_AUT.NU_NOTA_FISCAL, 
CPT_AUT.NU_ITEM_NOTA_FISCAL, CPT_AUT.QT_QUANTIDADE QT_QUANTIDADE_AUTORIZADA,
CPT_AUT.CD_PROPRIEDADE, CPT_AUT.CD_COOPERATIVA_FILIAL, CPT_AUT.CD_SACARIA,
CPT_AUT.CD_PRODUTO_SAP, CPT_AUT.NU_CONTRATO, CPT_AUT.NU_ORDEM_VENDA, 
CPT_AUT.NU_CONTRATO_SAP, CPT_AUT.CD_ITEM_CONTRATO
FROM CPT.ENTREGA CPT_ENT 
INNER JOIN CPT.AUTORIZACAO_ENTREGA CPT_AUT 
ON CPT_ENT.CD_AUTORIZACAO_ENTREGA = CPT_AUT.CD_AUTORIZACAO_ENTREGA 
WHERE
CPT_ENT.SG_STATUS NOT IN ( 'C')
AND EXISTS (SELECT 1 
        FROM CTE_CONTRATO_PEDIDOS PRPT 
        WHERE CPT_AUT.NU_CONTRATO_SAP = PRPT.NU_CONTRATO_SAP
        AND CPT_AUT.CD_ITEM_CONTRATO = CPT_AUT.CD_ITEM_CONTRATO)

UNION
SELECT CPT_ENT.CD_ENTREGA, CPT_ENT.DT_SUGESTAO_ENTREGA, CPT_ENT.QT_QUANTIDADE, 
CPT_ENT.DS_ROTEIRO,CPT_ENT.SG_STATUS, CPT_ENT.QT_FORNECIDO, CPT_ENT.NU_PROTOCOLO_ENTREGA,
CPT_ENT.IC_ENTREGA_OUTRA_FILIAL, CPT_AUT.CD_COOPERADO, CPT_AUT.NU_NOTA_FISCAL, 
CPT_AUT.NU_ITEM_NOTA_FISCAL, CPT_AUT.QT_QUANTIDADE QT_QUANTIDADE_AUTORIZADA,
CPT_AUT.CD_PROPRIEDADE, CPT_AUT.CD_COOPERATIVA_FILIAL, CPT_AUT.CD_SACARIA,
CPT_AUT.CD_PRODUTO_SAP, CPT_AUT.NU_CONTRATO, CPT_AUT.NU_ORDEM_VENDA, 
CPT_AUT.NU_CONTRATO_SAP, CPT_AUT.CD_ITEM_CONTRATO
FROM CPT.ENTREGA CPT_ENT 
INNER JOIN CPT.AUTORIZACAO_ENTREGA CPT_AUT 
ON CPT_ENT.CD_AUTORIZACAO_ENTREGA = CPT_AUT.CD_AUTORIZACAO_ENTREGA 
WHERE
CPT_ENT.SG_STATUS NOT IN ( 'C')
AND EXISTS (SELECT 1 
        FROM CTE_CONTRATO_PEDIDOS PRPT 
        WHERE CPT_ENT.NU_PROTOCOLO_ENTREGA = PRPT.NU_PROTOCOLO
       )
       
), 
--SELECT * FROM CTE_ENTREGA
CTE_CARTEIRA AS 
(

SELECT CC.CD_ELO_CARTEIRA, CC.CD_ELO_AGENDAMENTO, CC.NU_CONTRATO_SAP, CC.CD_ITEM_CONTRATO, CC.NU_ORDEM_VENDA,
XAGE.CD_WEEK, XAGE.CD_CENTRO_EXPEDIDOR

FROM 
(

SELECT CTA.CD_ELO_CARTEIRA, CTA.CD_ELO_AGENDAMENTO, CTA.NU_CONTRATO_SAP, CTA.CD_ITEM_CONTRATO, CTA.NU_ORDEM_VENDA
FROM VND.ELO_CARTEIRA CTA
INNER JOIN AGENDAMENTO AGEN
ON CTA.CD_ELO_AGENDAMENTO = AGEN.CD_ELO_AGENDAMENTO 
WHERE 
CTA.IC_ATIVO = 'S'
UNION 
SELECT CTA.CD_ELO_CARTEIRA, CTA.CD_ELO_AGENDAMENTO, CTA.NU_CONTRATO_SAP, CTA.CD_ITEM_CONTRATO, CTA.NU_ORDEM_VENDA
FROM VND.ELO_CARTEIRA CTA
INNER JOIN CTE_CONTRATO_PEDIDOS AGEN
ON CTA.NU_CONTRATO_SAP = AGEN.NU_CONTRATO_SAP
AND CTA.CD_ITEM_CONTRATO = AGEN.CD_ITEM_CONTRATO
WHERE 
CTA.IC_ATIVO = 'S'
UNION 
SELECT CTA.CD_ELO_CARTEIRA, CTA.CD_ELO_AGENDAMENTO, CTA.NU_CONTRATO_SAP, CTA.CD_ITEM_CONTRATO, CTA.NU_ORDEM_VENDA
FROM VND.ELO_CARTEIRA CTA
INNER JOIN CTE_CONTRATO_PEDIDOS AGEN
ON CTA.NU_ORDEM_VENDA = AGEN.NU_ORDEM_VENDA
WHERE 
CTA.IC_ATIVO = 'S'
UNION 
SELECT CTA.CD_ELO_CARTEIRA, CTA.CD_ELO_AGENDAMENTO, CTA.NU_CONTRATO_SAP, CTA.CD_ITEM_CONTRATO, CTA.NU_ORDEM_VENDA
FROM VND.ELO_CARTEIRA CTA
INNER JOIN CTE_DISPONIBILIDADE_PROT AGEN
ON CTA.CD_ELO_CARTEIRA = AGEN.CD_ELO_CARTEIRA
WHERE 
CTA.IC_ATIVO = 'S'
UNION 
SELECT CTA.CD_ELO_CARTEIRA, CTA.CD_ELO_AGENDAMENTO, CTA.NU_CONTRATO_SAP, CTA.CD_ITEM_CONTRATO, CTA.NU_ORDEM_VENDA
FROM VND.ELO_CARTEIRA CTA
INNER JOIN CTE_ENTREGA AGEN
ON CTA.NU_CONTRATO_SAP = AGEN.NU_CONTRATO_SAP
AND CTA.CD_ITEM_CONTRATO = AGEN.CD_ITEM_CONTRATO
WHERE 
CTA.IC_ATIVO = 'S'
UNION 
SELECT CTA.CD_ELO_CARTEIRA, CTA.CD_ELO_AGENDAMENTO, CTA.NU_CONTRATO_SAP, CTA.CD_ITEM_CONTRATO, CTA.NU_ORDEM_VENDA
FROM VND.ELO_CARTEIRA CTA
INNER JOIN CTE_ENTREGA AGEN
ON CTA.NU_ORDEM_VENDA = AGEN.NU_ORDEM_VENDA
WHERE 
CTA.IC_ATIVO = 'S'
) CC
LEFT JOIN VND.ELO_AGENDAMENTO XAGE
ON
XAGE.CD_ELO_AGENDAMENTO = CC.CD_ELO_AGENDAMENTO

), 

        ELO_AG_DAY_BY_INCOTERMS_ITEM  AS (
        SELECT  EA_SUP_I.CD_ELO_AGENDAMENTO, EA_SUP_I.CD_SALES_GROUP , EAG_ITEM_I.CD_ELO_AGENDAMENTO_ITEM, EAG_ITEM_I.CD_INCOTERMS, 
        DAYY.CD_GRUPO_EMBALAGEM, DAYY.NU_DIA_SEMANA, SUM(DAYY.NU_QUANTIDADE) NU_QUANTIDADE, 
        MAX(CD_COTA_COMPARTILHADA) CD_COTA_COMPARTILHADA, EAG_ITEM_I.CD_CLIENTE
        FROM AGENDAMENTO FILT
        INNER JOIN VND.ELO_AGENDAMENTO_SUPERVISOR EA_SUP_I  
        ON FILT.CD_ELO_AGENDAMENTO = EA_SUP_I.CD_ELO_AGENDAMENTO
        INNER JOIN VND.VW_ELO_AGENDAMENTO_ITEM_R EAG_ITEM_I
        ON 
        EAG_ITEM_I.CD_ELO_AGENDAMENTO_SUPERVISOR = EA_SUP_I.CD_ELO_AGENDAMENTO_SUPERVISOR
        AND EAG_ITEM_I.IC_ATIVO = 'S'	
        
        INNER JOIN VND.VW_ELO_AGENDAMENTO_WEEK_PLAN EAG_WE_I
        ON EAG_ITEM_I.CD_ELO_AGENDAMENTO_ITEM = EAG_WE_I.CD_ELO_AGENDAMENTO_ITEM
        
        --LEFT JOIN VND.ELO_AGENDAMENTO_GROUPING EAG_GRO_I
        --ON EAG_GRO_I.CD_ELO_AGENDAMENTO_WEEK = EAG_WE_I.CD_ELO_AGENDAMENTO_WEEK
        INNER JOIN VND.VW_ELO_AGENDAMENTO_DAY_PLAN DAYY
        ON 
        DAYY.CD_ELO_AGENDAMENTO_WEEK = EAG_WE_I.CD_ELO_AGENDAMENTO_WEEK
        
        WHERE 
        EA_SUP_I.IC_ATIVO = 'S'
           
        AND             EXISTS (
                    SELECT 1 FROM CTE_CARTEIRA CTAS 
                    INNER JOIN VND.ELO_CARTEIRA CTA
                    ON CTAS.CD_ELO_CARTEIRA = CTA.CD_ELO_CARTEIRA
                    WHERE 
                    CTA.CD_ELO_AGENDAMENTO_ITEM = EAG_ITEM_I.CD_ELO_AGENDAMENTO_ITEM
                    )
                                        
        GROUP BY  EA_SUP_I.CD_ELO_AGENDAMENTO, EA_SUP_I.CD_SALES_GROUP , EAG_ITEM_I.CD_ELO_AGENDAMENTO_ITEM, 
        EAG_ITEM_I.CD_INCOTERMS, DAYY.CD_GRUPO_EMBALAGEM, DAYY.NU_DIA_SEMANA , EAG_ITEM_I.CD_CLIENTE                                   
        )--   ,
        --SELECT * FROM ELO_AG_DAY_BY_INCOTERMS_ITEM






SELECT CTE_CC.CD_WEEK,
TB_CART.CD_ELO_CARTEIRA, TB_CART.QT_AGENDADA_CONFIRMADA, TB_CART.CD_STATUS_CUSTOMER_SERVICE, TB_CART.CD_STATUS_CEL_FINAL,
TB_CART.NU_CONTRATO_SAP, TB_CART.CD_ITEM_CONTRATO, TB_CART.NU_ORDEM_VENDA,
--TB_CART.* ,
ICONT.*,
ICONTITEM.*,
CE_PED.*,
PROT.*, 
CTE_ENT.*

FROM CTE_CARTEIRA CTE_CC
INNER JOIN VND.ELO_CARTEIRA TB_CART
ON CTE_CC.CD_ELO_CARTEIRA =   TB_CART.CD_ELO_CARTEIRA
LEFT JOIN CTE_CONTRATO ICONT
ON 
ICONT.NU_CONTRATO_SAP = CTE_CC.NU_CONTRATO_SAP
LEFT JOIN CTE_ITEM_CONTRATO ICONTITEM
ON
ICONTITEM.CD_CONTRATO = ICONT.CD_CONTRATO
LEFT JOIN CTE_PEDIDO CE_PED
ON 
CE_PED.NU_CONTRATO_SAP = ICONT.NU_CONTRATO_SAP
AND CE_PED.CD_ITEM_CONTRATO = ICONTITEM.CD_ITEM_CONTRATO

LEFT JOIN CTE_DISPONIBILIDADE_PROT PROT
ON
PROT.CD_ELO_CARTEIRA = CTE_CC.CD_ELO_CARTEIRA
LEFT JOIN CTE_ENTREGA  CTE_ENT
ON 
CTE_CC.NU_CONTRATO_SAP = CTE_ENT.NU_CONTRATO_SAP
AND CTE_CC.CD_ITEM_CONTRATO = CTE_ENT.CD_ITEM_CONTRATO;







        












