WITH CTE_CARTEIRA AS 
(
SELECT 
CT.CD_ELO_CARTEIRA, CT.CD_ELO_AGENDAMENTO_ITEM, CT.CD_STATUS_CEL_FINAL,
CT.QT_AGENDADA_CONFIRMADA, CT.CD_ELO_AGENDAMENTO
FROM VND.ELO_CARTEIRA CT
INNER JOIN VND.ELO_AGENDAMENTO AGE
ON CT.CD_ELO_AGENDAMENTO = AGE.CD_ELO_AGENDAMENTO
INNER JOIN VND.ELO_STATUS AGESTAT
ON AGESTAT.CD_ELO_STATUS = AGE.CD_ELO_STATUS
LEFT JOIN VND.ELO_STATUS STCELL 
ON STCELL.CD_ELO_STATUS = CT.CD_STATUS_CEL_FINAL 
WHERE 
CT.IC_ATIVO = 'S'
AND AGE.IC_ATIVO = 'S'
AND NOT(STCELL.SG_STATUS = 'AGENC')
AND CT.CD_ELO_CARTEIRA = 23408--V_CD_ELO_CARTEIRA
AND CT.CD_ELO_AGENDAMENTO_ITEM = 4349 --V_CD_ELO_AGENDAMENTO_ITEM
AND CT.CD_TIPO_AGENDAMENTO = 25 
AND NOT(NVL(STCELL.SG_STATUS, 'BRANCO') = 'CLOOK')
AND NVL(CT.QT_AGENDADA_CONFIRMADA ,0) >= 0 
)

SELECT 
IGROUP.CD_ELO_AGENDAMENTO_GROUPING, 
CT.CD_ELO_CARTEIRA, 
CT.CD_ELO_AGENDAMENTO_ITEM, 
PROTO.CD_ELO_VBAK_PROTOCOLO,
PROTO.NU_PROTOCOLO, 
PROTO.QT_AGENDADA_PROTOCOLO, 
IGROUP.QT_AGENDADA 
--CT.QT_AGENDADA_CONFIRMADA, --CENT.QT_QUANTIDADE, --CENT.QT_FORNECIDO, --CENT.CD_AUTORIZACAO_ENTREGA
--CT.CD_STATUS_CEL_FINAL, --IGROUP.CD_ELO_AGENDAMENTO_WEEK,

FROM CTE_CARTEIRA CT
INNER JOIN VND.ELO_VBAK_PROTOCOLO PROTO
ON CT.CD_ELO_CARTEIRA = PROTO.CD_ELO_CARTEIRA
INNER JOIN VND.ELO_AGENDAMENTO_SUPERVISOR AGSUP
ON AGSUP.CD_ELO_AGENDAMENTO = CT.CD_ELO_AGENDAMENTO
INNER JOIN VND.ELO_AGENDAMENTO_ITEM AGITEM
ON AGSUP.CD_ELO_AGENDAMENTO_SUPERVISOR = AGITEM.CD_ELO_AGENDAMENTO_SUPERVISOR
INNER JOIN VND.ELO_AGENDAMENTO_WEEK WEESK
ON AGITEM.CD_ELO_AGENDAMENTO_ITEM = WEESK.CD_ELO_AGENDAMENTO_ITEM
AND WEESK.CD_ELO_AGENDAMENTO_ITEM = CT.CD_ELO_AGENDAMENTO_ITEM
INNER JOIN VND.ELO_AGENDAMENTO_GROUPING  IGROUP
ON WEESK.CD_ELO_AGENDAMENTO_WEEK = IGROUP.CD_ELO_AGENDAMENTO_WEEK
--INNER JOIN CPT.ENTREGA CENT
--ON PROTO.NU_PROTOCOLO = CENT.NU_PROTOCOLO_ENTREGA
--AND PROTO.CD_ENTREGA = CENT.CD_AUTORIZACAO_ENTREGA

WHERE 
PROTO.QT_AGENDADA_PROTOCOLO > 0 
AND PROTO.IC_ATIVO = 'S'
--AND CENT.SG_STATUS NOT IN ('C')
AND IGROUP.SG_TIPO_DOCUMENTO = 'P'
AND IGROUP.NU_DOCUMENTO IS NOT NULL
AND AGSUP.IC_ATIVO = 'S'
AND AGITEM.IC_ATIVO = 'S'
ORDER BY IGROUP.CD_ELO_AGENDAMENTO_GROUPING DESC;


SELECT * FROM VND.ELO_AGENDAMENTO_WEEK
WHERE CD_ELO_AGENDAMENTO_ITEM IN (9955, 9956); 

INSERT INTO VND.ELO_AGENDAMENTO_WEEK 
(CD_ELO_AGENDAMENTO_WEEK, CD_ELO_AGENDAMENTO_ITEM, NU_SEMANA, QT_COTA, QT_SEMANA, QT_EMERGENCIAL)
VALUES 
(SEQ_ELO_AGENDAMENTO_WEEK.NEXTVAL, 9955, 1, 271.2, 60, 0);

INSERT INTO VND.ELO_AGENDAMENTO_WEEK 
(CD_ELO_AGENDAMENTO_WEEK, CD_ELO_AGENDAMENTO_ITEM, NU_SEMANA, QT_COTA, QT_SEMANA, QT_EMERGENCIAL)
VALUES 
(SEQ_ELO_AGENDAMENTO_WEEK.NEXTVAL, 9956, 1, 271.2, 45, 0);


SELECT * FROM VND.ELO_AGENDAMENTO_DAY 
WHERE 
CD_ELO_AGENDAMENTO_WEEK IN (4335, 4336);

INSERT INTO VND.ELO_AGENDAMENTO_DAY 
(CD_ELO_AGENDAMENTO_DAY, CD_ELO_AGENDAMENTO_WEEK, NU_DIA_SEMANA, CD_GRUPO_EMBALAGEM, NU_QUANTIDADE)
VALUES 
(
SEQ_ELO_AGENDAMENTO_DAY.NEXTVAL, 4335, 6, 'B', 60
);


INSERT INTO VND.ELO_AGENDAMENTO_DAY 
(CD_ELO_AGENDAMENTO_DAY, CD_ELO_AGENDAMENTO_WEEK, NU_DIA_SEMANA, CD_GRUPO_EMBALAGEM, NU_QUANTIDADE)
VALUES 
(
SEQ_ELO_AGENDAMENTO_DAY.NEXTVAL, 4336, 6, 'B', 45
);

