UPDATE VND.ELO_VBAK_PROTOCOLO SET QT_AGENDADA_PROTOCOLO = 8 WHERE CD_ELO_VBAK_PROTOCOLO = 197 AND CD_ELO_CARTEIRA = 27043 AND QT_AGENDADA_PROTOCOLO = 0 ;
UPDATE VND.ELO_VBAK_PROTOCOLO SET QT_AGENDADA_PROTOCOLO = 22 WHERE CD_ELO_VBAK_PROTOCOLO = 232 AND CD_ELO_CARTEIRA = 27458 AND QT_AGENDADA_PROTOCOLO = 0 ;
UPDATE VND.ELO_VBAK_PROTOCOLO SET QT_AGENDADA_PROTOCOLO = 90 WHERE CD_ELO_VBAK_PROTOCOLO = 204 AND CD_ELO_CARTEIRA = 24874 AND QT_AGENDADA_PROTOCOLO = 0 ;
UPDATE VND.ELO_VBAK_PROTOCOLO SET QT_AGENDADA_PROTOCOLO = 15 WHERE CD_ELO_VBAK_PROTOCOLO = 105 AND CD_ELO_CARTEIRA = 22093 AND QT_AGENDADA_PROTOCOLO = 0 ;
UPDATE VND.ELO_VBAK_PROTOCOLO SET QT_AGENDADA_PROTOCOLO = 60 WHERE CD_ELO_VBAK_PROTOCOLO = 220 AND CD_ELO_CARTEIRA = 27229 AND QT_AGENDADA_PROTOCOLO = 0 ;
UPDATE VND.ELO_VBAK_PROTOCOLO SET QT_AGENDADA_PROTOCOLO = 62 WHERE CD_ELO_VBAK_PROTOCOLO = 195 AND CD_ELO_CARTEIRA = 27035 AND QT_AGENDADA_PROTOCOLO = 0 ;
UPDATE VND.ELO_VBAK_PROTOCOLO SET QT_AGENDADA_PROTOCOLO = 23 WHERE CD_ELO_VBAK_PROTOCOLO = 248 AND CD_ELO_CARTEIRA = 27498 AND QT_AGENDADA_PROTOCOLO = 0 ;
UPDATE VND.ELO_VBAK_PROTOCOLO SET QT_AGENDADA_PROTOCOLO = 60 WHERE CD_ELO_VBAK_PROTOCOLO = 193 AND CD_ELO_CARTEIRA = 22419 AND QT_AGENDADA_PROTOCOLO = 0 ;
UPDATE VND.ELO_VBAK_PROTOCOLO SET QT_AGENDADA_PROTOCOLO = 80 WHERE CD_ELO_VBAK_PROTOCOLO = 196 AND CD_ELO_CARTEIRA = 27023 AND QT_AGENDADA_PROTOCOLO = 0 ;
UPDATE VND.ELO_VBAK_PROTOCOLO SET QT_AGENDADA_PROTOCOLO = 111 WHERE CD_ELO_VBAK_PROTOCOLO = 171 AND CD_ELO_CARTEIRA = 22401 AND QT_AGENDADA_PROTOCOLO = 0 ;
UPDATE VND.ELO_VBAK_PROTOCOLO SET QT_AGENDADA_PROTOCOLO = 30 WHERE CD_ELO_VBAK_PROTOCOLO = 191 AND CD_ELO_CARTEIRA = 24883 AND QT_AGENDADA_PROTOCOLO = 0 ;
UPDATE VND.ELO_VBAK_PROTOCOLO SET QT_AGENDADA_PROTOCOLO = 8 WHERE CD_ELO_VBAK_PROTOCOLO = 184 AND CD_ELO_CARTEIRA = 22382 AND QT_AGENDADA_PROTOCOLO = 0 ;
UPDATE VND.ELO_VBAK_PROTOCOLO SET QT_AGENDADA_PROTOCOLO = 14 WHERE CD_ELO_VBAK_PROTOCOLO = 181 AND CD_ELO_CARTEIRA = 22387 AND QT_AGENDADA_PROTOCOLO = 0 ;
UPDATE VND.ELO_VBAK_PROTOCOLO SET QT_AGENDADA_PROTOCOLO = 20 WHERE CD_ELO_VBAK_PROTOCOLO = 183 AND CD_ELO_CARTEIRA = 22381 AND QT_AGENDADA_PROTOCOLO = 0 ;
UPDATE VND.ELO_VBAK_PROTOCOLO SET QT_AGENDADA_PROTOCOLO = 13 WHERE CD_ELO_VBAK_PROTOCOLO = 180 AND CD_ELO_CARTEIRA = 22386 AND QT_AGENDADA_PROTOCOLO = 0 ;
UPDATE VND.ELO_VBAK_PROTOCOLO SET QT_AGENDADA_PROTOCOLO = 18 WHERE CD_ELO_VBAK_PROTOCOLO = 178 AND CD_ELO_CARTEIRA = 22379 AND QT_AGENDADA_PROTOCOLO = 0 ;
UPDATE VND.ELO_VBAK_PROTOCOLO SET QT_AGENDADA_PROTOCOLO = 7 WHERE CD_ELO_VBAK_PROTOCOLO = 182 AND CD_ELO_CARTEIRA = 22388 AND QT_AGENDADA_PROTOCOLO = 0 ;
UPDATE VND.ELO_VBAK_PROTOCOLO SET QT_AGENDADA_PROTOCOLO = 100 WHERE CD_ELO_VBAK_PROTOCOLO = 209 AND CD_ELO_CARTEIRA = 27224 AND QT_AGENDADA_PROTOCOLO = 0 ;
UPDATE VND.ELO_VBAK_PROTOCOLO SET QT_AGENDADA_PROTOCOLO = 4 WHERE CD_ELO_VBAK_PROTOCOLO = 186 AND CD_ELO_CARTEIRA = 22385 AND QT_AGENDADA_PROTOCOLO = 0 ;
UPDATE VND.ELO_VBAK_PROTOCOLO SET QT_AGENDADA_PROTOCOLO = 14 WHERE CD_ELO_VBAK_PROTOCOLO = 173 AND CD_ELO_CARTEIRA = 22376 AND QT_AGENDADA_PROTOCOLO = 0 ;
UPDATE VND.ELO_VBAK_PROTOCOLO SET QT_AGENDADA_PROTOCOLO = 36 WHERE CD_ELO_VBAK_PROTOCOLO = 172 AND CD_ELO_CARTEIRA = 22417 AND QT_AGENDADA_PROTOCOLO = 0 ;
UPDATE VND.ELO_VBAK_PROTOCOLO SET QT_AGENDADA_PROTOCOLO = 120 WHERE CD_ELO_VBAK_PROTOCOLO = 217 AND CD_ELO_CARTEIRA = 27250 AND QT_AGENDADA_PROTOCOLO = 0 ;
UPDATE VND.ELO_VBAK_PROTOCOLO SET QT_AGENDADA_PROTOCOLO = 26 WHERE CD_ELO_VBAK_PROTOCOLO = 198 AND CD_ELO_CARTEIRA = 27044 AND QT_AGENDADA_PROTOCOLO = 0 ;
UPDATE VND.ELO_VBAK_PROTOCOLO SET QT_AGENDADA_PROTOCOLO = 23 WHERE CD_ELO_VBAK_PROTOCOLO = 219 AND CD_ELO_CARTEIRA = 27060 AND QT_AGENDADA_PROTOCOLO = 0 ;
UPDATE VND.ELO_VBAK_PROTOCOLO SET QT_AGENDADA_PROTOCOLO = 7 WHERE CD_ELO_VBAK_PROTOCOLO = 218 AND CD_ELO_CARTEIRA = 27061 AND QT_AGENDADA_PROTOCOLO = 0 ;
UPDATE VND.ELO_VBAK_PROTOCOLO SET QT_AGENDADA_PROTOCOLO = 10 WHERE CD_ELO_VBAK_PROTOCOLO = 262 AND CD_ELO_CARTEIRA = 27548 AND QT_AGENDADA_PROTOCOLO = 0 ;
UPDATE VND.ELO_VBAK_PROTOCOLO SET QT_AGENDADA_PROTOCOLO = 14 WHERE CD_ELO_VBAK_PROTOCOLO = 261 AND CD_ELO_CARTEIRA = 27547 AND QT_AGENDADA_PROTOCOLO = 0 ;
UPDATE VND.ELO_VBAK_PROTOCOLO SET QT_AGENDADA_PROTOCOLO = 5 WHERE CD_ELO_VBAK_PROTOCOLO = 250 AND CD_ELO_CARTEIRA = 26733 AND QT_AGENDADA_PROTOCOLO = 0 ;
UPDATE VND.ELO_VBAK_PROTOCOLO SET QT_AGENDADA_PROTOCOLO = 30 WHERE CD_ELO_VBAK_PROTOCOLO = 233 AND CD_ELO_CARTEIRA = 27450 AND QT_AGENDADA_PROTOCOLO = 0 ;
UPDATE VND.ELO_VBAK_PROTOCOLO SET QT_AGENDADA_PROTOCOLO = 30 WHERE CD_ELO_VBAK_PROTOCOLO = 286 AND CD_ELO_CARTEIRA = 27580 AND QT_AGENDADA_PROTOCOLO = 0 ;
UPDATE VND.ELO_VBAK_PROTOCOLO SET QT_AGENDADA_PROTOCOLO = 47 WHERE CD_ELO_VBAK_PROTOCOLO = 273 AND CD_ELO_CARTEIRA = 27565 AND QT_AGENDADA_PROTOCOLO = 0 ;
UPDATE VND.ELO_VBAK_PROTOCOLO SET QT_AGENDADA_PROTOCOLO = 56 WHERE CD_ELO_VBAK_PROTOCOLO = 294 AND CD_ELO_CARTEIRA = 27641 AND QT_AGENDADA_PROTOCOLO = 0 ;
UPDATE VND.ELO_VBAK_PROTOCOLO SET QT_AGENDADA_PROTOCOLO = 37 WHERE CD_ELO_VBAK_PROTOCOLO = 291 AND CD_ELO_CARTEIRA = 27630 AND QT_AGENDADA_PROTOCOLO = 0 ;


UPDATE VND.ELO_VBAK_PROTOCOLO SET QT_AGENDADA_PROTOCOLO = 72 WHERE CD_ELO_VBAK_PROTOCOLO = 124 AND CD_ELO_CARTEIRA = 22207 AND QT_AGENDADA_PROTOCOLO = 0 ;
UPDATE VND.ELO_VBAK_PROTOCOLO SET QT_AGENDADA_PROTOCOLO = 228 WHERE CD_ELO_VBAK_PROTOCOLO = 125 AND CD_ELO_CARTEIRA = 22207 AND QT_AGENDADA_PROTOCOLO = 0 ;
UPDATE VND.ELO_VBAK_PROTOCOLO SET QT_AGENDADA_PROTOCOLO = 7 WHERE CD_ELO_VBAK_PROTOCOLO = 201 AND CD_ELO_CARTEIRA = 27099 AND QT_AGENDADA_PROTOCOLO = 0 ;
UPDATE VND.ELO_VBAK_PROTOCOLO SET QT_AGENDADA_PROTOCOLO = 9 WHERE CD_ELO_VBAK_PROTOCOLO = 202 AND CD_ELO_CARTEIRA = 27099 AND QT_AGENDADA_PROTOCOLO = 0 ;

UPDATE VND.ELO_VBAK_PROTOCOLO SET QT_AGENDADA_PROTOCOLO = 32 WHERE CD_ELO_VBAK_PROTOCOLO = 128 AND CD_ELO_CARTEIRA = 22209 AND QT_AGENDADA_PROTOCOLO = 0 ;
UPDATE VND.ELO_VBAK_PROTOCOLO SET QT_AGENDADA_PROTOCOLO = 168 WHERE CD_ELO_VBAK_PROTOCOLO = 131 AND CD_ELO_CARTEIRA = 22210 AND QT_AGENDADA_PROTOCOLO = 0 ;

UPDATE VND.ELO_VBAK_PROTOCOLO SET QT_AGENDADA_PROTOCOLO = 11 WHERE CD_ELO_VBAK_PROTOCOLO = 185 AND CD_ELO_CARTEIRA = 22383 AND QT_AGENDADA_PROTOCOLO = 0 ;
UPDATE VND.ELO_VBAK_PROTOCOLO SET QT_AGENDADA_PROTOCOLO = 21 WHERE CD_ELO_VBAK_PROTOCOLO = 194 AND CD_ELO_CARTEIRA = 22387 AND QT_AGENDADA_PROTOCOLO = 0 ;

UPDATE VND.ELO_VBAK_PROTOCOLO SET QT_AGENDADA_PROTOCOLO = 21 WHERE CD_ELO_VBAK_PROTOCOLO = 194 AND CD_ELO_CARTEIRA = 22384 AND QT_AGENDADA_PROTOCOLO = 0 ;

UPDATE VND.ELO_VBAK_PROTOCOLO SET QT_AGENDADA_PROTOCOLO = 16 WHERE CD_ELO_VBAK_PROTOCOLO = 259 AND CD_ELO_CARTEIRA = 27535 AND QT_AGENDADA_PROTOCOLO = 0 ;
UPDATE VND.ELO_VBAK_PROTOCOLO SET QT_AGENDADA_PROTOCOLO = 6 WHERE CD_ELO_VBAK_PROTOCOLO = 22 AND CD_ELO_CARTEIRA = 1750 AND  QT_AGENDADA_PROTOCOLO = 0 ;



