SELECT 

current_date AS DATA_INSERT,
AREA.SQL_TEXT,
AREA.SORTS,
AREA.USERS_OPENING,
AREA.FETCHES,
AREA.EXECUTIONS,
AREA.FIRST_LOAD_TIME,
TO_DATE(AREA.FIRST_LOAD_TIME, 'yyyy-mm-dd/hh24:mi:ss') AS FIRST_LOAD_DT,
AREA.PARSE_CALLS,
AREA.DISK_READS,
(AREA.DISK_READS /AREA.executions) AS DISK_READ_IN_MED,

AREA.ROWS_PROCESSED,
(AREA.ROWS_PROCESSED /AREA.executions) AS ROWS_PROCESSED_IN_MED,

AREA.COMMAND_TYPE,
AREA.PARSING_USER_ID,
USERS.USERNAME,
AREA.PARSING_SCHEMA_ID,
AREA.MODULE,
AREA.CPU_TIME,
((AREA.CPU_TIME/10000000)/AREA.EXECUTIONS) AS CPU_TIME_IN_SEC_MED,

AREA.ELAPSED_TIME,
((AREA.ELAPSED_TIME/10000000)/AREA.EXECUTIONS) as ELAPSED_IN_SEC_MED,
AREA.IS_OBSOLETE

FROM V$SQLAREA AREA
INNER JOIN ALL_USERS USERS
ON
AREA.parsing_user_id = USERS.USER_ID


WHERE 
(
    not(AREA.parsing_schema_ID = 0) AND  
    AREA.executions > 6 AND 
    TO_DATE(AREA.FIRST_LOAD_TIME, 'yyyy-mm-dd/hh24:mi:ss') > TO_DATE('2009-01-01 00:00:00', 'yyyy-mm-dd hh24:mi:ss')
   
)
AND

(
    (AREA.DISK_READS/AREA.executions) > 100 OR --last 10000
    (AREA.ROWS_PROCESSED/AREA.executions) > 100 OR  --last 1000
    (((AREA.ELAPSED_TIME/AREA.executions)/1000000) > 0.50) OR 
    AREA.users_opening > 1 
);


select * from V$SQLAREA AREA where users_opening >= 0 and nvl(AREA.MODULE, 'x') <> 'DbControlService.exe'
and parsing_schema_name = 'xECC_USER'
or sql_id = '90507gwundvjd';

000000067645E408	3713573235	d4qs0xzfpj8bm
2jgz18hhuy4r8



d4qs0xzfpj8bm
bavwgj2yym9jf
d4qs0xzfpj8bm


SELECT * FROM V$SESSION 
WHERE STATUS = 'ACTIVE' and NVL(type, 'ZX') <> 'BACKGROUND'; 

prev-sql-ddr        prev_hash_vale  prev_sql_i
000000067711A1C8	893840941	90507gwundvjd


SELECT * FROM ALL_SOURCE 
WHERE UPPER(TEXT) LIKE '%JOIN ELO_AGENDAMENTO_SUPERVISOR AP%'



SELECT (24/ 60 / 60 /2),  SYSDATE + 0.0033, SYSDATE FROM DUAL;


SELECT * FROM VND.VW_ELO_CD_WEEK_SEMANAL;



