/* Formatted on 30/11/2018 16:23:52 (QP5 v5.318) */
/*
5	Comercial
10	Crédito
15	Cobrança
20	Liberado
25	Finalizado
30	Recusado/Cancelado
99	Verificar erro status
35	Bloqueio de Material
90	Contrato Excluido no SAP
40	Incompleto
*/

SELECT (SELECT SUM (NVL (IC.NU_QUANTIDADE, 0) - NVL (IC.NU_QTY_DELIVERED, 0))
          FROM VND.ITEM_CONTRATO IC
         WHERE IC.CD_CONTRATO = CONT.CD_CONTRATO)
           SALDOITEM,
       CONT.*
  FROM VND.CONTRATO CONT
 WHERE     CONT.IC_ATIVO = 'S'
       AND EXISTS
               (SELECT 1
                  FROM VND.ITEM_CONTRATO IC
                 WHERE     IC.CD_CONTRATO = CONT.CD_CONTRATO
                       AND   NVL (IC.NU_QUANTIDADE, 0)
                           - NVL (IC.NU_QTY_DELIVERED, 0) >
                           1)
       AND CONT.CD_STATUS_CONTRATO = '8'
       AND CONT.DT_FIM < CURRENT_DATE - 180
       --AND IC_SIGNED = 'S'
       --AND IC_SAP_READY = 'S'
       AND CONT.CD_SITUACAO_CONTRATO IN (50,
                                         100,
                                         150,
                                         20)
       -- AND DH_ULT_INTERFACE < CURRENT_DATE - 30
       -- AND CD_BLOQUEIO_CREDITO IS NULL
       AND CONT.CD_BLOQUEIO_ENTREGA IS NULL
       AND CONT.CD_BLOQUEIO_FATURAMENTO IS NULL
       AND CONT.CD_BLOQUEIO_REMESSA IS NULL
       AND CONT.DS_CREDIT_BLOCK_REASON IS NULL
--AND nu_contrato_sap IN ('0040410395', 'X0040396255')
--NU_CONTRATO IN('3056544', '3056545')
;
SELECT *
  FROM CTF.CLIENTE
 WHERE CD_CLIENTE = '4055613' OR CD_CLIENTE = '0004055613' or nu_cpf_cnpj like '%39771059068%';


SELECT *
  FROM VND.CONTRATO
 WHERE     1 = 1
       --AND NU_CONTRATO_SAP IS NULL AND NU_CONTRATO IS NULL
       --AND IC_ATIVO = 'S'
       --AND CD_AGENTE_VENDA = '0040410004'
       --AND DH_INCLUSAO > CURRENT_DATE - 10
     -- AND NU_CONTRATO_SAP IN ('0040418977')
       AND NU_CONTRATO IN ( 3076246 )
--AND CD_CONTRATO = 242418
;
SELECT *
  FROM VND.ITEM_CONTRATO
 WHERE CD_CONTRATO = 219848;

--
--AND CD_ITEM_CONTRATO = 10
--AND CD_PRODUTO_SAP = '000000000000119200'

--

--UPDATE VND.CONTRATO
--SET DS_PDF = NULL
-- WHERE CD_CONTRATO = 214457;

--COMMIT;



SELECT *
  FROM VND.CLIENTE_CONTRATO
 WHERE CD_CLIENTE_CONTRATO = '516383';
-- 
-- edit VND.CLIENTE_CONTRATO
-- WHERE CD_CLIENTE_CONTRATO = '106304';

  SELECT C.CD_STATUS_CONTRATO || STC.DS_STATUS_CONTRATO STATUS,
         C.IC_ATIVO,
         TRUNC (DT_FIM, 'YEAR')                       ANO,
         TRUNC (DT_FIM, 'MONTH')                      MES,
         COUNT (1),
         C.CD_SITUACAO_CONTRATO,
         SITCC.DS_SITUACAO_CONTRATO
    FROM VND.CONTRATO C
         INNER JOIN VND.STATUS_CONTRATO STC
             ON C.CD_STATUS_CONTRATO = STC.CD_STATUS_CONTRATO
         LEFT JOIN VND.SITUACAO_CONTRATO SITCC
             ON C.CD_SITUACAO_CONTRATO = SITCC.CD_SITUACAO_CONTRATO
   WHERE                                     --STC.CD_STATUS_CONTRATO IS NULL;
         DT_FIM > CURRENT_DATE - 180
--CD_SITUACAO_CONTRATO = 90
GROUP BY C.CD_STATUS_CONTRATO,
         C.IC_ATIVO,
         STC.DS_STATUS_CONTRATO,
         TRUNC (DT_FIM, 'YEAR'),
         TRUNC (DT_FIM, 'MONTH'),
         C.CD_SITUACAO_CONTRATO,
         SITCC.DS_SITUACAO_CONTRATO
ORDER BY C.CD_STATUS_CONTRATO;

SELECT * FROM VND.STATUS_CONTRATO;

SELECT * FROM VND.SITUACAO_CONTRATO;


SELECT *
  FROM VND.ELO_VBAK
 WHERE     (CD_ELO_VBAK = 3332426 OR NU_CONTRATO_SAP = '0040390395')
       AND CD_ITEM_CONTRATO = 70;


SELECT *
  FROM VND.ELO_CARTEIRA
 WHERE CD_ELO_CARTEIRA IN (330903, 330911);


SELECT *
  FROM VND.ELO_VBAK_PROTOCOLO
 WHERE     CD_ELO_CARTEIRA IN (330903, 330911)
       AND NU_PROTOCOLO IN ('R129782BL1', 'R131502SD1')
       AND CD_ELO_VBAK_PROTOCOLO IN (9714, 9619);

SELECT *
  FROM VND.ELO_AGENDAMENTO_GROUPING
 WHERE NU_DOCUMENTO IN ('R132819GD1');

SELECT *
  FROM VND.ITEM_CONTRATO
 WHERE CD_CONTRATO IN (229701);

SELECT *
  FROM CTF.USUARIO
 WHERE 1 = 1 --AND CD_USUARIO_ORIGINAL IS NOT NULL
             --AND DH_ULTIMO_ACESSO > CURRENT_DATE - 5
             AND UPPER(NO_USUARIO) LIKE '%ERIKA%';
             --AND CD_USUARIO = 3533;

--UPDATE VND.ITEM_CONTRATO
--SET VL_PRECO_NEGOCIADO = 399.00
--WHERE
--CD_CONTRATO = 223284
--AND CD_ITEM_CONTRATO = 10
--AND CD_PRODUTO_SAP = '000000000000118773'
;
COMMIT;

--DH_ULT_ALTERACAO


SELECT *
  FROM CTF.CLIENTE
 WHERE 1 = 1 AND CD_CLIENTE = '0004078057';
 
 
 select * from ctf.cliente_sales_area
 WHERE 1 = 1 AND CD_CLIENTE = '0004078057';
 ;

SELECT *
  FROM CTF.MUNICIPIO
 WHERE CD_MUNICIPIO = 317020;

SELECT *
  FROM CPT.COOPERADO
 WHERE CD_COOPERADO IN (33832, 33831);

SELECT *
  FROM CPT.COOPERATIVA_FILIAL
 WHERE CD_COOPERATIVA_FILIAL = 577;


SELECT *
  FROM CPT.COOPERATIVA
 WHERE CD_COOPERATIVA = 168;
 
 select * from cpt.propriedade_cooperado
 where cd_cooperado = 36345;

SELECT *
  FROM CTF.USUARIO
 WHERE CD_USUARIO = 3409;

SELECT *
  FROM CPT.AUTORIZACAO_ENTREGA
 WHERE     1 = 1
      -- AND NU_CONTRATO = '6055615'
       --AND CD_ITEM_CONTRATO in (10,20)
       --AND CD_PRODUTO_SAP = '000000000000119200'
       --AND NU_CONTRATO = '3066378'
       
       AND CD_AUTORIZACAO_ENTREGA in (138193
);

SELECT *
  FROM CPT.ENTREGA
 WHERE 1 = 1 AND NU_PROTOCOLO_ENTREGA = 'R138290LZ1'
             AND NOT(SG_STATUS = 'C')
             AND CD_AUTORIZACAO_ENTREGA in (
SELECT cd_autorizacao_entrega
  FROM CPT.AUTORIZACAO_ENTREGA
 WHERE     1 = 1
       AND NU_CONTRATO_SAP = '0040360748'
    --   AND CD_ITEM_CONTRATO in (10,20)             
);

SELECT *
  FROM CPT.HISTORICO_STATUS_ENTREGA
 WHERE CD_AUTORIZACAO_ENTREGA in (137459,
137464,
137470,
137474,
137477
);

SELECT * FROM CPT.STATUS_ENTREGA;


SELECT DISTINCT USERSE.NO_USUARIO,
                AUTOE.NU_NOTA_FISCAL,
                AUTOE.NU_ITEM_NOTA_FISCAL,
                AUTOE.NU_CONTRATO,
                AUTOE.NU_CONTRATO_SAP,
                AUTOE.CD_ITEM_CONTRATO,
                ENT.*,
                --, HISTENT.* ,
                STENT.*
  FROM CPT.ENTREGA  ENT
       INNER JOIN CPT.AUTORIZACAO_ENTREGA AUTOE
           ON ENT.CD_AUTORIZACAO_ENTREGA = AUTOE.CD_AUTORIZACAO_ENTREGA
       LEFT JOIN CTF.USUARIO USERSE ON USERSE.CD_USUARIO = ENT.CD_USUARIO
       LEFT JOIN CPT.HISTORICO_STATUS_ENTREGA HISTENT
           ON     ENT.CD_AUTORIZACAO_ENTREGA = HISTENT.CD_AUTORIZACAO_ENTREGA
              AND ENT.CD_ENTREGA = HISTENT.CD_ENTREGA
       LEFT JOIN CPT.STATUS_ENTREGA STENT
           ON     ENT.SG_STATUS = STENT.SG_STATUS_ENTREGA
              AND HISTENT.CD_STATUS_ENTREGA > STENT.CD_STATUS_ENTREGA
 WHERE     1 = 1
       --AND ENT.SG_STATUS IN ('P', 'A','R')
       --AND NVL(ENT.QT_QUANTIDADE,0) - NVL(ENT.QT_FORNECIDO,0) > 1
       --AND ( UPPER(ENT.DS_LOG_SAP)  LIKE '%PARA%A%' OR NVL(HISTENT.CD_STATUS_ENTREGA, 6) IN(6))
       --AND ENT.NU_PROTOCOLO_ENTREGA = 'R127929PB1'
       AND AUTOE.NU_CONTRATO = '3077384'
       AND AUTOE.CD_ITEM_CONTRATO = 40;

SELECT NO_USUARIO,
       NU_NOTA_FISCAL,
       NU_ITEM_NOTA_FISCAL,
       NU_CONTRATO,
       NU_CONTRATO_SAP,
       CD_ITEM_CONTRATO,
       DT_SUGESTAO_ENTREGA,
       QT_QUANTIDADE,
       SG_STATUS,
       QT_FORNECIDO,
       CD_AUTORIZACAO_ENTREGA,
       CD_USUARIO,
       NU_PROTOCOLO_ENTREGA,
       DS_LOG_SAP,
       CD_STATUS_ENTREGA,
       SG_STATUS_ENTREGA,
       DS_STATUS_ENTREGA,
       CD_STATUS_ENTREGA_HIST
  FROM (SELECT DISTINCT USERSE.NO_USUARIO,
                        AUTOE.NU_NOTA_FISCAL,
                        AUTOE.NU_ITEM_NOTA_FISCAL,
                        AUTOE.NU_CONTRATO,
                        AUTOE.NU_CONTRATO_SAP,
                        AUTOE.CD_ITEM_CONTRATO,
                        ENT.CD_ENTREGA,
                        ENT.DT_LIBERACAO_ENTREGA,
                        ENT.DT_INCLUSAO_ENTREGA,
                        ENT.DT_SUGESTAO_ENTREGA,
                        ENT.QT_QUANTIDADE,
                        ENT.DS_COMPOSICAO_CARGA,
                        ENT.DS_ROTEIRO,
                        ENT.SG_STATUS,
                        ENT.IC_LIBERADO_ENTREGA,
                        ENT.DS_OBSERVACAO,
                        ENT.QT_FORNECIDO,
                        ENT.CD_AUTORIZACAO_ENTREGA,
                        ENT.CD_USUARIO,
                        ENT.NU_PROTOCOLO_ENTREGA,
                        ENT.IC_ENTREGA_OUTRA_FILIAL,
                        ENT.DS_TRANSPORTADORA_CLIENTE,
                        ENT.DS_LOG_SAP,
                        ENT.NU_ORDEM_VENDA_ORIGINAL,
                        ENT.CD_ITEM_PEDIDO,
                        ENT.IC_FORNECIDO,
                        ENT.IC_COMPOSICAO_CARGA,
                        STENT.CD_STATUS_ENTREGA,
                        STENT.SG_STATUS_ENTREGA,
                        STENT.DS_STATUS_ENTREGA,
                        ST_HIST.CD_STATUS_ENTREGA CD_STATUS_ENTREGA_HIST
          --, HISTENT.* ,

          FROM CPT.ENTREGA  ENT
               INNER JOIN CPT.AUTORIZACAO_ENTREGA AUTOE
                   ON ENT.CD_AUTORIZACAO_ENTREGA =
                      AUTOE.CD_AUTORIZACAO_ENTREGA
               LEFT JOIN CTF.USUARIO USERSE
                   ON USERSE.CD_USUARIO = ENT.CD_USUARIO
               LEFT JOIN CPT.HISTORICO_STATUS_ENTREGA HISTENT
                   ON     ENT.CD_AUTORIZACAO_ENTREGA =
                          HISTENT.CD_AUTORIZACAO_ENTREGA
                      AND ENT.CD_ENTREGA = HISTENT.CD_ENTREGA
               LEFT JOIN CPT.STATUS_ENTREGA STENT
                   ON ENT.SG_STATUS = STENT.SG_STATUS_ENTREGA
               LEFT JOIN CPT.STATUS_ENTREGA ST_HIST
                   ON HISTENT.CD_STATUS_ENTREGA = ST_HIST.CD_STATUS_ENTREGA
         WHERE     1 = 1
               --AND ENT.SG_STATUS IN ('P', 'A', 'R')
               --AND NVL(ENT.QT_QUANTIDADE,0) - NVL(ENT.QT_FORNECIDO,0) > 1
               --AND ( UPPER(ENT.DS_LOG_SAP)  LIKE '%PARA%A%')
               --AND ENT.NU_PROTOCOLO_ENTREGA = 'R127929PB1'
               AND AUTOE.NU_CONTRATO = '3077384' AND AUTOE.CD_ITEM_CONTRATO = 40

                                                ) DLOKO
 --WHERE DLOKO.CD_STATUS_ENTREGA_HIST <> DLOKO.CD_STATUS_ENTREGA
 ;


--UPDATE CPT.ENTREGA ENT
--SET
----SG_STATUS = 'C',
----QT_FORNECIDO = 0,
----IC_FORNECIDO = 'N',
----DS_ROTEIRO = DS_ROTEIRO || ' CANCELADO PELO USUARIA '
--DS_OBSERVACAO= 'CANCELAMENTO MANUAL POR GRAZIELLE MATOSO EM 2018-11-13'


--WHERE
-- AND ENT.NU_PROTOCOLO_ENTREGA = 'R134405XV1'
-- AND ENT.SG_STATUS = 'C'
-- AND ENT.CD_AUTORIZACAO_ENTREGA = 134405
-- AND EXISTS (SELECT 1
--             FROM CPT.HISTORICO_STATUS_ENTREGA HI
--              WHERE HI.CD_AUTORIZACAO_ENTREGA = ENT.CD_AUTORIZACAO_ENTREGA
--                      AND HI.CD_ENTREGA = ENT.CD_ENTREGA)
--;
----COMMIT;
;

SELECT *
  FROM VND.PEDIDO
 WHERE 1 = 1 AND NU_CONTRATO_SAP = '0040394372'
             AND NU_ORDEM_VENDA IN ('0002396091');

SELECT *
  FROM VND.INTERFACE
 WHERE NU_CODIGO = '0002396091';

SELECT * FROM VND.SITUACAO_PEDIDO;


/*
INSERT INTO VND.INTERFACE (
CD_INTERFACE, 
IC_TIPO, 
NU_CODIGO
)
SELECT
(SELECT MAX(CD_INTERFACE) FROM INTERFACE) + ROWNUM,
'C',
NU_ORDEM_VENDA
FROM VND.PEDIDO
WHERE
NU_ORDEM_VENDA IN( 
'0002469776'

);
COMMIT;


INSERT INTO VND.INTERFACE (
CD_INTERFACE, 
IC_TIPO, 
NU_CODIGO
)
SELECT
(SELECT MAX(CD_INTERFACE) FROM INTERFACE) + ROWNUM,
'G',
NU_CONTRATO_SAP
FROM VND.CONTRATO
WHERE NU_CONTRATO_SAP IN (
'0040400385'

);
COMMIT;

*/

SELECT DISTINCT WEES.QT_SEMANA,
                --GROU.NU_DOCUMENTO,
                VBAK.*,
                AG.*,
                C.*,
                CEFIL.DS_STATUS,
                CEFIL.SG_STATUS,
                CASE 
                WHEN C.IC_COOPERATIVE = 'S' AND VBAK.QT_AGENDADA_PROTOCOLO > 0 THEN 
                'T' || VND.FX_GET_PROTOCOLO(C.NU_CONTRATO, C.NU_CONTRATO_SAP, C.CD_ITEM_CONTRATO) 
                WHEN C.IC_COOPERATIVE = 'S' AND NVL(VBAK.QT_AGENDADA_PROTOCOLO,0) = 0 and c.qt_agendada_confirmada > 0  THEN 
                'B' || VND.FX_GET_PROTOCOLO(C.NU_CONTRATO, C.NU_CONTRATO_SAP, C.CD_ITEM_CONTRATO) 
                
                ELSE '' END PROTOCOLO_ENTREGA
                
  FROM VND.ELO_CARTEIRA  C
       INNER JOIN VND.ELO_AGENDAMENTO AG
           ON C.CD_ELO_AGENDAMENTO = AG.CD_ELO_AGENDAMENTO
       LEFT JOIN VND.ELO_VBAK_PROTOCOLO VBAK
           ON VBAK.CD_ELO_CARTEIRA = C.CD_ELO_CARTEIRA
       LEFT JOIN VND.ELO_AGENDAMENTO_WEEK WEES
           ON C.CD_ELO_AGENDAMENTO_ITEM = WEES.CD_ELO_AGENDAMENTO_ITEM
       LEFT JOIN VND.ELO_AGENDAMENTO_GROUPING GROU
           ON WEES.CD_ELO_AGENDAMENTO_WEEK = GROU.CD_ELO_AGENDAMENTO_WEEK
       LEFT JOIN VND.ELO_STATUS CEFIL
           ON C.CD_STATUS_CEL_FINAL = CEFIL.CD_ELO_STATUS
 WHERE     1 = 1
       AND AG.CD_WEEK = 'W512018'
       --AND AG.CD_CENTRO_EXPEDIDOR IN ('6100')
       --AND VBAK.QT_AGENDADA_PROTOCOLO > 0
      AND AG.CD_POLO = 'P002'
       --AND (C.CD_STATUS_TORRE_FRETES IN (10, 11,12) OR C.DH_LIBERACAO_TORRE_FRETES IS NOT NULL)
       --AND C.CD_SALES_GROUP IN (807)
       --AND UPPER(C.NO_CLIENTE) IN ('ANTONIO EDUARDO DIAS GARCIA', 'LUIZ DA CUNHA SOBRINHO',
       --'JOSE ANTONIO VISSOSO', 'JOÃO CARLOS VISSOSO', 'JOAO CARLOS VISSOSO', 'LUIZ DAL RI', 'JOAO LUIS SCHOLL'
       --
       --)
       --AND UPPER(C.NO_CLIENTE) LIKE '%AGROINSUMOS COMERCIAL AGRICOLA LTDA%'
       --AND UPPER(C.NO_PRODUTO_SAP) LIKE '%FFALM 00 18 18+ 0,1 ZN + 0,03 B + 0,1 MN%'
       --AND (NVL(C.CD_TIPO_AGENDAMENTO, 22) IN (22,23,24) OR (C.CD_TIPO_AGENDAMENTO = 25 AND C.CD_STATUS_REPLAN = 32))
       --AND C.CD_ELO_AGENDAMENTO_ITEM = 177515
       --AND C.CD_PRODUTO_SAP = '000000000000119200'
       --AND C.CD_CLIENTE = '0004024635'
       --AND NU_CONTRATO = '3065348'
      -- AND NU_CONTRATO_SAP IN ('0040418338'  )
       --AND CD_ITEM_CONTRATO = 10
       AND NVL (NU_ORDEM_VENDA, '0') IN ('0002384282')
       --                                         '0',
       --                                         '         0',
       --                                         '0         ')
       --AND NU_CONTRATO = '3040592'
       --AND CD_WEEK  = 'W302018'
       --AND CD_POLO = 'P001'
       --AND C.CD_CENTRO_EXPEDIDOR ='6100'
       --AND C.CD_INCOTERMS= 'CIF'
       --AND C.CD_STATUS_CEL_FINAL = 59
      --AND NVL (C.QT_AGENDADA_CONFIRMADA, 0) >= 0
     -- AND VBAK.NU_PROTOCOLO IN ( 'R138229GJ1' )
       AND C.IC_COOPERATIVE = 'S'
       --AND (   NVL(C.CD_TIPO_AGENDAMENTO,22) IN (22, 23, 24) OR (C.CD_TIPO_AGENDAMENTO = 25 AND C.CD_STATUS_REPLAN = 32))
     ;

SELECT PED.DS_ROTEIRO_ENTREGA,
       PED.NU_QUANTIDADE,
       PED.NU_QUANTIDADE_ENTREGUE,
       PED.NU_QUANTIDADE_SALDO,
       PED.CD_MOTIVO_RECUSA,
       PED.CD_BLOQUEIO_REMESSA,
       PED.CD_BLOQUEIO_REMESSA_ITEM,
       PED.CD_BLOQUEIO_FATURAMENTO,
       PED.CD_BLOQUEIO_FATURAMENTO_ITEM,
       PED.CD_BLOQUEIO_CREDITO,
       PED.DS_CREDIT_BLOCK_REASON,
       0
  FROM VND.PEDIDO PED
 WHERE     --CD_ITEM_PEDIDO = V_CD_ITEM_PEDIDO
           PED.NU_ORDEM_VENDA = '0002451234'
       --AND PED.CD_PRODUTO_SAP = C_LINHA(V_LINHA).CD_PRODUTO_SAP
       AND (   PED.DH_ENTREGA =
               (SELECT MAX (DH_ENTREGA) DH
                  FROM VND.PEDIDO PIT
                 WHERE     PED.CD_PEDIDO = PIT.CD_PEDIDO
                       AND PIT.NU_ORDEM_VENDA = '0002464583')
            OR PED.DH_ENTREGA IS NULL)
       AND ROWNUM = 1;


--UPDATE ELO_CARTEIRA
--SET CD_STATUS_CEL_FINAL = 59,
--qt_agendada_confirmada = 72
--WHERE CD_ELO_CARTEIRA = 449992;
--COMMIT;


SELECT *
  FROM VND.ELO_CARTEIRA
 WHERE cD_ELO_CARTEIRA IN (449992)
--OR NU_ORDEM_VENDA = '0002469776'
;
SELECT *
  FROM VND.ELO_AGENDAMENTO
 WHERE CD_ELO_AGENDAMENTO IN (670) AND CD_ELO_STATUS IN (1, 2, 3);



SELECT *
  FROM INTERFACE
 WHERE 1 = 1 --AND DH_EXECUCAO IS NULL
             AND DH_EXECUCAO > CURRENT_DATE - 1;

SELECT *
  FROM INTERFACE
 WHERE DH_EXECUCAO IS NULL;


SELECT DISTINCT *
  FROM VND.ELO_BLOCKING_TYPES_COLUMNS EB
 WHERE EB.CD_BLOCKING_LEVEL IN (1,
                                2,
                                3,
                                4,
                                5);


SELECT PED.DS_ROTEIRO_ENTREGA,
       PED.NU_QUANTIDADE,
       PED.NU_QUANTIDADE_ENTREGUE,
       PED.NU_QUANTIDADE_SALDO,
       PED.CD_MOTIVO_RECUSA,
       PED.CD_BLOQUEIO_REMESSA,
       PED.CD_BLOQUEIO_REMESSA_ITEM,
       PED.CD_BLOQUEIO_FATURAMENTO,
       PED.CD_BLOQUEIO_FATURAMENTO_ITEM,
       PED.CD_BLOQUEIO_CREDITO,
       PED.DS_CREDIT_BLOCK_REASON,
       0,
       PED.CD_PRODUTO_SAP
  FROM VND.PEDIDO PED
 WHERE     1 = 1                           --CD_ITEM_PEDIDO = V_CD_ITEM_PEDIDO
       AND PED.NU_ORDEM_VENDA = '0002399631'
       AND PED.CD_PRODUTO_SAP = '000000000000119200'
       AND (   PED.DH_ENTREGA =
               (SELECT MAX (DH_ENTREGA) DH
                  FROM VND.PEDIDO PIT
                 WHERE     PED.CD_PEDIDO = PIT.CD_PEDIDO
                       AND PIT.NU_ORDEM_VENDA = '0002399631')
            OR PED.DH_ENTREGA IS NULL)
       AND ROWNUM = 1;


SELECT PED.DS_ROTEIRO_ENTREGA,
       PED.NU_QUANTIDADE,
       PED.NU_QUANTIDADE_ENTREGUE,
       PED.NU_QUANTIDADE_SALDO,
       PED.CD_MOTIVO_RECUSA,
       PED.CD_BLOQUEIO_REMESSA,
       PED.CD_BLOQUEIO_REMESSA_ITEM,
       PED.CD_BLOQUEIO_FATURAMENTO,
       PED.CD_BLOQUEIO_FATURAMENTO_ITEM,
       PED.CD_BLOQUEIO_CREDITO,
       PED.DS_CREDIT_BLOCK_REASON,
       0
  FROM VND.PEDIDO PED
 WHERE                                     --CD_ITEM_PEDIDO = V_CD_ITEM_PEDIDO
       PED.NU_ORDEM_VENDA = '0002418680';

SELECT *
  FROM VND.PEDIDO
 WHERE NU_ORDEM_VENDA = '0002469776';

--
--UPDATE VND.PEDIDO
--SET CD_SITUACAO_PEDIDO = '90'
--WHERE NU_ORDEM_VENDA = '0002446005'
--AND CD_PRODUTO_SAP = '000000000000107371'
--AND NU_CONTRATO ='3057715'
--AND NU_CONTRATO_SAP = '0040392832'
--AND CD_ITEM_CONTRATO = 30
--AND CD_PEDIDO = 904592;


SELECT *
  FROM VND.PEDIDO
 WHERE IC_PEDIDO = 'N';


SELECT *
  FROM VND.ELO_AGENDAMENTO
 WHERE CD_ELO_AGENDAMENTO = 215;

SELECT *
  FROM VND.ELO_AGENDAMENTO
 WHERE     1 = 1
       AND CD_WEEK = 'W422018'
       AND CD_CENTRO_EXPEDIDOR IN ('6220')
       --AND CD_POLO = 'P002'
       AND CD_ELO_STATUS IN (3,
                             4,
                             5,
                             6,
                             7,
                             8);


SELECT NU_PROTOCOLO_ENTREGA, QT_QUANTIDADE, QT_FORNECIDO
  FROM CPT.ENTREGA
 WHERE NU_PROTOCOLO_ENTREGA IN (SELECT *
                                  --NU_PROTOCOLO
                                  FROM VND.ELO_VBAK_PROTOCOLO
                                 WHERE                  --CD_ELO_CARTEIRA IN (
                                       --120699
                                       --);
                                       --  CD_ELO_VBAK IN (2011, 15594)
                                       -- CD_ELO_VBAK_PROTOCOLO IN (
                                       --3715
                                       --)
                                       --AND

                                        NU_PROTOCOLO IN ('R134297DT1'));


SELECT *
  FROM CPT.ENTREGA
 WHERE     1 = 1
       AND NU_PROTOCOLO_ENTREGA IN ('R111691GW1', 'NNR135902EZ1')
       AND CD_AUTORIZACAO_ENTREGA IN (135902);

--
--UPDATE CPT.ENTREGA
--SET SG_STATUS = 'R'
--WHERE
--NU_PROTOCOLO_ENTREGA IN(
--'R135902EZ1'
--
--) AND CD_AUTORIZACAO_ENTREGA = 135902;
--COMMIT;

SELECT * FROM VND.STATUS_PROPOSTA_CREDITO;

SELECT * FROM CPT.STATUS_ENTREGA;


SELECT *
  FROM CPT.AUTORIZACAO_ENTREGA
 --WHERE NU_ORDEM_VENDA = '0002373238';
 WHERE 1 = 1 --AND CD_PRODUTO_SAP = '000000000000117640'
             AND NU_CONTRATO_SAP = '0040336769'
             AND CD_ITEM_CONTRATO = '20'
             AND CD_AUTORIZACAO_ENTREGA IN (114455);

;

UPDATE   VND.ELO_VBAK_PROTOCOLO
SET QT_AGENDADA_PROTOCOLO = 0

WHERE
QT_AGENDADA_PROTOCOLO > 0
AND CD_ELO_CARTEIRA
IN (
471879

 )
AND NU_PROTOCOLO IN (
'R138290LZ1'

)
AND CD_ELO_VBAK_PROTOCOLO IN (
14744

);
COMMIT;


SELECT * FROM VND.ELO_CARTEIRA
WHERE CD_ELO_CARTEIRA IN (381101) AND QT_AGENDADA_PROTOCOLO > 0;

UPDATE VND.ELO_CARTEIRA
SET QT_AGENDADA_PROTOCOLO = 10307
WHERE
 CD_ELO_CARTEIRA IN (463784
);
COMMIT;


--';
--AND CD_ELO_VBAK_PROTOCOLO IN (
--SELECT * FROM VND.ELO_VBAK_PROTOCOLO

--WHERE
--CD_ELO_CARTEIRA IN (
--120699
--);

--AND   CD_ELO_VBAK = 2426--4965

---- CD_ELO_VBAK_PROTOCOLO IN (
--2831,
--3442
----
--)
--AND
--
-- NU_PROTOCOLO IN(
--'R124652GY1');
--
--
----R123516SF1  LIMPAR
--
--
--87529///////


SELECT *
  FROM VND.ELO_STATUS
 WHERE CD_ELO_STATUS = 57;


SELECT *
  FROM ALL_SOURCE
 WHERE UPPER (TEXT) LIKE '%FUNCTION%'
 AND OWNER IN ('VND', 'VND_SEC', 'CPT', 'CTF');


/*
INSERT INTO VND.INTERFACE (
CD_INTERFACE, 
IC_TIPO, 
NU_CODIGO
)
SELECT
(SELECT MAX(CD_INTERFACE) FROM INTERFACE) + ROWNUM,
'C',
'0002477373' NU_ORDEM_VENDA
FROM DUAL;
COMMIT;

INSERT INTO VND.INTERFACE (
CD_INTERFACE, 
IC_TIPO, 
NU_CODIGO
)
SELECT
(SELECT MAX(CD_INTERFACE) FROM INTERFACE) + ROWNUM,
'G',
'0004055613' NU_ORDEM_VENDA
FROM DUAL;
COMMIT;

*/

--UPDATE VND.ELO_AGENDAMENTO
--SET CD_ELO_STATUS = 8
--
--WHERE CD_ELO_AGENDAMENTO IN (
--627
--
--)
--AND CD_POLO = 'P012'
--AND CD_CENTRO_EXPEDIDOR = '6220'
--AND CD_WEEK = 'W422018'
--AND CD_ELO_STATUS = 9;
--COMMIT;



SELECT *
  FROM VND.ELO_AGENDAMENTO                                       --_SUPERVISOR
 WHERE CD_ELO_AGENDAMENTO IN (529);

SELECT *
  FROM VND.ELO_CARTEIRA
 WHERE CD_ELO_AGENDAMENTO = 301 AND CD_ELO_CARTEIRA = 125914
--NU_ORDEM_VENDA = '0002376951'
;
SELECT *
  FROM VND.ELO_CARTEIRA
 WHERE 1 = 1  --AND NU_ORDEM_VENDA = '0002383442' AND CD_ELO_AGENDAMENTO = 271
             AND CD_ELO_CARTEIRA IN (123716, 144212);


--UPDATE ELO_CARTEIRA
--SET --CD_STATUS_CEL_FINAL = 59,
--QT_AGENDADA = 111,
--QT_AGENDADA_CONFIRMADA = 111,
--CD_STATUS_REPLAN = null,
--QT_AGENDADA_ANTERIOR = 0
--WHERE CD_ELO_CARTEIRA IN (371709,380459,377731,365340,380460);
--COMMIT;

SELECT DISTINCT
       AGE.NU_CARTEIRA_VERSION,
       AGE.CD_ELO_AGENDAMENTO,
       AGE.CD_WEEK,
       AGE.CD_POLO,
       AGE.CD_CENTRO_EXPEDIDOR,
       AGE.CD_ELO_STATUS,
       EC.NU_PROTOCOLO,
       CC.DS_CENTRO_EXPEDIDOR,
       EC.DS_CENTRO_EXPEDIDOR,
       EC.CD_CENTRO_EXPEDIDOR,
       EC.CD_ELO_CARTEIRA,
       EC.NU_CONTRATO_SAP,
       EC.NU_ORDEM_VENDA,
       EC.QT_AGENDADA_CONFIRMADA,
       EC.CD_STATUS_CEL_FINAL,
       EC.QT_SALDO,
       EC.DS_CREDIT_BLOCK_REASON,
       EC.*,
       (SELECT '1'
          FROM VND.ELO_STATUS STB
         WHERE     STB.CD_ELO_TIPO_STATUS = 10
               AND SUBSTR (EC.DS_CREDIT_BLOCK_REASON, 1, 2) =
                   SUBSTR (STB.DS_STATUS, 1, 2)
               AND ROWNUM = 1),
       1
  FROM VND.ELO_AGENDAMENTO  AGE
       INNER JOIN VND.ELO_CARTEIRA EC
           ON AGE.CD_ELO_AGENDAMENTO = EC.CD_ELO_AGENDAMENTO
       LEFT JOIN CTF.CENTRO_EXPEDIDOR CC
           ON EC.CD_CENTRO_EXPEDIDOR = CC.CD_CENTRO_EXPEDIDOR
 WHERE     EC.IC_ATIVO = 'S'
       AND AGE.CD_WEEK = 'W402018'
       AND (EC.CD_CENTRO_EXPEDIDOR IN ('6100') OR AGE.CD_POLO = 'P001D')
       --AND NU_CONTRATO_SAP IN ('0040392900')
       AND EC.NU_ORDEM_VENDA IN ('0002442371')
       AND NVL (EC.QT_AGENDADA_CONFIRMADA, 0) >= 0
       --AND EC.CD_SALES_OFFICE = 5921
       --AND EC.NU_CONTRATO = 3060713
       --AND EC.QT_AGENDADA > 0
       --AND EC.CD_INCOTERMS = 'CIF'
       --AND EC.CD_SALES_GROUP = 768

       --AND EC.CD_GRUPO_EMBALAGEM = 'B'
       --AND EC.NO_PRODUTO_SAP = 'MS09F 07 34 12 S9'
       --AND EC.DS_CREDIT_BLOCK_REASON IS NOT NULL
       --AND EC.CD_BLOQUEIO_CREDITO NOT IN ( 'B')
       --AND NVL(EC.CD_STATUS_CEL_FINAL, 999) =  59
       --AND IC_COOPERATIVE = 'S'
       --AND AGE.CD_ELO_STATUS IN (40,50,6)
       --AND UPPER(EC.NO_CLIENTE) LIKE '%COOPERMOTA%'

       AND (   EC.CD_TIPO_AGENDAMENTO IN (22, 23, 24)
            OR (EC.CD_TIPO_AGENDAMENTO = 25 AND EC.CD_STATUS_REPLAN = 32));

/*
INSERT INTO CTF.EMAIL_LOGISTICA
VALUES 
('6220', 6, 'CATALAO DISPATCH - MOSAIC', 'CATALAO.DISPATCH@MOSAICCO.COM');
COMMIT;
*/

SELECT *
  FROM CTF.EMAIL_LOGISTICA
 WHERE CD_CENTRO_EXPEDIDOR IN (6220, 6222, 6221);

SELECT * FROM CTF.POLO;

SELECT *
  FROM VND.ELO_CARTEIRA
 WHERE     1 = 1
       -- (CD_ELO_CARTEIRA IN (
       --121656

       --) OR CD_ELO_AGENDAMENTO_ITEM = 55348)
       AND CD_ELO_AGENDAMENTO = 264
       AND (   CD_TIPO_AGENDAMENTO IN (22, 23, 24)
            OR (CD_TIPO_AGENDAMENTO = 25 AND CD_STATUS_REPLAN = 32));


SELECT EC.CD_ELO_CARTEIRA,
       EC.CD_CENTRO_EXPEDIDOR,
       CC.CD_CENTRO_EXPEDIDOR,
       EC.DS_CENTRO_EXPEDIDOR,
       CC.DS_CENTRO_EXPEDIDOR CORRETOCC
  FROM VND.ELO_CARTEIRA  EC
       INNER JOIN CTF.CENTRO_EXPEDIDOR CC
           ON EC.CD_CENTRO_EXPEDIDOR = CC.CD_CENTRO_EXPEDIDOR
 WHERE EC.DS_CENTRO_EXPEDIDOR <> CC.DS_CENTRO_EXPEDIDOR;


SELECT *
  FROM VND.VW_ELO_CARTEIRA_SAP
 WHERE CD_CENTRO_EXPEDIDOR = '6280';

SELECT *
  FROM VND.ELO_CARTEIRA
 WHERE     (CD_ELO_CARTEIRA = 121158 OR NU_ORDEM_VENDA = 'B0002369498')
       AND CD_ELO_AGENDAMENTO = 215;

--CD_ELO_AGENDAMENTO_ITEM = 44005;


--UPDATE VND.CONTRATO
--SET CD_SITUACAO_CONTRATO = 25
--WHERE
----NU_CONTRATO_SAP IN( '0040399178')
----AND NU_CONTRATO = '3061828'
-- CD_CONTRATO IN( 425,
--114119,
--203069,
--211518,
--225361
--)
--;
--COMMIT;


SELECT *
  FROM VND.CONTRATO
 WHERE 1 = 1 --AND NU_CONTRATO_SAP IS NULL AND NU_CONTRATO IS NULL
             --AND IC_ATIVO = 'S'
             --AND CD_AGENTE_VENDA = '0040405716'
             --AND DH_INCLUSAO > CURRENT_DATE - 10
             --AND NU_CONTRATO_SAP IN ('0040399178')
             AND NU_CONTRATO IN ('3056712') AND CD_CONTRATO = 224148;

SELECT *
  FROM VND.ELO_CARTEIRA
 WHERE CD_ELO_AGENDAMENTO_ITEM IN (129174);

--EDIT VND.ELO_CARTEIRA WHERE CD_ELO_AGENDAMENTO_ITEM IN( 160132);

SELECT *
  FROM VND.ELO_AGENDAMENTO_WEEK
 WHERE CD_ELO_AGENDAMENTO_ITEM IN (219200);

SELECT *
  FROM VND.ELO_AGENDAMENTO_DAY
 WHERE CD_ELO_AGENDAMENTO_WEEK IN (219200);                                                                                                                           -- 253

SELECT *
  FROM VND.ELO_AGENDAMENTO_ITEM
 WHERE CD_ELO_AGENDAMENTO_ITEM IN (219200);                                                                                                                            --CIF

SELECT *
  FROM VND.ELO_AGENDAMENTO
 WHERE CD_ELO_AGENDAMENTO IN (517);


SELECT *
  FROM VND.ELO_AGENDAMENTO_SUPERVISOR
 WHERE CD_ELO_AGENDAMENTO IN (670);

SELECT *
  FROM VND.ELO_AGENDAMENTO_SUPERVISOR
 WHERE CD_ELO_AGENDAMENTO_SUPERVISOR IN (5596);


  SELECT AGE.CD_ELO_AGENDAMENTO,
         AGE.CD_WEEK,
         AGE.CD_POLO,
         AGE.CD_CENTRO_EXPEDIDOR,
         AGE.CD_ELO_STATUS,
         SUP.CD_ELO_STATUS,
         COUNT (1)
    FROM VND.ELO_AGENDAMENTO_SUPERVISOR SUP
         INNER JOIN VND.ELO_AGENDAMENTO AGE
             ON AGE.CD_ELO_AGENDAMENTO = SUP.CD_ELO_AGENDAMENTO
   WHERE AGE.CD_ELO_AGENDAMENTO = 517
GROUP BY AGE.CD_ELO_AGENDAMENTO,
         AGE.CD_WEEK,
         AGE.CD_POLO,
         AGE.CD_CENTRO_EXPEDIDOR,
         SUP.CD_ELO_STATUS,
         AGE.CD_ELO_STATUS
ORDER BY CD_ELO_AGENDAMENTO;


SELECT *
  FROM CTF.POLO_CENTRO_EXPEDIDOR
 WHERE CD_CENTRO_EXPEDIDOR = '6122';


SELECT *
  FROM VND.ELO_STATUS
 WHERE CD_ELO_STATUS = 31;

SELECT * FROM CTF.POLO;

SELECT *
  FROM VND.ELO_CARTEIRA
 WHERE CD_ELO_AGENDAMENTO_ITEM IN (153135);


  SELECT AGE.CD_ELO_AGENDAMENTO,
         AGE.CD_POLO,
         AGE.CD_CENTRO_EXPEDIDOR,
         AGE.CD_MACHINE,
         AGE.CD_WEEK,
         AGE.NU_CARTEIRA_VERSION,
         AGE.CD_ELO_STATUS
    FROM VND.ELO_AGENDAMENTO AGE
   WHERE 1 = 1 AND AGE.CD_ELO_AGENDAMENTO = 289  --AND AGE.CD_ELO_STATUS IN(6)
                                                AND AGE.IC_ATIVO = 'S'
ORDER BY AGE.CD_CENTRO_EXPEDIDOR, AGE.CD_POLO;


SELECT *
  FROM VND.CONTRATO
 WHERE                                                --CD_CONTRATO = '230485'
       --OR
        NU_CONTRATO_SAP = '0040406827';


SELECT *
  FROM CTF.USUARIO
 WHERE                                 --CD_USUARIO_ORIGINAL LIKE '%4076853%';
       --UPPER(DS_EMAIL) LIKE '%FERNANDO%'
        CD_USUARIO_ORIGINAL IS NOT NULL;

SELECT *
  FROM VND.ELO_CARTEIRA_SAP
 WHERE     1 = 1
       AND NU_CARTEIRA_VERSION = '20181105213006'
       --       AND CD_PRODUTO_SAP = '000000000000119200'
       AND NU_CONTRATO_SAP = '0040408241';

--AND NU_ORDEM_VENDA = '0002437919';


  SELECT MAX (MM.CD_INTERFACE) CD_INTERFACE, MM.NU_CODIGO, MM.IC_TIPO
    FROM VND.INTERFACE MM
   WHERE     MM.DH_EXECUCAO > CURRENT_DATE - 2
         AND EXISTS
                 ((SELECT 1
                     FROM (  SELECT IT.NU_CODIGO, COUNT (1)
                               FROM VND.INTERFACE IT
                              WHERE IT.DH_EXECUCAO > CURRENT_DATE - 2
                           GROUP BY IT.NU_CODIGO
                             HAVING COUNT (1) > 1) SS
                    WHERE SS.NU_CODIGO = MM.NU_CODIGO))
GROUP BY MM.NU_CODIGO, MM.IC_TIPO;


SELECT *
  FROM VND.INTERFACE
 WHERE NU_CODIGO LIKE '%0040411133%';


SELECT DISTINCT *
  FROM VND.ELO_CARTEIRA_SAP
 WHERE NU_CONTRATO_SAP = '0040411133' --OR CD_SALES_GROUP = '733';
                                      AND DH_CARTEIRA > SYSDATE - 1;



  SELECT                                                --NU_CARTEIRA_VERSION,
         NU_ORDEM_VENDA, COUNT (1)
    FROM (  SELECT C.NU_ORDEM_VENDA, --MAX(C.NU_CARTEIRA_VERSION) NU_CARTEIRA_VERSION,
                                     (CD_ELO_CARTEIRA_SAP) CD_ELO_CARTEIRA_SAP
              FROM VND.ELO_CARTEIRA_SAP C
             WHERE     NU_ORDEM_VENDA IS NOT NULL
                   AND NU_CARTEIRA_VERSION >= '20180702233016'
          GROUP BY NU_ORDEM_VENDA, CD_ELO_CARTEIRA_SAP)
GROUP BY NU_ORDEM_VENDA                                --, NU_CARTEIRA_VERSION
  HAVING COUNT (1) > 1;


SELECT *
  FROM VND.ELO_CARTEIRA
 WHERE     NU_ORDEM_VENDA = '0002312110'
       AND NU_CARTEIRA_VERSION = '20180702233016';


  SELECT                                                --NU_CARTEIRA_VERSION,
         CD_ELO_AGENDAMENTO, NU_ORDEM_VENDA, COUNT (1)
    FROM (  SELECT C.NU_ORDEM_VENDA,
                   --MAX(C.NU_CARTEIRA_VERSION) NU_CARTEIRA_VERSION,
                   (CD_ELO_CARTEIRA) CD_ELO_CARTEIRA,
                   A.CD_ELO_AGENDAMENTO
              FROM VND.ELO_CARTEIRA C
                   INNER JOIN VND.ELO_AGENDAMENTO A
                       ON C.CD_ELO_AGENDAMENTO = A.CD_ELO_AGENDAMENTO
             WHERE     1 = 1
                   --NU_ORDEM_VENDA IS NOT NULL AND INSTR(NU_ORDEM_VENDA, '0 ') = 0
                   --AND A.CD_ELO_STATUS IN (3,4,5,6,7,8)
                   AND C.QT_AGENDADA_CONFIRMADA > 0
                   AND A.CD_ELO_AGENDAMENTO = 289
                   AND C.CD_STATUS_CEL_FINAL = 59
                   AND (   C.CD_TIPO_AGENDAMENTO IN (22, 23, 24)
                        OR (    C.CD_TIPO_AGENDAMENTO = 25
                            AND C.CD_STATUS_REPLAN = 32))
                   AND C.CD_ELO_AGENDAMENTO IS NOT NULL
          --NU_CARTEIRA_VERSION >='20180702233016'
          GROUP BY NU_ORDEM_VENDA, CD_ELO_CARTEIRA, A.CD_ELO_AGENDAMENTO)
GROUP BY NU_ORDEM_VENDA, CD_ELO_AGENDAMENTO            --, NU_CARTEIRA_VERSION
  HAVING COUNT (1) > 1;

SELECT MAX (CD_CONTRACT_MATERIAL_BLOCK) FROM CONTRACT_MATERIAL_BLOCK;

SELECT *
  FROM CTF.USUARIO
 WHERE    UPPER (CD_LOGIN) = 'ANASCIME'
       OR UPPER (DS_EMAIL) LIKE '%ANDRE.NASCIMENTO2@MOSAICCO.COM%';

--CD_USUARIO_ORIGINAL IS NOT NULL AND DH_ULTIMO_ACESSO > CURRENT_DATE - 30 ;
-- NO_USUARIO LIKE '%WELCE%';

SELECT *
  FROM CPT.USUARIO_COOPERATIVA
 WHERE CD_USUARIO = 4235;


  SELECT *
    FROM VND.ELO_CARTEIRA_HIST
   WHERE 1 = 1                    --AND DH_ULT_ALTERACAO > CURRENT_DATE - 0.05
               AND CD_ELO_AGENDAMENTO_ITEM = 202610
--AND CD_ELO_CARTEIRA = 264222
ORDER BY CD_ELO_CARTEIRA, ID;

SELECT *
  FROM VND.INTERFACE
 WHERE NU_CODIGO = '0002432990';


SELECT *
  FROM VND.ELO_AGENDAMENTO_ITEM
 WHERE CD_ELO_AGENDAMENTO_ITEM = 202610;


SELECT AD.IC_ADICAO, C.*
  FROM VND.ELO_CARTEIRA  C
       LEFT JOIN VND.VW_ELO_AGENDAMENTO_ITEM_ADICAO AD
           ON C.CD_ELO_AGENDAMENTO_ITEM = AD.CD_ELO_AGENDAMENTO_ITEM
 WHERE NU_CONTRATO_SAP = '0040398421'
--CD_ELO_CARTEIRA = 109680
;
SELECT *
  FROM VND.ELO_AGENDAMENTO
 WHERE CD_ELO_AGENDAMENTO = 278;


SELECT *
  FROM ELO_CARTEIRA_HIST
 WHERE CD_TIPO_AGENDAMENTO = 25 AND CD_STATUS_REPLAN IS NULL;

--UPDATE ELO_CARTEIRA_HIST
--SET DS_VERSAO = NULL
--WHERE ID = 1;
--COMMIT;

SELECT SYS_CONTEXT ('USERENV', 'CURRENT_SQL') FROM DUAL;


SELECT SYSDATE, CURRENT_DATE FROM DUAL;

SELECT *
  FROM V$OPTION
 WHERE PARAMETER = 'UNIFIED AUDITING';


SELECT SYS_CONTEXT ('USERENV', 'ACTION') FROM DUAL;


SELECT CD.CD_SITUACAO_CONTRATO, CD.DS_CREDIT_BLOCK_REASON, CD.*
  FROM VND.CONTRATO CD
 WHERE     1 = 1
       AND CD.NU_CONTRATO_SAP = '0040409904'
       AND CD.NU_CONTRATO = '3070824';


SELECT *
  FROM VND.ITEM_CONTRATO
 WHERE CD_CONTRATO = 227126;

SELECT 1500 - 1131.88
  FROM DUAL;

--UPDATE VND.CONTRATO
--SET --IC_ATIVO = 'S',
--CD_STATUS_CONTRATO = 4,
--CD_SITUACAO_CONTRATO = 20,
--DS_CREDIT_BLOCK_REASON = NULL
--NU_CONTRATO_SAP = NULL
--DS_CREDENCIAMENTO_FOB = 'ROD BR163  - FAZ. SÃO CARLOS'
--DS_FORMA_PAGAMENTO = 'Y190 - 30 DIAS - DATA DO DOCUMENTO',
--CD_FORMA_PAGAMENTO = 'Y190'
--
--WHERE CD_CONTRATO = 234306
--AND NU_CONTRATO = 3070824
--AND NU_CONTRATO_SAP = '0040409904'
;
--COMMIT;

--CD_STATUS_CONTRATO = 4 E IC_ATIVO = S


SELECT * FROM VND.VW_ELO_AGENDAMENTO_ITEM_ADICAO;

SELECT *
  FROM VND.CONTRATO
 WHERE CD_FORMA_PAGAMENTO = 'Y190';


SELECT *
  FROM CTF.CLIENTE
 --WHERE NU_CGC_CPF LIKE '%48342%';
 WHERE -- NO_CLIENTE = 'THIAGO GEOVANNE SILVA FERREIRA'
        CD_CLIENTE = '0004024635';

SELECT COUNT (1)
  FROM CTF.USUARIO
 WHERE CD_USUARIO = 3485;


SELECT *
  FROM VND.ELO_STATUS
 WHERE CD_ELO_TIPO_STATUS = 10;


SELECT *
  FROM VND.ELO_VBAK
 WHERE NU_CONTRATO_SAP IN ('0040388011', '0040396404');

SELECT ORA_ROWSCN, NU_CARTEIRA_VERSION
  FROM VND.ELO_CARTEIRA_SAP
 WHERE CD_ELO_CARTEIRA_SAP IN (1062572, 1049741);

SELECT SCN_TO_TIMESTAMP (ORA_ROWSCN), NU_CARTEIRA_VERSION
  FROM VND.ELO_CARTEIRA_SAP
 WHERE CD_ELO_CARTEIRA_SAP = 1049741;


SELECT COUNT (1)
  FROM VND.ELO_CARTEIRA_SAP
 WHERE 1 = 1 --NU_CARTEIRA_VERSION = '20180722213005'
             --AND NU_CONTRATO_SAP = '0040409410'
             --AND CD_SALES_GROUP = '768'
             AND DH_CARTEIRA > CURRENT_DATE - 1
-- = NU_ORDEM_VENDA
;
SELECT ORA_ROWSCN, P.*
  FROM VND.PEDIDO P
 WHERE     DH_ULT_INTERFACE > CURRENT_DATE - 1000
       AND DH_ULT_INTERFACE < CURRENT_DATE - 999;



SELECT (ORA_ROWSCN), DH_ULT_INTERFACE
  FROM VND.PEDIDO
 WHERE CD_PEDIDO = 428467 AND CD_ITEM_PEDIDO = 10;

SELECT SCN_TO_TIMESTAMP (6153484692217), DH_ULT_INTERFACE
  FROM VND.PEDIDO PED
 WHERE CD_PEDIDO > 645000 AND CD_ITEM_PEDIDO = 10;

WITH
    CTEGC
    AS
        (  SELECT MAX (CD_ELO_CARTEIRA_SAP) CD_ELO_CARTEIRA_SAP,
                  C.NU_CONTRATO_SAP,
                  C.CD_ITEM_CONTRATO,
                  C.NU_ORDEM_VENDA
             FROM VND.ELO_CARTEIRA_SAP C
            WHERE     NU_CARTEIRA_VERSION = '20180722213005'
                  AND NOT (NVL (C.NU_ORDEM_VENDA, '0') IN
                               ('          ', '0', '0         '))
                  AND QT_SALDO > 0
                  AND CD_BLOQUEIO_REMESSA IS NULL
                  AND CD_BLOQUEIO_FATURAMENTO IS NULL
                  AND CD_BLOQUEIO_CREDITO IS NULL
                  AND CD_BLOQUEIO_REMESSA_ITEM IS NULL
                  AND CD_BLOQUEIO_FATURAMENTO_ITEM IS NULL
                  AND CD_MOTIVO_RECUSA IS NULL
                  AND CD_BLOQUEIO_ENTREGA IS NULL
                  AND NVL (DS_CREDIT_BLOCK_REASON, ' ') = ' '
         GROUP BY C.NU_CONTRATO_SAP, C.CD_ITEM_CONTRATO, C.NU_ORDEM_VENDA)
SELECT PARAAT.*
  FROM (SELECT G.*,
               (SELECT MAX (OV.DH_ULT_INTERFACE) DH_INTERFACE_OV
                  FROM VND.PEDIDO OV
                 WHERE OV.NU_ORDEM_VENDA = G.NU_ORDEM_VENDA)
                   DH_ULT_OV,
               (SELECT MAX (CC.DH_ULT_INTERFACE) DH_INTERFACE_CC
                  FROM VND.CONTRATO CC
                 WHERE CC.NU_CONTRATO_SAP = G.NU_CONTRATO_SAP)
                   DH_ULT_CC,
               (SELECT MAX (CC.NU_QUANTIDADE_SALDO) NU_QUANTIDADE_SALDO
                  FROM VND.PEDIDO CC
                 WHERE CC.NU_ORDEM_VENDA = G.NU_ORDEM_VENDA)
                   NU_QUANTIDADE_SALDO,
               (SELECT SUM (
                             NVL (CI.NU_QUANTIDADE, 0)
                           - NVL (CI.NU_QTY_DELIVERED, 0))
                           SALDOCC
                  FROM VND.CONTRATO  CC
                       INNER JOIN VND.ITEM_CONTRATO CI
                           ON CC.CD_CONTRATO = CI.CD_CONTRATO
                 WHERE     CC.NU_CONTRATO_SAP = G.NU_CONTRATO_SAP
                       AND CI.CD_ITEM_CONTRATO = G.CD_ITEM_CONTRATO)
                   SALDOCC,
               (SELECT    TO_CHAR (
                                SUM (NVL (ENT.QT_QUANTIDADE, 0))
                              - SUM (NVL (ENT.QT_FORNECIDO, 0)))
                       || ':'
                       || MAX (ENT.NU_PROTOCOLO_ENTREGA)
                           QTPROTO
                  FROM CPT.ENTREGA  ENT
                       INNER JOIN CPT.AUTORIZACAO_ENTREGA AUTENT
                           ON ENT.CD_AUTORIZACAO_ENTREGA =
                              AUTENT.CD_AUTORIZACAO_ENTREGA
                 WHERE     ENT.SG_STATUS NOT IN ('P', 'C')
                       AND   NVL (ENT.QT_QUANTIDADE, 0)
                           - NVL (ENT.QT_FORNECIDO, 0) >
                           1
                       AND AUTENT.NU_CONTRATO_SAP = G.NU_CONTRATO_SAP
                       AND AUTENT.CD_ITEM_CONTRATO = G.CD_ITEM_CONTRATO
                       AND AUTENT.CD_PRODUTO_SAP = G.CD_PRODUTO_SAP)
                   QT_AND_PROTO
          FROM VND.ELO_CARTEIRA_SAP  G
               INNER JOIN
               (SELECT CD_ELO_CARTEIRA_SAP,
                       NU_CONTRATO_SAP,
                       CD_ITEM_CONTRATO,
                       NU_ORDEM_VENDA
                  FROM CTEGC) GC
                   ON GC.CD_ELO_CARTEIRA_SAP = G.CD_ELO_CARTEIRA_SAP) PARAAT
 WHERE --(NVL(DH_ULT_OV, CURRENT_DATE - 30) < CURRENT_DATE -20 OR DH_ULT_CC < CURRENT_DATE - 20)
       --AND ABS(SALDOCC-1) > 0
        DH_ULT_OV IS NULL;

SELECT G.*
  FROM VND.ELO_CARTEIRA_SAP G
 WHERE DH_CARTEIRA > CURRENT_DATE - 1;

SELECT                                                         --AD.IC_ADICAO,
       C.*
  FROM VND.ELO_CARTEIRA C
 --LEFT JOIN VND.VW_ELO_AGENDAMENTO_ITEM_ADICAO AD
 --ON C.CD_ELO_AGENDAMENTO_ITEM = AD.CD_ELO_AGENDAMENTO_ITEM
 WHERE NU_CONTRATO_SAP = '0040407363' AND NU_ORDEM_VENDA IN ('0002435015');

SELECT *
  --NU_CONTRATO_SAP, CD_ITEM_CONTRATO, CD_PRODUTO_SAP, CD_TIPO_CONTRATO
  FROM VND.ELO_CARTEIRA_SAP
 WHERE     1 = 1
       --AND NU_CARTEIRA_VERSION ='20180829213001' --AND CD_SALES_GROUP = 768
       AND DH_CARTEIRA > CURRENT_DATE - 1
       AND NU_CONTRATO_SAP IN ('0040387276')
       AND NU_ORDEM_VENDA IN ('0002350797')

--AND NU_CONTRATO_SAP IN ('0040392900' )
--AND EC.NU_ORDEM_VENDA IN( '0002370998' )

--GROUP BY CD_TIPO_CONTRATO
;
--ACHAR O RELACIONAMENTO DE CONTRATO CLIENTE E COOPERATIVA E FILIAL

SELECT CC.*,
       CLICONT.*,
       GRPCLI.*,
       SEGCLI.*
  FROM VND.CONTRATO  CC
       INNER JOIN VND.ITEM_CONTRATO IC ON CC.CD_CONTRATO = IC.CD_CONTRATO
       INNER JOIN VND.CLIENTE_CONTRATO CLICONT
           ON     CLICONT.CD_CLIENTE_CONTRATO = CC.CD_CLIENTE_CONTRATO
              AND CLICONT.CD_SALES_ORG = CC.CD_SALES_ORG
              AND CLICONT.CD_DISTRIBUTION_CHANNEL =
                  CC.CD_DISTRIBUTION_CHANNEL
              AND CLICONT.CD_SALES_DIVISION = CC.CD_SALES_DIVISION
       INNER JOIN CTF.GRUPO_CLIENTES GRPCLI
           ON CLICONT.CD_GRUPO_CLIENTES = GRPCLI.CD_GRUPO_CLIENTES
       INNER JOIN CTF.SEGMENTO_CLIENTE SEGCLI
           ON SEGCLI.CD_SEGMENTO_CLIENTE = CLICONT.CD_SEGMENTO_CLIENTE
 WHERE     CC.NU_CONTRATO_SAP = '0040404353'
       AND IC.CD_ITEM_CONTRATO = 10
       AND IC.CD_PRODUTO_SAP = '000000000000119200'
       AND IC.CD_CONTRATO = 229259
       AND CC.NU_CONTRATO = 3066378
--AND CC.CD_CLIENTE_CONTRATO = 495257
--AND CC.CD_SALES_ORG = 'BR02'
--AND CC.CD_DISTRIBUTION_CHANNEL = 10
--AND CC.CD_SALES_DIVISION = 10
--AND CC.CD_TIPO_CONTRATO = 'ZCQN'
--AND CD_CLIENTE = '0004077055'
;

SELECT *
  FROM CPT.COOPERATIVA_FILIAL
 WHERE CD_CLIENTE IN ('0004068482', '0004068483', '0006024932');

SELECT *
  FROM CPT.COOPERATIVA
 WHERE 1 = 1 --AND UPPER (NO_COOPERATIVA) LIKE '%AGROTECNICA%'
AND CD_COOPERATIVA IN (748)
;

SELECT *
  FROM CPT.AUTORIZACAO_ENTREGA
 WHERE NU_CONTRATO_SAP = '0040410395' AND CD_ITEM_CONTRATO = 10;

SELECT * FROM CPT.COOPERADO
where nu_cpf_cnpj like '%04620782807%'
;

edit  CPT.COOPERADO
where cd_cooperado = 36410
--nu_cpf_cnpj like '%2474324151%'
;

SELECT *
  FROM CPT.PROPRIEDADE_COOPERADO
 WHERE
 cd_cooperado = 36438  
 --            --CD_PROPRIEDADE IN (38671,22588,38672,38672,22588,38670);
  --     CD_CLIENTE IN ('0004068482', '0004068483', '0006024932')
  ;

SELECT *
  FROM VND.DESDOBRAMENTO
 WHERE                                         --NU_ORDEM_VENDA = '0002407444'
       CD_CONTRATO = 223065;

SELECT *
  FROM CTF.SEGMENTO_CLIENTE SEGCLI;


SELECT *
  FROM VND.DESDOBRAMENTO_CADENCIA
 WHERE CD_CONTRATO = 237511;

SELECT * FROM VND.CLIENTE_CONTRATO;

SELECT * FROM VND.CLIENTE_DOCUMENTO;

SELECT *
  FROM VND.CADENCIA
 WHERE CD_CONTRATO = 237511;

SELECT * FROM VND.DETALHE_PLANEJAMENTO;

SELECT * FROM VND.RESUMO_PEDIDO;

SELECT * FROM CTF.EMAIL_MENSAGEM;

--EDIT CTF.EMAIL_MENSAGEM
--WHERE
--CD_EMAIL_MENSAGEM = 1;
--COMMIT;

SELECT *
  FROM CTF.EMAIL_SERVICE
 WHERE 1 = 1 --AND UPPER(DS_SUBJECT) LIKE '%COOPERATIVAS%'
             AND IC_ACTIVE = 'S' AND DT_ADDED > CURRENT_DATE - 1;

SELECT *
  FROM CTF.EMAIL_LOGISTICA A
 WHERE UPPER (DS_EMAIL_LOGISTICA) LIKE '%RENATA%';


SELECT *
  FROM CTF.EMAIL_MENSAGEM A
 WHERE UPPER (DS_SUBJECT) LIKE '%COOPERATIVAS%';


  SELECT *
    FROM CTF.E_MAIL
   WHERE DS_SUBJECT = 'PORTAL DAS COOPERATIVAS: CADASTRO DE CLIENTES'
ORDER BY CD_EMAIL DESC;

SELECT * FROM VND.SITUACAO_CONTRATO;

SELECT * FROM VND.SALES_ORG;

SELECT *
  FROM ALL_SOURCE
 WHERE UPPER (TEXT) LIKE '%USD_TIPO_ORDEM%';


SELECT --   'CD_TIPO_ORDEM = '''
       --|| CD_TIPO_ORDEM
       --|| ''' and CD_SALES_ORG = '''
       --|| CD_SALES_ORG
       --|| ''' AND CD_DISTRIBUTION_CHANNEL = '''
       --|| CD_DISTRIBUTION_CHANNEL
       --|| ''' AND CD_SALES_DIVISION = '''
       --|| CD_SALES_DIVISION
       --|| ''''
        --   TOD
            *
           
  FROM VND.TIPO_ORDEM
 WHERE     1 = 1
       AND CD_TIPO_ORDEM = 'ZCQN'
       AND CD_SALES_ORG = 'PY01'
       AND CD_DISTRIBUTION_CHANNEL = '10'
       AND CD_SALES_DIVISION = '10'
--UNION
--SELECT * FROM VND.TIPO_ORDEM
--WHERE 1=1
--AND CD_TIPO_ORDEM = 'ZCQP'
--AND CD_SALES_ORG = 'BR02'
--AND CD_DISTRIBUTION_CHANNEL = '10'
--AND CD_SALES_DIVISION = '10'
--AND TIPO_ORDEM_CURRENCY = 'USD'
;

SELECT * FROM VND.STATUS_CONTRATO;

SELECT *
  FROM CTF.CLIENTE
 WHERE    CD_CLIENTE = '0004071960'
       OR NO_CLIENTE = 'CASA DO CAFE COM E REPR DE PROD AGR';


SELECT *
  FROM CTF.USUARIO
 WHERE     CD_USUARIO = 3409
       --   (UPPER (DS_EMAIL) LIKE '%LUIZ_PEREIRA_REZENDE@CARGILL.COM%')
       AND UPPER (NO_USUARIO) LIKE '%ALTENHOFEN%'
       AND DH_ULTIMO_ACESSO > CURRENT_DATE - 2;

SELECT *
  FROM ALL_TABLES
 WHERE OWNER = 'CPT';


SELECT *
  FROM CPT.USUARIO_COOPERATIVA
 WHERE CD_USUARIO = 3100 AND CD_COOPERATIVA = 308;

--UPDATE CPT.USUARIO_COOPERATIVA
--SET CD_COOPERATIVA = 308
--WHERE
--CD_COOPERATIVA = 279
--AND CD_USUARIO = 3934;

SELECT *
  FROM CTF.USUARIO
 WHERE CD_USUARIO = 3536 OR DS_EMAIL = 'OLEGARIO@GRUPOAGROTECNICA.COM.BR';

SELECT *
  FROM CTF.CENTRO_EXPEDIDOR CC
 WHERE UPPER (DS_CENTRO_EXPEDIDOR) LIKE '%RIO VERDE%';


BEGIN
    DBMS_SESSION.FREE_UNUSED_USER_MEMORY;
END;


SELECT *
  FROM VND.ELO_CARTEIRA
 WHERE CD_ELO_AGENDAMENTO_ITEM IN (204710);

SELECT * FROM V$SESSION_LONGOPS;

--EDIT VND.CADENCIA WHERE CD_CONTRATO = 233970;

SELECT *
  FROM VND.CADENCIA
 WHERE CD_CONTRATO = 233970;


--INSERT INTO  VND.INTERFACE
--(CD_INTERFACE, IC_TIPO, NU_CODIGO)

  SELECT (SELECT MAX (CD_INTERFACE) FROM INTERFACE) + ROWNUM,
         'G' TIPO,
         NU_CONTRATO_SAP
    FROM (SELECT DISTINCT CONT.NU_CONTRATO_SAP
            FROM VND.CONTRATO CONT
                 INNER JOIN VND.ITEM_CONTRATO IC
                     ON CONT.CD_CONTRATO = IC.CD_CONTRATO
                 INNER JOIN VND.CLIENTE_CONTRATO CLI_CONT
                     ON CONT.CD_CLIENTE_CONTRATO = CLI_CONT.CD_CLIENTE_CONTRATO
           WHERE     IC.NU_QUANTIDADE - IC.NU_QTY_DELIVERED > 0
                 AND CONT.CD_STATUS_CONTRATO = 8
                 AND CONT.CD_SITUACAO_CONTRATO = 10
                 AND CONT.CD_BLOQUEIO_ENTREGA IS NULL
                 AND CONT.CD_BLOQUEIO_FATURAMENTO IS NULL
                 --AND NVL(CONT.DS_CREDIT_BLOCK_REASON, '  ') = '  '
                 --AND (CONT.DS_CREDIT_BLOCK_REASON IS NULL OR CONT.DS_CREDIT_BLOCK_REASON = '  '  )
                 AND CONT.DT_FIM > CURRENT_DATE - 666
                 AND CONT.DH_ULT_INTERFACE > CURRENT_DATE - 100)
   WHERE ROWNUM < 1000
ORDER BY NU_CONTRATO_SAP DESC;


SELECT *
  FROM VND.INTERFACE
 WHERE DH_EXECUCAO IS NULL OR NU_CODIGO = '0040415972';

  SELECT *
    FROM VND.INTERFACE
   WHERE DH_EXECUCAO IS NOT NULL
ORDER BY DH_EXECUCAO DESC;


SELECT *
  FROM CTF.CLIENTE
 WHERE CD_CLIENTE = '0004071960';


SELECT *
  FROM VND.ELO_CARTEIRA_SAP
 WHERE 1 = 1 --AND NU_ORDEM_VENDA = '0002446005'
             --NU_CONTRATO = '3077121'
             AND NU_CONTRATO_SAP = '0040412578'
--AND CD_SALES_GROUP = 704
-- AND NU_CARTEIRA_VERSION = '20181027213048'
;


SELECT *
  FROM VND.CONTRATO                                                  --_LOGGER
 WHERE 1 = 1 --AND NU_CONTRATO_SAP IS NULL AND NU_CONTRATO IS NULL
             --AND IC_ATIVO = 'S'
             --AND CD_AGENTE_VENDA = '0040410004'
             --AND DH_INCLUSAO > CURRENT_DATE - 10
             --AND NU_CONTRATO_SAP = '0040130234'
             AND NU_CONTRATO IN ('3075529')
--AND  DS_MESSAGE LIKE '%221407%'
;

SELECT *
  FROM VND.PEDIDO
 WHERE NU_CONTRATO_SAP = '0040409904';


--UPDATE VND.CONTRATO
--SET
--DS_CREDIT_BLOCK_REASON = NULL,
--CD_BLOQUEIO_CREDITO = 'D',
--CD_SITUACAO_CONTRATO = 25
--CD_BLOQUEIO_REMESSA = NULL,
--CD_BLOQUEIO_FATURAMENTO = NULL,
--CD_BLOCKING_REASON = NULL
--
--WHERE
--NU_CONTRATO_SAP = '0040130234'
--AND CD_CONTRATO = 20508
--AND CD_SITUACAO_CONTRATO = 20
--;

SELECT *
  FROM VND.CONTRATO
 WHERE NU_CONTRATO_SAP = '0040360748' AND NU_CONTRATO = 6055615;


SELECT *
  FROM VND.ITEM_CONTRATO
 WHERE CD_CONTRATO = 233686;

SELECT NU_CONTRATO_SAP,
       DH_ULT_INTERFACE,
       CD_SITUACAO_CONTRATO,
       CD_BLOQUEIO_CREDITO,
       DS_CREDIT_BLOCK_REASON
  FROM VND.CONTRATO
 WHERE     DH_ULT_INTERFACE > CURRENT_DATE - 30
       AND CD_SITUACAO_CONTRATO IN (10)
       AND DS_CREDIT_BLOCK_REASON IS NULL;



SELECT (SELECT SUM (NVL (IC.NU_QUANTIDADE, 0) - NVL (IC.NU_QTY_DELIVERED, 0))
          FROM VND.ITEM_CONTRATO IC
         WHERE IC.CD_CONTRATO = CONT.CD_CONTRATO)
           SALDOITEM,
       CONT.*
  FROM VND.CONTRATO CONT
 WHERE     CONT.IC_ATIVO = 'S'
       AND EXISTS
               (SELECT 1
                  FROM VND.ITEM_CONTRATO IC
                 WHERE     IC.CD_CONTRATO = CONT.CD_CONTRATO
                       AND   NVL (IC.NU_QUANTIDADE, 0)
                           - NVL (IC.NU_QTY_DELIVERED, 0) >
                           1)
       AND CONT.CD_STATUS_CONTRATO = '8'
       AND CONT.DT_FIM BETWEEN CURRENT_DATE - 180 AND CURRENT_DATE + 360
       --AND IC_SIGNED = 'S'
       --AND IC_SAP_READY = 'S'
       AND CONT.CD_SITUACAO_CONTRATO IN (25)
       --AND DH_ULT_INTERFACE < CURRENT_DATE - 30
       --AND CD_BLOQUEIO_CREDITO IS NULL
       AND CONT.CD_INCOTERMS = 'CIF'
       AND NVL (CONT.VL_FRETE_DISTRIBUICAO, 0) = 0
       AND CONT.CD_BLOQUEIO_ENTREGA IS NULL
       AND CONT.CD_BLOQUEIO_FATURAMENTO IS NULL
       AND CONT.CD_BLOQUEIO_REMESSA IS NULL
       AND CONT.DS_CREDIT_BLOCK_REASON IS NULL
--AND NU_CONTRATO_SAP IN ('0040410395', 'X0040396255')
;
SELECT CLI.*
  FROM CTF.CLIENTE  CLI
       INNER JOIN CTF.USUARIO US ON CLI.CD_CLIENTE = US.CD_USUARIO_ORIGINAL
 WHERE     CLI.IC_ATIVO = 'S'
       AND US.IC_BLOQUEADO = 'N'
       AND US.IC_ATIVO = 'S'
       AND CLI.IC_AGENTE = 'N'
       AND CLI.IC_TIPO_CLIENTE = 'C'
--AND CLI.CD_CLIENTE = '0004076201'
;

SELECT *
  FROM CTF.AGENTE
 WHERE 
 cd_agente_venda = '0004072814';
 --NO_AGENTE LIKE '%KSB%';


SELECT *
  FROM CTF.CLIENTE
 WHERE NO_CLIENTE LIKE '%KSB%';
 
 
SELECT * FROM CTF.CLIENTE 
WHERE CD_CLIENTE = '0004055613';


SELECT *
  FROM CTF.AGENTE ag
  inner join ctf.usuario us
  on ag.CD_AGENTE_VENDA = us.cd_usuario_original
  where 1=1
  and us.IC_ATIVO = 'S'
  AND ag.IC_ATIVO = 'S'
  AND us.IC_BLOQUEADO = 'N'
  AND us.DH_ULTIMO_ACESSO > = current_date - 30 
  
  ;



SELECT *
  FROM VND.ELO_CARTEIRA_SAP
 WHERE     1 = 1
       --CD_BLOQUEIO_REMESSA = '99'--;
       --NU_CONTRATO IN ('3075550', '3075569')
       --NU_CONTRATO_SAP = '0040414897'
       --AND nu_ordem_venda = '0002477373'
       AND DH_CARTEIRA > CURRENT_DATE - 2;

--
--UPDATE
--CPT.AUTORIZACAO_ENTREGA
--SET QT_QUANTIDADE = 78
--
-- WHERE
--NU_CONTRATO_SAP =  '0040415231'
--AND CD_ITEM_CONTRATO = 30
--AND CD_PRODUTO_SAP = '000000000000105719'
--AND NU_CONTRATO = '3074908'
--AND CD_AUTORIZACAO_ENTREGA = 136623;


SELECT *
  FROM CPT.AUTORIZACAO_ENTREGA
 WHERE     1 = 1
       AND NU_CONTRATO_SAP = '0040360748'
       AND CD_ITEM_CONTRATO = 30
       --AND CD_PRODUTO_SAP = '000000000000119200'
       --AND NU_CONTRATO = '3066378'
       AND CD_AUTORIZACAO_ENTREGA = 136623;


SELECT *
  FROM CTF.USUARIO
 WHERE UPPER (CD_LOGIN) LIKE '%RISHIKAW%' AND CD_USUARIO = 2991;


--UPDATE CTF.USUARIO
--SET CD_LIST_SEGMENT = '4',
--CD_LIST_SEGMENT_FUTURE = '5'
--WHERE CD_LOGIN = 'RISHIKAW'
--AND CD_USUARIO = 2991;


SELECT DISTINCT S.NU_CONTRATO_SAP,
                C.CD_SITUACAO_CONTRATO,
                S.CD_BLOQUEIO_REMESSA,
                C.CD_BLOQUEIO_REMESSA,
                C.CD_BLOCKING_REASON
  FROM VND.ELO_CARTEIRA_SAP  S
       INNER JOIN VND.CONTRATO C ON S.NU_CONTRATO_SAP = C.NU_CONTRATO_SAP
 WHERE     1 = 1
       AND S.CD_BLOQUEIO_REMESSA > '  '
       AND C.CD_BLOQUEIO_REMESSA = C.CD_BLOCKING_REASON
       AND C.CD_BLOQUEIO_REMESSA > '  '
       AND C.CD_SITUACAO_CONTRATO IN (5,
                                      10,
                                      15,
                                      20);


SELECT DISTINCT NU_CONTRATO_SAP,
                DT_FIM,
                CD_BLOCKING_REASON,
                CD_BLOQUEIO_CREDITO,
                CD_BLOQUEIO_ENTREGA,
                CD_BLOQUEIO_FATURAMENTO,
                CD_BLOQUEIO_REMESSA,
                CD_SITUACAO_CONTRATO
  FROM VND.CONTRATO
 WHERE     CD_STATUS_CONTRATO = 8
       AND CD_SITUACAO_CONTRATO IN (50,
                                    10,
                                    15,
                                    20)
       AND NVL (CD_BLOCKING_REASON, 'XS') <> NVL (CD_BLOQUEIO_REMESSA, 'XS');