

WITH AGENDAMENTO AS 
(

SELECT AGE.CD_ELO_AGENDAMENTO, AGE.CD_WEEK, AGE.CD_POLO, AGE.CD_MACHINE, AGE.CD_CENTRO_EXPEDIDOR, 
AGE.CD_ELO_STATUS
FROM VND.ELO_AGENDAMENTO AGE
WHERE 
AGE.IC_ATIVO = 'S'
--AND AGE.CD_ELO_STATUS IN (3,4,5,6,7)
--AND AGE.CD_ELO_STATUS IN (3,4,5,6)
--AND AGE.CD_ELO_STATUS IN (4,6)  --1 PASSO SEM ERRO STATUS 59
AND AGE.CD_ELO_STATUS IN (3,4,5,6 )  --2 PASSO SEM ERRO STATUS 59 
),
--select * from AGENDAMENTO

CTE_CONTRATO_PEDIDOS_STATUS AS 
(
SELECT DISTINCT 
CT.NU_CONTRATO_SAP, 
CT.NU_ORDEM_VENDA

FROM VND.ELO_CARTEIRA CT
INNER JOIN AGENDAMENTO AG
ON 
AG.CD_ELO_AGENDAMENTO = CT.CD_ELO_AGENDAMENTO
WHERE 
CT.IC_ATIVO = 'S'

AND NVL(CT.QT_AGENDADA_CONFIRMADA,0) >= 0
AND CT.QT_AGENDADA > 0
AND (CT.DH_CORTADO_FABRICA IS NULL AND NVL(CT.QT_AGENDADA_CELULA, 1) > 0)  
AND NVL(CT.CD_STATUS_CEL_FINAL, 40) NOT IN (40, 41, 59, 57, 58 )
AND CT.CD_MOTIVO_RECUSA IS NULL
and AG.CD_ELO_STATUS IN (3,4,5,6)
AND NOT(NVL(CT.NU_ORDEM_VENDA, '0') IN ('          ', '0', '0         ' )) 
AND (CT.CD_TIPO_AGENDAMENTO IN (22,23,24) 
        OR (CT.CD_TIPO_AGENDAMENTO = 25 AND CT.CD_STATUS_REPLAN = 32) 
        OR (CT.CD_TIPO_AGENDAMENTO IS NULL 
        AND EXISTS (SELECT 1 FROM VND.VW_ELO_AGENDAMENTO_ITEM_ADICAO IIS WHERE IIS.CD_ELO_AGENDAMENTO_ITEM = CT.CD_ELO_AGENDAMENTO_ITEM)) )

),
--SELECT DISTINCT GD.NU_CONTRATO_SAP, CTR.DH_ULT_INTERFACE FROM CTE_CONTRATO_PEDIDOS GD
--INNER JOIN VND.CONTRATO CTR ON GD.NU_CONTRATO_SAP = CTR.NU_CONTRATO_SAP
--SELECT DISTINCT GD.NU_ORDEM_VENDA, CTR.DH_ULT_INTERFACE FROM CTE_CONTRATO_PEDIDOS GD
--INNER JOIN VND.PEDIDO CTR ON GD.NU_ORDEM_VENDA = CTR.NU_ORDEM_VENDA

CTE_CONTRATO_TODOS AS 
(
select CCC.* from vnd.contrato CCC
where CCC.IC_ATIVO = 'S'

),


CTE_CONTRATO_PEDIDOS AS 
(
SELECT DISTINCT 
CT.NU_CONTRATO_SAP, 
CT.NU_ORDEM_VENDA

FROM VND.ELO_CARTEIRA CT
INNER JOIN AGENDAMENTO AG
ON 
AG.CD_ELO_AGENDAMENTO = CT.CD_ELO_AGENDAMENTO
WHERE 
CT.IC_ATIVO = 'S'

AND NVL(CT.QT_AGENDADA_CONFIRMADA,0) > 0
AND CT.QT_AGENDADA > 0
AND (CT.DH_CORTADO_FABRICA IS NULL AND NVL(CT.QT_AGENDADA_CELULA, 1) >= 0)  
AND NVL(CT.CD_STATUS_CEL_FINAL, 62)  IN ( 59)
AND CT.CD_MOTIVO_RECUSA IS NULL
and AG.CD_ELO_STATUS IN (3,4,5,6)
AND NOT(NVL(CT.NU_ORDEM_VENDA, '0') IN ('          ', '0', '0         ' )) 
AND (CT.CD_TIPO_AGENDAMENTO IN (22,23,24) OR (CT.CD_TIPO_AGENDAMENTO = 25 AND CT.CD_STATUS_REPLAN = 32)
        OR (CT.CD_TIPO_AGENDAMENTO IS NULL 
        AND EXISTS (SELECT 1 FROM VND.VW_ELO_AGENDAMENTO_ITEM_ADICAO IIS WHERE IIS.CD_ELO_AGENDAMENTO_ITEM = CT.CD_ELO_AGENDAMENTO_ITEM)) )

UNION 
SELECT STT.NU_CONTRATO_SAP, STT.NU_ORDEM_VENDA
FROM CTE_CONTRATO_PEDIDOS_STATUS STT
UNION 
SELECT DISTINCT CC.NU_CONTRATO_SAP, CC.NU_ORDEM_VENDA--, NU_PROTOCOLO 
FROM VND.ELO_CARTEIRA CC 
INNER JOIN VND.ELO_AGENDAMENTO AGC
ON 
AGC.CD_ELO_AGENDAMENTO = CC.CD_ELO_AGENDAMENTO
WHERE 
CC.NU_PROTOCOLO > 'INICI' || TO_CHAR(CURRENT_DATE-7, 'YYYY-MM-DD')
AND NVL(CC.QT_AGENDADA_CONFIRMADA,0) > 0
AND CC.QT_AGENDADA > 0
and AGC.CD_ELO_STATUS IN (3,4,5,6)
AND NOT(NVL(CC.NU_ORDEM_VENDA, '0') IN ('          ', '0', '0         ' )) 
AND (CC.CD_TIPO_AGENDAMENTO IN (22,23,24) OR (CC.CD_TIPO_AGENDAMENTO = 25 AND CC.CD_STATUS_REPLAN = 32)
        OR (CC.CD_TIPO_AGENDAMENTO IS NULL 
        AND EXISTS (SELECT 1 FROM VND.VW_ELO_AGENDAMENTO_ITEM_ADICAO IIS WHERE IIS.CD_ELO_AGENDAMENTO_ITEM = CC.CD_ELO_AGENDAMENTO_ITEM)) )

UNION 
select CONT.NU_CONTRATO_SAP, CC.NU_ORDEM_VENDA 
from CTE_CONTRATO_TODOS CONT
INNER JOIN VND.ELO_CARTEIRA CC
ON CC.NU_CONTRATO_SAP = CONT.NU_CONTRATO_SAP 
INNER JOIN VND.ELO_AGENDAMENTO AGC
ON 
AGC.CD_ELO_AGENDAMENTO = CC.CD_ELO_AGENDAMENTO
WHERE 
NVL(CC.QT_AGENDADA_CONFIRMADA,0) > 0
AND CC.QT_AGENDADA > 0
and AGC.CD_ELO_STATUS IN (3,4,5,6, 7, 8)
and CC.CD_STATUS_CEL_FINAL = 59 
AND NOT(NVL(CC.NU_ORDEM_VENDA, '0') IN ('          ', '0', '0         ' )) 
AND (CC.CD_TIPO_AGENDAMENTO IN (22,23,24) OR (CC.CD_TIPO_AGENDAMENTO = 25 AND CC.CD_STATUS_REPLAN = 32)
        OR (CC.CD_TIPO_AGENDAMENTO IS NULL 
        AND EXISTS (SELECT 1 FROM VND.VW_ELO_AGENDAMENTO_ITEM_ADICAO IIS WHERE IIS.CD_ELO_AGENDAMENTO_ITEM = CC.CD_ELO_AGENDAMENTO_ITEM)) )

AND CONT.ic_ativo = 'S' AND CONT.CD_STATUS_CONTRATO = '8' 
AND  CONT.dt_fim > current_date -10 AND CONT.IC_SIGNED = 'S' 
AND CONT.IC_SAP_READY = 'S'
AND CONT.CD_SITUACAO_CONTRATO IN (5, 10, 15, 20) 
AND CONT.DH_ULT_INTERFACE < CURRENT_DATE - 30



),




CTE_CONTRATO AS
(
SELECT  
CONT.NU_CONTRATO_SAP, CONT.DH_ULT_INTERFACE
FROM CTE_CONTRATO_TODOS CONT
WHERE 
EXISTS (SELECT 1 FROM  CTE_CONTRATO_PEDIDOS CP 
WHERE CP.NU_CONTRATO_SAP = CONT.NU_CONTRATO_SAP )

UNION 
select CONT.NU_CONTRATO_SAP, CONT.DH_ULT_INTERFACE  
from CTE_CONTRATO_TODOS CONT
where CONT.ic_ativo = 'S' AND CONT.CD_STATUS_CONTRATO = '8' 
AND  CONT.dt_fim > current_date -10 AND CONT.IC_SIGNED = 'S' 
AND CONT.IC_SAP_READY = 'S'
AND CONT.CD_SITUACAO_CONTRATO IN (5, 10, 15, 20) 
AND CONT.DH_ULT_INTERFACE < CURRENT_DATE - 30

),
--SELECT * FROM CTE_CONTRATO 

CTE_CONTRATO_DESATUALIZADO AS
(
SELECT CONT.NU_CONTRATO_SAP, CONT.DH_ULT_INTERFACE
FROM CTE_CONTRATO CONT 
WHERE CONT.DH_ULT_INTERFACE > CURRENT_DATE - 60
),
 
CTE_PEDIDO_TODOS AS 
(
select ov.* from vnd.pedido ov
where 1=1 
--ov.nu_quantidade_saldo > 1
),

CTE_PEDIDO AS
(
SELECT  
CONT.NU_ORDEM_VENDA, CONT.DH_ULT_INTERFACE

FROM CTE_PEDIDO_TODOS CONT
WHERE 
EXISTS (SELECT 1 FROM  CTE_CONTRATO_PEDIDOS CP 
WHERE CP.NU_ORDEM_VENDA = CONT.NU_ORDEM_VENDA )
),
--SELECT * FROM CTE_PEDIDO
CTE_PEDIDO_DESATUALIZADO AS 
(
SELECT CONT.NU_ORDEM_VENDA, CONT.DH_ULT_INTERFACE
FROM CTE_PEDIDO CONT 
WHERE CONT.DH_ULT_INTERFACE > CURRENT_DATE - 15
)
,

 
CTE_QQ_C AS (

SELECT QQ.IC_TIPO, SUBSTR(QQ.NU_CODIGO, 1, 10) NU_CODIGO, DH_ULT_INTERFACE FROM 
(
SELECT  'C' IC_TIPO, GG.NU_ORDEM_VENDA  NU_CODIGO, NVL(CTR.DH_ULT_INTERFACE, CURRENT_DATE) DH_ULT_INTERFACE
FROM CTE_CONTRATO_PEDIDOS GG
LEFT JOIN CTE_PEDIDO CTR
ON GG.NU_ORDEM_VENDA = CTR.NU_ORDEM_VENDA 
WHERE CTR.NU_ORDEM_VENDA IS NULL
--AND (TRIM(NVL(CTR.NU_ORDEM_VENDA, '0')) NOT IN ('0', ' ', '' ))
UNION 
SELECT DISTINCT 'C' IC_TIPO, CC.NU_ORDEM_VENDA  NU_CODIGO,  CURRENT_DATE DH_ULT_INTERFACE
FROM CTE_CONTRATO_PEDIDOS CC
--WHERE (TRIM(NVL(CC.NU_ORDEM_VENDA, '0')) NOT IN ('0', ' ', '' ))
) QQ
) ,
--SELECT * FROM CTE_QQ_C

 
CTE_QQ_G AS (

SELECT QQ.IC_TIPO, SUBSTR(QQ.NU_CODIGO, 1, 10) NU_CODIGO, DH_ULT_INTERFACE FROM 
(
SELECT  'G' IC_TIPO, GG.NU_CONTRATO_SAP NU_CODIGO, NVL(CTR.DH_ULT_INTERFACE, CURRENT_DATE) DH_ULT_INTERFACE
FROM CTE_CONTRATO_PEDIDOS GG
LEFT JOIN CTE_CONTRATO CTR
ON GG.NU_CONTRATO_SAP = CTR.NU_CONTRATO_SAP 
WHERE CTR.NU_CONTRATO_SAP IS NULL 
UNION 
SELECT DISTINCT 'G' IC_TIPO, CC.NU_CONTRATO_SAP  NU_CODIGO,  CURRENT_DATE DH_ULT_INTERFACE
FROM CTE_CONTRATO_PEDIDOS CC
) QQ
)
--SELECT * FROM CTE_QQ_G


SELECT RET.IC_TIPO, RET.NU_CODIGO FROM 
(
SELECT QQ.IC_TIPO, QQ.NU_CODIGO 
FROM CTE_QQ_C QQ
LEFT JOIN CTE_PEDIDO_DESATUALIZADO PED 
ON 
PED.NU_ORDEM_VENDA =QQ.NU_CODIGO
AND QQ.IC_TIPO = 'C'
AND QQ.NU_CODIGO IS NOT NULL WHERE PED.NU_ORDEM_VENDA IS NULL and NVL(PED.DH_ULT_INTERFACE, CURRENT_DATE -1) < TRUNC(CURRENT_DATE)
UNION 
SELECT QQ.IC_TIPO, QQ.NU_CODIGO 
FROM CTE_QQ_G QQ 
LEFT JOIN CTE_CONTRATO_DESATUALIZADO CONTR 
ON 
CONTR.NU_CONTRATO_SAP = QQ.NU_CODIGO
AND QQ.IC_TIPO = 'G'
WHERE CONTR.NU_CONTRATO_SAP IS NULL and NVL(CONTR.DH_ULT_INTERFACE, CURRENT_DATE -1) < TRUNC(CURRENT_DATE)
--FORCAR A INCLUSAO DE CONTRATOS E OV ATIVOS E COM DESATUALIZACAO DE 30 DIAS  
UNION
select DISTINCT 'C' , -- CONT.NU_CONTRATO_SAP
 CC.NU_ORDEM_VENDA 
from CTE_CONTRATO_TODOS CONT
INNER JOIN VND.ELO_CARTEIRA CC
ON CC.NU_CONTRATO_SAP = CONT.NU_CONTRATO_SAP 
INNER JOIN VND.ELO_AGENDAMENTO AGC
ON 
AGC.CD_ELO_AGENDAMENTO = CC.CD_ELO_AGENDAMENTO
WHERE 
NVL(CC.QT_AGENDADA_CONFIRMADA,0) > 0
AND CC.QT_AGENDADA > 0
and AGC.CD_ELO_STATUS IN (3,4,5,6, 7, 8)
and CC.CD_STATUS_CEL_FINAL = 59 
AND NOT(NVL(CC.NU_ORDEM_VENDA, '0') IN ('          ', '0', '0         ' )) 
AND (CC.CD_TIPO_AGENDAMENTO IN (22,23,24) OR (CC.CD_TIPO_AGENDAMENTO = 25 AND CC.CD_STATUS_REPLAN = 32)
        OR (CC.CD_TIPO_AGENDAMENTO IS NULL 
        AND EXISTS (SELECT 1 FROM VND.VW_ELO_AGENDAMENTO_ITEM_ADICAO IIS WHERE IIS.CD_ELO_AGENDAMENTO_ITEM = CC.CD_ELO_AGENDAMENTO_ITEM)) )

AND CONT.ic_ativo = 'S' AND CONT.CD_STATUS_CONTRATO = '8' 
AND  CONT.dt_fim > current_date -10 AND CONT.IC_SIGNED = 'S' 
AND CONT.IC_SAP_READY = 'S'
AND CONT.CD_SITUACAO_CONTRATO IN (5, 10, 15, 20) 
AND CONT.DH_ULT_INTERFACE < CURRENT_DATE - 30 

UNION
select DISTINCT 'G' , CONT.NU_CONTRATO_SAP
 --CC.NU_ORDEM_VENDA 
from CTE_CONTRATO_TODOS CONT
INNER JOIN VND.ELO_CARTEIRA CC
ON CC.NU_CONTRATO_SAP = CONT.NU_CONTRATO_SAP 
INNER JOIN VND.ELO_AGENDAMENTO AGC
ON 
AGC.CD_ELO_AGENDAMENTO = CC.CD_ELO_AGENDAMENTO
WHERE 
NVL(CC.QT_AGENDADA_CONFIRMADA,0) > 0
AND CC.QT_AGENDADA > 0
and AGC.CD_ELO_STATUS IN (3,4,5,6, 7, 8)
and CC.CD_STATUS_CEL_FINAL = 59 
AND NOT(NVL(CC.NU_ORDEM_VENDA, '0') IN ('          ', '0', '0         ' )) 
AND (CC.CD_TIPO_AGENDAMENTO IN (22,23,24) OR (CC.CD_TIPO_AGENDAMENTO = 25 AND CC.CD_STATUS_REPLAN = 32)
        OR (CC.CD_TIPO_AGENDAMENTO IS NULL 
        AND EXISTS (SELECT 1 FROM VND.VW_ELO_AGENDAMENTO_ITEM_ADICAO IIS WHERE IIS.CD_ELO_AGENDAMENTO_ITEM = CC.CD_ELO_AGENDAMENTO_ITEM)) )

AND CONT.ic_ativo = 'S' AND CONT.CD_STATUS_CONTRATO = '8' 
AND  CONT.dt_fim > current_date -10 AND CONT.IC_SIGNED = 'S' 
AND CONT.IC_SAP_READY = 'S'
AND CONT.CD_SITUACAO_CONTRATO IN (5, 10, 15, 20) 
AND CONT.DH_ULT_INTERFACE < CURRENT_DATE - 30 

UNION

select DISTINCT 'G' , CONT.NU_CONTRATO_SAP
 --CC.NU_ORDEM_VENDA 
from CTE_CONTRATO_TODOS CONT
INNER JOIN 
(SELECT HIS.* FROM VND.ELO_CARTEIRA_hist HIS 
INNER JOIN (
    SELECT MAXID.CD_ELO_CARTEIRA, MAX(MAXID.ID) ID 
    FROM VND.ELO_CARTEIRA_HIST MAXID GROUP BY MAXID.CD_ELO_CARTEIRA 
    )
 MAXD ON HIS.ID = HIS.ID)    
  CC
ON CC.NU_CONTRATO_SAP = CONT.NU_CONTRATO_SAP 
INNER JOIN VND.ELO_AGENDAMENTO AGC
ON 
AGC.CD_ELO_AGENDAMENTO = CC.CD_ELO_AGENDAMENTO
WHERE 
NVL(CC.QT_AGENDADA_CONFIRMADA,0) > 0
--AND CC.QT_AGENDADA > 0
and AGC.CD_ELO_STATUS IN (1,2, 3,4,5,6, 7)
--and CC.CD_STATUS_CEL_FINAL = 59 
AND NOT(NVL(CC.NU_ORDEM_VENDA, '0') IN ('          ', '0', '0         ' )) 
AND (CC.CD_TIPO_AGENDAMENTO IN (22,23,24) OR (CC.CD_TIPO_AGENDAMENTO = 25 AND CC.CD_STATUS_REPLAN = 32)
        OR (CC.CD_TIPO_AGENDAMENTO IS NULL 
        AND EXISTS (SELECT 1 FROM VND.VW_ELO_AGENDAMENTO_ITEM_ADICAO IIS WHERE IIS.CD_ELO_AGENDAMENTO_ITEM = CC.CD_ELO_AGENDAMENTO_ITEM)) )

AND CONT.ic_ativo = 'S' AND CONT.CD_STATUS_CONTRATO = '8' 
AND  CONT.dt_fim > current_date -7 AND CONT.IC_SIGNED = 'S' 
AND CONT.IC_SAP_READY = 'S'
AND (CC.DH_ULT_ALTERACAO < CURRENT_DATE - 2 OR CC.DH_ULT_INTERFACE_CONTRATO < CURRENT_DATE - 2 OR CC.DH_ULT_INTERFACE_OV < CURRENT_DATE -2)
--AND CONT.CD_SITUACAO_CONTRATO IN (5, 10, 15, 20) 
AND CONT.DH_ULT_INTERFACE < CURRENT_DATE - 15 
UNION

select DISTINCT 'C' , CONT.NU_ORDEM_VENDA
 --CC.NU_ORDEM_VENDA 
from CTE_PEDIDO_TODOS CONT
INNER JOIN 
(SELECT HIS.* FROM VND.ELO_CARTEIRA_hist HIS 
INNER JOIN (
    SELECT MAXID.CD_ELO_CARTEIRA, MAX(MAXID.ID) ID 
    FROM VND.ELO_CARTEIRA_HIST MAXID GROUP BY MAXID.CD_ELO_CARTEIRA 
    )
 MAXD ON HIS.ID = HIS.ID)    
  CC
ON CC.NU_ORDEM_VENDA = CONT.NU_ORDEM_VENDA 
INNER JOIN VND.ELO_AGENDAMENTO AGC
ON 
AGC.CD_ELO_AGENDAMENTO = CC.CD_ELO_AGENDAMENTO
WHERE 
NVL(CC.QT_AGENDADA_CONFIRMADA,0) > 0
--AND CC.QT_AGENDADA > 0
and AGC.CD_ELO_STATUS IN (1,2, 3,4,5,6, 7)
--and CC.CD_STATUS_CEL_FINAL = 59 
AND NOT(NVL(CC.NU_ORDEM_VENDA, '0') IN ('          ', '0', '0         ' )) 
AND (CC.CD_TIPO_AGENDAMENTO IN (22,23,24) OR (CC.CD_TIPO_AGENDAMENTO = 25 AND CC.CD_STATUS_REPLAN = 32)
        OR (CC.CD_TIPO_AGENDAMENTO IS NULL 
        AND EXISTS (SELECT 1 FROM VND.VW_ELO_AGENDAMENTO_ITEM_ADICAO IIS WHERE IIS.CD_ELO_AGENDAMENTO_ITEM = CC.CD_ELO_AGENDAMENTO_ITEM)) )

--AND CONT.ic_ativo = 'S' AND CONT.CD_STATUS_CONTRATO = '8' 
--AND  CONT.dt_fim > current_date -7 AND CONT.IC_SIGNED = 'S' 
--AND CONT.IC_SAP_READY = 'S'
AND CONT.NU_QUANTIDADE_SALDO > 0
AND (CC.DH_ULT_ALTERACAO < CURRENT_DATE - 2 OR CC.DH_ULT_INTERFACE_CONTRATO < CURRENT_DATE - 2 OR CC.DH_ULT_INTERFACE_OV < CURRENT_DATE -2)
--AND CONT.CD_SITUACAO_CONTRATO IN (5, 10, 15, 20) 
AND CONT.DH_ULT_INTERFACE < CURRENT_DATE - 15 

UNION 


select distinct 'C' IC_TIPO, sap.nu_ordem_venda from vnd.elo_carteira_sap sap
inner join 
(select (cc.nu_carteira_version) nu_carteira_version 
    from vnd.elo_carteira_sap cc where dh_carteira > current_date - 60 group by cc.nu_carteira_version) maxcc
     on maxcc.nu_carteira_version = sap.nu_carteira_version
left join CTE_PEDIDO_TODOS ov on sap.nu_ordem_venda = ov.nu_ordem_venda 
where 
1=1
--sap.nu_carteira_version = '20180724213016'
and NOT(NVL(sap.NU_ORDEM_VENDA, '0') IN ('          ', '0', '0         ' ))
and ov.cd_produto_sap is null

UNION 

select distinct 'G' IC_TIPO, sap.NU_CONTRATO_SAP from vnd.elo_carteira_sap sap
inner join 
(select (cc.nu_carteira_version) nu_carteira_version 
    from vnd.elo_carteira_sap cc where dh_carteira > current_date - 60 group by cc.nu_carteira_version) maxcc
     on maxcc.nu_carteira_version = sap.nu_carteira_version
left join CTE_CONTRATO_TODOS ov on sap.NU_CONTRATO_SAP = ov.NU_CONTRATO_SAP 
where 
1=1
--sap.nu_carteira_version = '20180724213016'
and ov.CD_CONTRATO is null


) RET
WHERE 
NOT EXISTS (SELECT 1 FROM VND.INTERFACE TR
WHERE SUBSTR(TR.NU_CODIGO, 1,10) = RET.NU_CODIGO
AND TR.DH_EXECUCAO > CURRENT_DATE - 15) 

;


SELECT * FROM VND.PEDIDO 
WHERE NU_ORDEM_VENDA = '0002375981';

SELECT * FROM VND.INTERFACE 
WHERE NU_CODIGO LIKE '%2375981%';


SELECT * FROM VND.SITUACAO_PEDIDO;


SELECT * FROM VND.ELO_CARTEIRA_SAP
WHERE NU_ORDEM_VENDA = '0002375981';

SELECT * FROM VND.ELO_CARTEIRA
WHERE NU_ORDEM_VENDA = '0002375981';

WITH CTE_PEDIDO AS 
(
SELECT NU_CARTEIRA_VERSION CV , NU_ORDEM_VENDA OV
FROM VND.ELO_CARTEIRA_SAP 
GROUP BY NU_CARTEIRA_VERSION, NU_ORDEM_VENDA
HAVING COUNT(1) > 1 

),
CTE_WHOPEDID AS (
SELECT NU_CARTEIRA_VERSION, NU_ORDEM_VENDA, COUNT(1) QT, CD_CENTRO_EXPEDIDOR, DS_CENTRO_EXPEDIDOR,
DS_STATUS_CONTRATO_SAP, TRUNC(DH_CARTEIRA, 'YEAR') YYYY, TRUNC(DH_CARTEIRA, 'MONTH') MM,
DS_SEGMENTO_CLIENTE_SAP, DS_TIPO_PAGAMENTO, 
DS_CREDIT_BLOCK_REASON , cd_SUPPLY_GROUP, DS_VENDA_COMPARTILHADA
FROM VND.ELO_CARTEIRA_SAP SS 
inner join CTE_PEDIDO DD on DD.CV = SS.NU_CARTEIRA_VERSION AND DD.OV = SS.NU_ORDEM_VENDA

GROUP BY DS_STATUS_CONTRATO_SAP,TRUNC(DH_CARTEIRA, 'YEAR') , TRUNC(DH_CARTEIRA, 'MONTH') ,
DS_SEGMENTO_CLIENTE_SAP, DS_TIPO_PAGAMENTO, 
DS_CREDIT_BLOCK_REASON , 
cd_SUPPLY_GROUP, DS_VENDA_COMPARTILHADA, NU_CARTEIRA_VERSION, NU_ORDEM_VENDA,
CD_CENTRO_EXPEDIDOR, DS_CENTRO_EXPEDIDOR
)

SELECT 
PED.NU_CARTEIRA_VERSION, PED.NU_ORDEM_VENDA, PED.QT, PED.CD_CENTRO_EXPEDIDOR, PED.DS_CENTRO_EXPEDIDOR,
PED.DS_STATUS_CONTRATO_SAP,  PED.YYYY, PED.MM,
PED.DS_SEGMENTO_CLIENTE_SAP, PED.DS_TIPO_PAGAMENTO, 
PED.DS_CREDIT_BLOCK_REASON , PED.cd_SUPPLY_GROUP, PED.DS_VENDA_COMPARTILHADA
FROM CTE_WHOPEDID PED
INNER JOIN (

SELECT DU.NU_CARTEIRA_VERSION , DU.NU_ORDEM_VENDA 
FROM CTE_WHOPEDID DU
GROUP BY DU.NU_CARTEIRA_VERSION , DU.NU_ORDEM_VENDA
HAVING COUNT(1) > 1

) DUPLI 
ON DUPLI.NU_CARTEIRA_VERSION =  PED.NU_CARTEIRA_VERSION AND DUPLI.NU_ORDEM_VENDA = PED.NU_ORDEM_VENDA

ORDER BY PED.NU_CARTEIRA_VERSION, PED.NU_ORDEM_VENDA, PED.YYYY , PED.MM

;


SELECT * FROM VND.ELO_CARTEIRA_SAP 
WHERE 
--DS_TIPO_PAGAMENTO= 'CRA:  Agribusiness A/R Certificate' 
NU_CARTEIRA_VERSION = '20180722213005' AND NU_ORDEM_VENDA = '0002364620';

20180407020010	0002303812









