
DECLARE 

CURSOR C_WHO_UPDATE IS 
WITH AGENDAMENTO AS 
(

SELECT AGE.CD_ELO_AGENDAMENTO, AGE.CD_WEEK, AGE.CD_POLO, AGE.CD_MACHINE, AGE.CD_CENTRO_EXPEDIDOR, 
AGE.CD_ELO_STATUS
FROM VND.ELO_AGENDAMENTO AGE
WHERE 
AGE.IC_ATIVO = 'S'

AND AGE.CD_ELO_STATUS IN (1,2,3,4,5,6,70,80 )  --2 PASSO SEM ERRO STATUS 59 
),
--select * from AGENDAMENTO

CTE_CONTRATO_PEDIDOS_STATUS AS 
(
SELECT DISTINCT 
CT.NU_CONTRATO_SAP, 
CT.NU_ORDEM_VENDA

FROM VND.ELO_CARTEIRA CT
INNER JOIN AGENDAMENTO AG
ON 
AG.CD_ELO_AGENDAMENTO = CT.CD_ELO_AGENDAMENTO
WHERE 
CT.IC_ATIVO = 'S'

AND NVL(CT.QT_AGENDADA_CONFIRMADA,0) >= 0
AND NVL(CT.QT_AGENDADA,0) >= 0
AND NVL(CT.CD_STATUS_CEL_FINAL, 40) NOT IN (40, 41, 59, 57, 58 )
AND CT.CD_MOTIVO_RECUSA IS NULL
and AG.CD_ELO_STATUS IN (3,4,5,6)
AND NOT(NVL(CT.NU_ORDEM_VENDA, '0') IN ('          ', '0', '0         ' )) 
AND (CT.CD_TIPO_AGENDAMENTO IN (22,23,24) 
        OR (CT.CD_TIPO_AGENDAMENTO = 25 AND CT.CD_STATUS_REPLAN = 32) 
        OR (CT.CD_TIPO_AGENDAMENTO IS NULL 
        AND EXISTS (SELECT 1 FROM VND.VW_ELO_AGENDAMENTO_ITEM_ADICAO IIS WHERE IIS.CD_ELO_AGENDAMENTO_ITEM = CT.CD_ELO_AGENDAMENTO_ITEM)) )

),
--SELECT DISTINCT GD.NU_CONTRATO_SAP, CTR.DH_ULT_INTERFACE FROM CTE_CONTRATO_PEDIDOS GD
--INNER JOIN VND.CONTRATO CTR ON GD.NU_CONTRATO_SAP = CTR.NU_CONTRATO_SAP
--SELECT DISTINCT GD.NU_ORDEM_VENDA, CTR.DH_ULT_INTERFACE FROM CTE_CONTRATO_PEDIDOS GD
--INNER JOIN VND.PEDIDO CTR ON GD.NU_ORDEM_VENDA = CTR.NU_ORDEM_VENDA

CTE_CONTRATO_TODOS AS 
(

SELECT FORA.* FROM (

SELECT CONT.CD_CONTRATO,        CONT.NU_CONTRATO,        CONT.CD_STATUS_CONTRATO,
       CONT.CD_CLIENTE_CONTRATO,       -- CONT.CD_CLIENTE_EMISSOR,        CONT.CD_TIPO_ORDEM,
       CONT.CD_CENTRO_EXPEDIDOR,        --CONT.CD_USUARIO_VENDA,        CONT.CD_AGENTE_VENDA,
      -- CONT.CD_USUARIO_INCLUSAO,        CONT.DH_INCLUSAO,        CONT.DH_GERACAO,
     --  CONT.DH_IMPRESSAO,        CONT.DH_ASSINATURA,        CONT.DH_ENVIO_ADVEN,
     --  CONT.DH_ENVIO_SAP,        CONT.DH_PROCESSAMENTO,        CONT.DT_PAGAMENTO,
    --   CONT.DS_FORMA_PAGAMENTO,        CONT.DS_COND_ESP_PAGTO,       
     CONT.DT_INICIO,        CONT.DT_FIM,  
       --      CONT.VL_FRETE_DISTRIBUICAO,       
       CONT.IC_ATIVO,
    --   CONT.CD_MOTIVO_ORDEM,        CONT.IC_ALTERA_SUBSTITUI,        CONT.DH_LISTA_PRECO,
       CONT.CD_INCOTERMS,       
       -- CONT.DS_GARANTIAS,        CONT.DH_PRAZO_GARANTIA,
     --  CONT.VL_FACIL,        
       CONT.CD_SALES_ORG,        CONT.CD_DISTRIBUTION_CHANNEL,
       CONT.CD_SALES_DIVISION,        --CONT.IC_NEW_PRODUCT,        CONT.IC_NEW_CUSTOMER,
       CONT.IC_SIGNED,       
        CONT.IC_SAP_READY,        CONT.DH_NEW_PRODUCT,
       --CONT.DH_NEW_CUSTOMER,        CONT.DH_SAP_READY,        CONT.DH_EMAIL_MASTERDATA,
       --CONT.DH_EMAIL_ADVEN,      
        CONT.NU_CONTRATO_SAP,       -- CONT.CD_TIPO_CONTRATO,
       --CONT.DH_CANCELAMENTO,        CONT.CD_USUARIO_CANCELAMENTO,       
        CONT.DH_ULT_INTERFACE,
       CONT.CD_BLOCKING_REASON,        CONT.CD_SITUACAO_CONTRATO,       -- CONT.CD_FORMA_PAGAMENTO,
      -- CONT.IC_SAP,        CONT.CD_STATUS_CONTRATO_SAP,        CONT.CD_USUARIO_RECEBIMENTO,
      -- CONT.DH_RECEBIMENTO,        CONT.IC_RECEBIDO,        CONT.DH_ULT_ALTERACAO,
     --  CONT.IC_ORIGEM_CONTRATO,        CONT.CD_TIPO_PAGAMENTO,        CONT.CD_CLIENTE_PO_NUMERO,
     --  CONT.DH_ENVIO_ASSINATURA,        CONT.DH_REENVIO_ASSINATURA,       CONT.CD_USUARIO_APROVACAO_CLIENTE,
     --  CONT.CD_USUARIO_REJEICAO_CLIENTE,        CONT.CD_USUARIO_REJEICAO_SUPERVISOR,
     --  CONT.DH_APROVACAO_CLIENTE,        CONT.DH_REJEICAO_CLIENTE,        CONT.DH_REJEICAO_SUPERVISOR,
     --  CONT.IC_ASSINATURA_ELETRONICA,        CONT.CD_USUARIO_APROVACAO_SUPERV,
     --  CONT.DH_APROVACAO_SUPERVISOR,       
        CONT.CD_BLOQUEIO_CREDITO,        CONT.CD_BLOQUEIO_ENTREGA,
       CONT.CD_BLOQUEIO_FATURAMENTO,        CONT.CD_BLOQUEIO_REMESSA,        CONT.DS_CREDIT_BLOCK_REASON
  FROM VND.CONTRATO CONT
 WHERE CONT.IC_ATIVO = 'S'
and exists (select 1 
            from vnd.item_contrato ic 
            where ic.cd_contrato = cont.cd_contrato 
            and nvl(ic.NU_QUANTIDADE,0) - nvl(ic.NU_QTY_DELIVERED,0) > 1)  
AND  CONT.CD_STATUS_CONTRATO = '8' 
AND CONT.CD_SITUACAO_CONTRATO IN (5, 10, 15, 20) 
and cont.dt_fim > current_date -365  
) fora
WHERE fora.DH_ULT_INTERFACE > current_date -15  

 
) ,
--SELECT * FROM CTE_CONTRATO_TODOS


CTE_CONTRATO_PEDIDOS AS 
(
SELECT DISTINCT 
CT.NU_CONTRATO_SAP, 
CT.NU_ORDEM_VENDA

FROM VND.ELO_CARTEIRA CT
INNER JOIN AGENDAMENTO AG
ON 
AG.CD_ELO_AGENDAMENTO = CT.CD_ELO_AGENDAMENTO
WHERE 
CT.IC_ATIVO = 'S'
AND AG.CD_ELO_STATUS IN (3,4,5)

AND NVL(CT.QT_AGENDADA_CONFIRMADA,0) > 0
AND NVL(CT.QT_AGENDADA,0) >= 0
AND NVL(CT.CD_STATUS_CEL_FINAL, 62)  IN ( 59)
AND CT.CD_MOTIVO_RECUSA IS NULL
and AG.CD_ELO_STATUS IN (3,4,5,6)
AND NOT(NVL(CT.NU_ORDEM_VENDA, '0') IN ('          ', '0', '0         ' )) 
AND (CT.CD_TIPO_AGENDAMENTO IN (22,23,24) OR (CT.CD_TIPO_AGENDAMENTO = 25 AND CT.CD_STATUS_REPLAN = 32)
        OR (CT.CD_TIPO_AGENDAMENTO IS NULL 
        AND EXISTS (SELECT 1 FROM VND.VW_ELO_AGENDAMENTO_ITEM_ADICAO IIS WHERE IIS.CD_ELO_AGENDAMENTO_ITEM = CT.CD_ELO_AGENDAMENTO_ITEM)) )

UNION 
SELECT STT.NU_CONTRATO_SAP, STT.NU_ORDEM_VENDA
FROM CTE_CONTRATO_PEDIDOS_STATUS STT
UNION 
SELECT DISTINCT CC.NU_CONTRATO_SAP, CC.NU_ORDEM_VENDA--, NU_PROTOCOLO 
FROM VND.ELO_CARTEIRA CC 
INNER JOIN AGENDAMENTO AGC
ON 
AGC.CD_ELO_AGENDAMENTO = CC.CD_ELO_AGENDAMENTO
WHERE 
CC.NU_PROTOCOLO > 'INICI' || TO_CHAR(CURRENT_DATE-7, 'YYYY-MM-DD')
AND NVL(CC.QT_AGENDADA_CONFIRMADA,0) > 0
AND NVL(CC.QT_AGENDADA,0) >= 0
and AGC.CD_ELO_STATUS IN (3,4,5,6)
AND NOT(NVL(CC.NU_ORDEM_VENDA, '0') IN ('          ', '0', '0         ' )) 
AND (CC.CD_TIPO_AGENDAMENTO IN (22,23,24) OR (CC.CD_TIPO_AGENDAMENTO = 25 AND CC.CD_STATUS_REPLAN = 32)
        OR (CC.CD_TIPO_AGENDAMENTO IS NULL 
        AND EXISTS (SELECT 1 FROM VND.VW_ELO_AGENDAMENTO_ITEM_ADICAO IIS WHERE IIS.CD_ELO_AGENDAMENTO_ITEM = CC.CD_ELO_AGENDAMENTO_ITEM)) )

UNION 
select CONT.NU_CONTRATO_SAP, CC.NU_ORDEM_VENDA 
from CTE_CONTRATO_TODOS CONT
INNER JOIN VND.ELO_CARTEIRA CC
ON CC.NU_CONTRATO_SAP = CONT.NU_CONTRATO_SAP 
INNER JOIN AGENDAMENTO AGC
ON 
AGC.CD_ELO_AGENDAMENTO = CC.CD_ELO_AGENDAMENTO
WHERE 
NVL(CC.QT_AGENDADA_CONFIRMADA,0) > 0
AND NVL(CC.QT_AGENDADA,0) >= 0
and AGC.CD_ELO_STATUS IN (3,4,5,6, 7, 8)
and CC.CD_STATUS_CEL_FINAL = 59 
AND NOT(NVL(CC.NU_ORDEM_VENDA, '0') IN ('          ', '0', '0         ' )) 
AND (CC.CD_TIPO_AGENDAMENTO IN (22,23,24) OR (CC.CD_TIPO_AGENDAMENTO = 25 AND CC.CD_STATUS_REPLAN = 32)
        OR (CC.CD_TIPO_AGENDAMENTO IS NULL 
        AND EXISTS (SELECT 1 FROM VND.VW_ELO_AGENDAMENTO_ITEM_ADICAO IIS WHERE IIS.CD_ELO_AGENDAMENTO_ITEM = CC.CD_ELO_AGENDAMENTO_ITEM)) )
 

) ,
--SELECT * FROM CTE_CONTRATO_PEDIDOS



CTE_CONTRATO AS
(
SELECT  
CONT.NU_CONTRATO_SAP, CONT.DH_ULT_INTERFACE
FROM CTE_CONTRATO_TODOS CONT
WHERE 
EXISTS (SELECT 1 FROM  CTE_CONTRATO_PEDIDOS CP 
WHERE CP.NU_CONTRATO_SAP = CONT.NU_CONTRATO_SAP )

UNION 
select CONT.NU_CONTRATO_SAP, CONT.DH_ULT_INTERFACE  
from CTE_CONTRATO_TODOS CONT
where CONT.ic_ativo = 'S' 

),
--SELECT * FROM CTE_CONTRATO 

CTE_CONTRATO_DESATUALIZADO AS
(
SELECT CONT.NU_CONTRATO_SAP, CONT.DH_ULT_INTERFACE
FROM CTE_CONTRATO CONT 
WHERE CONT.DH_ULT_INTERFACE > CURRENT_DATE - 60
),
 
CTE_PEDIDO_TODOS AS 
(

SELECT FORAOV.* FROM (

SELECT OV.CD_PEDIDO,        OV.CD_ITEM_PEDIDO,        OV.CD_CONTRATO,
       OV.CD_SITUACAO_PEDIDO,        OV.CD_CLIENTE_RECEBEDOR,       OV.CD_CLIENTE_PAGADOR, 
       OV.CD_PRODUTO_SAP,        OV.DS_PRODUTO_SAP,
       OV.CD_CLIENTE_EMISSOR,        OV.CD_CENTRO_EXPEDIDOR,
       OV.NU_ORDEM_VENDA,        OV.DH_PEDIDO,       OV.CD_INCOTERMS,        OV.NU_QUANTIDADE,
       OV.NU_QUANTIDADE_SALDO,        OV.CD_TIPO_ORDEM,       OV.IC_CANCELAMENTO,
       OV.DH_CANCELAMENTO, 
              --OV.DS_ROTEIRO_ENTREGA,
       OV.CD_BLOQUEIO_REMESSA,        OV.CD_BLOQUEIO_FATURAMENTO,        OV.CD_BLOQUEIO_CREDITO,
       OV.CD_MOTIVO_RECUSA,        OV.CD_SACARIA,        OV.DH_ULT_ALTERACAO,        OV.DH_INCLUSAO,
       OV.CD_MOTIVO_BLOQUEIO_CREDITO,        OV.DH_ULT_INTERFACE,        OV.NU_CONTRATO,
       OV.NU_CONTRATO_SAP,        OV.NU_QUANTIDADE_ENTREGUE,        OV.CD_ITEM_CONTRATO,
       OV.CD_BLOQUEIO_ENTREGA,        OV.CD_BLOQUEIO_FATURAMENTO_ITEM,
       OV.CD_BLOQUEIO_REMESSA_ITEM,        OV.DS_CREDIT_BLOCK_REASON,
       OV.CD_MOTIVO_ORDEM
  FROM VND.PEDIDO OV

where 1=1 
and ov.CD_SITUACAO_PEDIDO in (5, 10,15,20,25) 
AND ov.NU_QUANTIDADE_SALDO > 1 
and TRUNC(NVL(OV.dh_entrega, CURRENT_DATE), 'YEAR') > trunc(current_date - 400, 'YEAR')
) FORAOV
WHERE FORAOV.DH_ULT_INTERFACE < CURRENT_DATE - 15
--ov.nu_quantidade_saldo > 1
--5	Comercial
--10	Crédito
--15	Cobrança
--20	Liberado
--25	Finalizado
--30	Recusado/Cancelado
--99	Verificar erro status
--35	Bloqueio de Material
--90	Pedido Excluido no SAP

),
--SELECT * FROM CTE_PEDIDO_TODOS

CTE_PEDIDO AS
(
SELECT  
CONT.NU_ORDEM_VENDA, CONT.DH_ULT_INTERFACE

FROM CTE_PEDIDO_TODOS CONT
WHERE 
EXISTS (SELECT 1 FROM  CTE_CONTRATO_PEDIDOS CP 
WHERE CP.NU_ORDEM_VENDA = CONT.NU_ORDEM_VENDA )
),
--SELECT * FROM CTE_PEDIDO
CTE_PEDIDO_DESATUALIZADO AS 
(
SELECT CONT.NU_ORDEM_VENDA, CONT.DH_ULT_INTERFACE
FROM CTE_PEDIDO CONT 
WHERE CONT.DH_ULT_INTERFACE > CURRENT_DATE - 15
) ,

--SELECT * FROM CTE_PEDIDO_DESATUALIZADO
 
CTE_QQ_C AS (

SELECT QQ.IC_TIPO, SUBSTR(QQ.NU_CODIGO, 1, 10) NU_CODIGO, DH_ULT_INTERFACE FROM 
(
SELECT  'C' IC_TIPO, GG.NU_ORDEM_VENDA  NU_CODIGO, NVL(CTR.DH_ULT_INTERFACE, CURRENT_DATE) DH_ULT_INTERFACE
FROM CTE_CONTRATO_PEDIDOS GG
LEFT JOIN CTE_PEDIDO CTR
ON GG.NU_ORDEM_VENDA = CTR.NU_ORDEM_VENDA 
WHERE CTR.NU_ORDEM_VENDA IS NULL
--AND (TRIM(NVL(CTR.NU_ORDEM_VENDA, '0')) NOT IN ('0', ' ', '' ))
UNION 
SELECT DISTINCT 'C' IC_TIPO, CC.NU_ORDEM_VENDA  NU_CODIGO,  CURRENT_DATE DH_ULT_INTERFACE
FROM CTE_CONTRATO_PEDIDOS CC
--WHERE (TRIM(NVL(CC.NU_ORDEM_VENDA, '0')) NOT IN ('0', ' ', '' ))
) QQ
) ,
--SELECT * FROM CTE_QQ_C

 
CTE_QQ_G AS (

SELECT QQ.IC_TIPO, SUBSTR(QQ.NU_CODIGO, 1, 10) NU_CODIGO, DH_ULT_INTERFACE FROM 
(
SELECT  'G' IC_TIPO, GG.NU_CONTRATO_SAP NU_CODIGO, NVL(CTR.DH_ULT_INTERFACE, CURRENT_DATE) DH_ULT_INTERFACE
FROM CTE_CONTRATO_PEDIDOS GG
LEFT JOIN CTE_CONTRATO CTR
ON GG.NU_CONTRATO_SAP = CTR.NU_CONTRATO_SAP 
WHERE CTR.NU_CONTRATO_SAP IS NULL 
UNION 
SELECT DISTINCT 'G' IC_TIPO, CC.NU_CONTRATO_SAP  NU_CODIGO,  CURRENT_DATE DH_ULT_INTERFACE
FROM CTE_CONTRATO_PEDIDOS CC
) QQ
)
--SELECT * FROM CTE_QQ_G


SELECT RET.IC_TIPO, RET.NU_CODIGO FROM 
(
SELECT QQ.IC_TIPO, QQ.NU_CODIGO 
FROM CTE_QQ_C QQ
LEFT JOIN CTE_PEDIDO_DESATUALIZADO PED 
ON 
PED.NU_ORDEM_VENDA =QQ.NU_CODIGO
AND QQ.IC_TIPO = 'C'
AND QQ.NU_CODIGO IS NOT NULL WHERE PED.NU_ORDEM_VENDA IS NULL and NVL(PED.DH_ULT_INTERFACE, CURRENT_DATE -1) < TRUNC(CURRENT_DATE)
UNION 
SELECT QQ.IC_TIPO, QQ.NU_CODIGO 
FROM CTE_QQ_G QQ 
LEFT JOIN CTE_CONTRATO_DESATUALIZADO CONTR 
ON 
CONTR.NU_CONTRATO_SAP = QQ.NU_CODIGO
AND QQ.IC_TIPO = 'G'
WHERE CONTR.NU_CONTRATO_SAP IS NULL and NVL(CONTR.DH_ULT_INTERFACE, CURRENT_DATE -1) < TRUNC(CURRENT_DATE)
--FORCAR A INCLUSAO DE CONTRATOS E OV ATIVOS E COM DESATUALIZACAO DE 30 DIAS  
UNION
select DISTINCT 'C' , -- CONT.NU_CONTRATO_SAP
 CC.NU_ORDEM_VENDA 
from CTE_CONTRATO_TODOS CONT
INNER JOIN VND.ELO_CARTEIRA CC
ON CC.NU_CONTRATO_SAP = CONT.NU_CONTRATO_SAP 
INNER JOIN AGENDAMENTO AGC
ON 
AGC.CD_ELO_AGENDAMENTO = CC.CD_ELO_AGENDAMENTO
WHERE 
NVL(CC.QT_AGENDADA_CONFIRMADA,0) > 0
AND NVL(CC.QT_AGENDADA,0) >= 0
and AGC.CD_ELO_STATUS IN (3,4,5,6, 7, 8)
and CC.CD_STATUS_CEL_FINAL = 59 
AND NOT(NVL(CC.NU_ORDEM_VENDA, '0') IN ('          ', '0', '0         ' )) 
AND (CC.CD_TIPO_AGENDAMENTO IN (22,23,24) OR (CC.CD_TIPO_AGENDAMENTO = 25 AND CC.CD_STATUS_REPLAN = 32)
        OR (CC.CD_TIPO_AGENDAMENTO IS NULL 
        AND EXISTS (SELECT 1 FROM VND.VW_ELO_AGENDAMENTO_ITEM_ADICAO IIS WHERE IIS.CD_ELO_AGENDAMENTO_ITEM = CC.CD_ELO_AGENDAMENTO_ITEM)) )

AND CONT.ic_ativo = 'S' 

UNION
select DISTINCT 'G' , CONT.NU_CONTRATO_SAP
 --CC.NU_ORDEM_VENDA 
from CTE_CONTRATO_TODOS CONT
INNER JOIN VND.ELO_CARTEIRA CC
ON CC.NU_CONTRATO_SAP = CONT.NU_CONTRATO_SAP 
INNER JOIN AGENDAMENTO AGC
ON 
AGC.CD_ELO_AGENDAMENTO = CC.CD_ELO_AGENDAMENTO
WHERE 
NVL(CC.QT_AGENDADA_CONFIRMADA,0) > 0
AND NVL(CC.QT_AGENDADA,0) >= 0
and AGC.CD_ELO_STATUS IN (3,4,5,6, 7, 8)
and CC.CD_STATUS_CEL_FINAL = 59 
AND NOT(NVL(CC.NU_ORDEM_VENDA, '0') IN ('          ', '0', '0         ' )) 
AND (CC.CD_TIPO_AGENDAMENTO IN (22,23,24) OR (CC.CD_TIPO_AGENDAMENTO = 25 AND CC.CD_STATUS_REPLAN = 32)
        OR (CC.CD_TIPO_AGENDAMENTO IS NULL 
        AND EXISTS (SELECT 1 FROM VND.VW_ELO_AGENDAMENTO_ITEM_ADICAO IIS WHERE IIS.CD_ELO_AGENDAMENTO_ITEM = CC.CD_ELO_AGENDAMENTO_ITEM)) )

AND CONT.ic_ativo = 'S' 

UNION

select DISTINCT 'G' , CONT.NU_CONTRATO_SAP
 --CC.NU_ORDEM_VENDA 
from CTE_CONTRATO_TODOS CONT
INNER JOIN 
(SELECT HIS.ID, HIS.NU_CONTRATO_SAP, HIS.CD_ELO_AGENDAMENTO ,
HIS.DH_ULT_INTERFACE_OV, HIS.DH_ULT_INTERFACE_CONTRATO, 
HIS.DH_ULT_ALTERACAO, HIS.CD_TIPO_AGENDAMENTO, 
HIS.CD_STATUS_REPLAN, HIS.CD_ELO_AGENDAMENTO_ITEM, HIS.NU_ORDEM_VENDA,
HIS.QT_AGENDADA_CONFIRMADA

FROM VND.ELO_CARTEIRA_hist HIS 
INNER JOIN (
    SELECT MAXID.CD_ELO_CARTEIRA, MAX(MAXID.ID) ID 
    FROM VND.ELO_CARTEIRA_HIST MAXID GROUP BY MAXID.CD_ELO_CARTEIRA 
    )
 MAXD ON MAXD.ID = HIS.ID)    
  CC
ON CC.NU_CONTRATO_SAP = CONT.NU_CONTRATO_SAP 
INNER JOIN AGENDAMENTO AGC
ON 
AGC.CD_ELO_AGENDAMENTO = CC.CD_ELO_AGENDAMENTO
WHERE 
NVL(CC.QT_AGENDADA_CONFIRMADA,0) > 0
--AND CC.QT_AGENDADA > 0
and AGC.CD_ELO_STATUS IN (1,2, 3,4,5,6, 7)
--and CC.CD_STATUS_CEL_FINAL = 59 
AND NOT(NVL(CC.NU_ORDEM_VENDA, '0') IN ('          ', '0', '0         ' )) 
AND (CC.CD_TIPO_AGENDAMENTO IN (22,23,24) OR (CC.CD_TIPO_AGENDAMENTO = 25 AND CC.CD_STATUS_REPLAN = 32)
        OR (CC.CD_TIPO_AGENDAMENTO IS NULL 
        AND EXISTS (SELECT 1 FROM VND.VW_ELO_AGENDAMENTO_ITEM_ADICAO IIS WHERE IIS.CD_ELO_AGENDAMENTO_ITEM = CC.CD_ELO_AGENDAMENTO_ITEM)) )

AND CONT.ic_ativo = 'S' 
AND (CC.DH_ULT_ALTERACAO < CURRENT_DATE - 2 OR CC.DH_ULT_INTERFACE_CONTRATO < CURRENT_DATE - 2 OR CC.DH_ULT_INTERFACE_OV < CURRENT_DATE -2)
--AND CONT.CD_SITUACAO_CONTRATO IN (5, 10, 15, 20) 
AND CONT.DH_ULT_INTERFACE < CURRENT_DATE - 15 
UNION

select DISTINCT 'C' , CONT.NU_ORDEM_VENDA
 --CC.NU_ORDEM_VENDA 
from CTE_PEDIDO_TODOS CONT
INNER JOIN 
(SELECT HIS.ID, HIS.NU_CONTRATO_SAP, HIS.CD_ELO_AGENDAMENTO ,
HIS.DH_ULT_INTERFACE_OV, HIS.DH_ULT_INTERFACE_CONTRATO, 
HIS.DH_ULT_ALTERACAO, HIS.CD_TIPO_AGENDAMENTO, 
HIS.CD_STATUS_REPLAN, HIS.CD_ELO_AGENDAMENTO_ITEM, HIS.NU_ORDEM_VENDA,
HIS.QT_AGENDADA_CONFIRMADA
 FROM VND.ELO_CARTEIRA_hist HIS 
INNER JOIN (
    SELECT MAXID.CD_ELO_CARTEIRA, MAX(MAXID.ID) ID 
    FROM VND.ELO_CARTEIRA_HIST MAXID GROUP BY MAXID.CD_ELO_CARTEIRA 
    )
 MAXD ON MAXD.ID = HIS.ID)    
  CC
ON CC.NU_ORDEM_VENDA = CONT.NU_ORDEM_VENDA 
INNER JOIN AGENDAMENTO AGC
ON 
AGC.CD_ELO_AGENDAMENTO = CC.CD_ELO_AGENDAMENTO
WHERE 
NVL(CC.QT_AGENDADA_CONFIRMADA,0) > 0
--AND CC.QT_AGENDADA > 0
and AGC.CD_ELO_STATUS IN (1,2, 3,4,5,6, 7)
--and CC.CD_STATUS_CEL_FINAL = 59 
AND NOT(NVL(CC.NU_ORDEM_VENDA, '0') IN ('          ', '0', '0         ' )) 
AND (CC.CD_TIPO_AGENDAMENTO IN (22,23,24) OR (CC.CD_TIPO_AGENDAMENTO = 25 AND CC.CD_STATUS_REPLAN = 32)
        OR (CC.CD_TIPO_AGENDAMENTO IS NULL 
        AND EXISTS (SELECT 1 FROM VND.VW_ELO_AGENDAMENTO_ITEM_ADICAO IIS WHERE IIS.CD_ELO_AGENDAMENTO_ITEM = CC.CD_ELO_AGENDAMENTO_ITEM)) )


AND CONT.NU_QUANTIDADE_SALDO > 0
AND (CC.DH_ULT_ALTERACAO < CURRENT_DATE - 2 OR CC.DH_ULT_INTERFACE_CONTRATO < CURRENT_DATE - 2 OR CC.DH_ULT_INTERFACE_OV < CURRENT_DATE -2)

AND CONT.DH_ULT_INTERFACE < CURRENT_DATE - 15 

UNION 


select 'C' IC_TIPO, sap.nu_ordem_venda from vnd.elo_carteira sap
inner join AGENDAMENTO ag on sap.cd_elo_agendamento = ag.cd_elo_agendamento
left join CTE_PEDIDO_TODOS ov on sap.nu_ordem_venda = ov.nu_ordem_venda 
where 
1=1
--sap.nu_carteira_version = '20180724213016'
and NOT(NVL(sap.NU_ORDEM_VENDA, '0') IN ('          ', '0', '0         ' ))
and ov.cd_produto_sap is null
group by sap.nu_ordem_venda

UNION 

select 'G' IC_TIPO, sap.NU_CONTRATO_SAP from vnd.elo_carteira sap
inner join AGENDAMENTO ag on sap.cd_elo_agendamento = ag.cd_elo_agendamento
left join CTE_CONTRATO_TODOS ov on sap.NU_CONTRATO_SAP = ov.NU_CONTRATO_SAP 
where 
1=1
and ov.CD_CONTRATO is null
group by sap.NU_CONTRATO_SAP


) RET
WHERE 
NOT EXISTS (SELECT 1 FROM VND.INTERFACE TR
WHERE SUBSTR(TR.NU_CODIGO, 1,10) = RET.NU_CODIGO
AND TR.DH_EXECUCAO > CURRENT_DATE - 15
) 

;


V_LIMIT NUMBER:=800;

TYPE elo_interface_r IS RECORD
(
ic_tipo     VND.INTERFACE.IC_TIPO%TYPE,
nu_codigo   VND.INTERFACE.NU_CODIGO%TYPE

); 

TYPE elo_interface_t IS TABLE OF elo_interface_r
INDEX BY PLS_INTEGER;
tof_elo_interface elo_interface_t;

tof_elo_interface_todos elo_interface_t;

V_INTERFACE    NUMBER;
V_MAX_CD_INTERFACE  VND.INTERFACE.CD_INTERFACE%TYPE;

V_IS_VALID VARCHAR2(1);

PROCEDURE RANGEVALID (pi_ic_tipo     VND.INTERFACE.IC_TIPO%TYPE,
pi_nu_codigo   VND.INTERFACE.NU_CODIGO%TYPE, IS_VALID OUT VARCHAR2 )
IS 

V_QTDE NUMBER;

BEGIN

IS_VALID:='N';

IF pi_ic_tipo = 'G' THEN 
    BEGIN
    SELECT COUNT(1) INTO V_QTDE
    FROM VND.CONTRATO CONT
    WHERE 
    CONT.NU_CONTRATO_SAP = pi_nu_codigo;
    EXCEPTION 
    WHEN NO_DATA_FOUND THEN 
    V_QTDE:= -1;
    WHEN OTHERS THEN 
    V_QTDE:= -1;
    
    END;
    
    IF V_QTDE > 0 THEN
    
        BEGIN
        SELECT COUNT(1) INTO V_QTDE
        FROM VND.CONTRATO CONT
        INNER JOIN VND.ITEM_CONTRATO IC 
        ON CONT.CD_CONTRATO = IC.CD_CONTRATO
        WHERE 
        CONT.NU_CONTRATO_SAP = pi_nu_codigo
        AND CONT.IC_ATIVO = 'S'
        AND CONT.CD_STATUS_CONTRATO = '8' 
        AND NVL(IC.NU_QUANTIDADE,0) - NVL(IC.NU_QTY_DELIVERED,0) > 1
        AND (CONT.dt_fim > current_date -180  
        AND CONT.CD_SITUACAO_CONTRATO IN (5, 10, 15, 20)
        AND CONT.DH_ULT_INTERFACE < CURRENT_DATE - 7); 
        
        EXCEPTION 
        WHEN NO_DATA_FOUND THEN 
        V_QTDE:= 0;
        WHEN OTHERS THEN 
        V_QTDE:= 0;

        END;
    
    END IF;
    
    

ELSE 
    BEGIN
    SELECT COUNT(1) INTO V_QTDE
    FROM VND.PEDIDO CONT
    WHERE 
    CONT.NU_ORDEM_VENDA = pi_nu_codigo;
    EXCEPTION 
    WHEN NO_DATA_FOUND THEN 
    V_QTDE:= -1;
    WHEN OTHERS THEN 
    V_QTDE:= -1;
    
    END;
    
    IF V_QTDE > 0 THEN

    BEGIN
    SELECT COUNT(1) INTO V_QTDE
    FROM VND.PEDIDO PED
    WHERE 
    PED.NU_ORDEM_VENDA = pi_nu_codigo
    and (PED.CD_SITUACAO_PEDIDO in (5, 10,15,20,25) 
    AND PED.NU_QUANTIDADE_SALDO > 0 
    AND PED.DH_ULT_INTERFACE < CURRENT_DATE - 7)
    AND EXISTS (SELECT 1 
                FROM VND.CONTRATO CONT 
                INNER JOIN VND.ITEM_CONTRATO IC 
                ON CONT.CD_CONTRATO = IC.CD_CONTRATO
                WHERE CONT.NU_CONTRATO_SAP = PED.NU_CONTRATO_SAP 
                AND CONT.CD_SITUACAO_CONTRATO IN (5, 10, 15, 20, 25) 
                AND NVL(IC.NU_QUANTIDADE,0) - NVL(IC.NU_QTY_DELIVERED,0) > 0
                AND  CONT.CD_STATUS_CONTRATO = '8'
                AND PED.CD_ITEM_CONTRATO = IC.CD_ITEM_CONTRATO)
    ;
                      
    EXCEPTION 
    WHEN NO_DATA_FOUND THEN 
    V_QTDE:= 0;
    WHEN OTHERS THEN 
    V_QTDE:= 0;
    
    END;      

     
    END IF;
    

END IF;    
    
    IF NVL(V_QTDE, 1) > 0 OR V_QTDE < 0 THEN 
        IS_VALID:='S';
    END IF ;

END;


BEGIN

BEGIN 
SELECT COUNT(1) INTO V_INTERFACE 
FROM VND.INTERFACE 
WHERE 
DH_EXECUCAO IS NULL;
EXCEPTION 
WHEN NO_DATA_FOUND THEN 
V_INTERFACE:=0;
WHEN OTHERS THEN 
V_INTERFACE:=0;
END;
    
IF V_INTERFACE < 200 THEN 
BEGIN


    BEGIN 
    OPEN    C_WHO_UPDATE;                               
    FETCH   C_WHO_UPDATE BULK COLLECT INTO tof_elo_interface_todos LIMIT V_LIMIT;
    CLOSE   C_WHO_UPDATE;
    EXCEPTION  
    WHEN OTHERS THEN 
    BEGIN
    RAISE_APPLICATION_ERROR(-20001, 'ERRO ENCONTRADO: GX_ELO_BATCH_ISSUE.303 - ' || SQLCODE || ' -ERROR- ' || SQLERRM);
    --ROLLBACK;
    END;
    
    END;

    IF tof_elo_interface_todos.COUNT > 0 THEN 
        V_IS_VALID:='N';
        FOR i_cartT in tof_elo_interface_todos.FIRST .. tof_elo_interface_todos.LAST
        LOOP
            RANGEVALID(tof_elo_interface_todos(i_cartT).IC_TIPO, tof_elo_interface_todos(i_cartT).NU_CODIGO, V_IS_VALID);
            IF V_IS_VALID = 'S' THEN 
                tof_elo_interface(tof_elo_interface.COUNT +1):=tof_elo_interface_todos(i_cartT);        
            END IF;
        
        END LOOP;
        
    
    
    END IF;
    
    select max(cd_interface) + 1 INTO V_MAX_CD_INTERFACE from vnd.interface;
    
	IF tof_elo_interface.COUNT > 0 THEN 
	BEGIN 
		FOR i_cart in tof_elo_interface.FIRST .. tof_elo_interface.LAST
		LOOP
            
            BEGIN
                INSERT INTO  VND.INTERFACE 
                (cd_interface, ic_tipo, nu_codigo)
                VALUES
                ( 
                V_MAX_CD_INTERFACE,
                tof_elo_interface(i_cart).ic_tipo,
                tof_elo_interface(i_cart).nu_codigo
                );
		
            COMMIT;  
            
            V_MAX_CD_INTERFACE:=V_MAX_CD_INTERFACE+1;
                  
            EXCEPTION  
            WHEN OTHERS THEN 
            BEGIN
            RAISE_APPLICATION_ERROR(-20001, 'ERRO ENCONTRADO: GX_ELO_BATCH_ISSUE.304 - ' || SQLCODE || ' -ERROR- ' || SQLERRM);
            ROLLBACK;
            END;
            END;
		END LOOP; 

	END;
	END IF;    
    
END;
END IF;

DBMS_SESSION.free_unused_user_memory;

END;

--select * from vnd.interface where dh_execucao is null;






