SELECT C.CD_ELO_AGENDAMENTO FROM VND.ELO_AGENDAMENTO C WHERE CD_WEEK = 'W202018' AND CD_POLO = 'P002';

SELECT 'UPDATE VND.ELO_CARTEIRA SET QT_AGENDADA_CONFIRMADA = ' || TO_CHAR(1) 
|| ' WHERE CD_ELO_CARTEIRA = ' || TO_CHAR(C.CD_ELO_CARTEIRA) 
|| ' AND NU_ORDEM_VENDA = ''' || C.NU_ORDEM_VENDA || '''' ||  
';' || '--' || C.DS_VERSAO

SELECT C.*

FROM VND.ELO_CARTEIRA C
WHERE 1=1 
--C.CD_ELO_AGENDAMENTO = 72
AND C.QT_SALDO > 0 
AND C.DS_VERSAO IS NOT NULL
AND C.CD_TIPO_AGENDAMENTO = 25 AND C.CD_STATUS_REPLAN = 32 AND C.QT_AGENDADA_CONFIRMADA = 0
AND NOT(C.CD_STATUS_CEL_FINAL = 59)
AND EXISTS (SELECT 1 FROM VND.PEDIDO P
WHERE P.NU_ORDEM_VENDA = C.NU_ORDEM_VENDA 
AND P.NU_QUANTIDADE_SALDO = 0 AND P.NU_QUANTIDADE_ENTREGUE > 0
)


