WITH AGENDAMENTO AS 
(
--SELECT * FROM CTF.POLO
SELECT AGE.CD_ELO_AGENDAMENTO, AGE.CD_WEEK, AGE.CD_POLO, AGE.CD_MACHINE, AGE.CD_CENTRO_EXPEDIDOR, 
AGE.CD_ELO_STATUS
FROM VND.ELO_AGENDAMENTO AGE
WHERE 
AGE.IC_ATIVO = 'S'
AND AGE.CD_ELO_STATUS IN (1,2,3,4, 5,6,7) 
--AND ('6100' IS NULL OR AGE.CD_CENTRO_EXPEDIDOR = '6100')
--AND ('P002' IS NULL OR AGE.CD_POLO = 'P002')
--AND AGE.CD_WEEK = 'W172018'
),
--select * from AGENDAMENTO

CTE_SHOW_BY_TYPE AS 
(
SELECT 'CARTEIRA', 'S' IC_ATIVO FROM  DUAL
UNION
SELECT 'CONTRATO', 'N' IC_ATIVO FROM  DUAL
UNION
SELECT 'ITEM_CONTRATO', 'N' IC_ATIVO FROM  DUAL
UNION
SELECT 'PEDIDO', 'S' IC_ATIVO FROM  DUAL
UNION
SELECT 'PROTOCOLO', 'N' IC_ATIVO FROM  DUAL
UNION
SELECT 'ENTREGA', 'N' IC_ATIVO FROM  DUAL
UNION
SELECT 'AGENDAMENTO_ITEM', 'N' IC_ATIVO FROM  DUAL
UNION
SELECT 'AGENDAMENTO_DAY', 'N' IC_ATIVO FROM  DUAL

),


--SELECT * FROM CTE_SHOW_BY_TYPE

CTE_CONTRATO_PEDIDOS AS 
(
SELECT 
'' NU_CONTRATO_SAP, 
0 CD_ITEM_CONTRATO, 
'' NU_ORDEM_VENDA, 
'' CD_PRODUTO_SAP, 
0 NU_CONTRATO ,
'' NU_PROTOCOLO
FROM DUAL
UNION
SELECT 
'' NU_CONTRATO_SAP, 
0 CD_ITEM_CONTRATO, 
'' NU_ORDEM_VENDA, 
'' CD_PRODUTO_SAP , 
0 NU_CONTRATO ,
'' NU_PROTOCOLO
FROM DUAL
UNION 
SELECT DISTINCT 
CT.NU_CONTRATO_SAP, 
CT.CD_ITEM_CONTRATO, 
CT.NU_ORDEM_VENDA, 
CT.CD_PRODUTO_SAP, 
CT.NU_CONTRATO ,
'' NU_PROTOCOLO
FROM VND.ELO_CARTEIRA CT
INNER JOIN AGENDAMENTO AG
ON 
AG.CD_ELO_AGENDAMENTO = CT.CD_ELO_AGENDAMENTO
WHERE 
CT.IC_ATIVO = 'S'
AND CT.QT_AGENDADA_CONFIRMADA >=0
--AND CT.CD_STATUS_CEL_FINAL <> 59

),
--SELECT * FROM CTE_CONTRATO_PEDIDOS

CTE_CONTRATO AS
(
SELECT  
CONT.CD_CONTRATO,CONT.NU_CONTRATO,CONT.CD_STATUS_CONTRATO,CONT.CD_CLIENTE_CONTRATO,
CONT.CD_CLIENTE_EMISSOR,CONT.CD_TIPO_ORDEM, CONT.CD_CENTRO_EXPEDIDOR,CONT.CD_USUARIO_VENDA,
CONT.CD_AGENTE_VENDA,CONT.CD_USUARIO_INCLUSAO,CONT.DH_INCLUSAO,
CONT.DH_GERACAO,CONT.DH_IMPRESSAO,CONT.DH_ASSINATURA,CONT.DH_ENVIO_ADVEN,CONT.DH_ENVIO_SAP,
CONT.DH_PROCESSAMENTO,CONT.DT_PAGAMENTO,CONT.DS_FORMA_PAGAMENTO,CONT.DS_COND_ESP_PAGTO,CONT.DT_INICIO,
CONT.DT_FIM,CONT.VL_FRETE_DISTRIBUICAO,CONT.DS_PROTOCOLO,CONT.IC_ATIVO,CONT.DS_JUSTIFICATIVA,
CONT.CD_MOTIVO_ORDEM,CONT.DS_COMPOSICAO_CARGA,CONT.DS_OBSERVACAO,CONT.IC_ALTERA_SUBSTITUI,
CONT.CD_INCOTERMS,CONT.DH_LISTA_PRECO,CONT.DS_GARANTIAS,CONT.DH_PRAZO_GARANTIA,CONT.VL_FACIL,
CONT.DS_CREDENCIAMENTO_FOB,CONT.CD_SALES_ORG,CONT.CD_DISTRIBUTION_CHANNEL,CONT.CD_SALES_DIVISION,
CONT.IC_NEW_PRODUCT,CONT.IC_NEW_CUSTOMER,CONT.IC_SIGNED,CONT.IC_SAP_READY,CONT.DH_NEW_PRODUCT,
CONT.DH_NEW_CUSTOMER,CONT.DH_SAP_READY,CONT.DH_EMAIL_MASTERDATA,CONT.DH_EMAIL_ADVEN,CONT.NU_CONTRATO_SAP,
CONT.CD_TIPO_CONTRATO,CONT.DH_CANCELAMENTO,CONT.CD_USUARIO_CANCELAMENTO,CONT.DH_ULT_INTERFACE,
CONT.CD_BLOCKING_REASON,CONT.CD_SITUACAO_CONTRATO,CONT.CD_FORMA_PAGAMENTO,CONT.IC_SAP,
CONT.CD_STATUS_CONTRATO_SAP,CONT.CD_USUARIO_RECEBIMENTO,CONT.DH_RECEBIMENTO,
CONT.IC_RECEBIDO,CONT.DH_ULT_ALTERACAO,CONT.IC_ORIGEM_CONTRATO,CONT.CD_TIPO_PAGAMENTO,
CONT.CD_CLIENTE_PO_NUMERO,CONT.DH_ENVIO_ASSINATURA,CONT.DH_REENVIO_ASSINATURA,
CONT.CD_USUARIO_APROVACAO_CLIENTE,CONT.CD_USUARIO_REJEICAO_CLIENTE,CONT.CD_USUARIO_REJEICAO_SUPERVISOR,
CONT.DH_APROVACAO_CLIENTE,CONT.DH_REJEICAO_CLIENTE,CONT.DH_REJEICAO_SUPERVISOR,CONT.DS_MOTIVO_REJEICAO_CLIENTE,
CONT.DS_MOTIVO_REJEICAO_SUPERVISOR,CONT.IC_ASSINATURA_ELETRONICA,
CONT.CD_USUARIO_APROVACAO_SUPERV,CONT.DH_APROVACAO_SUPERVISOR,CONT.CD_BLOQUEIO_CREDITO,CONT.CD_BLOQUEIO_ENTREGA,
CONT.CD_BLOQUEIO_FATURAMENTO,CONT.CD_BLOQUEIO_REMESSA,CONT.DS_CREDIT_BLOCK_REASON,CONT.DS_ROTEIRO_ENTREGA

FROM vnd.contrato CONT
WHERE 
EXISTS (SELECT 1 FROM  CTE_CONTRATO_PEDIDOS CP 
WHERE CP.NU_CONTRATO_SAP = CONT.NU_CONTRATO_SAP AND NVL(CP.CD_ITEM_CONTRATO, '') = ''  )
UNION
SELECT DISTINCT 
CONT.CD_CONTRATO,CONT.NU_CONTRATO,CONT.CD_STATUS_CONTRATO,CONT.CD_CLIENTE_CONTRATO,
CONT.CD_CLIENTE_EMISSOR,CONT.CD_TIPO_ORDEM, CONT.CD_CENTRO_EXPEDIDOR,CONT.CD_USUARIO_VENDA,
CONT.CD_AGENTE_VENDA,CONT.CD_USUARIO_INCLUSAO,CONT.DH_INCLUSAO,
CONT.DH_GERACAO,CONT.DH_IMPRESSAO,CONT.DH_ASSINATURA,CONT.DH_ENVIO_ADVEN,CONT.DH_ENVIO_SAP,
CONT.DH_PROCESSAMENTO,CONT.DT_PAGAMENTO,CONT.DS_FORMA_PAGAMENTO,CONT.DS_COND_ESP_PAGTO,CONT.DT_INICIO,
CONT.DT_FIM,CONT.VL_FRETE_DISTRIBUICAO,CONT.DS_PROTOCOLO,CONT.IC_ATIVO,CONT.DS_JUSTIFICATIVA,
CONT.CD_MOTIVO_ORDEM,CONT.DS_COMPOSICAO_CARGA,CONT.DS_OBSERVACAO,CONT.IC_ALTERA_SUBSTITUI,
CONT.CD_INCOTERMS,CONT.DH_LISTA_PRECO,CONT.DS_GARANTIAS,CONT.DH_PRAZO_GARANTIA,CONT.VL_FACIL,
CONT.DS_CREDENCIAMENTO_FOB,CONT.CD_SALES_ORG,CONT.CD_DISTRIBUTION_CHANNEL,CONT.CD_SALES_DIVISION,
CONT.IC_NEW_PRODUCT,CONT.IC_NEW_CUSTOMER,CONT.IC_SIGNED,CONT.IC_SAP_READY,CONT.DH_NEW_PRODUCT,
CONT.DH_NEW_CUSTOMER,CONT.DH_SAP_READY,CONT.DH_EMAIL_MASTERDATA,CONT.DH_EMAIL_ADVEN,CONT.NU_CONTRATO_SAP,
CONT.CD_TIPO_CONTRATO,CONT.DH_CANCELAMENTO,CONT.CD_USUARIO_CANCELAMENTO,CONT.DH_ULT_INTERFACE,
CONT.CD_BLOCKING_REASON,CONT.CD_SITUACAO_CONTRATO,CONT.CD_FORMA_PAGAMENTO,CONT.IC_SAP,
CONT.CD_STATUS_CONTRATO_SAP,CONT.CD_USUARIO_RECEBIMENTO,CONT.DH_RECEBIMENTO,
CONT.IC_RECEBIDO,CONT.DH_ULT_ALTERACAO,CONT.IC_ORIGEM_CONTRATO,CONT.CD_TIPO_PAGAMENTO,
CONT.CD_CLIENTE_PO_NUMERO,CONT.DH_ENVIO_ASSINATURA,CONT.DH_REENVIO_ASSINATURA,
CONT.CD_USUARIO_APROVACAO_CLIENTE,CONT.CD_USUARIO_REJEICAO_CLIENTE,CONT.CD_USUARIO_REJEICAO_SUPERVISOR,
CONT.DH_APROVACAO_CLIENTE,CONT.DH_REJEICAO_CLIENTE,CONT.DH_REJEICAO_SUPERVISOR,CONT.DS_MOTIVO_REJEICAO_CLIENTE,
CONT.DS_MOTIVO_REJEICAO_SUPERVISOR,CONT.IC_ASSINATURA_ELETRONICA,
CONT.CD_USUARIO_APROVACAO_SUPERV,CONT.DH_APROVACAO_SUPERVISOR,CONT.CD_BLOQUEIO_CREDITO,CONT.CD_BLOQUEIO_ENTREGA,
CONT.CD_BLOQUEIO_FATURAMENTO,CONT.CD_BLOQUEIO_REMESSA,CONT.DS_CREDIT_BLOCK_REASON,CONT.DS_ROTEIRO_ENTREGA
FROM vnd.contrato CONT
INNER JOIN VND.ITEM_CONTRATO ICTR
ON CONT.CD_CONTRATO = ICTR.CD_CONTRATO
WHERE 
EXISTS (
SELECT 1 FROM  CTE_CONTRATO_PEDIDOS CP 
WHERE 
CP.NU_CONTRATO_SAP = CONT.NU_CONTRATO_SAP 
AND CP.CD_ITEM_CONTRATO = ICTR.CD_ITEM_CONTRATO )
),
--SELECT * FROM CTE_CONTRATO


CTE_ITEM_CONTRATO AS 
(
SELECT ICTR.* FROM VND.ITEM_CONTRATO ICTR
WHERE EXISTS (SELECT 1 FROM CTE_CONTRATO CCTR WHERE CCTR.CD_CONTRATO = ICTR.CD_CONTRATO)
),

--SELECT * FROM CTE_ITEM_CONTRATO
CTE_WHOISPEDIDO AS 
(
SELECT PED.CD_PEDIDO, PED.CD_ITEM_PEDIDO, PED.NU_ORDEM_VENDA FROM VND.PEDIDO PED
WHERE
EXISTS (SELECT 1 FROM CTE_CONTRATO_PEDIDOS CCP 
WHERE CCP.NU_CONTRATO = PED.NU_CONTRATO)
UNION 
SELECT PED.CD_PEDIDO, PED.CD_ITEM_PEDIDO, PED.NU_ORDEM_VENDA FROM VND.PEDIDO PED
WHERE 
EXISTS (SELECT 1 FROM CTE_CONTRATO_PEDIDOS CCP 
WHERE CCP.NU_ORDEM_VENDA = PED.NU_ORDEM_VENDA)
)

SELECT DISTINCT CS.NU_ORDEM_VENDA 
FROM CTE_CONTRATO_PEDIDOS CS
LEFT JOIN CTE_WHOISPEDIDO DS
ON CS.NU_ORDEM_VENDA = DS.NU_ORDEM_VENDA
WHERE
DS.NU_ORDEM_VENDA IS NULL;




