select 

(SELECT 

SUM(NVL(SS.QT_SEMANA,0)) QT_SEMANA
--SUM(NVL(DDAY.NU_QUANTIDADE,0)) NU_QUANTIDADE
FROM VND.ELO_AGENDAMENTO_SUPERVISOR SUP
INNER JOIN VND.ELO_AGENDAMENTO_ITEM ITEM 
ON SUP.CD_ELO_AGENDAMENTO_SUPERVISOR = ITEM.CD_ELO_AGENDAMENTO_SUPERVISOR
LEFT JOIN VND.ELO_AGENDAMENTO_WEEK SS 
ON ITEM.CD_ELO_AGENDAMENTO_ITEM = SS.CD_ELO_AGENDAMENTO_ITEM
WHERE
SUP.CD_ELO_AGENDAMENTO = AGE.CD_ELO_AGENDAMENTO 
) QT_SEMANA_TOT_AGENDA,
(
SELECT 
SUM(NVL(DDAY.NU_QUANTIDADE,0)) NU_QUANTIDADE
FROM VND.ELO_AGENDAMENTO_SUPERVISOR SUP
INNER JOIN VND.ELO_AGENDAMENTO_ITEM ITEM 
ON SUP.CD_ELO_AGENDAMENTO_SUPERVISOR = ITEM.CD_ELO_AGENDAMENTO_SUPERVISOR
LEFT JOIN VND.ELO_AGENDAMENTO_WEEK SS 
ON ITEM.CD_ELO_AGENDAMENTO_ITEM = SS.CD_ELO_AGENDAMENTO_ITEM
LEFT JOIN VND.ELO_AGENDAMENTO_DAY DDAY ON 
SS.CD_ELO_AGENDAMENTO_WEEK = DDAY.CD_ELO_AGENDAMENTO_WEEK 
WHERE
SUP.CD_ELO_AGENDAMENTO = AGE.CD_ELO_AGENDAMENTO 
) QT_DAY_TOT_AGENDA, 
CT.QT_AGENDADA_CONFIRMADA QT_VOLUME_PROGRAMADO, 

(

SELECT 

SUM(NVL(SUP.QT_AGENDADA_CONFIRMADA,0)) QT_ITEM
--SUM(NVL(DDAY.NU_QUANTIDADE,0)) NU_QUANTIDADE
FROM VND.ELO_CARTEIRA SUP
WHERE
SUP.CD_ELO_AGENDAMENTO_ITEM = CT.CD_ELO_AGENDAMENTO_ITEM 
) QT_ITEM,

(

SELECT 

SUM(NVL(SS.QT_SEMANA,0)) QT_SEMANA
--SUM(NVL(DDAY.NU_QUANTIDADE,0)) NU_QUANTIDADE
FROM VND.ELO_AGENDAMENTO_SUPERVISOR SUP
INNER JOIN VND.ELO_AGENDAMENTO_ITEM ITEM 
ON SUP.CD_ELO_AGENDAMENTO_SUPERVISOR = ITEM.CD_ELO_AGENDAMENTO_SUPERVISOR
LEFT JOIN VND.ELO_AGENDAMENTO_WEEK SS 
ON ITEM.CD_ELO_AGENDAMENTO_ITEM = SS.CD_ELO_AGENDAMENTO_ITEM
WHERE
ITEM.CD_ELO_AGENDAMENTO_ITEM = CT.CD_ELO_AGENDAMENTO_ITEM 
) QT_SEMANA,
(
SELECT 
SUM(NVL(DDAY.NU_QUANTIDADE,0)) NU_QUANTIDADE
FROM VND.ELO_AGENDAMENTO_SUPERVISOR SUP
INNER JOIN VND.ELO_AGENDAMENTO_ITEM ITEM 
ON SUP.CD_ELO_AGENDAMENTO_SUPERVISOR = ITEM.CD_ELO_AGENDAMENTO_SUPERVISOR
LEFT JOIN VND.ELO_AGENDAMENTO_WEEK SS 
ON ITEM.CD_ELO_AGENDAMENTO_ITEM = SS.CD_ELO_AGENDAMENTO_ITEM
LEFT JOIN VND.ELO_AGENDAMENTO_DAY DDAY ON 
SS.CD_ELO_AGENDAMENTO_WEEK = DDAY.CD_ELO_AGENDAMENTO_WEEK 
WHERE
ITEM.CD_ELO_AGENDAMENTO_ITEM = CT.CD_ELO_AGENDAMENTO_ITEM
) QT_DAY,


(

SELECT 

SUM(NVL(SUP.QT_AGENDADA_CONFIRMADA,0)) QT_ITEM
--SUM(NVL(DDAY.NU_QUANTIDADE,0)) NU_QUANTIDADE
FROM VND.ELO_CARTEIRA SUP
WHERE
SUP.CD_ELO_AGENDAMENTO = CT.CD_ELO_AGENDAMENTO
--AND SUP.NU_CONTRATO_SAP = CT.NU_CONTRATO_SAP
--AND SUP.CD_ITEM_CONTRATO = CT.CD_ITEM_CONTRATO
AND SUP.CD_PRODUTO_SAP = CT.CD_PRODUTO_SAP
AND SUP.CD_SALES_GROUP = CT.CD_SALES_GROUP
--AND SUP.NU_ORDEM_VENDA = CT.NU_ORDEM_VENDA
AND (CASE WHEN SUP.CD_INCOTERMS = 'CIF' THEN SUP.CD_CLIENTE_RECEBEDOR END = CT.CD_CLIENTE_RECEBEDOR
     OR CASE WHEN SUP.CD_INCOTERMS = 'FOB' THEN SUP.CD_CLIENTE_PAGADOR END = CT.CD_CLIENTE_PAGADOR)

AND SUP.CD_INCOTERMS = CT.CD_INCOTERMS
AND (SUP.CD_TIPO_AGENDAMENTO IN (22,23,24) OR (SUP.CD_TIPO_AGENDAMENTO = 25 AND SUP.CD_STATUS_REPLAN = 32) 
)
--AND NOT(SUP.CD_ELO_CARTEIRA = CT.CD_ELO_CARTEIRA) 
AND NOT(SUP.CD_ELO_AGENDAMENTO_ITEM = CT.CD_ELO_AGENDAMENTO_ITEM)
) QT_ITEM_COM_RESBOSTHER,


--COUNT(1)
CT.*,
AGE.CD_WEEK,
AGE.CD_POLO,
AGE.CD_CENTRO_EXPEDIDOR CD_CENTRO_EXPEDIDOR_AGEND,
AGE.CD_ELO_STATUS



FROM VND.ELO_CARTEIRA CT 
INNER JOIN VND.ELO_AGENDAMENTO AGE
ON 
AGE.CD_ELO_AGENDAMENTO = CT.CD_ELO_AGENDAMENTO

WHERE  
NVL(CT.QT_AGENDADA_CONFIRMADA,-1) <=0
AND NVL(CT.QT_AGENDADA,-1) <= 0
and AGE.CD_ELO_STATUS IN (10,20,30,40,50,61,71,8,90)
and AGE.DT_WEEK_START < current_date - 30
and NVL(CT.CD_STATUS_CEL_FINAL, 33) NOT IN (59) 
--AND NVL(CT.CD_TIPO_AGENDAMENTO, 32) IN (22,23,24, 25, 32)
AND (CT.NU_PROTOCOLO IS NULL)
; 
        
       


select * from vnd.elo_agendamento 
where cd_elo_agendamento = 336;


select * from vnd.elo_carteira
where cd_elo_agendamento = 336;

--
--update vnd.elo_agendamento
--set cd_elo_status = 9 
--where cd_elo_agendamento = 336;