WITH CTE_AGENDAMENTO AS 
        (
        SELECT AGE.CD_ELO_AGENDAMENTO, AGE.CD_CENTRO_EXPEDIDOR, 
        AGE.CD_MACHINE, ma.DS_MACHINE, AGE.CD_WEEK , AGE.CD_POLO,
        es.DS_STATUS, AGE.CD_ELO_STATUS, AGE.NU_CARTEIRA_VERSION
        FROM VND.ELO_AGENDAMENTO AGE 
        LEFT JOIN CTF.MACHINE ma
        on AGE.CD_MACHINE = ma.CD_MACHINE
        inner join VND.ELO_STATUS es
        on es.CD_ELO_STATUS = AGE.CD_ELO_STATUS
        
        WHERE AGE.IC_ATIVO = 'S'

        AND ('W292018' is null OR AGE.CD_WEEK = 'W292018')
        --and ('6100' is null or AGE.CD_CENTRO_EXPEDIDOR = '6100')
         and ('P013' is null or AGE.CD_POLO = 'P013')
        
        ),
        
        CTE_CARTEIRA AS 
        (
        
        SELECT 
--        
        CTAF.CD_ELO_AGENDAMENTO, 
        CTAF.CD_ELO_AGENDAMENTO_ITEM,
        AGEF.CD_WEEK,
        AGEF.CD_POLO,
        AGEF.CD_ELO_STATUS, 
        AGEF.NU_CARTEIRA_VERSION           
        FROM VND.ELO_CARTEIRA CTAF
        INNER JOIN CTE_AGENDAMENTO AGEF
        ON CTAF.CD_ELO_AGENDAMENTO = AGEF.CD_ELO_AGENDAMENTO
        WHERE
        CTAF.IC_ATIVO = 'S'
        --AND CTAF.NU_ORDEM_VENDA in('0002388464', '0002393620')

        AND (CTAF.cd_tipo_agendamento in (22,23,24) 
            or (CTAF.cd_tipo_agendamento = 25 and CTAF.cd_status_replan = 32) 
            or (
                exists (
                    select 1 
                        from vnd.VW_ELO_AGENDAMENTO_ITEM_ADICAO initem 
                        where initem.CD_ELO_AGENDAMENTO_ITEM = CTAF.CD_ELO_AGENDAMENTO_ITEM
                        AND CTAF.CD_TIPO_AGENDAMENTO IS NULL )))
       
        ),
        --SELECT * FROM CTE_CARTEIRA
        
        CTE_AGENDAMENTO_FILTER AS 
        (
        SELECT ag.CD_ELO_AGENDAMENTO, ag.CD_CENTRO_EXPEDIDOR, ag.CD_MACHINE, ag.DS_MACHINE, ag.CD_WEEK , ag.DS_STATUS, ag.CD_ELO_STATUS
        FROM CTE_AGENDAMENTO ag
        
        ),
     
        ELO_AG_DAY_BY_INCOTERMS_ITEM AS 
        (

        SELECT  EA_SUP_I.CD_ELO_AGENDAMENTO, EAG_WE_I.CD_ELO_AGENDAMENTO_WEEK, EAG_ITEM_I.CD_ELO_AGENDAMENTO_ITEM, DAYY.CD_GRUPO_EMBALAGEM, DAYY.NU_DIA_SEMANA, 
        SUM(DAYY.NU_QUANTIDADE) NU_QUANTIDADE, EAG_ITEM_I.CD_CLIENTE, EAG_ITEM_I.CD_INCOTERMS,
        MAX(EAG_WE_I.QT_SEMANA) QT_SEMANA_SALDO, 
        MAX((SELECT SUM(SUD.NU_QUANTIDADE) 
            FROM VND.ELO_AGENDAMENTO_DAY SUD 
            WHERE SUD.CD_ELO_AGENDAMENTO_WEEK = EAG_WE_I.CD_ELO_AGENDAMENTO_WEEK)) QT_SUM_DAY_WEEK,
        MAX((SELECT SUM(SUD.NU_QUANTIDADE) 
            FROM VND.ELO_AGENDAMENTO_DAY SUD 
            WHERE SUD.CD_ELO_AGENDAMENTO_WEEK = DAYY.CD_ELO_AGENDAMENTO_WEEK
            AND SUD.CD_GRUPO_EMBALAGEM = DAYY.CD_GRUPO_EMBALAGEM
            --AND SUD.NU_DIA_SEMANA = DAYY.NU_DIA_SEMANA 
            )) QT_SUM_DAY_EMBALAGEM      
        
        FROM CTE_AGENDAMENTO_FILTER FILT
        INNER JOIN VND.ELO_AGENDAMENTO_SUPERVISOR EA_SUP_I  
        ON FILT.CD_ELO_AGENDAMENTO = EA_SUP_I.CD_ELO_AGENDAMENTO
        INNER JOIN VND.ELO_AGENDAMENTO_ITEM EAG_ITEM_I
        --INNER JOIN VND.ELO_AGENDAMENTO_ITEM EAG_ITEM_I
        ON 
        EAG_ITEM_I.CD_ELO_AGENDAMENTO_SUPERVISOR = EA_SUP_I.CD_ELO_AGENDAMENTO_SUPERVISOR
        AND EAG_ITEM_I.IC_ATIVO = 'S'	
        
        INNER JOIN VND.ELO_AGENDAMENTO_WEEK EAG_WE_I
        ON EAG_ITEM_I.CD_ELO_AGENDAMENTO_ITEM = EAG_WE_I.CD_ELO_AGENDAMENTO_ITEM
        
        --LEFT JOIN VND.ELO_AGENDAMENTO_GROUPING EAG_GRO_I
        --ON EAG_GRO_I.CD_ELO_AGENDAMENTO_WEEK = EAG_WE_I.CD_ELO_AGENDAMENTO_WEEK
        INNER JOIN VND.ELO_AGENDAMENTO_DAY DAYY
        ON 
        DAYY.CD_ELO_AGENDAMENTO_WEEK = EAG_WE_I.CD_ELO_AGENDAMENTO_WEEK
        
        WHERE 
        EA_SUP_I.IC_ATIVO = 'S'
        --        AND             EXISTS (
        --            SELECT 1 FROM CTE_CARTEIRA CTA 
       --             WHERE 
       --             CTA.CD_ELO_AGENDAMENTO_ITEM = EAG_ITEM_I.CD_ELO_AGENDAMENTO_ITEM
        --            )

                                        
        GROUP BY  EA_SUP_I.CD_ELO_AGENDAMENTO, EAG_WE_I.CD_ELO_AGENDAMENTO_WEEK, DAYY.CD_GRUPO_EMBALAGEM, DAYY.NU_DIA_SEMANA , EAG_ITEM_I.CD_ELO_AGENDAMENTO_ITEM  , EAG_ITEM_I.CD_CLIENTE,
        EAG_ITEM_I.CD_INCOTERMS
        
        )--,
        --SELECT * FROM ELO_AG_DAY_BY_INCOTERMS_ITEM 
        --WHERE NU_QUANTIDADE >0 AND QT_SEMANA_SALDO < QT_SUM_DAY_WEEK
       -- ORDER BY CD_ELO_AGENDAMENTO_ITEM, CD_GRUPO_EMBALAGEM, NU_DIA_SEMANA;
        
       -- TONELADAS AGENDADAS 12905.34
       
SELECT 

distinct 



CASE
WHEN CAT.DS_CREDIT_BLOCK_REASON IS NOT NULL AND CAT.DS_CREDIT_BLOCK_REASON <> ' ' THEN 'BLOQUEIO'
WHEN CAT.CD_MOTIVO_RECUSA IS NOT NULL THEN 'BLOQUEIO'
WHEN CAT.CD_TIPO_AGENDAMENTO = 25 AND CAT.CD_STATUS_REPLAN = 33 THEN 'REPLAN REPROVADO'
WHEN (NVL(CAT.NU_ORDEM_VENDA, '0') IN ('          ', '0', '0         ' )) THEN 'SEM ORDEM DE VENDA' 
WHEN NVL(CAT.QT_AGENDADA,0) = 0 AND CAT.CD_TIPO_AGENDAMENTO IS NULL THEN 'SEM DISTRIBUICAO'
WHEN NVL(CAT.QT_AGENDADA_CONFIRMADA, 0) = 0 THEN 'SEM PROGRAMACAO'
WHEN CAT.CD_STATUS_CEL_FINAL = 59 THEN 'OK'
WHEN 
(SELECT SUM(QT_SEMANA)  FROM VND.ELO_AGENDAMENTO_WEEK WEEKSS
WHERE WEEKSS.CD_ELO_AGENDAMENTO_ITEM = CAT.CD_ELO_AGENDAMENTO_ITEM) > 0 THEN 'SEMANAL AGENDADO'

END COMENTARIO,
 
(SELECT SSS.DS_STATUS FROM VND.ELO_STATUS SSS WHERE SSS.CD_ELO_STATUS = CAT.cd_status_cel_final) CD_ELO_CEL_FINAL,
CAT.CD_TIPO_AGENDAMENTO, CAT.CD_STATUS_REPLAN,

(SELECT DISTINCT 1 FROM ELO_AG_DAY_BY_INCOTERMS_ITEM SSS
WHERE SSS.CD_ELO_AGENDAMENTO_ITEM = CAT.CD_ELO_AGENDAMENTO_ITEM) TEMAGENDA,

(SELECT SUM(QT_SEMANA)  FROM VND.ELO_AGENDAMENTO_WEEK WEEKSS
WHERE WEEKSS.CD_ELO_AGENDAMENTO_ITEM = CAT.CD_ELO_AGENDAMENTO_ITEM) TOTALSEMANA,

CAT.nu_protocolo, CAT.QT_AGENDADA
,
AGEF.CD_WEEK , AGEF.CD_POLO, AGEF.CD_ELO_STATUS, AGEF.DS_STATUS,
CAT.ds_centro_expedidor, CAT.cd_centro_expedidor, CAT.cd_elo_carteira, 
CAT.nu_contrato_sap, CAT.nu_ordem_venda, CAT.qt_agendada_confirmada , 
CAT.DS_CREDIT_BLOCK_REASON, CAT.CD_ELO_AGENDAMENTO_ITEM,           
CAT.NU_CONTRATO , CAT.DS_STATUS_CONTRATO_SAP,CAT.CD_CLIENTE ,CAT.NO_CLIENTE  ,                                                                    
CAT.CD_INCOTERMS , CAT.CD_SALES_DISTRICT, CAT.NO_SALES_DISTRICT, CAT.CD_SALES_OFFICE,
CAT.NO_SALES_OFFICE ,  CAT.CD_SALES_GROUP,CAT.NO_SALES_GROUP , CAT.CD_AGENTE_VENDA,
CAT.NO_AGENTE ,  CAT.CD_PRODUTO_SAP  , CAT.NO_PRODUTO_SAP, 
CAT.QT_PROGRAMADA QT_ENTREGUE, CAT.QT_SALDO, 
CAT.CD_BLOQUEIO_REMESSA,CAT.CD_BLOQUEIO_FATURAMENTO, CAT.CD_BLOQUEIO_CREDITO ,
CAT.CD_BLOQUEIO_REMESSA_ITEM,CAT.CD_BLOQUEIO_FATURAMENTO_ITEM, 
CAT.CD_MOTIVO_RECUSA,CAT.CD_BLOQUEIO_ENTREGA,
CAT.NU_CNPJ,CAT.NU_CPF ,
CAT.CD_CLIENTE_RECEBEDOR, CAT.NO_CLIENTE_RECEBEDOR ,                                                           
CAT.CD_ITEM_PEDIDO ,CAT.CD_CLIENTE_PAGADOR, CAT.NO_CLIENTE_PAGADOR ,                                                             
CAT.NU_ORDEM ,CAT.QT_AGENDADA_FABRICA, CAT.QT_AGENDADA_SAP,
CAT.DH_LIBERACAO_TORRE_FRETES, CAT.CD_GRUPO_EMBALAGEM,
CAT.CD_ELO_AGENDAMENTO ,CAT.CD_ITEM_CONTRATO ,CAT.CD_STATUS_LOGISTICA, 
CAT.IC_CORTADO_FABRICA,CAT.IC_COOPERATIVE , CAT.CD_STATUS_CEL_FINAL

,(SELECT '1'
FROM VND.ELO_STATUS STB 
WHERE 
STB.CD_ELO_TIPO_STATUS = 10 
AND SUBSTR(CAT.DS_CREDIT_BLOCK_REASON, 1,2) = SUBSTR(STB.DS_STATUS, 1,2) AND ROWNUM=1) DESC_STATUS_BLOQUEIO
, 
CASE 
WHEN CAT.IC_COOPERATIVE = 'S' THEN 
NVL((SELECT SUM(QT_AGENDADA_PROTOCOLO) FROM VND.ELO_VBAK_PROTOCOLO PROT 
WHERE PROT.CD_ELO_CARTEIRA = CAT.CD_ELO_CARTEIRA), 99999) 
ELSE
0 END TEM_CONTA_ORDEM ,

CASE 
WHEN NVL(CAT.CD_STATUS_CEL_FINAL, 99) <> 59 
    AND EXISTS (SELECT 1 
                FROM VND.VW_ELO_AGENDAMENTO_ITEM_ADICAO  ITES 
                WHERE 
                ITES.CD_ELO_AGENDAMENTO_ITEM = CAT.CD_ELO_AGENDAMENTO_ITEM 
                ) THEN 
NVL((SELECT SUM(WEE.QT_SEMANA) FROM VND.ELO_AGENDAMENTO_WEEK WEE
INNER JOIN VW_ELO_AGENDAMENTO_ITEM_ADICAO ITEM ON WEE.CD_ELO_AGENDAMENTO_ITEM = ITEM.CD_ELO_AGENDAMENTO_ITEM 
AND WEE.QT_SEMANA > 0 
WHERE WEE.CD_ELO_AGENDAMENTO_ITEM = CAT.CD_ELO_AGENDAMENTO_ITEM), -1111) 
------------------------------------------------------------
WHEN CAT.CD_STATUS_CEL_FINAL = 59 
    AND EXISTS (SELECT 1 
                FROM VND.VW_ELO_AGENDAMENTO_ITEM_ADICAO ITES 
                WHERE 
                ITES.CD_ELO_AGENDAMENTO_ITEM = CAT.CD_ELO_AGENDAMENTO_ITEM 
                ) THEN 
NVL((SELECT SUM(WEE.QT_SEMANA) FROM VND.ELO_AGENDAMENTO_WEEK WEE
INNER JOIN VND.VW_ELO_AGENDAMENTO_ITEM_ADICAO ITEM ON WEE.CD_ELO_AGENDAMENTO_ITEM = ITEM.CD_ELO_AGENDAMENTO_ITEM 
AND WEE.QT_SEMANA > 0 
WHERE WEE.CD_ELO_AGENDAMENTO_ITEM = CAT.CD_ELO_AGENDAMENTO_ITEM), -5959) 

ELSE
0 END EH_ADICAO ,

CAT.*

 FROM VND.ELO_CARTEIRA CAT
    INNER JOIN CTE_AGENDAMENTO AGEF
    ON CAT.CD_ELO_AGENDAMENTO = AGEF.CD_ELO_AGENDAMENTO
WHERE 1=1 
--AND CAT.CD_ELO_AGENDAMENTO = 231
AND (CAT.cd_tipo_agendamento in (22,23,24) or (CAT.cd_tipo_agendamento = 25 and CAT.cd_status_replan = 32) )
--AND cat.NU_ORDEM_VENDA in('0002388464', '0002393620')
--AND CAT.NO_CLIENTE_PAGADOR = 'AMAGGI EXPORTACAO E IMPORTACAO LTDA'

--AND (cat.no_cliente_PAGADOR = 'THIAGO GEOVANNE SILVA FERREIRA' or cat.CD_CLIENTE_PAGADOR IN ('0004021173','0004015377', '0004039246'))
and cat.cd_incoterms = 'FOB' 
--AND CAT.QT_AGENDADA_CONFIRMADA > 0 
--AND CAT.CD_STATUS_CEL_FINAL = 59



--AND (CAT.DH_LIBERACAO_TORRE_FRETES IS NULL OR CAT.CD_STATUS_TORRE_FRETES IS NULL OR NVL(CAT.CD_STATUS_CUSTOMER_SERVICE, 10) = 10) 

and --(
(CAT.QT_AGENDADA > 0 OR CAT.NU_ORDEM IS NOT NULL OR CAT.CD_TIPO_AGENDAMENTO IS NOT NULL OR CAT.QT_AGENDADA_CONFIRMADA IS NOT NULL
OR CAT.CD_STATUS_CUSTOMER_SERVICE IS NOT NULL OR CAT.CD_STATUS_CONTROLADORIA IS NOT NULL OR 
EXISTS (SELECT 1 
                FROM VND.VW_ELO_AGENDAMENTO_ITEM_ADICAO ITES 
                WHERE 
                ITES.CD_ELO_AGENDAMENTO_ITEM = CAT.CD_ELO_AGENDAMENTO_ITEM 
                AND CAT.CD_TIPO_AGENDAMENTO IS NULL
                )

);
--AND EXISTS

