select 
    NU_PROTOCOLO_ENTREGA PROTOCOLO,
    AE.NU_CONTRATO CONTRATO,
    AE.CD_ITEM_CONTRATO "ITEM CONTRATO",
    NO_COOPERATIVA COOPERATIVA,
    E.QT_QUANTIDADE "QUANTIDADE SOLICITADA",
    nvl(E.QT_FORNECIDO, 0) "QUANTIDADE FORNECIDA",
    DS_STATUS_ENTREGA "STATUS DA ENTREGA",
    C.DH_INCLUSAO "DATA INCLUSÃO CONTRATO",
    E.DT_INCLUSAO_ENTREGA "DATA INCLUSÃO ENTREGA",
    IC.IC_RECUSADO,
    CASE IC.IC_RECUSADO 
      WHEN 'S' 
        THEN 'SIM'
      ELSE
        'NÃO'
    END "ITEM CONTRATO RECUSADO",
    NO_PRODUTO_SAP PRODUTO
from CPT.ENTREGA E
JOIN CPT.AUTORIZACAO_ENTREGA AE
  ON E.CD_AUTORIZACAO_ENTREGA = AE.CD_AUTORIZACAO_ENTREGA
JOIN CPT.COOPERATIVA_FILIAL CF
  ON AE.CD_COOPERATIVA_FILIAL = CF.CD_COOPERATIVA_FILIAL
JOIN CPT.COOPERATIVA COOP
  ON CF.CD_COOPERATIVA = COOP.CD_COOPERATIVA
JOIN CPT.STATUS_ENTREGA SE
  ON E.SG_STATUS = SE.SG_STATUS_ENTREGA
JOIN VND.CONTRATO C
  ON AE.NU_CONTRATO = C.NU_CONTRATO
JOIN VND.ITEM_CONTRATO IC
  ON AE.CD_ITEM_CONTRATO = IC.CD_ITEM_CONTRATO AND C.CD_CONTRATO = IC.CD_CONTRATO
JOIN CTF.PRODUTO_SAP PS
  ON AE.CD_PRODUTO_SAP = PS.CD_PRODUTO_SAP
where nvl(sg_status, 'X') not in ('C', 'P')
--order by ae.nu_contrato,
--         ae.cd_item_contrato
         
union 

select 
    NU_PROTOCOLO_ENTREGA PROTOCOLO,
    AE.NU_CONTRATO CONTRATO,
    AE.CD_ITEM_CONTRATO "ITEM CONTRATO",
    NO_COOPERATIVA COOPERATIVA,
    E.QT_QUANTIDADE "QUANTIDADE SOLICITADA",
    nvl(E.QT_FORNECIDO, 0) "QUANTIDADE FORNECIDA",
    DS_STATUS_ENTREGA "STATUS DA ENTREGA",
    C.DH_INCLUSAO "DATA INCLUSÃO CONTRATO",
    E.DT_INCLUSAO_ENTREGA "DATA INCLUSÃO ENTREGA",
    IC.IC_RECUSADO,
    CASE IC.IC_RECUSADO 
      WHEN 'S' 
        THEN 'SIM'
      ELSE
        'NÃO'
    END "ITEM CONTRATO RECUSADO",
    NO_PRODUTO_SAP PRODUTO
from CPT.ENTREGA E
LEFT JOIN CPT.AUTORIZACAO_ENTREGA AE
  ON E.CD_AUTORIZACAO_ENTREGA = AE.CD_AUTORIZACAO_ENTREGA
left JOIN CPT.COOPERATIVA_FILIAL CF
  ON AE.CD_COOPERATIVA_FILIAL = CF.CD_COOPERATIVA_FILIAL
left JOIN CPT.COOPERATIVA COOP
  ON CF.CD_COOPERATIVA = COOP.CD_COOPERATIVA
left JOIN CPT.STATUS_ENTREGA SE
  ON E.SG_STATUS = SE.SG_STATUS_ENTREGA
left JOIN VND.CONTRATO C
  ON AE.NU_CONTRATO = C.NU_CONTRATO
left JOIN VND.ITEM_CONTRATO IC
  ON AE.CD_ITEM_CONTRATO = IC.CD_ITEM_CONTRATO AND C.CD_CONTRATO = IC.CD_CONTRATO
left JOIN CTF.PRODUTO_SAP PS
  ON AE.CD_PRODUTO_SAP = PS.CD_PRODUTO_SAP
where nvl(sg_status, 'X') not in ('C', 'P')
order by contrato,
         "ITEM CONTRATO";         