        WITH CTE_AGENDAMENTO AS 
        (
        SELECT AGE.CD_ELO_AGENDAMENTO, AGE.CD_CENTRO_EXPEDIDOR, 
        AGE.CD_MACHINE, ma.DS_MACHINE, AGE.CD_WEEK ,
        es.DS_STATUS, AGE.CD_ELO_STATUS
        FROM VND.ELO_AGENDAMENTO AGE 
        LEFT JOIN CTF.MACHINE ma
        on AGE.CD_MACHINE = ma.CD_MACHINE
        inner join VND.ELO_STATUS es
        on es.CD_ELO_STATUS = AGE.CD_ELO_STATUS
        
        WHERE AGE.IC_ATIVO = 'S'
        --AND (es.SG_STATUS IN ('PLAN','AGCTR','AGENC'))
        --AND (P_WEEK is null OR AGE.CD_WEEK = P_WEEK)
        AND ('W212018' is null OR AGE.CD_WEEK = 'W212018')
        --and (P_MACHINES is null OR AGE.CD_MACHINE IN (P_MACHINES))
        
        ),
        --SELECT * FROM CTE_AGENDAMENTO
        
        CTE_PARAM AS (
        /*SELECT 
        NVL(P_INCOTERM, 'CIF') INCOTERMS,
        NVL(P_PACKAGE,'0')  CD_GRUPO_EMBALAGEM, 
        NVL(P_VOLUME,0) P_VOLUMED,
        V_POLO CD_POLO
        FROM DUAL
        */
        SELECT 
        'CIF' INCOTERMS,
        'B'  CD_GRUPO_EMBALAGEM, 
        NVL(0,0) P_VOLUMED, 
        'P002' CD_POLO
        FROM DUAL  
        --SELECT * FROM CTF.POLO_CENTRO_EXPEDIDOR      
        
        ) , 
        --SELECT * FROM CTE_PARAM
        
        CTE_WEEK_DAYS AS 
        (
        /*
            select regexp_substr(P_WEEKDAYS,'[^,]+', 1, level) NU_DIA_SEMANA from dual
            where P_WEEKDAYS IS NOT NULL
            connect by regexp_substr(P_WEEKDAYS, '[^,]+', 1, level) is not null )
            union 
            select regexp_substr('0,1,2,3,4,5,6,7','[^,]+', 1, level) NU_DIA_SEMANA  from dual 
            where null is null 
            connect by regexp_substr('0,1,2,3,4,5,6,7', '[^,]+', 1, level) is not null               
        */
            select regexp_substr('1,2,3,4,5,6,7','[^,]+', 1, level) NU_DIA_SEMANA  from dual 
            where null is not null 
            connect by regexp_substr('1,2,3,4,5,6,7', '[^,]+', 1, level) is not null
            union 
            select regexp_substr('0,1,2,3,4,5,6,7','[^,]+', 1, level) NU_DIA_SEMANA  from dual 
            where null is null 
            connect by regexp_substr('0,1,2,3,4,5,6,7', '[^,]+', 1, level) is not null             
        
        ), 
        --SELECT * FROM CTE_WEEK_DAYS 
        
    CTE_CARTEIRA AS 
        (
        
        SELECT DISTINCT 
        CTAF.CD_ELO_CARTEIRA , 
        CTAF.CD_ELO_AGENDAMENTO, 
        CTAF.CD_TIPO_AGENDAMENTO, 
        CTAF.CD_TIPO_REPLAN, 
        CTAF.QT_AGENDADA_CONFIRMADA,
        CTAF.CD_ELO_AGENDAMENTO_ITEM,
        CTAF.CD_INCOTERMS,
        CTAF.CD_CLIENTE ,
        CTAF.NO_CLIENTE ,
        CTAF.DH_BACKLOG_CIF,
        NVL((SELECT DS.DS_CENTRO_EXPEDIDOR 
        FROM CTF.CENTRO_EXPEDIDOR DS 
        WHERE DS.CD_CENTRO_EXPEDIDOR = CTAF.CD_CENTRO_EXPEDIDOR_FABRICA), CTAF.DS_CENTRO_EXPEDIDOR) DS_CENTRO_EXPEDIDOR,
        NVL(CTAF.CD_CENTRO_EXPEDIDOR_FABRICA, CTAF.CD_CENTRO_EXPEDIDOR) CD_CENTRO_EXPEDIDOR,

        CTAF.CD_SALES_GROUP,
        CTAF.CD_GRUPO_EMBALAGEM,
        CTAF.IC_ATIVO,
        CTAF.QT_SALDO
        FROM VND.ELO_CARTEIRA CTAF
        INNER JOIN CTE_AGENDAMENTO AGEF
        ON CTAF.CD_ELO_AGENDAMENTO = AGEF.CD_ELO_AGENDAMENTO
        WHERE
        CTAF.IC_ATIVO = 'S'
        --and (P_CD_CENTRO is null or CTAF.CD_CENTRO_EXPEDIDOR = P_CD_CENTRO)
        --AND (P_CD_CENTRO is null OR  
        and ('6023' IS NULL OR 
        
        EXISTS (SELECT 1 FROM CTF.POLO_CENTRO_EXPEDIDOR pc, CTE_PARAM PAR 
        WHERE pc.CD_CENTRO_EXPEDIDOR = NVL(CTAF.CD_CENTRO_EXPEDIDOR_FABRICA,CTAF.CD_CENTRO_EXPEDIDOR )
        AND pc.CD_POLO = PAR.CD_POLO )) 
        --and ('6060' is null or CTAF.CD_CENTRO_EXPEDIDOR = '6060')
        --AND (NVL(CTAF.QT_AGENDADA_CONFIRMADA,0) <> 0 AND (CTAF.IC_CORTADO_FABRICA <> 1 OR CTAF.IC_CORTADO_FABRICA IS NULL))
        AND CTAF.CD_STATUS_CEL_FINAL = 59
        AND ((CTAF.QT_AGENDADA_CONFIRMADA > 0 AND CTAF.CD_TIPO_AGENDAMENTO = 25 AND CTAF.CD_STATUS_REPLAN = 32)
          OR (CTAF.CD_TIPO_AGENDAMENTO IN (22, 23, 24) AND CTAF.QT_AGENDADA_CONFIRMADA > 0)
          )

    and ('CX' is null OR UPPER(CTAF.NO_CLIENTE) = UPPER('USINA SANTA LUCIA S/A'))        

        --and (P_NO_CLIENTE is null OR UPPER(CTAF.NO_CLIENTE) = UPPER(P_NO_CLIENTE))
        --and ((P_INCOTERM IS NULL ) OR (P_INCOTERM = CTAF.CD_INCOTERMS ))
        --and (P_PACKAGE is null OR CTAF.CD_GRUPO_EMBALAGEM = P_PACKAGE)     -- nao ativar     
          
        
        ),
        --SELECT * FROM CTE_CARTEIRA
        
        CTE_AGENDAMENTO_FILTER AS 
        (
        SELECT ag.CD_ELO_AGENDAMENTO, ag.CD_CENTRO_EXPEDIDOR, ag.CD_MACHINE, ag.DS_MACHINE, ag.CD_WEEK , ag.DS_STATUS, ag.CD_ELO_STATUS
        FROM CTE_AGENDAMENTO ag
        WHERE 
            EXISTS (
                    SELECT 1 FROM CTE_CARTEIRA CTA 
                    WHERE 
                    CTA.CD_ELO_AGENDAMENTO = ag.CD_ELO_AGENDAMENTO
                    )
        ),
        --SELECT * FROM CTE_AGENDAMENTO_FILTER
        
        ELO_AG_DAY_BY_INCOTERMS_ITEM  AS (
        SELECT  EA_SUP_I.CD_ELO_AGENDAMENTO, EAG_ITEM_I.CD_ELO_AGENDAMENTO_ITEM, EAG_ITEM_I.CD_INCOTERMS, 
        DAYY.CD_GRUPO_EMBALAGEM, DAYY.NU_DIA_SEMANA, SUM(DAYY.NU_QUANTIDADE) NU_QUANTIDADE, 
        MAX(CD_COTA_COMPARTILHADA) CD_COTA_COMPARTILHADA, EAG_ITEM_I.CD_CLIENTE
        FROM CTE_AGENDAMENTO_FILTER FILT
        INNER JOIN VND.ELO_AGENDAMENTO_SUPERVISOR EA_SUP_I  
        ON FILT.CD_ELO_AGENDAMENTO = EA_SUP_I.CD_ELO_AGENDAMENTO
        INNER JOIN VND.VW_ELO_AGENDAMENTO_ITEM_R EAG_ITEM_I
        ON 
        EAG_ITEM_I.CD_ELO_AGENDAMENTO_SUPERVISOR = EA_SUP_I.CD_ELO_AGENDAMENTO_SUPERVISOR
        AND EAG_ITEM_I.IC_ATIVO = 'S'	
        
        INNER JOIN VND.ELO_AGENDAMENTO_WEEK EAG_WE_I
        ON EAG_ITEM_I.CD_ELO_AGENDAMENTO_ITEM = EAG_WE_I.CD_ELO_AGENDAMENTO_ITEM
        
        --LEFT JOIN VND.ELO_AGENDAMENTO_GROUPING EAG_GRO_I
        --ON EAG_GRO_I.CD_ELO_AGENDAMENTO_WEEK = EAG_WE_I.CD_ELO_AGENDAMENTO_WEEK
        INNER JOIN VND.ELO_AGENDAMENTO_DAY DAYY
        ON 
        DAYY.CD_ELO_AGENDAMENTO_WEEK = EAG_WE_I.CD_ELO_AGENDAMENTO_WEEK
        
        WHERE 
        EA_SUP_I.IC_ATIVO = 'S'
        --and ((NVL('G', '0') ='0') OR (DAYY.CD_GRUPO_EMBALAGEM = 'G'))   
        and ((NVL((SELECT PAR.CD_GRUPO_EMBALAGEM FROM CTE_PARAM PAR WHERE ROWNUM=1), '0') = '0') 
        OR (DAYY.CD_GRUPO_EMBALAGEM = (SELECT PAR.CD_GRUPO_EMBALAGEM FROM CTE_PARAM PAR WHERE ROWNUM=1)))   
        AND             EXISTS (
                    SELECT 1 FROM CTE_CARTEIRA CTA 
                    WHERE 
                    CTA.CD_ELO_AGENDAMENTO_ITEM = EAG_ITEM_I.CD_ELO_AGENDAMENTO_ITEM
                    )
                                        
        GROUP BY  EA_SUP_I.CD_ELO_AGENDAMENTO, EAG_ITEM_I.CD_ELO_AGENDAMENTO_ITEM, 
        EAG_ITEM_I.CD_INCOTERMS, DAYY.CD_GRUPO_EMBALAGEM, DAYY.NU_DIA_SEMANA , EAG_ITEM_I.CD_CLIENTE                                   
        )   ,
        --SELECT * FROM ELO_AG_DAY_BY_INCOTERMS_ITEM

       ELO_AG_DAY AS (
        SELECT  EADBI.CD_ELO_AGENDAMENTO, EADBI.CD_GRUPO_EMBALAGEM, 
        EADBI.NU_DIA_SEMANA, SUM(EADBI.NU_QUANTIDADE) NU_QUANTIDADE,
        EADBI.CD_INCOTERMS,
        EADBI.CD_CLIENTE
        FROM ELO_AG_DAY_BY_INCOTERMS_ITEM EADBI
        GROUP BY  EADBI.CD_ELO_AGENDAMENTO,  EADBI.CD_GRUPO_EMBALAGEM, EADBI.NU_DIA_SEMANA , 
        EADBI.CD_INCOTERMS, EADBI.CD_CLIENTE                                   
        ) ,  
        --SELECT * FROM ELO_AG_DAY
        CTE_EMB_INCOTERMS_DIA AS 
        (
        SELECT 
        EEID.CD_INCOTERMS,
        EEID.CD_GRUPO_EMBALAGEM,
        EEID.NU_DIA_SEMANA
        FROM ELO_EMBALAGEM_INCOTERMS EEID,
        CTE_WEEK_DAYS EDDAY
        WHERE 
        (EEID.NU_DIA_SEMANA =  EDDAY.NU_DIA_SEMANA)
        and ((NVL((SELECT PAR.CD_GRUPO_EMBALAGEM FROM CTE_PARAM PAR WHERE ROWNUM=1), '0') = '0') 
        OR (EEID.CD_GRUPO_EMBALAGEM = (SELECT PAR.CD_GRUPO_EMBALAGEM FROM CTE_PARAM PAR WHERE ROWNUM=1)))                                 
                                         
        ),
        --SELECT * FROM CTE_EMB_INCOTERMS_DIA
        
       
CTE_CENARIO_CIF_FOB AS 
(
    select  
    ag.CD_ELO_AGENDAMENTO ,
    (select d.CD_ELO_CARTEIRA 
    FROM CTE_CARTEIRA D 
    where d.CD_ELO_AGENDAMENTO_ITEM = AGDAY.CD_ELO_AGENDAMENTO_ITEM 
    AND ROWNUM =1 ) CD_ELO_CARTEIRA ,
    ag.CD_WEEK ,
    ag.CD_ELO_STATUS ,
    ag.DS_STATUS  ,
    --TO_CHAR(ec.CD_TIPO_REPLAN) || '-' || estrp.DS_STATUS                 as TIPO_REPLAN,
    (select d.CD_TIPO_REPLAN  || '-' || estrp.DS_STATUS
    FROM CTE_CARTEIRA D 
    INNER JOIN VND.ELO_STATUS estrp
    ON d.CD_TIPO_REPLAN = estrp.CD_ELO_STATUS
    where d.CD_ELO_AGENDAMENTO_ITEM = AGDAY.CD_ELO_AGENDAMENTO_ITEM 
    AND ROWNUM =1 ) TIPO_REPLAN,
    --------------------- ADD ADRIANO -- 2018-05-04
        (select CASE WHEN NVL(d.CD_TIPO_AGENDAMENTO,22) IN (22, 23, 24) THEN 22 ELSE d.CD_TIPO_AGENDAMENTO END 
    FROM CTE_CARTEIRA D 
    where d.CD_ELO_AGENDAMENTO_ITEM = AGDAY.CD_ELO_AGENDAMENTO_ITEM 
    AND ROWNUM =1 ) CD_TIPO_AGENDAMENTO,
    --------------------- ADD ADRIANO -- 2018-05-04    
    
    --to_char(ec.DH_BACKLOG_CIF)  DH_BACKLOG_CIF,
    (select d.DH_BACKLOG_CIF 
    FROM CTE_CARTEIRA D 
    where d.CD_ELO_AGENDAMENTO_ITEM = AGDAY.CD_ELO_AGENDAMENTO_ITEM 
    AND ROWNUM =1 ) DH_BACKLOG_CIF,
    (select d.DS_CENTRO_EXPEDIDOR 
    FROM CTE_CARTEIRA D 
    where d.CD_ELO_AGENDAMENTO_ITEM = AGDAY.CD_ELO_AGENDAMENTO_ITEM 
    AND d.DS_CENTRO_EXPEDIDOR is not null
    AND ROWNUM =1 ) DS_CENTRO_EXPEDIDOR ,
    NVL(ag.CD_CENTRO_EXPEDIDOR, ( select d.CD_CENTRO_EXPEDIDOR 
    FROM CTE_CARTEIRA D 
    where d.CD_ELO_AGENDAMENTO_ITEM = AGDAY.CD_ELO_AGENDAMENTO_ITEM 
    AND d.CD_CENTRO_EXPEDIDOR is not null
    AND ROWNUM =1  )) CD_CENTRO_EXPEDIDOR,
    ma.DS_MACHINE ,
    ma.CD_MACHINE,
    AGDAY.CD_INCOTERMS ,
    AGDAY.CD_CLIENTE ,
    NVL(CLI.NO_CLIENTE, (select d.NO_CLIENTE 
    FROM CTE_CARTEIRA D 
    where d.CD_ELO_AGENDAMENTO_ITEM = AGDAY.CD_ELO_AGENDAMENTO_ITEM 
    AND ROWNUM =1 )) NO_CLIENTE  ,
    --eai.CD_COTA_COMPARTILHADA                                            as COTA,
    '' AS COTA,
    (SELECT u.CD_USUARIO || '-' || u.NO_USUARIO 
    FROM CTE_CARTEIRA d 
    INNER JOIN CTF.USUARIO u
    on D.CD_SALES_GROUP = u.CD_USUARIO_ORIGINAL
    where d.CD_ELO_AGENDAMENTO_ITEM = AGDAY.CD_ELO_AGENDAMENTO_ITEM 
    AND ROWNUM =1) as SUPERVISOR,
    (SELECT GEI.DS_GRUPO_EMBALAGEM FROM VND.GRUPO_EMBALAGEM GEI 
        WHERE AGDAY.CD_GRUPO_EMBALAGEM = GEI.CD_GRUPO_EMBALAGEM ) as EMBALAGEM,
    ''     as DIA_EXATO,
    AGDAY.NU_QUANTIDADE   as VALOR,
    AGDAY.CD_ELO_AGENDAMENTO_ITEM,
    AGDAY.CD_COTA_COMPARTILHADA,
    AGDAY.NU_DIA_SEMANA,
    AGDAY.CD_GRUPO_EMBALAGEM
    
    FROM ELO_AG_DAY_BY_INCOTERMS_ITEM AGDAY
    INNER JOIN CTE_AGENDAMENTO_FILTER ag
    ON 
    ag.CD_ELO_AGENDAMENTO = AGDAY.CD_ELO_AGENDAMENTO
    left join CTF.MACHINE ma
    on ag.CD_MACHINE = ma.CD_MACHINE
    
    left JOIN  CTF.CLIENTE CLI
    ON AGDAY.CD_CLIENTE = CLI.CD_CLIENTE
    INNER JOIN CTE_EMB_INCOTERMS_DIA FILTRO_DIA
    ON 
    FILTRO_DIA.CD_INCOTERMS = AGDAY.CD_INCOTERMS
    AND FILTRO_DIA.CD_GRUPO_EMBALAGEM = AGDAY.CD_GRUPO_EMBALAGEM
    AND FILTRO_DIA.NU_DIA_SEMANA = AGDAY.NU_DIA_SEMANA
    
    WHERE 
    AGDAY.CD_INCOTERMS IN( 'CIF', 'FOB')
    AND FILTRO_DIA.CD_INCOTERMS IN( 'CIF', 'FOB')
   
  
),
--SELECT * FROM CTE_CENARIO_CIF_FOB

CTE_FOB AS 
(
    select --distinct 
    eai.CD_ELO_CARTEIRA  ,
    eai.CD_CENTRO_EXPEDIDOR ,
    eai.DS_CENTRO_EXPEDIDOR,
    eai.CD_CLIENTE ,
    eai.NO_CLIENTE  ,
    eai.CD_MACHINE ,
    eai.DS_MACHINE  ,
    eai.CD_INCOTERMS,
    eai.EMBALAGEM ,
    eai.CD_COTA_COMPARTILHADA,
    -----------------------------------------------------------------                        
    NVL(( SELECT SUM(DD_DAY.NU_QUANTIDADE) NU_QUANTIDADE 
    FROM ELO_AG_DAY_BY_INCOTERMS_ITEM DD_DAY
    WHERE DD_DAY.CD_ELO_AGENDAMENTO = eai.CD_ELO_AGENDAMENTO
    and DD_DAY.CD_ELO_AGENDAMENTO_ITEM = eai.CD_ELO_AGENDAMENTO_ITEM
    AND DD_DAY.CD_INCOTERMS = 'FOB'
    and DD_DAY.NU_DIA_SEMANA = eai.NU_DIA_SEMANA
    AND DD_DAY.CD_INCOTERMS = eai.CD_INCOTERMS
    AND DD_DAY.CD_GRUPO_EMBALAGEM = eai.CD_GRUPO_EMBALAGEM
    AND DD_DAY.CD_CLIENTE = eai.CD_CLIENTE
    
    ),0) QT_AGENDADA_CONF_OU_BYDAY ,
    -----------------------------------------------------------------
    greatest(NVL(( SELECT SUM(DD_DAY.NU_QUANTIDADE) NU_QUANTIDADE 
    FROM ELO_AG_DAY_BY_INCOTERMS_ITEM DD_DAY
    WHERE DD_DAY.CD_ELO_AGENDAMENTO = eai.CD_ELO_AGENDAMENTO
    and DD_DAY.CD_ELO_AGENDAMENTO_ITEM = eai.CD_ELO_AGENDAMENTO_ITEM
    AND DD_DAY.CD_INCOTERMS = 'FOB'
    and DD_DAY.NU_DIA_SEMANA = eai.NU_DIA_SEMANA
    AND DD_DAY.CD_INCOTERMS = eai.CD_INCOTERMS
    AND DD_DAY.CD_GRUPO_EMBALAGEM = eai.CD_GRUPO_EMBALAGEM
    AND DD_DAY.CD_CLIENTE = eai.CD_CLIENTE
    
    ),0) -  NVL((SELECT SUM(E_MAR.NU_QUANTIDADE) NU_QUANTIDADE 
    FROM VND.ELO_MARCACAO E_MAR
    INNER JOIN CTE_CARTEIRA ec
    ON ec.CD_ELO_CARTEIRA = E_MAR.CD_ELO_CARTEIRA
    WHERE 
    E_MAR.IC_DESISTENCIA = 'N' 
    AND E_MAR.IC_DISPENSADO = 'N'
    AND E_MAR.CD_CLIENTE = eai.CD_CLIENTE
    AND E_MAR.CD_GRUPO_EMBALAGEM = eai.CD_GRUPO_EMBALAGEM 
    AND ec.CD_ELO_AGENDAMENTO_ITEM = eai.CD_ELO_AGENDAMENTO_ITEM
    AND E_MAR.CD_INCOTERMS = eai.CD_INCOTERMS
    
     AND EXISTS (SELECT 1 
                    FROM CTE_EMB_INCOTERMS_DIA FIL_DIA
                    WHERE 
                    FIL_DIA.CD_GRUPO_EMBALAGEM = E_MAR.CD_GRUPO_EMBALAGEM
                    AND FIL_DIA.CD_INCOTERMS = 'FOB'
                    AND FIL_DIA.NU_DIA_SEMANA = (1 + TRUNC (E_MAR.DH_MARCACAO) - TRUNC (E_MAR.DH_MARCACAO, 'IW')) 
                    )
    AND E_MAR.SG_CLASSIFICACAO = 'Plan')  ,0),0) QT_AGENDADA_CORTE , 

    --------------------------------------------------------                          
    
    NVL((SELECT SUM(E_MAR.NU_QUANTIDADE) NU_QUANTIDADE 
    FROM VND.ELO_MARCACAO E_MAR
    INNER JOIN CTE_CARTEIRA ec
    ON ec.CD_ELO_CARTEIRA = E_MAR.CD_ELO_CARTEIRA
    WHERE 
    E_MAR.IC_DESISTENCIA = 'N' 
    AND E_MAR.IC_DISPENSADO = 'N'
    AND E_MAR.CD_CLIENTE = eai.CD_CLIENTE
    AND E_MAR.CD_GRUPO_EMBALAGEM = eai.CD_GRUPO_EMBALAGEM 
    AND ec.CD_ELO_AGENDAMENTO_ITEM = eai.CD_ELO_AGENDAMENTO_ITEM
    AND E_MAR.CD_INCOTERMS = eai.CD_INCOTERMS
    
     AND EXISTS (SELECT 1 
                    FROM CTE_EMB_INCOTERMS_DIA FIL_DIA  --CONSIDERAR SOMENTE FOB AQUELE CLIENTE
                    WHERE 
                    FIL_DIA.CD_GRUPO_EMBALAGEM = E_MAR.CD_GRUPO_EMBALAGEM
                    AND FIL_DIA.CD_INCOTERMS = 'FOB'
                    AND FIL_DIA.NU_DIA_SEMANA = (1 + TRUNC (E_MAR.DH_MARCACAO) - TRUNC (E_MAR.DH_MARCACAO, 'IW')) 
                    )
    AND E_MAR.SG_CLASSIFICACAO = 'Plan')  ,0)  SOMA_MARCACAO,
    --------------------------------------------------------
    999999999  SOMA_MARCACAO_SEMANA,

    --NVL(0,0) P_VOLUMED, 
    NVL((SELECT PAR.P_VOLUMED FROM CTE_PARAM PAR WHERE ROWNUM=1),0) P_VOLUMED, 

    0   as SaldoReplanejado,
     
    NVL(eai.CD_COTA_COMPARTILHADA, 0)   as CompartCota,
    NVL(( SELECT SUM(DD_DAY.NU_QUANTIDADE) NU_QUANTIDADE 
    FROM ELO_AG_DAY_BY_INCOTERMS_ITEM DD_DAY
    WHERE DD_DAY.CD_ELO_AGENDAMENTO = eai.CD_ELO_AGENDAMENTO
    and DD_DAY.CD_ELO_AGENDAMENTO_ITEM = eai.CD_ELO_AGENDAMENTO_ITEM
    and DD_DAY.NU_DIA_SEMANA = eai.NU_DIA_SEMANA
    and DD_DAY.CD_INCOTERMS = eai.CD_INCOTERMS
    AND DD_DAY.CD_CLIENTE = eai.CD_CLIENTE
    AND DD_DAY.CD_GRUPO_EMBALAGEM = eai.CD_GRUPO_EMBALAGEM
    AND DD_DAY.CD_INCOTERMS = 'FOB'
    --and DD_DAY.CD_ELO_AGENDAMENTO_ITEM = ec.CD_ELO_AGENDAMENTO_ITEM
    
    ),0) VOLUME_MAXIMO_FOB , 
    eai.NU_DIA_SEMANA,
    eai.CD_TIPO_AGENDAMENTO

    FROM CTE_CENARIO_CIF_FOB eai
    WHERE eai.CD_INCOTERMS = 'FOB'
    AND eai.CD_TIPO_AGENDAMENTO = 22 
UNION

    select --distinct 
    eai.CD_ELO_CARTEIRA  ,
    eai.CD_CENTRO_EXPEDIDOR ,
    eai.DS_CENTRO_EXPEDIDOR,
    eai.CD_CLIENTE ,
    eai.NO_CLIENTE  ,
    eai.CD_MACHINE ,
    eai.DS_MACHINE  ,
    eai.CD_INCOTERMS,
    eai.EMBALAGEM ,
    eai.CD_COTA_COMPARTILHADA,
    -----------------------------------------------------------------                        
    NVL(( SELECT SUM(DD_DAY.NU_QUANTIDADE) NU_QUANTIDADE 
    FROM ELO_AG_DAY_BY_INCOTERMS_ITEM DD_DAY
    WHERE DD_DAY.CD_ELO_AGENDAMENTO = eai.CD_ELO_AGENDAMENTO
    and DD_DAY.CD_ELO_AGENDAMENTO_ITEM = eai.CD_ELO_AGENDAMENTO_ITEM
    AND DD_DAY.CD_INCOTERMS = 'FOB'
    and DD_DAY.NU_DIA_SEMANA = eai.NU_DIA_SEMANA
    AND DD_DAY.CD_INCOTERMS = eai.CD_INCOTERMS
    AND DD_DAY.CD_GRUPO_EMBALAGEM = eai.CD_GRUPO_EMBALAGEM
    AND DD_DAY.CD_CLIENTE = eai.CD_CLIENTE
    
    ),0) QT_AGENDADA_CONF_OU_BYDAY ,
    -----------------------------------------------------------------
    greatest(NVL(( SELECT SUM(DD_DAY.NU_QUANTIDADE) NU_QUANTIDADE 
    FROM ELO_AG_DAY_BY_INCOTERMS_ITEM DD_DAY
    WHERE DD_DAY.CD_ELO_AGENDAMENTO = eai.CD_ELO_AGENDAMENTO
    and DD_DAY.CD_ELO_AGENDAMENTO_ITEM = eai.CD_ELO_AGENDAMENTO_ITEM
    AND DD_DAY.CD_INCOTERMS = 'FOB'
    and DD_DAY.NU_DIA_SEMANA = eai.NU_DIA_SEMANA
    AND DD_DAY.CD_INCOTERMS = eai.CD_INCOTERMS
    AND DD_DAY.CD_GRUPO_EMBALAGEM = eai.CD_GRUPO_EMBALAGEM
    AND DD_DAY.CD_CLIENTE = eai.CD_CLIENTE
    
    ),0) -  NVL((SELECT SUM(E_MAR.NU_QUANTIDADE) NU_QUANTIDADE 
    FROM VND.ELO_MARCACAO E_MAR
    INNER JOIN CTE_CARTEIRA ec
    ON ec.CD_ELO_CARTEIRA = E_MAR.CD_ELO_CARTEIRA
    WHERE 
    E_MAR.IC_DESISTENCIA = 'N' 
    AND E_MAR.IC_DISPENSADO = 'N'
    AND E_MAR.CD_CLIENTE = eai.CD_CLIENTE
    AND E_MAR.CD_GRUPO_EMBALAGEM = eai.CD_GRUPO_EMBALAGEM 
    AND ec.CD_ELO_AGENDAMENTO_ITEM = eai.CD_ELO_AGENDAMENTO_ITEM
    AND E_MAR.CD_INCOTERMS = eai.CD_INCOTERMS
    
     AND EXISTS (SELECT 1 
                    FROM CTE_EMB_INCOTERMS_DIA FIL_DIA
                    WHERE 
                    FIL_DIA.CD_GRUPO_EMBALAGEM = E_MAR.CD_GRUPO_EMBALAGEM
                    AND FIL_DIA.CD_INCOTERMS = 'FOB'
                    AND FIL_DIA.NU_DIA_SEMANA = (1 + TRUNC (E_MAR.DH_MARCACAO) - TRUNC (E_MAR.DH_MARCACAO, 'IW')) 
                    )
    AND E_MAR.SG_CLASSIFICACAO = 'Replan')  ,0),0) QT_AGENDADA_CORTE , 

    --------------------------------------------------------                          
    
    NVL((SELECT SUM(E_MAR.NU_QUANTIDADE) NU_QUANTIDADE 
    FROM VND.ELO_MARCACAO E_MAR
    INNER JOIN CTE_CARTEIRA ec
    ON ec.CD_ELO_CARTEIRA = E_MAR.CD_ELO_CARTEIRA
    WHERE 
    E_MAR.IC_DESISTENCIA = 'N' 
    AND E_MAR.IC_DISPENSADO = 'N'
    AND E_MAR.CD_CLIENTE = eai.CD_CLIENTE
    AND E_MAR.CD_GRUPO_EMBALAGEM = eai.CD_GRUPO_EMBALAGEM 
    AND ec.CD_ELO_AGENDAMENTO_ITEM = eai.CD_ELO_AGENDAMENTO_ITEM
    AND E_MAR.CD_INCOTERMS = eai.CD_INCOTERMS
    
     AND EXISTS (SELECT 1 
                    FROM CTE_EMB_INCOTERMS_DIA FIL_DIA  --CONSIDERAR SOMENTE FOB AQUELE CLIENTE
                    WHERE 
                    FIL_DIA.CD_GRUPO_EMBALAGEM = E_MAR.CD_GRUPO_EMBALAGEM
                    AND FIL_DIA.CD_INCOTERMS = 'FOB'
                    AND FIL_DIA.NU_DIA_SEMANA = (1 + TRUNC (E_MAR.DH_MARCACAO) - TRUNC (E_MAR.DH_MARCACAO, 'IW')) 
                    )
    AND E_MAR.SG_CLASSIFICACAO = 'Replan')  ,0)  SOMA_MARCACAO,
    --------------------------------------------------------
    999999999  SOMA_MARCACAO_SEMANA,

    --NVL(0,0) P_VOLUMED, 
   NVL((SELECT PAR.P_VOLUMED FROM CTE_PARAM PAR WHERE ROWNUM=1),0) P_VOLUMED,

    0   as SaldoReplanejado,
     
    NVL(eai.CD_COTA_COMPARTILHADA, 0)   as CompartCota,
    NVL(( SELECT SUM(DD_DAY.NU_QUANTIDADE) NU_QUANTIDADE 
    FROM ELO_AG_DAY_BY_INCOTERMS_ITEM DD_DAY
    WHERE DD_DAY.CD_ELO_AGENDAMENTO = eai.CD_ELO_AGENDAMENTO
    and DD_DAY.CD_ELO_AGENDAMENTO_ITEM = eai.CD_ELO_AGENDAMENTO_ITEM
    and DD_DAY.NU_DIA_SEMANA = eai.NU_DIA_SEMANA
    and DD_DAY.CD_INCOTERMS = eai.CD_INCOTERMS
    AND DD_DAY.CD_CLIENTE = eai.CD_CLIENTE
    AND DD_DAY.CD_GRUPO_EMBALAGEM = eai.CD_GRUPO_EMBALAGEM
    AND DD_DAY.CD_INCOTERMS = 'FOB'
    --and DD_DAY.CD_ELO_AGENDAMENTO_ITEM = ec.CD_ELO_AGENDAMENTO_ITEM
    
    ),0) VOLUME_MAXIMO_FOB , 
    eai.NU_DIA_SEMANA,
    eai.CD_TIPO_AGENDAMENTO

    FROM CTE_CENARIO_CIF_FOB eai
    WHERE eai.CD_INCOTERMS = 'FOB'
    AND eai.CD_TIPO_AGENDAMENTO = 25 

),
--SELECT * FROM CTE_FOB

CTE_CIF AS 
(
    select --distinct 
    eai.CD_ELO_CARTEIRA  ,
    eai.CD_CENTRO_EXPEDIDOR ,
    eai.DS_CENTRO_EXPEDIDOR,
    eai.CD_CLIENTE ,
    eai.NO_CLIENTE  ,
    eai.CD_MACHINE ,
    eai.DS_MACHINE  ,
    eai.CD_INCOTERMS,
    eai.EMBALAGEM ,
    eai.CD_COTA_COMPARTILHADA,
    -----------------------------------------------------------------                        
    NVL(
    NVL(((
    SELECT SUM(AGEMAT.NU_QUANTIDADE)  NU_QUANTIDADE 
     
    FROM ELO_CONTROLLERSHIP_MATINAL AGEMAT
    WHERE AGEMAT.CD_ELO_AGENDAMENTO = eai.CD_ELO_AGENDAMENTO
    --and AGEMAT.CD_ELO_AGENDAMENTO_ITEM = eai.CD_ELO_AGENDAMENTO_ITEM
    AND eai.CD_INCOTERMS = 'CIF'
    and AGEMAT.NU_DIA_SEMANA = eai.NU_DIA_SEMANA
    --AND AGEMAT.CD_INCOTERMS = eai.CD_INCOTERMS
    AND AGEMAT.CD_GRUPO_EMBALAGEM = eai.CD_GRUPO_EMBALAGEM
    AND AGEMAT.CD_CENTRO_EXPEDIDOR = eai.CD_CENTRO_EXPEDIDOR
    --AND AGEMAT.CD_CLIENTE = eai.CD_CLIENTE
    ) / (SELECT COUNT(1) TOTAL 
    FROM ELO_AG_DAY_BY_INCOTERMS_ITEM DD_DAY 
    WHERE 
    eai.CD_INCOTERMS = DD_DAY.CD_INCOTERMS
    AND DD_DAY.CD_GRUPO_EMBALAGEM = eai.CD_GRUPO_EMBALAGEM
    --AND DD_DAY.CD_CENTRO_EXPEDIDOR = eai.CD_CENTRO_EXPEDIDOR
    AND DD_DAY.CD_CLIENTE = eai.CD_CLIENTE
    AND DD_DAY.NU_DIA_SEMANA = eai.NU_DIA_SEMANA
    AND eai.CD_INCOTERMS = 'CIF'
    
    )
    
    
    )
    
    ,
    ( SELECT SUM(DD_DAY.NU_QUANTIDADE) NU_QUANTIDADE 
    FROM ELO_AG_DAY_BY_INCOTERMS_ITEM DD_DAY
    WHERE DD_DAY.CD_ELO_AGENDAMENTO = eai.CD_ELO_AGENDAMENTO
    --and DD_DAY.CD_ELO_AGENDAMENTO_ITEM = eai.CD_ELO_AGENDAMENTO_ITEM
    AND DD_DAY.CD_INCOTERMS = 'CIF'
    and DD_DAY.NU_DIA_SEMANA = eai.NU_DIA_SEMANA
    AND DD_DAY.CD_INCOTERMS = eai.CD_INCOTERMS
    AND DD_DAY.CD_GRUPO_EMBALAGEM = eai.CD_GRUPO_EMBALAGEM
    --AND DD_DAY.CD_CLIENTE = eai.CD_CLIENTE
    )
    )
    ,0) QT_AGENDADA_CONF_OU_BYDAY ,
    -----------------------------------------------------------------
    GREATEST(NVL(
    CASE 
    WHEN NVL((SELECT EDDAY.NU_DIA_SEMANA 
        FROM CTE_WEEK_DAYS EDDAY 
        WHERE EDDAY.NU_DIA_SEMANA = '0'),'0') = '0' 
        THEN --P_WEEKDAYS IS NULL THEN 
    (SELECT SUM(DD_DAY.NU_QUANTIDADE) NU_QUANTIDADE 
    FROM ELO_AG_DAY_BY_INCOTERMS_ITEM DD_DAY
    WHERE DD_DAY.CD_ELO_AGENDAMENTO = eai.CD_ELO_AGENDAMENTO
    and DD_DAY.CD_ELO_AGENDAMENTO_ITEM = eai.CD_ELO_AGENDAMENTO_ITEM
    AND DD_DAY.CD_INCOTERMS = 'CIF'
    and DD_DAY.NU_DIA_SEMANA = eai.NU_DIA_SEMANA 
    AND DD_DAY.CD_INCOTERMS = eai.CD_INCOTERMS
    AND DD_DAY.CD_GRUPO_EMBALAGEM = eai.CD_GRUPO_EMBALAGEM
    AND DD_DAY.CD_CLIENTE = eai.CD_CLIENTE)
    ELSE
    (SELECT SUM(DD_DAY.NU_QUANTIDADE) NU_QUANTIDADE 
    FROM ELO_AG_DAY_BY_INCOTERMS_ITEM DD_DAY
    WHERE DD_DAY.CD_ELO_AGENDAMENTO = eai.CD_ELO_AGENDAMENTO
    --and DD_DAY.CD_ELO_AGENDAMENTO_ITEM = eai.CD_ELO_AGENDAMENTO_ITEM
    AND DD_DAY.CD_INCOTERMS = 'CIF'
    --and DD_DAY.NU_DIA_SEMANA = eai.NU_DIA_SEMANA 
    AND DD_DAY.CD_INCOTERMS = eai.CD_INCOTERMS
    AND DD_DAY.CD_GRUPO_EMBALAGEM = eai.CD_GRUPO_EMBALAGEM
    AND DD_DAY.CD_CLIENTE = eai.CD_CLIENTE
    )
    END
    
    ,0) -  NVL((SELECT SUM(E_MAR.NU_QUANTIDADE) NU_QUANTIDADE 
    FROM VND.ELO_MARCACAO E_MAR
    INNER JOIN VND.ELO_CARTEIRA ec
    ON ec.CD_ELO_CARTEIRA = E_MAR.CD_ELO_CARTEIRA
    WHERE 
    E_MAR.IC_DESISTENCIA = 'N' 
    AND E_MAR.IC_DISPENSADO = 'N'
    AND E_MAR.CD_CLIENTE = eai.CD_CLIENTE   --PWEE DAY IS NOT NULL
    AND E_MAR.CD_GRUPO_EMBALAGEM = eai.CD_GRUPO_EMBALAGEM 
    --AND ec.CD_ELO_AGENDAMENTO_ITEM = eai.CD_ELO_AGENDAMENTO_ITEM
    AND E_MAR.CD_INCOTERMS = eai.CD_INCOTERMS
    AND ec.CD_ELO_AGENDAMENTO = eai.CD_ELO_AGENDAMENTO
    
     AND EXISTS (SELECT 1 
                    FROM VND.ELO_EMBALAGEM_INCOTERMS FIL_DIA  --CHOOSE ALL DAYUS ANY WA
                    WHERE 
                    FIL_DIA.CD_GRUPO_EMBALAGEM = E_MAR.CD_GRUPO_EMBALAGEM
                    AND FIL_DIA.CD_INCOTERMS = 'CIF'
                    AND FIL_DIA.NU_DIA_SEMANA = (1 + TRUNC (E_MAR.DH_MARCACAO) - TRUNC (E_MAR.DH_MARCACAO, 'IW')) 
                    )
    AND E_MAR.SG_CLASSIFICACAO = 'Plan')  ,0),0) QT_AGENDADA_CORTE , 


    --------------------------------------------------------                          
    
    NVL((SELECT SUM(E_MAR.NU_QUANTIDADE) NU_QUANTIDADE 
    FROM VND.ELO_MARCACAO E_MAR
    INNER JOIN VND.ELO_CARTEIRA ec
    ON ec.CD_ELO_CARTEIRA = E_MAR.CD_ELO_CARTEIRA
    WHERE 
    E_MAR.IC_DESISTENCIA = 'N' 
    AND E_MAR.IC_DISPENSADO = 'N'
    --AND E_MAR.CD_CLIENTE = eai.CD_CLIENTE
    AND E_MAR.CD_GRUPO_EMBALAGEM = eai.CD_GRUPO_EMBALAGEM 
    AND ec.CD_ELO_AGENDAMENTO = eai.CD_ELO_AGENDAMENTO
    AND E_MAR.CD_INCOTERMS = eai.CD_INCOTERMS
    
     AND EXISTS (SELECT 1 
                    FROM CTE_EMB_INCOTERMS_DIA FIL_DIA  --TODOS OS DIAS 
                    WHERE 
                    FIL_DIA.CD_GRUPO_EMBALAGEM = E_MAR.CD_GRUPO_EMBALAGEM
                    AND FIL_DIA.CD_INCOTERMS = 'CIF'
                    AND FIL_DIA.NU_DIA_SEMANA = (1 + TRUNC (E_MAR.DH_MARCACAO) - TRUNC (E_MAR.DH_MARCACAO, 'IW')) 
                    )
    AND E_MAR.SG_CLASSIFICACAO = 'Plan')  ,0)  SOMA_MARCACAO,
    --------------------------------------------------------
    
    NVL((SELECT SUM(E_MAR.NU_QUANTIDADE) NU_QUANTIDADE 
    FROM VND.ELO_MARCACAO E_MAR
    INNER JOIN VND.ELO_CARTEIRA ec
    ON ec.CD_ELO_CARTEIRA = E_MAR.CD_ELO_CARTEIRA
    WHERE 
    E_MAR.IC_DESISTENCIA = 'N' 
    AND E_MAR.IC_DISPENSADO = 'N'
    --AND E_MAR.CD_CLIENTE = eai.CD_CLIENTE
    AND E_MAR.CD_GRUPO_EMBALAGEM = eai.CD_GRUPO_EMBALAGEM 
    --AND ec.CD_ELO_AGENDAMENTO_ITEM = eai.CD_ELO_AGENDAMENTO_ITEM
    AND ec.CD_ELO_AGENDAMENTO = eai.CD_ELO_AGENDAMENTO
    AND E_MAR.CD_INCOTERMS = eai.CD_INCOTERMS
    
     AND EXISTS (SELECT 1 
                    FROM ELO_EMBALAGEM_INCOTERMS FIL_DIA  --TODOS OS DIAS 
                    WHERE 
                    FIL_DIA.CD_GRUPO_EMBALAGEM = E_MAR.CD_GRUPO_EMBALAGEM
                    AND FIL_DIA.CD_INCOTERMS = 'CIF'
                    AND FIL_DIA.NU_DIA_SEMANA = (1 + TRUNC (E_MAR.DH_MARCACAO) - TRUNC (E_MAR.DH_MARCACAO, 'IW')) 
                    )
    AND E_MAR.SG_CLASSIFICACAO = 'Plan')  ,0)  SOMA_MARCACAO_SEMANA,
        --------------------------------------------------------                          
    
    

    --NVL(0,0) P_VOLUMED, 
    NVL((SELECT PAR.P_VOLUMED FROM CTE_PARAM PAR WHERE ROWNUM=1),0) P_VOLUMED,

    0  as SaldoReplanejado,
     
    NVL(eai.CD_COTA_COMPARTILHADA, 0)   as CompartCota,
    NVL(( SELECT SUM(DD_DAY.NU_QUANTIDADE) NU_QUANTIDADE 
    FROM ELO_AG_DAY_BY_INCOTERMS_ITEM DD_DAY
    WHERE DD_DAY.CD_ELO_AGENDAMENTO = eai.CD_ELO_AGENDAMENTO
    and DD_DAY.CD_ELO_AGENDAMENTO_ITEM = eai.CD_ELO_AGENDAMENTO_ITEM
    and DD_DAY.NU_DIA_SEMANA = eai.NU_DIA_SEMANA
    and DD_DAY.CD_INCOTERMS = eai.CD_INCOTERMS
    AND DD_DAY.CD_CLIENTE = eai.CD_CLIENTE
    AND DD_DAY.CD_GRUPO_EMBALAGEM = eai.CD_GRUPO_EMBALAGEM
    AND DD_DAY.CD_INCOTERMS = 'CIF'
    --and DD_DAY.CD_ELO_AGENDAMENTO_ITEM = ec.CD_ELO_AGENDAMENTO_ITEM
    
    ),0) VOLUME_MAXIMO_FOB   , 
    eai.NU_DIA_SEMANA,
    eai.CD_TIPO_AGENDAMENTO
    

    FROM CTE_CENARIO_CIF_FOB eai
    WHERE eai.CD_INCOTERMS = 'CIF'
    AND eai.CD_TIPO_AGENDAMENTO = 22
    
    UNION
    select --distinct 
    eai.CD_ELO_CARTEIRA  ,
    eai.CD_CENTRO_EXPEDIDOR ,
    eai.DS_CENTRO_EXPEDIDOR,
    eai.CD_CLIENTE ,
    eai.NO_CLIENTE  ,
    eai.CD_MACHINE ,
    eai.DS_MACHINE  ,
    eai.CD_INCOTERMS,
    eai.EMBALAGEM ,
    eai.CD_COTA_COMPARTILHADA,
    -----------------------------------------------------------------                        
    NVL(
    NVL(((
    SELECT SUM(AGEMAT.NU_QUANTIDADE)  NU_QUANTIDADE 
     
    FROM ELO_CONTROLLERSHIP_MATINAL AGEMAT
    WHERE AGEMAT.CD_ELO_AGENDAMENTO = eai.CD_ELO_AGENDAMENTO
    --and AGEMAT.CD_ELO_AGENDAMENTO_ITEM = eai.CD_ELO_AGENDAMENTO_ITEM
    AND eai.CD_INCOTERMS = 'CIF'
    and AGEMAT.NU_DIA_SEMANA = eai.NU_DIA_SEMANA
    --AND AGEMAT.CD_INCOTERMS = eai.CD_INCOTERMS
    AND AGEMAT.CD_GRUPO_EMBALAGEM = eai.CD_GRUPO_EMBALAGEM
    AND AGEMAT.CD_CENTRO_EXPEDIDOR = eai.CD_CENTRO_EXPEDIDOR
    --AND AGEMAT.CD_CLIENTE = eai.CD_CLIENTE
    ) / (SELECT COUNT(1) TOTAL 
    FROM ELO_AG_DAY_BY_INCOTERMS_ITEM DD_DAY 
    WHERE 
    eai.CD_INCOTERMS = DD_DAY.CD_INCOTERMS
    AND DD_DAY.CD_GRUPO_EMBALAGEM = eai.CD_GRUPO_EMBALAGEM
    --AND DD_DAY.CD_CENTRO_EXPEDIDOR = eai.CD_CENTRO_EXPEDIDOR
    AND DD_DAY.CD_CLIENTE = eai.CD_CLIENTE
    AND DD_DAY.NU_DIA_SEMANA = eai.NU_DIA_SEMANA
    AND eai.CD_INCOTERMS = 'CIF'
    
    )
    
    
    )
    
    ,
    ( SELECT SUM(DD_DAY.NU_QUANTIDADE) NU_QUANTIDADE 
    FROM ELO_AG_DAY_BY_INCOTERMS_ITEM DD_DAY
    WHERE DD_DAY.CD_ELO_AGENDAMENTO = eai.CD_ELO_AGENDAMENTO
    --and DD_DAY.CD_ELO_AGENDAMENTO_ITEM = eai.CD_ELO_AGENDAMENTO_ITEM
    AND DD_DAY.CD_INCOTERMS = 'CIF'
    and DD_DAY.NU_DIA_SEMANA = eai.NU_DIA_SEMANA
    AND DD_DAY.CD_INCOTERMS = eai.CD_INCOTERMS
    AND DD_DAY.CD_GRUPO_EMBALAGEM = eai.CD_GRUPO_EMBALAGEM
    --AND DD_DAY.CD_CLIENTE = eai.CD_CLIENTE
    )
    )
    ,0) QT_AGENDADA_CONF_OU_BYDAY ,
    -----------------------------------------------------------------
    GREATEST(NVL(
    CASE 
   WHEN NVL((SELECT EDDAY.NU_DIA_SEMANA 
        FROM CTE_WEEK_DAYS EDDAY 
        WHERE EDDAY.NU_DIA_SEMANA = '0'),'0') = '0' 
        THEN --P_WEEKDAYS IS NULL 
    (SELECT SUM(DD_DAY.NU_QUANTIDADE) NU_QUANTIDADE 
    FROM ELO_AG_DAY_BY_INCOTERMS_ITEM DD_DAY
    WHERE DD_DAY.CD_ELO_AGENDAMENTO = eai.CD_ELO_AGENDAMENTO
    and DD_DAY.CD_ELO_AGENDAMENTO_ITEM = eai.CD_ELO_AGENDAMENTO_ITEM
    AND DD_DAY.CD_INCOTERMS = 'CIF'
    and DD_DAY.NU_DIA_SEMANA = eai.NU_DIA_SEMANA 
    AND DD_DAY.CD_INCOTERMS = eai.CD_INCOTERMS
    AND DD_DAY.CD_GRUPO_EMBALAGEM = eai.CD_GRUPO_EMBALAGEM
    AND DD_DAY.CD_CLIENTE = eai.CD_CLIENTE)
    ELSE
    (SELECT SUM(DD_DAY.NU_QUANTIDADE) NU_QUANTIDADE 
    FROM ELO_AG_DAY_BY_INCOTERMS_ITEM DD_DAY
    WHERE DD_DAY.CD_ELO_AGENDAMENTO = eai.CD_ELO_AGENDAMENTO
    --and DD_DAY.CD_ELO_AGENDAMENTO_ITEM = eai.CD_ELO_AGENDAMENTO_ITEM
    AND DD_DAY.CD_INCOTERMS = 'CIF'
    --and DD_DAY.NU_DIA_SEMANA = eai.NU_DIA_SEMANA 
    AND DD_DAY.CD_INCOTERMS = eai.CD_INCOTERMS
    AND DD_DAY.CD_GRUPO_EMBALAGEM = eai.CD_GRUPO_EMBALAGEM
    AND DD_DAY.CD_CLIENTE = eai.CD_CLIENTE
    )
    END
    
    ,0) -  NVL((SELECT SUM(E_MAR.NU_QUANTIDADE) NU_QUANTIDADE 
    FROM VND.ELO_MARCACAO E_MAR
    INNER JOIN VND.ELO_CARTEIRA ec
    ON ec.CD_ELO_CARTEIRA = E_MAR.CD_ELO_CARTEIRA
    WHERE 
    E_MAR.IC_DESISTENCIA = 'N' 
    AND E_MAR.IC_DISPENSADO = 'N'
    AND E_MAR.CD_CLIENTE = eai.CD_CLIENTE   --PWEE DAY IS NOT NULL
    AND E_MAR.CD_GRUPO_EMBALAGEM = eai.CD_GRUPO_EMBALAGEM 
    --AND ec.CD_ELO_AGENDAMENTO_ITEM = eai.CD_ELO_AGENDAMENTO_ITEM
    AND E_MAR.CD_INCOTERMS = eai.CD_INCOTERMS
    AND ec.CD_ELO_AGENDAMENTO = eai.CD_ELO_AGENDAMENTO
    
     AND EXISTS (SELECT 1 
                    FROM VND.ELO_EMBALAGEM_INCOTERMS FIL_DIA  --CHOOSE ALL DAYUS ANY WA
                    WHERE 
                    FIL_DIA.CD_GRUPO_EMBALAGEM = E_MAR.CD_GRUPO_EMBALAGEM
                    AND FIL_DIA.CD_INCOTERMS = 'CIF'
                    AND FIL_DIA.NU_DIA_SEMANA = (1 + TRUNC (E_MAR.DH_MARCACAO) - TRUNC (E_MAR.DH_MARCACAO, 'IW')) 
                    )
    AND E_MAR.SG_CLASSIFICACAO = 'Replan')  ,0),0) QT_AGENDADA_CORTE , 


    --------------------------------------------------------                          
    
    NVL((SELECT SUM(E_MAR.NU_QUANTIDADE) NU_QUANTIDADE 
    FROM VND.ELO_MARCACAO E_MAR
    INNER JOIN VND.ELO_CARTEIRA ec
    ON ec.CD_ELO_CARTEIRA = E_MAR.CD_ELO_CARTEIRA
    WHERE 
    E_MAR.IC_DESISTENCIA = 'N' 
    AND E_MAR.IC_DISPENSADO = 'N'
    --AND E_MAR.CD_CLIENTE = eai.CD_CLIENTE
    AND E_MAR.CD_GRUPO_EMBALAGEM = eai.CD_GRUPO_EMBALAGEM 
    AND ec.CD_ELO_AGENDAMENTO = eai.CD_ELO_AGENDAMENTO
    AND E_MAR.CD_INCOTERMS = eai.CD_INCOTERMS
    
     AND EXISTS (SELECT 1 
                    FROM CTE_EMB_INCOTERMS_DIA FIL_DIA  --TODOS OS DIAS 
                    WHERE 
                    FIL_DIA.CD_GRUPO_EMBALAGEM = E_MAR.CD_GRUPO_EMBALAGEM
                    AND FIL_DIA.CD_INCOTERMS = 'CIF'
                    AND FIL_DIA.NU_DIA_SEMANA = (1 + TRUNC (E_MAR.DH_MARCACAO) - TRUNC (E_MAR.DH_MARCACAO, 'IW')) 
                    )
    AND E_MAR.SG_CLASSIFICACAO = 'Replan')  ,0)  SOMA_MARCACAO,
    --------------------------------------------------------
    
    NVL((SELECT SUM(E_MAR.NU_QUANTIDADE) NU_QUANTIDADE 
    FROM VND.ELO_MARCACAO E_MAR
    INNER JOIN VND.ELO_CARTEIRA ec
    ON ec.CD_ELO_CARTEIRA = E_MAR.CD_ELO_CARTEIRA
    WHERE 
    E_MAR.IC_DESISTENCIA = 'N' 
    AND E_MAR.IC_DISPENSADO = 'N'
    --AND E_MAR.CD_CLIENTE = eai.CD_CLIENTE
    AND E_MAR.CD_GRUPO_EMBALAGEM = eai.CD_GRUPO_EMBALAGEM 
    --AND ec.CD_ELO_AGENDAMENTO_ITEM = eai.CD_ELO_AGENDAMENTO_ITEM
    AND ec.CD_ELO_AGENDAMENTO = eai.CD_ELO_AGENDAMENTO
    AND E_MAR.CD_INCOTERMS = eai.CD_INCOTERMS
    
     AND EXISTS (SELECT 1 
                    FROM ELO_EMBALAGEM_INCOTERMS FIL_DIA  --TODOS OS DIAS 
                    WHERE 
                    FIL_DIA.CD_GRUPO_EMBALAGEM = E_MAR.CD_GRUPO_EMBALAGEM
                    AND FIL_DIA.CD_INCOTERMS = 'CIF'
                    AND FIL_DIA.NU_DIA_SEMANA = (1 + TRUNC (E_MAR.DH_MARCACAO) - TRUNC (E_MAR.DH_MARCACAO, 'IW')) 
                    )
    AND E_MAR.SG_CLASSIFICACAO = 'Replan')  ,0)  SOMA_MARCACAO_SEMANA,
        --------------------------------------------------------                          
    
    

    --NVL(0,0) P_VOLUMED, 
    NVL((SELECT PAR.P_VOLUMED FROM CTE_PARAM PAR WHERE ROWNUM=1),0) P_VOLUMED, 

    0  as SaldoReplanejado,
     
    NVL(eai.CD_COTA_COMPARTILHADA, 0)   as CompartCota,
    NVL(( SELECT SUM(DD_DAY.NU_QUANTIDADE) NU_QUANTIDADE 
    FROM ELO_AG_DAY_BY_INCOTERMS_ITEM DD_DAY
    WHERE DD_DAY.CD_ELO_AGENDAMENTO = eai.CD_ELO_AGENDAMENTO
    and DD_DAY.CD_ELO_AGENDAMENTO_ITEM = eai.CD_ELO_AGENDAMENTO_ITEM
    and DD_DAY.NU_DIA_SEMANA = eai.NU_DIA_SEMANA
    and DD_DAY.CD_INCOTERMS = eai.CD_INCOTERMS
    AND DD_DAY.CD_CLIENTE = eai.CD_CLIENTE
    AND DD_DAY.CD_GRUPO_EMBALAGEM = eai.CD_GRUPO_EMBALAGEM
    AND DD_DAY.CD_INCOTERMS = 'CIF'
    --and DD_DAY.CD_ELO_AGENDAMENTO_ITEM = ec.CD_ELO_AGENDAMENTO_ITEM
    
    ),0) VOLUME_MAXIMO_FOB   , 
    eai.NU_DIA_SEMANA,
    eai.CD_TIPO_AGENDAMENTO
    

    FROM CTE_CENARIO_CIF_FOB eai
    WHERE eai.CD_INCOTERMS = 'CIF'
    AND eai.CD_TIPO_AGENDAMENTO = 25    
    

)

--SELECT * FROM CTE_CIF WHERE CD_ELO_CARTEIRA IS NOT NULL
--AND CD_CLIENTE = '0004055408'
--AND EMBALAGEM = 'Ensacado'

      
        
        SELECT --G_TOTAL.* 
                G_TOTAL.CodeCarteira,
                G_TOTAL.CodeCenter,
                G_TOTAL.DescriptionCenter,
                G_TOTAL.CodeCustomer,
                G_TOTAL.DescriptionCustomer,
                G_TOTAL.CodeMachine,
                G_TOTAL.DescriptionMachine,
                G_TOTAL.DescriptionIncoterms,
                G_TOTAL.DescriptionPackage,
                CASE WHEN ROUND(G_TOTAL.SaldoPlanejado,0) > 0 THEN ROUND(G_TOTAL.SaldoPlanejado,0) ELSE 0 END SaldoPlanejado ,
                CASE WHEN ROUND(G_TOTAL.SaldoReplanejado,0) > 0 THEN ROUND(G_TOTAL.SaldoReplanejado,0) ELSE 0 END SaldoReplanejado ,
                G_TOTAL.CompartCota,
                G_TOTAL.VOLUME_MAXIMO_FOB
        
        FROM 
        (
        ---------------- THIS SCENARIO IS PLAN -----------------        
        -------- this scenario is FOB-------------------
        
         select MAX(CD_ELO_CARTEIRA) CodeCarteira,
                CD_CENTRO_EXPEDIDOR CodeCenter,
                DS_CENTRO_EXPEDIDOR DescriptionCenter,
                CD_CLIENTE CodeCustomer,
                NO_CLIENTE DescriptionCustomer,
                CD_MACHINE CodeMachine,
                DS_MACHINE DescriptionMachine,
                CD_INCOTERMS DescriptionIncoterms,
                EMBALAGEM DescriptionPackage,

                SUM(
                CASE 
                WHEN QT_AGENDADA_CORTE  <
                
                (CASE 
                WHEN P_VOLUMED = 0 THEN QT_AGENDADA_CONF_OU_BYDAY - SOMA_MARCACAO 
                WHEN P_VOLUMED > (QT_AGENDADA_CONF_OU_BYDAY  - SOMA_MARCACAO ) THEN QT_AGENDADA_CONF_OU_BYDAY  - SOMA_MARCACAO 
                WHEN P_VOLUMED <=(QT_AGENDADA_CONF_OU_BYDAY - SOMA_MARCACAO )  THEN P_VOLUMED
                ELSE 0 END) THEN QT_AGENDADA_CORTE 
                ELSE 
                 (CASE 
                WHEN P_VOLUMED = 0 THEN QT_AGENDADA_CONF_OU_BYDAY - SOMA_MARCACAO  
                WHEN P_VOLUMED > (QT_AGENDADA_CONF_OU_BYDAY  - SOMA_MARCACAO ) THEN QT_AGENDADA_CONF_OU_BYDAY  - SOMA_MARCACAO 
                WHEN P_VOLUMED <=(QT_AGENDADA_CONF_OU_BYDAY - SOMA_MARCACAO )  THEN P_VOLUMED
                ELSE 0 END)
                END
                
              
                )             
                
                as SaldoPlanejado,

                SaldoReplanejado,
                CD_COTA_COMPARTILHADA CompartCota,

                SUM(VOLUME_MAXIMO_FOB)  VOLUME_MAXIMO_FOB
 
                from 
                (
                SELECT 
                MAX(CD_ELO_CARTEIRA) CD_ELO_CARTEIRA,
                CD_CENTRO_EXPEDIDOR,
                DS_CENTRO_EXPEDIDOR,
                CD_CLIENTE,
                NO_CLIENTE,
                CD_MACHINE,
                DS_MACHINE,
                CD_INCOTERMS,
                EMBALAGEM,
                QT_AGENDADA_CORTE,
                QT_AGENDADA_CONF_OU_BYDAY,
                SOMA_MARCACAO,
                CD_COTA_COMPARTILHADA,
                VOLUME_MAXIMO_FOB,
                P_VOLUMED,
                SaldoReplanejado, 
                NU_DIA_SEMANA
                
                FROM CTE_FOB
                WHERE CD_TIPO_AGENDAMENTO = 22 
                GROUP BY 
                --CD_ELO_CARTEIRA,
                CD_CENTRO_EXPEDIDOR,
                DS_CENTRO_EXPEDIDOR,
                CD_CLIENTE,
                NO_CLIENTE,
                CD_MACHINE,
                DS_MACHINE,
                CD_INCOTERMS,
                EMBALAGEM,
                QT_AGENDADA_CORTE,
                QT_AGENDADA_CONF_OU_BYDAY,
                SOMA_MARCACAO,
                CD_COTA_COMPARTILHADA,
                VOLUME_MAXIMO_FOB,
                P_VOLUMED,
                SaldoReplanejado,
                NU_DIA_SEMANA
                
                )
        
        group by CD_CENTRO_EXPEDIDOR,
                 DS_CENTRO_EXPEDIDOR,
                 CD_CLIENTE,
                 NO_CLIENTE,
                 CD_MACHINE,
                 DS_MACHINE,
                 CD_INCOTERMS,
                 EMBALAGEM,
                 SaldoReplanejado,
                 CD_COTA_COMPARTILHADA--, 
                 --VOLUME_MAXIMO_FOB
--------------------------------UNION  -------------------------                 
        UNION 
        
-------- this scenario is CIF----P_WEEKDAY IS NULL ---------------     
        
         select MAX(CD_ELO_CARTEIRA) CodeCarteira,
                CD_CENTRO_EXPEDIDOR CodeCenter,
                DS_CENTRO_EXPEDIDOR DescriptionCenter,
                CD_CLIENTE CodeCustomer,
                NO_CLIENTE DescriptionCustomer,
                CD_MACHINE CodeMachine,
                DS_MACHINE DescriptionMachine,
                CD_INCOTERMS DescriptionIncoterms,
                EMBALAGEM DescriptionPackage,

                SUM(
                CASE 
                WHEN QT_AGENDADA_CORTE  <
                
                (CASE 
                WHEN P_VOLUMED = 0 THEN QT_AGENDADA_CONF_OU_BYDAY /*- SOMA_MARCACAO */ 
                WHEN P_VOLUMED > (QT_AGENDADA_CONF_OU_BYDAY  /*- SOMA_MARCACAO */) THEN QT_AGENDADA_CONF_OU_BYDAY  /*- SOMA_MARCACAO */
                WHEN P_VOLUMED <=(QT_AGENDADA_CONF_OU_BYDAY /*- SOMA_MARCACAO */)  THEN P_VOLUMED
                ELSE 0 END) THEN QT_AGENDADA_CORTE 
                ELSE 
                 (CASE 
                WHEN P_VOLUMED = 0 THEN QT_AGENDADA_CONF_OU_BYDAY /*- SOMA_MARCACAO */ 
                WHEN P_VOLUMED > (QT_AGENDADA_CONF_OU_BYDAY  /*- SOMA_MARCACAO */) THEN QT_AGENDADA_CONF_OU_BYDAY  /*- SOMA_MARCACAO */
                WHEN P_VOLUMED <=(QT_AGENDADA_CONF_OU_BYDAY /*- SOMA_MARCACAO */)  THEN P_VOLUMED
                ELSE 0 END)
                END
                
              
                )             
                
                as SaldoPlanejado,

                SaldoReplanejado,
                CD_COTA_COMPARTILHADA CompartCota,

                SUM(VOLUME_MAXIMO_FOB) VOLUME_MAXIMO_FOB
 
                from 
                (
                SELECT 
                MAX(CD_ELO_CARTEIRA) CD_ELO_CARTEIRA,
                CD_CENTRO_EXPEDIDOR,
                DS_CENTRO_EXPEDIDOR,
                CD_CLIENTE,
                NO_CLIENTE,
                CD_MACHINE,
                DS_MACHINE,
                CD_INCOTERMS,
                EMBALAGEM,
                 
                
                SUM(QT_AGENDADA_CORTE) QT_AGENDADA_CORTE,
                SUM(QT_AGENDADA_CONF_OU_BYDAY) QT_AGENDADA_CONF_OU_BYDAY,
                SUM(SOMA_MARCACAO) SOMA_MARCACAO,
                CD_COTA_COMPARTILHADA,
                SUM( VOLUME_MAXIMO_FOB) VOLUME_MAXIMO_FOB,
                P_VOLUMED, 
                SaldoReplanejado,
                1 NU_DIA_SEMANA
                
                FROM CTE_CIF
                
                WHERE CD_ELO_CARTEIRA IS NOT NULL
                AND NVL((SELECT DDAYSS.NU_DIA_SEMANA FROM CTE_WEEK_DAYS DDAYSS WHERE DDAYSS.NU_DIA_SEMANA = '0'),'0') = '0' --P_WEEKDAYS IS NULL
                AND CD_TIPO_AGENDAMENTO = 22
                GROUP BY
                                --CD_ELO_CARTEIRA,
                CD_CENTRO_EXPEDIDOR,
                DS_CENTRO_EXPEDIDOR,
                CD_CLIENTE,
                NO_CLIENTE,
                CD_MACHINE,
                DS_MACHINE,
                CD_INCOTERMS,
                EMBALAGEM,
                --QT_AGENDADA_CORTE,
                --QT_AGENDADA_CONF_OU_BYDAY,
                --SOMA_MARCACAO,
                CD_COTA_COMPARTILHADA,
                --VOLUME_MAXIMO_FOB,
                P_VOLUMED, 
                SaldoReplanejado--, 
                --NU_DIA_SEMANA
                
                )
        
        group by CD_CENTRO_EXPEDIDOR,
                 DS_CENTRO_EXPEDIDOR,
                 CD_CLIENTE,
                 NO_CLIENTE,
                 CD_MACHINE,
                 DS_MACHINE,
                 CD_INCOTERMS,
                 EMBALAGEM,
                 SaldoReplanejado,
                 CD_COTA_COMPARTILHADA--, 
                 --VOLUME_MAXIMO_FOB        
UNION 

-------- this scenario is CIF----P_WEEKDAY IS NOT NULL ---------------     
        
         select MAX(CD_ELO_CARTEIRA) CodeCarteira,
                CD_CENTRO_EXPEDIDOR CodeCenter,
                DS_CENTRO_EXPEDIDOR DescriptionCenter,
                CD_CLIENTE CodeCustomer,
                NO_CLIENTE DescriptionCustomer,
                CD_MACHINE CodeMachine,
                DS_MACHINE DescriptionMachine,
                CD_INCOTERMS DescriptionIncoterms,
                EMBALAGEM DescriptionPackage,

                SUM(
                CASE 
                WHEN QT_AGENDADA_CORTE  <
                
                (CASE 
                WHEN P_VOLUMED = 0 THEN QT_AGENDADA_CONF_OU_BYDAY - SOMA_MARCACAO  
                WHEN P_VOLUMED > (QT_AGENDADA_CONF_OU_BYDAY  - SOMA_MARCACAO)  THEN QT_AGENDADA_CONF_OU_BYDAY  - SOMA_MARCACAO 
                WHEN P_VOLUMED <=(QT_AGENDADA_CONF_OU_BYDAY - SOMA_MARCACAO )  THEN P_VOLUMED
                ELSE 0 END) THEN QT_AGENDADA_CORTE 
                ELSE 
                 (CASE 
                WHEN P_VOLUMED = 0 THEN QT_AGENDADA_CONF_OU_BYDAY - SOMA_MARCACAO  
                WHEN P_VOLUMED > (QT_AGENDADA_CONF_OU_BYDAY  - SOMA_MARCACAO ) THEN QT_AGENDADA_CONF_OU_BYDAY  - SOMA_MARCACAO 
                WHEN P_VOLUMED <=(QT_AGENDADA_CONF_OU_BYDAY - SOMA_MARCACAO )  THEN P_VOLUMED
                ELSE 0 END)
                END
                
              
                )             
                
                as SaldoPlanejado,

                SaldoReplanejado,
                CD_COTA_COMPARTILHADA CompartCota,

                SUM(VOLUME_MAXIMO_FOB) VOLUME_MAXIMO_FOB
 
                from 
                (
                SELECT 
                MAX(CD_ELO_CARTEIRA) CD_ELO_CARTEIRA,
                CD_CENTRO_EXPEDIDOR,
                DS_CENTRO_EXPEDIDOR,
                CD_CLIENTE,
                NO_CLIENTE,
                CD_MACHINE,
                DS_MACHINE,
                CD_INCOTERMS,
                EMBALAGEM,
                 
                
                sum( QT_AGENDADA_CORTE )* 1 /*MAX(NU_DIA_SEMANA)*/ QT_AGENDADA_CORTE,
                SUM(QT_AGENDADA_CONF_OU_BYDAY) QT_AGENDADA_CONF_OU_BYDAY,
                SUM(SOMA_MARCACAO) SOMA_MARCACAO ,
                CD_COTA_COMPARTILHADA,
                SUM(VOLUME_MAXIMO_FOB) VOLUME_MAXIMO_FOB ,
                P_VOLUMED, 
                SaldoReplanejado,
                1 NU_DIA_SEMANA
                
                FROM CTE_CIF
                
                WHERE CD_ELO_CARTEIRA IS NOT NULL
                AND NVL((SELECT DDAYSS.NU_DIA_SEMANA FROM CTE_WEEK_DAYS DDAYSS WHERE DDAYSS.NU_DIA_SEMANA > '0'  AND ROWNUM=1),'0') > '0' --P_WEEKDAYS IS NULL
                AND CD_TIPO_AGENDAMENTO = 22
                GROUP BY
                                --CD_ELO_CARTEIRA,
                CD_CENTRO_EXPEDIDOR,
                DS_CENTRO_EXPEDIDOR,
                CD_CLIENTE,
                NO_CLIENTE,
                CD_MACHINE,
                DS_MACHINE,
                CD_INCOTERMS,
                EMBALAGEM,
                --QT_AGENDADA_CORTE,
                --QT_AGENDADA_CONF_OU_BYDAY,
                --SOMA_MARCACAO,
                CD_COTA_COMPARTILHADA,
                --VOLUME_MAXIMO_FOB,
                P_VOLUMED, 
                SaldoReplanejado--, 
                --NU_DIA_SEMANA
                
                )
        
        group by CD_CENTRO_EXPEDIDOR,
                 DS_CENTRO_EXPEDIDOR,
                 CD_CLIENTE,
                 NO_CLIENTE,
                 CD_MACHINE,
                 DS_MACHINE,
                 CD_INCOTERMS,
                 EMBALAGEM,
                 SaldoReplanejado,
                 CD_COTA_COMPARTILHADA--, 
                 --VOLUME_MAXIMO_FOB      
---------------- THIS SCENARIO IS PLAN -----------------        
UNION 

        ---------------- THIS SCENARIO IS REPLAN -----------------        
        -------- this scenario is FOB-------------------
        
         select MAX(CD_ELO_CARTEIRA) CodeCarteira,
                CD_CENTRO_EXPEDIDOR CodeCenter,
                DS_CENTRO_EXPEDIDOR DescriptionCenter,
                CD_CLIENTE CodeCustomer,
                NO_CLIENTE DescriptionCustomer,
                CD_MACHINE CodeMachine,
                DS_MACHINE DescriptionMachine,
                CD_INCOTERMS DescriptionIncoterms,
                EMBALAGEM DescriptionPackage,

                0 SaldoPlanejado,
                SUM(
                CASE 
                WHEN QT_AGENDADA_CORTE  <
                
                (CASE 
                WHEN P_VOLUMED = 0 THEN QT_AGENDADA_CONF_OU_BYDAY - SOMA_MARCACAO 
                WHEN P_VOLUMED > (QT_AGENDADA_CONF_OU_BYDAY  - SOMA_MARCACAO ) THEN QT_AGENDADA_CONF_OU_BYDAY  - SOMA_MARCACAO 
                WHEN P_VOLUMED <=(QT_AGENDADA_CONF_OU_BYDAY - SOMA_MARCACAO )  THEN P_VOLUMED
                ELSE 0 END) THEN QT_AGENDADA_CORTE 
                ELSE 
                 (CASE 
                WHEN P_VOLUMED = 0 THEN QT_AGENDADA_CONF_OU_BYDAY - SOMA_MARCACAO  
                WHEN P_VOLUMED > (QT_AGENDADA_CONF_OU_BYDAY  - SOMA_MARCACAO ) THEN QT_AGENDADA_CONF_OU_BYDAY  - SOMA_MARCACAO 
                WHEN P_VOLUMED <=(QT_AGENDADA_CONF_OU_BYDAY - SOMA_MARCACAO )  THEN P_VOLUMED
                ELSE 0 END)
                END
                
              
                ) AS  SaldoReplanejado,
                CD_COTA_COMPARTILHADA CompartCota,

                SUM(VOLUME_MAXIMO_FOB)  VOLUME_MAXIMO_FOB
 
                from 
                (
                SELECT 
                MAX(CD_ELO_CARTEIRA) CD_ELO_CARTEIRA,
                CD_CENTRO_EXPEDIDOR,
                DS_CENTRO_EXPEDIDOR,
                CD_CLIENTE,
                NO_CLIENTE,
                CD_MACHINE,
                DS_MACHINE,
                CD_INCOTERMS,
                EMBALAGEM,
                QT_AGENDADA_CORTE,
                QT_AGENDADA_CONF_OU_BYDAY,
                SOMA_MARCACAO,
                CD_COTA_COMPARTILHADA,
                VOLUME_MAXIMO_FOB,
                P_VOLUMED,
                SaldoReplanejado, 
                NU_DIA_SEMANA
                
                FROM CTE_FOB
                WHERE CD_TIPO_AGENDAMENTO = 25 
                GROUP BY 
                --CD_ELO_CARTEIRA,
                CD_CENTRO_EXPEDIDOR,
                DS_CENTRO_EXPEDIDOR,
                CD_CLIENTE,
                NO_CLIENTE,
                CD_MACHINE,
                DS_MACHINE,
                CD_INCOTERMS,
                EMBALAGEM,
                QT_AGENDADA_CORTE,
                QT_AGENDADA_CONF_OU_BYDAY,
                SOMA_MARCACAO,
                CD_COTA_COMPARTILHADA,
                VOLUME_MAXIMO_FOB,
                P_VOLUMED,
                SaldoReplanejado,
                NU_DIA_SEMANA
                
                )
        
        group by CD_CENTRO_EXPEDIDOR,
                 DS_CENTRO_EXPEDIDOR,
                 CD_CLIENTE,
                 NO_CLIENTE,
                 CD_MACHINE,
                 DS_MACHINE,
                 CD_INCOTERMS,
                 EMBALAGEM,
                 SaldoReplanejado,
                 CD_COTA_COMPARTILHADA--, 
                 --VOLUME_MAXIMO_FOB
--------------------------------UNION  -------------------------                 
        UNION 
        
-------- this scenario is CIF----P_WEEKDAY IS NULL ---------------     
        
         select MAX(CD_ELO_CARTEIRA) CodeCarteira,
                CD_CENTRO_EXPEDIDOR CodeCenter,
                DS_CENTRO_EXPEDIDOR DescriptionCenter,
                CD_CLIENTE CodeCustomer,
                NO_CLIENTE DescriptionCustomer,
                CD_MACHINE CodeMachine,
                DS_MACHINE DescriptionMachine,
                CD_INCOTERMS DescriptionIncoterms,
                EMBALAGEM DescriptionPackage,
                0 SaldoPlanejado,

                SUM(
                CASE 
                WHEN QT_AGENDADA_CORTE  <
                
                (CASE 
                WHEN P_VOLUMED = 0 THEN QT_AGENDADA_CONF_OU_BYDAY /*- SOMA_MARCACAO */ 
                WHEN P_VOLUMED > (QT_AGENDADA_CONF_OU_BYDAY  /*- SOMA_MARCACAO */) THEN QT_AGENDADA_CONF_OU_BYDAY  /*- SOMA_MARCACAO */
                WHEN P_VOLUMED <=(QT_AGENDADA_CONF_OU_BYDAY /*- SOMA_MARCACAO */)  THEN P_VOLUMED
                ELSE 0 END) THEN QT_AGENDADA_CORTE 
                ELSE 
                 (CASE 
                WHEN P_VOLUMED = 0 THEN QT_AGENDADA_CONF_OU_BYDAY /*- SOMA_MARCACAO */ 
                WHEN P_VOLUMED > (QT_AGENDADA_CONF_OU_BYDAY  /*- SOMA_MARCACAO */) THEN QT_AGENDADA_CONF_OU_BYDAY  /*- SOMA_MARCACAO */
                WHEN P_VOLUMED <=(QT_AGENDADA_CONF_OU_BYDAY /*- SOMA_MARCACAO */)  THEN P_VOLUMED
                ELSE 0 END)
                END
                
              
                )             
                
                as SaldoReplanejado,
                CD_COTA_COMPARTILHADA CompartCota,

                SUM(VOLUME_MAXIMO_FOB) VOLUME_MAXIMO_FOB
 
                from 
                (
                SELECT 
                MAX(CD_ELO_CARTEIRA) CD_ELO_CARTEIRA,
                CD_CENTRO_EXPEDIDOR,
                DS_CENTRO_EXPEDIDOR,
                CD_CLIENTE,
                NO_CLIENTE,
                CD_MACHINE,
                DS_MACHINE,
                CD_INCOTERMS,
                EMBALAGEM,
                 
                
                SUM(QT_AGENDADA_CORTE) QT_AGENDADA_CORTE,
                SUM(QT_AGENDADA_CONF_OU_BYDAY) QT_AGENDADA_CONF_OU_BYDAY,
                SUM(SOMA_MARCACAO) SOMA_MARCACAO,
                CD_COTA_COMPARTILHADA,
                SUM( VOLUME_MAXIMO_FOB) VOLUME_MAXIMO_FOB,
                P_VOLUMED, 
                SaldoReplanejado,
                1 NU_DIA_SEMANA
                
                FROM CTE_CIF
                
                WHERE CD_ELO_CARTEIRA IS NOT NULL
                AND NVL((SELECT DDAYSS.NU_DIA_SEMANA FROM CTE_WEEK_DAYS DDAYSS WHERE DDAYSS.NU_DIA_SEMANA = '0'),'0') = '0' --P_WEEKDAYS IS NULL

                AND CD_TIPO_AGENDAMENTO = 25
                GROUP BY
                                --CD_ELO_CARTEIRA,
                CD_CENTRO_EXPEDIDOR,
                DS_CENTRO_EXPEDIDOR,
                CD_CLIENTE,
                NO_CLIENTE,
                CD_MACHINE,
                DS_MACHINE,
                CD_INCOTERMS,
                EMBALAGEM,
                --QT_AGENDADA_CORTE,
                --QT_AGENDADA_CONF_OU_BYDAY,
                --SOMA_MARCACAO,
                CD_COTA_COMPARTILHADA,
                --VOLUME_MAXIMO_FOB,
                P_VOLUMED, 
                SaldoReplanejado--, 
                --NU_DIA_SEMANA
                
                )
        
        group by CD_CENTRO_EXPEDIDOR,
                 DS_CENTRO_EXPEDIDOR,
                 CD_CLIENTE,
                 NO_CLIENTE,
                 CD_MACHINE,
                 DS_MACHINE,
                 CD_INCOTERMS,
                 EMBALAGEM,
                 SaldoReplanejado,
                 CD_COTA_COMPARTILHADA--, 
                 --VOLUME_MAXIMO_FOB        
UNION 

-------- this scenario is CIF----P_WEEKDAY IS NOT NULL ---------------     
        
         select MAX(CD_ELO_CARTEIRA) CodeCarteira,
                CD_CENTRO_EXPEDIDOR CodeCenter,
                DS_CENTRO_EXPEDIDOR DescriptionCenter,
                CD_CLIENTE CodeCustomer,
                NO_CLIENTE DescriptionCustomer,
                CD_MACHINE CodeMachine,
                DS_MACHINE DescriptionMachine,
                CD_INCOTERMS DescriptionIncoterms,
                EMBALAGEM DescriptionPackage,
                0 SaldoPlanejado,
                SUM(
                CASE 
                WHEN QT_AGENDADA_CORTE  <
                
                (CASE 
                WHEN P_VOLUMED = 0 THEN QT_AGENDADA_CONF_OU_BYDAY - SOMA_MARCACAO  
                WHEN P_VOLUMED > (QT_AGENDADA_CONF_OU_BYDAY  - SOMA_MARCACAO)  THEN QT_AGENDADA_CONF_OU_BYDAY  - SOMA_MARCACAO 
                WHEN P_VOLUMED <=(QT_AGENDADA_CONF_OU_BYDAY - SOMA_MARCACAO )  THEN P_VOLUMED
                ELSE 0 END) THEN QT_AGENDADA_CORTE 
                ELSE 
                 (CASE 
                WHEN P_VOLUMED = 0 THEN QT_AGENDADA_CONF_OU_BYDAY - SOMA_MARCACAO  
                WHEN P_VOLUMED > (QT_AGENDADA_CONF_OU_BYDAY  - SOMA_MARCACAO ) THEN QT_AGENDADA_CONF_OU_BYDAY  - SOMA_MARCACAO 
                WHEN P_VOLUMED <=(QT_AGENDADA_CONF_OU_BYDAY - SOMA_MARCACAO )  THEN P_VOLUMED
                ELSE 0 END)
                END
                
              
                )             
                
                as SaldoReplanejado,
                CD_COTA_COMPARTILHADA CompartCota,

                SUM(VOLUME_MAXIMO_FOB) VOLUME_MAXIMO_FOB
 
                from 
                (
                SELECT 
                MAX(CD_ELO_CARTEIRA) CD_ELO_CARTEIRA,
                CD_CENTRO_EXPEDIDOR,
                DS_CENTRO_EXPEDIDOR,
                CD_CLIENTE,
                NO_CLIENTE,
                CD_MACHINE,
                DS_MACHINE,
                CD_INCOTERMS,
                EMBALAGEM,
                 
                
                sum( QT_AGENDADA_CORTE )* 1 /*MAX(NU_DIA_SEMANA)*/ QT_AGENDADA_CORTE,
                SUM(QT_AGENDADA_CONF_OU_BYDAY) QT_AGENDADA_CONF_OU_BYDAY,
                SUM(SOMA_MARCACAO) SOMA_MARCACAO ,
                CD_COTA_COMPARTILHADA,
                SUM(VOLUME_MAXIMO_FOB) VOLUME_MAXIMO_FOB ,
                P_VOLUMED, 
                SaldoReplanejado,
                1 NU_DIA_SEMANA
                
                FROM CTE_CIF
                
                WHERE CD_ELO_CARTEIRA IS NOT NULL
                 AND NVL((SELECT DDAYSS.NU_DIA_SEMANA FROM CTE_WEEK_DAYS DDAYSS WHERE DDAYSS.NU_DIA_SEMANA > '0' AND ROWNUM=1),'0') > '0' --P_WEEKDAYS IS NULL
                AND CD_TIPO_AGENDAMENTO = 25
                GROUP BY
                                --CD_ELO_CARTEIRA,
                CD_CENTRO_EXPEDIDOR,
                DS_CENTRO_EXPEDIDOR,
                CD_CLIENTE,
                NO_CLIENTE,
                CD_MACHINE,
                DS_MACHINE,
                CD_INCOTERMS,
                EMBALAGEM,
                --QT_AGENDADA_CORTE,
                --QT_AGENDADA_CONF_OU_BYDAY,
                --SOMA_MARCACAO,
                CD_COTA_COMPARTILHADA,
                --VOLUME_MAXIMO_FOB,
                P_VOLUMED, 
                SaldoReplanejado--, 
                --NU_DIA_SEMANA
                
                )
        
        group by CD_CENTRO_EXPEDIDOR,
                 DS_CENTRO_EXPEDIDOR,
                 CD_CLIENTE,
                 NO_CLIENTE,
                 CD_MACHINE,
                 DS_MACHINE,
                 CD_INCOTERMS,
                 EMBALAGEM,
                 SaldoReplanejado,
                 CD_COTA_COMPARTILHADA--, 
                 --VOLUME_MAXIMO_FOB      
---------------- THIS SCENARIO IS REPLAN -----------------    

        
 
 ) G_TOTAL
                 
        order by CodeCustomer,
                 DescriptionCustomer;
        
        
