
CREATE OR REPLACE FORCE VIEW VND.VW_ELO_CARTEIRA_SAP_SALESGROUP 
    (ID, NU_CARTEIRA_VERSION,CD_SALES_ORG, CD_SALES_DISTRICT,NO_SALES_DISTRICT,CD_SALES_OFFICE,NO_SALES_OFFICE,
     CD_SALES_GROUP,NO_SALES_GROUP)
     AS 
     (
SELECT 
        CTX.ID, 
        CTX.CD_SALES_ORG,
        CTX.NU_CARTEIRA_VERSION,
       CTX.CD_SALES_DISTRICT,
       CTX.NO_SALES_DISTRICT,
       CTX.CD_SALES_OFFICE,
       CTX.NO_SALES_OFFICE,
       CTX.CD_SALES_GROUP,
       CTX.NO_SALES_GROUP
  FROM VND.ELO_CARTEIRA_SAP_SALES_GROUP CTX
  );

GRANT SELECT ON VND.VW_ELO_CARTEIRA_SAP_SALESGROUP TO CPT;

GRANT SELECT ON VND.VW_ELO_CARTEIRA_SAP_SALESGROUP TO VND_SEC;

-----------------------------------------------------

CREATE OR REPLACE FORCE VIEW VND.VW_ELO_CD_WEEK_SEMANAL 
    (
ID,
CD_WEEK,
DT_WEEK_START_DAY,
IC_ATIVO,
CD_YEAR_WEEK,
CD_YEAR,
CD_WEEK_OF_YEAR,
CD_MONTH_OF_YEAR,
CD_DAY_OF_YEAR, 
NU_YEAR,
NU_WEEK_OF_YEAR,
NU_MONTH_OF_YEAR,
NU_DAY_OF_YEAR
        
    )
     AS 
     (
SELECT 
CTX.ID,
CTX.CD_WEEK,
CTX.DT_WEEK_START_DAY,
CTX.IC_ATIVO,
CTX.CD_YEAR_WEEK,
CTX.CD_YEAR,
CTX.CD_WEEK_OF_YEAR,
CTX.CD_MONTH_OF_YEAR,
CTX.CD_DAY_OF_YEAR, 
CTX.NU_YEAR,
CTX.NU_WEEK_OF_YEAR,
CTX.NU_MONTH_OF_YEAR,
CTX.NU_DAY_OF_YEAR

 FROM VND.ELO_CD_WEEK_SEMANAL CTX
  );

GRANT SELECT ON VND.VW_ELO_CD_WEEK_SEMANAL TO CPT;

GRANT SELECT ON VND.VW_ELO_CD_WEEK_SEMANAL TO VND_SEC;

