SELECT * FROM VND.ELO_AGENDAMENTO 
WHERE CD_ELO_STATUS = 9;

SELECT COUNT(1) FROM VND.ELO_AGENDAMENTO_WEEK_FROZZEN WHERE CD_ELO_STATUS_FROZZEN = 8;
SELECT * FROM VND.ELO_AGENDAMENTO_DAY_FROZZEN;

    WITH CTE_FROZZEN AS (
    SELECT SUP.CD_ELO_AGENDAMENTO--, WEFR.*
    FROM VND.ELO_AGENDAMENTO_SUPERVISOR SUP
    INNER JOIN VND.ELO_AGENDAMENTO_ITEM ITEM 
    ON SUP.CD_ELO_AGENDAMENTO_SUPERVISOR = ITEM.CD_ELO_AGENDAMENTO_SUPERVISOR
    INNER JOIN VND.ELO_AGENDAMENTO_WEEK WEES
    ON ITEM.CD_ELO_AGENDAMENTO_ITEM = WEES.CD_ELO_AGENDAMENTO_ITEM    
    INNER JOIN VND.ELO_AGENDAMENTO_WEEK_FROZZEN WEFR 
    ON ITEM.CD_ELO_AGENDAMENTO_ITEM = WEFR.CD_ELO_AGENDAMENTO_ITEM 
    WHERE 
    WEFR.CD_ELO_STATUS_FROZZEN = 3
    AND WEFR.DH_ULT_ALTERACAO > (SYSDATE - 365)
    GROUP BY 
    SUP.CD_ELO_AGENDAMENTO
    )
    
    --SELECT * FROM CTE_FROZZEN
    --WHERE CD_ELO_AGENDAMENTO = 50
    
    SELECT DISTINCT AGE.CD_ELO_AGENDAMENTO , AGE.CD_ELO_STATUS, 
(    SELECT MAX(WEFR.CD_ELO_AGENDAMENTO_WEEK)
    FROM VND.ELO_AGENDAMENTO_SUPERVISOR SUP
    INNER JOIN VND.ELO_AGENDAMENTO_ITEM ITEM 
    ON SUP.CD_ELO_AGENDAMENTO_SUPERVISOR = ITEM.CD_ELO_AGENDAMENTO_SUPERVISOR
    INNER JOIN VND.ELO_AGENDAMENTO_WEEK WEFR 
    ON ITEM.CD_ELO_AGENDAMENTO_ITEM = WEFR.CD_ELO_AGENDAMENTO_ITEM
    WHERE SUP.CD_ELO_AGENDAMENTO = AGE.CD_ELO_AGENDAMENTO ) TEM_WEEK,    
    
    FR.*
    FROM VND.ELO_AGENDAMENTO AGE 
    
    
    
    LEFT JOIN CTE_FROZZEN FR
    ON AGE.CD_ELO_AGENDAMENTO = FR.CD_ELO_AGENDAMENTO 
    
    WHERE 
    AGE.CD_ELO_STATUS in( 3,4,5,6,7,8,9) AND 
    FR.CD_ELO_AGENDAMENTO IS NULL;


SELECT * FROM VND.ELO_AGENDAMENTO 
WHERE CD_ELO_STATUS = 9;


    SELECT SUP.CD_ELO_AGENDAMENTO --INTO V_CD_ELO_AGENDAMENTO
    FROM VND.ELO_AGENDAMENTO_SUPERVISOR SUP
    INNER JOIN VND.ELO_AGENDAMENTO_ITEM ITEM 
    ON SUP.CD_ELO_AGENDAMENTO_SUPERVISOR = ITEM.CD_ELO_AGENDAMENTO_SUPERVISOR
    INNER JOIN VND.ELO_AGENDAMENTO_WEEK_FROZZEN WEFR 
    ON ITEM.CD_ELO_AGENDAMENTO_ITEM = WEFR.CD_ELO_AGENDAMENTO_ITEM 
    WHERE 1=1
    AND WEFR.CD_ELO_STATUS_FROZZEN = 3
    AND WEFR.DH_ULT_ALTERACAO > (SYSDATE - 365)
    AND SUP.CD_ELO_AGENDAMENTO = 50;
    
    
    
    SELECT 

  '50'  BATCH_ID ,
  30 CD_ELO_STATUS_FROZZEN  ,
  WEES.CD_ELO_AGENDAMENTO_WEEK ,
  WEES.CD_ELO_AGENDAMENTO_ITEM ,
  WEES.NU_SEMANA ,
  WEES.QT_COTA ,
  WEES.QT_SEMANA  ,
  WEES.QT_EMERGENCIAL ,
  CURRENT_DATE DH_ULT_ALTERACAO 

FROM VND.ELO_AGENDAMENTO_WEEK WEES 
WHERE 
EXISTS (SELECT ITEM.CD_ELO_AGENDAMENTO_ITEM FROM VND.ELO_AGENDAMENTO AGE 
INNER JOIN VND.ELO_AGENDAMENTO_SUPERVISOR SUP
ON AGE.CD_ELO_AGENDAMENTO = SUP.CD_ELO_AGENDAMENTO 
INNER JOIN VND.ELO_AGENDAMENTO_ITEM ITEM 
ON SUP.CD_ELO_AGENDAMENTO_SUPERVISOR = ITEM.CD_ELO_AGENDAMENTO_SUPERVISOR
WHERE
AGE.IC_ATIVO = 'S' 
--AND AGE.CD_ELO_STATUS IN (2,3)
AND AGE.CD_ELO_AGENDAMENTO = 50
AND WEES.CD_ELO_AGENDAMENTO_ITEM = ITEM.CD_ELO_AGENDAMENTO_ITEM);


SELECT * FROM VND.ELO_AGENDAMENTO_WEEK 
WHERE CD_ELO_AGENDAMENTO_ITEM = 5353;

SELECT * FROM VND.ELO_CARTEIRA 
WHERE CD_ELO_AGENDAMENTO = 50
AND QT_AGENDADA > 0;



SELECT CD_ELO_STATUS_FROZZEN, CD_ELO_AGENDAMENTO_WEEK, COUNT(1) 
 FROM VND.ELO_AGENDAMENTO_WEEK_FROZZEN
 GROUP BY CD_ELO_STATUS_FROZZEN, CD_ELO_AGENDAMENTO_WEEK
 HAVING COUNT(1) > 1 
;

SELECT * FROM VND.ELO_AGENDAMENTO_WEEK_FROZZEN 
WHERE CD_ELO_STATUS_FROZZEN = 7 AND DH_ULT_ALTERACAO = TO_DATE('14/06/2018 18:59:06', 'DD/MM/YYYY HH24:MI:SS')
AND CD_ELO_AGENDAMENTO_WEEK = 8919;

UPDATE VND.ELO_AGENDAMENTO_WEEK_FROZZEN
SET  CD_ELO_STATUS_FROZZEN = 3
WHERE CD_ELO_STATUS_FROZZEN = 7 AND DH_ULT_ALTERACAO = TO_DATE('14/06/2018 18:59:06', 'DD/MM/YYYY HH24:MI:SS');


UPDATE VND.ELO_AGENDAMENTO_DAY_FROZZEN
SET  CD_ELO_STATUS_FROZZEN = 3
WHERE CD_ELO_STATUS_FROZZEN = 7 AND DH_ULT_ALTERACAO = TO_DATE('14/06/2018 18:59:06', 'DD/MM/YYYY HH24:MI:SS');


SELECT * FROM VND.ELO_AGENDAMENTO_DAY_FROZZEN 
WHERE CD_ELO_STATUS_FROZZEN = 7 AND DH_ULT_ALTERACAO = TO_DATE('14/06/2018 18:59:06', 'DD/MM/YYYY HH24:MI:SS');

UPDATE VND.ELO_AGENDAMENTO_WEEK_FROZZEN
SET  CD_ELO_STATUS_FROZZEN = 3
WHERE CD_ELO_STATUS_FROZZEN NOT IN ( 3, 7);

UPDATE VND.ELO_AGENDAMENTO_DAY_FROZZEN
SET  CD_ELO_STATUS_FROZZEN = 3
WHERE CD_ELO_STATUS_FROZZEN NOT IN ( 3, 7);

SELECT * from VND.ELO_AGENDAMENTO_WEEK_FROZZEN
WHERE CD_ELO_STATUS_FROZZEN NOT IN ( 3, 7);

UPDATE ELO_AGENDAMENTO_WEEK_FROZZEN
SET BATCH_ID = 'BA18061405',
DH_ULT_ALTERACAO = CURRENT_DATE -0.1
WHERE BATCH_ID = 'BA18061406';

UPDATE ELO_AGENDAMENTO_DAY_FROZZEN
SET BATCH_ID = 'BA18061405',
DH_ULT_ALTERACAO = CURRENT_DATE -0.1
WHERE BATCH_ID = 'BA18061406';



UPDATE VND.ELO_AGENDAMENTO_WEEK_FROZZEN
SET BATCH_ID = 'BA18066',
DH_ULT_ALTERACAO = TO_DATE('14/06/2018 18:59:06', 'DD/MM/YYYY HH24:MI:SS')
WHERE CD_ELO_STATUS_FROZZEN IN ( 7);


UPDATE VND.ELO_AGENDAMENTO_DAY_FROZZEN
SET BATCH_ID = 'BA18066',
DH_ULT_ALTERACAO = TO_DATE('14/06/2018 18:59:06', 'DD/MM/YYYY HH24:MI:SS')
WHERE CD_ELO_STATUS_FROZZEN IN ( 7);





SELECT CURRENT_DATE - 0.1 FROM DUAL;

UPDATE VND.ELO_AGENDAMENTO_WEEK_FROZZEN
SET BATCH_ID = 'BA18060606'                
WHERE CD_ELO_STATUS_FROZZEN IN ( 7)
and BATCH_ID = 'BA18066';


UPDATE VND.ELO_AGENDAMENTO_day_FROZZEN
SET BATCH_ID = 'BA18060606'                
WHERE CD_ELO_STATUS_FROZZEN IN ( 7)
and BATCH_ID = 'BA18066';