PROCEDURE PI_AGENDAMENTO_DEVOLUTIVA
(
P_CD_ELO_AGENDAMENTO IN VND.ELO_AGENDAMENTO.CD_ELO_AGENDAMENTO%TYPE 
)
IS 

	V_CD_ELO_STATUS_FROZZEN VND.ELO_STATUS.CD_ELO_STATUS%TYPE;
	V_BATCH_ID VARCHAR2(10);
	V_CD_ELO_AGENDAMENTO  VND.ELO_AGENDAMENTO.CD_ELO_AGENDAMENTO%TYPE;
	
PROCEDURE INICIAR_DEVOLUTIVA 
(PI_CD_ELO_AGENDAMENTO VND.ELO_AGENDAMENTO.CD_ELO_AGENDAMENTO%TYPE);

PROCEDURE LIMPAR_DEVOLUTIVA 
(PI_CD_ELO_AGENDAMENTO VND.ELO_AGENDAMENTO.CD_ELO_AGENDAMENTO%TYPE);
	

BEGIN 

	V_CD_ELO_AGENDAMENTO:=P_CD_ELO_AGENDAMENTO;

	BEGIN
	SELECT 
	AGE.CD_ELO_STATUS INTO V_CD_ELO_STATUS_FROZZEN
	FROM VND.ELO_AGENDAMENTO AGE 
	WHERE 
	AGE.CD_ELO_AGENDAMENTO = P_CD_ELO_AGENDAMENTO
	AND AGE.CD_ELO_STATUS = 7;
	EXCEPTION  
	WHEN NO_DATA_FOUND THEN 
	BEGIN
		V_CD_ELO_AGENDAMENTO:=NULL;
		V_CD_ELO_STATUS_FROZZEN:=NULL;

	END;
	WHEN OTHERS THEN 
	BEGIN
	RAISE_APPLICATION_ERROR(-20001, 'ERRO ENCONTRADO: GX_ELO_BATCH_ISSUE.040 - ' || SQLCODE || ' -ERROR- ' || SQLERRM);
	--ROLLBACK;
	END;

	END;

IF V_CD_ELO_AGENDAMENTO IS NOT NULL THEN 
	LIMPAR_DEVOLUTIVA(V_CD_ELO_AGENDAMENTO);
	INICIAR_DEVOLUTIVA(V_CD_ELO_AGENDAMENTO);
END IF;

END;

PROCEDURE LIMPAR_DEVOLUTIVA 
(PI_CD_ELO_AGENDAMENTO VND.ELO_AGENDAMENTO.CD_ELO_AGENDAMENTO%TYPE)
IS

    CURSOR C_WEEK (PI_CD_ELO_AGENDAMENTO VND.ELO_AGENDAMENTO.CD_ELO_AGENDAMENTO%TYPE) IS 
    
    SELECT WEFR.ID
    FROM VND.ELO_AGENDAMENTO_SUPERVISOR SUP
    INNER JOIN VND.ELO_AGENDAMENTO_ITEM ITEM 
    ON SUP.CD_ELO_AGENDAMENTO_SUPERVISOR = ITEM.CD_ELO_AGENDAMENTO_SUPERVISOR
    INNER JOIN VND.ELO_AGENDAMENTO_WEEK_FROZZEN WEFR 
    ON ITEM.CD_ELO_AGENDAMENTO_ITEM = WEFR.CD_ELO_AGENDAMENTO_ITEM 
    WHERE 
	SUP.CD_ELO_AGENDAMENTO = PI_CD_ELO_AGENDAMENTO
    AND WEFR.CD_ELO_STATUS_FROZZEN = 7
	AND WEFR.CD_TIPO_DOC = 'D';
    
    CURSOR CCCC (PI_CD_ELO_AGENDAMENTO VND.ELO_AGENDAMENTO.CD_ELO_AGENDAMENTO%TYPE) IS 
    
    SELECT DAYFR.ID
    FROM VND.ELO_AGENDAMENTO_SUPERVISOR SUP
    INNER JOIN VND.ELO_AGENDAMENTO_ITEM ITEM 
    ON SUP.CD_ELO_AGENDAMENTO_SUPERVISOR = ITEM.CD_ELO_AGENDAMENTO_SUPERVISOR
    INNER JOIN VND.ELO_AGENDAMENTO_WEEK_FROZZEN WEFR 
    ON ITEM.CD_ELO_AGENDAMENTO_ITEM = WEFR.CD_ELO_AGENDAMENTO_ITEM 
    INNER JOIN VND.ELO_AGENDAMENTO_DAY_FROZZEN DAYFR 
    ON DAYFR.CD_ELO_AGENDAMENTO_WEEK = WEFR.CD_ELO_AGENDAMENTO_WEEK 
	
    WHERE 
	SUP.CD_ELO_AGENDAMENTO = PI_CD_ELO_AGENDAMENTO
    AND DAYFR.CD_ELO_STATUS_FROZZEN = 7
	AND DAYFR.CD_TIPO_DOC = 'D';
	
    TYPE elo_agendamento_week_r IS RECORD
    (
    id     vnd.elo_agendamento_week_frozzen.id%TYPE
    ); 
    
    TYPE elo_agendamento_week_t IS TABLE OF elo_agendamento_week_r
    INDEX BY PLS_INTEGER;
    
    tof_elo_agendamento_week elo_agendamento_week_t;
	
    TYPE elo_agendamento_day_r IS RECORD
    (
    id     vnd.elo_agendamento_day_frozzen.id%TYPE
    ); 
    
    TYPE elo_agendamento_day_t IS TABLE OF elo_agendamento_day_r
    INDEX BY PLS_INTEGER;
    
    tof_elo_agendamento_day elo_agendamento_day_t;
	V_LIMIT NUMBER:=10000;

BEGIN 

--- LIMPAR DAY FROZZEN DEVOLUTIVA -----------------------

    BEGIN 
    OPEN    C_DAY(PI_CD_ELO_AGENDAMENTO);                               
    FETCH   C_DAY BULK COLLECT INTO tof_elo_agendamento_day LIMIT V_LIMIT;
    CLOSE   C_DAY;
    EXCEPTION  
    WHEN OTHERS THEN 
    BEGIN
    RAISE_APPLICATION_ERROR(-20001, 'ERRO ENCONTRADO: GX_ELO_BATCH_ISSUE.050 - ' || SQLCODE || ' -ERROR- ' || SQLERRM);
    --ROLLBACK;
    END;
    
    END;
	
	IF tof_elo_agendamento_day.COUNT > 0 THEN 
	BEGIN 
		FORALL i_cart in INDICES OF tof_elo_agendamento_day
		DELETE FROM VND.ELO_AGENDAMENTO_DAY_FROZZEN wees
		WHERE 
		wees.ID = tof_elo_agendamento_day(i_cart).id
		;
		COMMIT;        
		EXCEPTION  
		WHEN OTHERS THEN 
		BEGIN
		RAISE_APPLICATION_ERROR(-20001, 'ERRO ENCONTRADO: GX_ELO_BATCH_ISSUE.051 - ' || SQLCODE || ' -ERROR- ' || SQLERRM);
		ROLLBACK;
		END; 

	END;
	END IF;

	--- LIMPAR WEEK FROZZEN DEVOLUTIVA -----------------------
	
    BEGIN 
    OPEN    C_WEEK(PI_CD_ELO_AGENDAMENTO);                               
    FETCH   C_WEEK BULK COLLECT INTO tof_elo_agendamento_week LIMIT V_LIMIT;
    CLOSE   C_WEEK;
    EXCEPTION  
    WHEN OTHERS THEN 
    BEGIN
    RAISE_APPLICATION_ERROR(-20001, 'ERRO ENCONTRADO: GX_ELO_BATCH_ISSUE.053 - ' || SQLCODE || ' -ERROR- ' || SQLERRM);
    --ROLLBACK;
    END;
    
    END;
	
	IF tof_elo_agendamento_week.COUNT > 0 THEN 
	BEGIN 
		FORALL i_cart in INDICES OF tof_elo_agendamento_week
		DELETE FROM VND.ELO_AGENDAMENTO_WEEK_FROZZEN wees
		WHERE 
		wees.ID = tof_elo_agendamento_week(i_cart).id
		;
		COMMIT;        
		EXCEPTION  
		WHEN OTHERS THEN 
		BEGIN
		RAISE_APPLICATION_ERROR(-20001, 'ERRO ENCONTRADO: GX_ELO_BATCH_ISSUE.054 - ' || SQLCODE || ' -ERROR- ' || SQLERRM);
		ROLLBACK;
		END; 

	END;
	END IF;
	

END LIMPAR_DEVOLUTIVA;


PROCEDURE INICIAR_DEVOLUTIVA 
(PI_CD_ELO_AGENDAMENTO VND.ELO_AGENDAMENTO.CD_ELO_AGENDAMENTO%TYPE)
IS
	V_BATCH_ID VARCHAR2(10);
	V_CD_TIPO_DOC VND.ELO_AGENDAMENTO_WEEK_FROZZEN.CD_TIPO_DOC%TYPE;

BEGIN 

V_BATCH_ID:='DF' || TO_CHAR(CURRENT_DATE, 'YYMMDDHH') ;
V_CD_TIPO_DOC:='D';

BEGIN 

INSERT INTO VND.ELO_AGENDAMENTO_WEEK_FROZZEN
(
  BATCH_ID ,
  CD_ELO_STATUS_FROZZEN  ,
  CD_ELO_AGENDAMENTO_WEEK ,
  CD_ELO_AGENDAMENTO_ITEM ,
  NU_SEMANA ,
  QT_COTA ,
  QT_SEMANA  ,
  QT_EMERGENCIAL ,
  DH_ULT_ALTERACAO   ,
  CD_TIPO_DOC

)

SELECT 

  V_BATCH_ID  BATCH_ID ,
  V_CD_ELO_STATUS_FROZZEN CD_ELO_STATUS_FROZZEN  ,
  WEES.CD_ELO_AGENDAMENTO_WEEK ,
  WEES.CD_ELO_AGENDAMENTO_ITEM ,
  WEES.NU_SEMANA ,
  WEES.QT_COTA ,
  WEES.QT_SEMANA  ,
  WEES.QT_EMERGENCIAL ,
  CURRENT_DATE DH_ULT_ALTERACAO ,
  V_CD_TIPO_DOC

FROM VND.ELO_AGENDAMENTO_WEEK WEES 
WHERE 
EXISTS (SELECT 1 FROM VND.ELO_AGENDAMENTO AGE 
INNER JOIN VND.ELO_AGENDAMENTO_SUPERVISOR SUP
ON AGE.CD_ELO_AGENDAMENTO = SUP.CD_ELO_AGENDAMENTO 
INNER JOIN VND.ELO_AGENDAMENTO_ITEM ITEM 
ON SUP.CD_ELO_AGENDAMENTO_SUPERVISOR = ITEM.CD_ELO_AGENDAMENTO_SUPERVISOR
WHERE
AGE.IC_ATIVO = 'S' 
AND AGE.CD_ELO_STATUS IN (7)
AND AGE.CD_ELO_AGENDAMENTO = PI_CD_ELO_AGENDAMENTO
AND WEES.CD_ELO_AGENDAMENTO_ITEM = ITEM.CD_ELO_AGENDAMENTO_ITEM)
;
COMMIT;
EXCEPTION  
WHEN OTHERS THEN 
BEGIN
RAISE_APPLICATION_ERROR(-20001, 'ERRO ENCONTRADO: GX_ELO_BATCH_ISSUE.041 - ' || SQLCODE || ' -ERROR- ' || SQLERRM);
ROLLBACK;
END;

END;


BEGIN 

INSERT INTO VND.ELO_AGENDAMENTO_DAY_FROZZEN
(

  BATCH_ID ,
  CD_ELO_STATUS_FROZZEN ,
  CD_ELO_AGENDAMENTO_DAY ,
  CD_ELO_AGENDAMENTO_WEEK ,
  NU_DIA_SEMANA ,
  CD_GRUPO_EMBALAGEM ,
  NU_QUANTIDADE  , 
  DH_ULT_ALTERACAO  ,
  CD_TIPO_DOC

)

SELECT 

  V_BATCH_ID  BATCH_ID ,
  V_CD_ELO_STATUS_FROZZEN CD_ELO_STATUS_FROZZEN  ,
  DDAYS.CD_ELO_AGENDAMENTO_DAY ,
  DDAYS.CD_ELO_AGENDAMENTO_WEEK ,
  DDAYS.NU_DIA_SEMANA ,
  DDAYS.CD_GRUPO_EMBALAGEM ,
  DDAYS.NU_QUANTIDADE  , 
  CURRENT_DATE DH_ULT_ALTERACAO ,
  V_CD_TIPO_DOC
  
FROM VND.ELO_AGENDAMENTO_DAY DDAYS
WHERE 
EXISTS (SELECT 1 FROM VND.ELO_AGENDAMENTO AGE 
INNER JOIN VND.ELO_AGENDAMENTO_SUPERVISOR SUP
ON AGE.CD_ELO_AGENDAMENTO = SUP.CD_ELO_AGENDAMENTO 
INNER JOIN VND.ELO_AGENDAMENTO_ITEM ITEM 
ON SUP.CD_ELO_AGENDAMENTO_SUPERVISOR = ITEM.CD_ELO_AGENDAMENTO_SUPERVISOR
INNER JOIN VND.ELO_AGENDAMENTO_WEEK WEES
ON WEES.CD_ELO_AGENDAMENTO_ITEM = ITEM.CD_ELO_AGENDAMENTO_ITEM
WHERE
AGE.IC_ATIVO = 'S' 
AND AGE.CD_ELO_STATUS IN (7)
AND AGE.CD_ELO_AGENDAMENTO = PI_CD_ELO_AGENDAMENTO
AND WEES.CD_ELO_AGENDAMENTO_WEEK = DDAYS.CD_ELO_AGENDAMENTO_WEEK)
;
COMMIT;
EXCEPTION  
WHEN OTHERS THEN 
BEGIN
RAISE_APPLICATION_ERROR(-20001, 'ERRO ENCONTRADO: GX_ELO_BATCH_ISSUE.042 - ' || SQLCODE || ' -ERROR- ' || SQLERRM);
ROLLBACK;
END;

END;

	

END INICIAR_DEVOLUTIVA;


END PI_AGENDAMENTO_DEVOLUTIVA;