WITH AGENDAMENTO AS 
(

SELECT AGE.CD_ELO_AGENDAMENTO, AGE.CD_WEEK, AGE.CD_POLO, AGE.CD_MACHINE, AGE.CD_CENTRO_EXPEDIDOR, 
AGE.CD_ELO_STATUS
FROM VND.ELO_AGENDAMENTO AGE
WHERE 
AGE.IC_ATIVO = 'S'
--AND AGE.CD_ELO_STATUS IN (3,4,5,6,7)
--AND AGE.CD_ELO_STATUS IN (3,4,5,6)
--AND AGE.CD_ELO_STATUS IN (4,6)  --1 PASSO SEM ERRO STATUS 59
AND AGE.CD_ELO_STATUS IN (1,2,3,4,5,6, 7,8)  --2 PASSO SEM ERRO STATUS 59 
),
--select * from AGENDAMENTO

CTE_CONTRATO_PEDIDOS_STATUS AS 
(
SELECT DISTINCT 
CT.NU_CONTRATO_SAP, 
CT.NU_ORDEM_VENDA,
CT.CD_ELO_AGENDAMENTO

FROM VND.ELO_CARTEIRA CT
INNER JOIN AGENDAMENTO AG
ON 
AG.CD_ELO_AGENDAMENTO = CT.CD_ELO_AGENDAMENTO
WHERE 
CT.IC_ATIVO = 'S'

AND NVL(CT.QT_AGENDADA_CONFIRMADA,0) >= 0
AND CT.QT_AGENDADA > 0
AND (CT.DH_CORTADO_FABRICA IS NULL AND NVL(CT.QT_AGENDADA_CELULA, 1) > 0)  
AND NVL(CT.CD_STATUS_CEL_FINAL, 40) NOT IN (40, 41, 59, 57, 58 )
AND CT.CD_MOTIVO_RECUSA IS NULL
and AG.CD_ELO_STATUS IN (1,2,3,4,5,6, 7,8)
AND NOT(NVL(CT.NU_ORDEM_VENDA, '0') IN ('          ', '0', '0         ' )) 
AND (CT.CD_TIPO_AGENDAMENTO IN (22,23,24) OR (CT.CD_TIPO_AGENDAMENTO = 25 AND CT.CD_STATUS_REPLAN = 32))

),
--SELECT DISTINCT GD.NU_CONTRATO_SAP, CTR.DH_ULT_INTERFACE FROM CTE_CONTRATO_PEDIDOS GD
--INNER JOIN VND.CONTRATO CTR ON GD.NU_CONTRATO_SAP = CTR.NU_CONTRATO_SAP
--SELECT DISTINCT GD.NU_ORDEM_VENDA, CTR.DH_ULT_INTERFACE FROM CTE_CONTRATO_PEDIDOS GD
--INNER JOIN VND.PEDIDO CTR ON GD.NU_ORDEM_VENDA = CTR.NU_ORDEM_VENDA

CTE_CONTRATO_PEDIDOS AS 
(
SELECT DISTINCT 
CT.NU_CONTRATO_SAP, 
CT.NU_ORDEM_VENDA, 
CT.CD_ELO_AGENDAMENTO

FROM VND.ELO_CARTEIRA CT
INNER JOIN AGENDAMENTO AG
ON 
AG.CD_ELO_AGENDAMENTO = CT.CD_ELO_AGENDAMENTO
WHERE 
CT.IC_ATIVO = 'S'

AND NVL(CT.QT_AGENDADA_CONFIRMADA,0) > 0
AND CT.QT_AGENDADA > 0
AND (CT.DH_CORTADO_FABRICA IS NULL AND NVL(CT.QT_AGENDADA_CELULA, 1) >= 0)  
AND NVL(CT.CD_STATUS_CEL_FINAL, 62)  IN ( 59)
AND CT.CD_MOTIVO_RECUSA IS NULL
and AG.CD_ELO_STATUS IN (1,2,3,4,5,6, 7,8)
AND NOT(NVL(CT.NU_ORDEM_VENDA, '0') IN ('          ', '0', '0         ' )) 
AND (CT.CD_TIPO_AGENDAMENTO IN (22,23,24) OR (CT.CD_TIPO_AGENDAMENTO = 25 AND CT.CD_STATUS_REPLAN = 32))

UNION 
SELECT STT.NU_CONTRATO_SAP, STT.NU_ORDEM_VENDA, STT.CD_ELO_AGENDAMENTO
FROM CTE_CONTRATO_PEDIDOS_STATUS STT
UNION 
SELECT DISTINCT CC.NU_CONTRATO_SAP, CC.NU_ORDEM_VENDA, CC.CD_ELO_AGENDAMENTO--, NU_PROTOCOLO 
FROM VND.ELO_CARTEIRA CC 
INNER JOIN VND.ELO_AGENDAMENTO AGC
ON 
AGC.CD_ELO_AGENDAMENTO = CC.CD_ELO_AGENDAMENTO
WHERE 
CC.NU_PROTOCOLO > 'INICI' || TO_CHAR(CURRENT_DATE-7, 'YYYY-MM-DD')
AND NVL(CC.QT_AGENDADA_CONFIRMADA,0) > 0
AND CC.QT_AGENDADA > 0
and AGC.CD_ELO_STATUS IN (1,2,3,4,5,6, 7, 8)
AND NOT(NVL(CC.NU_ORDEM_VENDA, '0') IN ('          ', '0', '0         ' )) 
AND (CC.CD_TIPO_AGENDAMENTO IN (22,23,24) OR (CC.CD_TIPO_AGENDAMENTO = 25 AND CC.CD_STATUS_REPLAN = 32))

)

SELECT AGE.CD_WEEK, AGE.DT_WEEK_START, AGE.CD_POLO, P.DS_POLO, AGE.CD_CENTRO_EXPEDIDOR, CC.DS_CENTRO_EXPEDIDOR, AGE.CD_ELO_STATUS,
STA.DS_STATUS, 
CASE 
WHEN EDD.CD_ELO_AGENDAMENTO IS NULL THEN '-'
ELSE 'X' END "CARTEIRAS PROCESSADAS"

FROM VND.ELO_AGENDAMENTO AGE
LEFT JOIN CTF.POLO P
ON P.CD_POLO = AGE.CD_POLO 
LEFT JOIN CTF.CENTRO_EXPEDIDOR CC 
ON  AGE.CD_CENTRO_EXPEDIDOR =  CC.CD_CENTRO_EXPEDIDOR
LEFT JOIN VND.ELO_STATUS STA
ON STA.CD_ELO_STATUS = AGE.CD_ELO_STATUS

lEFT JOIN 
(select DISTINCT EDD.CD_ELO_AGENDAMENTO 
from CTE_CONTRATO_PEDIDOS EDD
) EDD  ON EDD.CD_ELO_AGENDAMENTO = AGE.CD_ELO_AGENDAMENTO 
WHERE 
AGE.DT_WEEK_START < CURRENT_DATE - 15 AND AGE.CD_ELO_STATUS IN (1,2,3,4,5,6,7,8)
ORDER BY AGE.CD_ELO_STATUS; 




