
CREATE GLOBAL TEMPORARY TABLE VND.ELO_GROUPING_PROCESS_TMP
(

  ID                            NUMBER(9)  NOT NULL,
  CD_ELO_AGENDAMENTO_WEEK       NUMBER(9) ,
  NU_DOCUMENTO                  CHAR(10 BYTE) ,
  CD_ELO_AGENDAMENTO_GROUPING   NUMBER(9) ,
  CD_ELO_VBAK_PROTOCOLO         NUMBER(9) ,
  CD_ELO_CARTEIRA               NUMBER(9),
  CD_ELO_AGENDAMENTO_ITEM       NUMBER(9) ,
  DS_VERSAO                     VARCHAR2(255 BYTE)

)
ON COMMIT PRESERVE ROWS
NOCACHE;
