    WITH CTE_AGENDAMENTO AS 
    (
    SELECT AGE.CD_ELO_AGENDAMENTO , AGE.CD_ELO_STATUS
    FROM VND.ELO_AGENDAMENTO AGE
    WHERE 
    AGE.CD_ELO_STATUS NOT IN (1,2,3,9)
   -- AND (P_CD_WEEK IS NULL OR AGE.CD_WEEK = P_CD_WEEK)
   -- AND (P_CD_POLO IS NULL OR AGE.CD_POLO = P_CD_POLO)
   -- AND (P_CD_CENTRO_EXPEDIDOR IS NULL OR AGE.CD_CENTRO_EXPEDIDOR = P_CD_CENTRO_EXPEDIDOR)
   -- AND (P_CD_MACHINE IS NULL OR AGE.CD_MACHINE = P_CD_MACHINE)
    
    )
        
        
    SELECT DISTINCT
    EC.CD_ELO_AGENDAMENTO
    ,EC.CD_ELO_CARTEIRA
    ,EC.NU_ORDEM_VENDA
    ,EC.CD_ITEM_PEDIDO
    ,EC.CD_INCOTERMS 
    ,EC.IC_COOPERATIVE
    ,EC.NU_CONTRATO_SAP
    ,EC.CD_ITEM_CONTRATO
    ,NVL((SELECT SUM(NVL(POT.QT_AGENDADA_PROTOCOLO,0 )) QT 
                FROM VND.ELO_VBAK_PROTOCOLO POT 
                WHERE POT.CD_ELO_CARTEIRA = EC.CD_ELO_CARTEIRA 
                AND POT.IC_ATIVO='S'), 0)  QT_AGENDADA_PROTOCOLO
    ,EC.CD_PRODUTO_SAP
    ,EC.CD_TIPO_AGENDAMENTO
    , NVL( (SELECT DISTINCT PE.SG_STATUS FROM CPT.ENTREGA PE 
    INNER JOIN VND.ELO_VBAK_PROTOCOLO PROT
    ON PE.NU_PROTOCOLO_ENTREGA = PROT.NU_PROTOCOLO
    WHERE PROT.CD_ELO_CARTEIRA = EC.CD_ELO_CARTEIRA AND
    PROT.QT_AGENDADA_PROTOCOLO > 0 
    AND PROT.IC_ATIVO = 'S' 
    AND PE.SG_STATUS = 'C' ), 'P') SG_STATUS_PROTOCOLO
    ,EC.QT_AGENDADA_CONFIRMADA
    ,EC.CD_STATUS_CEL_FINAL
    ,EA.CD_ELO_STATUS
    
 
    FROM VND.ELO_CARTEIRA EC
    INNER JOIN CTE_AGENDAMENTO EA 
    ON EC.CD_ELO_AGENDAMENTO = EA.CD_ELO_AGENDAMENTO
    INNER JOIN VND.ELO_AGENDAMENTO_SUPERVISOR EAS ON EA.CD_ELO_AGENDAMENTO = EAS.CD_ELO_AGENDAMENTO
    WHERE
    ((EC.CD_STATUS_CUSTOMER_SERVICE IS NOT NULL AND NVL(EC.QT_AGENDADA_CONFIRMADA,0) >= 0
    AND (EC.CD_TIPO_AGENDAMENTO IN (22,23,24) OR (EC.CD_TIPO_AGENDAMENTO = 25 AND EC.CD_STATUS_REPLAN = 32))
    AND NOT(NVL(EC.CD_STATUS_CEL_FINAL, 58) = 59)
    )
    OR (
    EC.CD_STATUS_CUSTOMER_SERVICE IS NOT NULL AND EC.QT_AGENDADA_CONFIRMADA = 0 
    AND (EC.CD_TIPO_AGENDAMENTO IN (22,23,24) OR (EC.CD_TIPO_AGENDAMENTO = 25 AND EC.CD_STATUS_REPLAN = 32))
    AND EC.CD_STATUS_CEL_FINAL = 59 
    )
    OR EXISTS (SELECT 1 FROM CPT.ENTREGA PE 
    INNER JOIN VND.ELO_VBAK_PROTOCOLO PROT
    ON PE.NU_PROTOCOLO_ENTREGA = PROT.NU_PROTOCOLO
    WHERE PROT.CD_ELO_CARTEIRA = EC.CD_ELO_CARTEIRA AND
    PROT.QT_AGENDADA_PROTOCOLO > 0 
    AND PROT.IC_ATIVO = 'S' 
    AND PE.SG_STATUS = 'C' ) 
    
    )
    
    
     
    AND 
    EXISTS (SELECT 1 FROM VND.ELO_VBAK_PROTOCOLO PROTI 
    WHERE PROTI.CD_ELO_CARTEIRA = EC.CD_ELO_CARTEIRA
    AND PROTI.QT_AGENDADA_PROTOCOLO > 0
    AND PROTI.IC_ATIVO = 'S') 
    ;
